### ISSUE TITLE
Initial install, admin login kicks me back to login screen

### ISSUE THREAD

**Issue by rpdillon** [kiswa/TaskBoard#102]
Attempted an install, and logged in with admin/admin after the git clone.  The board page flashed for a moment, then I got kicked back to the log in page.  I checked the error console in Firefox and saw this:

```
"Error: fn is not a function
$http/promise.error/<@http://domain.tld/lib/angular.js:8120:11
qFactory/defer/deferred.promise.then/wrappedErrback@http://domain.tld/lib/angular.js:11582:31
qFactory/defer/deferred.promise.then/wrappedErrback@http://domain.tld/lib/angular.js:11582:31
qFactory/createInternalRejectedPromise/<.then/<@http://domain.tld/lib/angular.js:11715:29
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://domain.tld/lib/angular.js:12702:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://domain.tld/lib/angular.js:12514:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://domain.tld/lib/angular.js:12806:13
done@http://domain.tld/lib/angular.js:8379:34
completeRequest@http://domain.tld/lib/angular.js:8593:7
createHttpBackend/</xhr.onreadystatechange@http://domain.tld/lib/angular.js:8532:1
" angular.js:10072
consoleLog/<() angular.js:10072
$ExceptionHandlerProvider/this.$get</<() angular.js:7364
qFactory/defer/deferred.promise.then/wrappedErrback() angular.js:11585
qFactory/defer/deferred.promise.then/wrappedErrback() angular.js:11582
qFactory/createInternalRejectedPromise/<.then/<() angular.js:11715
$RootScopeProvider/this.$get</Scope.prototype.$eval() angular.js:12702
$RootScopeProvider/this.$get</Scope.prototype.$digest()
```

(I've replaced the real url with `domain.tld`)

**Comment by GliderPro** [comment]
I'm having the same issue on Dreamhost. I've tried PHP 5.6.4 with both FastCGI and CGI. I also tried the .htaccess fix suggested in the stackoverflow link shown above. Nothing has worked. I'm assuming it  is the same issue with the Authorization header being removed.

**Comment by kiswa** [comment]
Thanks for sharing the workaround! I'll add this to the v0.3.0 .htaccess

**Comment by GliderPro** [comment]
I pulled your dev branch into a fresh Dreamhost site with PHP 5.6.4 on FastCGI and confirmed it works without modification now. Thanks for the quick patch!

**Comment by kiswa** [comment]
Thanks for the quick confirmation!

**Comment by k4r7u** [comment]
I had to add the following to my apache vhost setting to get it to work:
`RewriteEngine On`
`RewriteCond %{HTTP:Authorization} .+`
`RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]`
With the dev branch it worked, for master I had to add `SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0`to .htaccess
