### ISSUE TITLE
Scroll to top on "refresh"

### ISSUE THREAD

**Issue by dpatou** [kiswa/TaskBoard#103]
Hey there, I'm having an annoying issue, I wonder if it's an intended "feature", a configuration issue, or an actual bug.

If I got a column with a lot of items on it, so that it won't fit on one screen, there's a scrollbar. If I scroll down to see items in the bottom, after a few seconds i'll get automatically scrolled back to top. My guess is that it does so after a "db check for update", but it's pretty annoying on a day to day use basis.

Is anyone facing the same issue, or having an idea on how to fix this ?

If this helps reproducing the bug (haven't had time to test extensively), said column have items with longish descriptions so that some of them also  have "internal" vertical scrollbars. I doubt it's involved in causing the situation, but who knows.

**Comment by deligant** [comment]
Still there after so many time. Is a fix planned?

**Comment by kiswa** [comment]
@deligant Yes and yes. I'm currently re-writing TaskBoard and this issue will be gone thanks to the new architecture.
