### ISSUE TITLE
Can't log on to new installation with admin/admin

### ISSUE THREAD

**Issue by sachams** [kiswa/TaskBoard#104]
Hi,

I have just set up a new installation but am unable to log in using admin/admin. I seem to get the same error as described in https://github.com/kiswa/TaskBoard/issues/71. The api directory is writeable, sqlite is installed and I have run `sudo a2enmod rewrite expires; sudo service apache2 restart`. I'm running on Ubuntu 14.04.

Can you help?

Many thanks

**Comment by Torsten-K** [comment]
Same issue. I uploaded all files onto two different standard web hosts. In one case, there is no error message, but I cannot log in with admin/admin. In the second case, there is a message, reading: API Error. Ensure api directory is writable.

This happens even after setting 0777 for the api directory and all of its subdirectories and files. The PHP versions are 5.3.29 and 5.6.3.

**Comment by kiswa** [comment]
@Torsten-K I'm not sure what to say, other than I need to dig into making the API layer more cross-version compatible. I can't remember right now if 5.3.29 will even work with TaskBoard, and I do remember someone noticing issues with 5.6.x (unfortunately, upstream).

There have been others mentioning that some hosts block the `Authentication` header, which may be contributing to your problem.

Take a look through some of the other resolved issues to see if anything they've tried helps you out.
