### ISSUE TITLE
Settings Board List: Add sorting by name

### ISSUE THREAD

**Issue by zenzire** [kiswa/TaskBoard#110]
Currently, boards list page displays boards unsorted (they are displayed by creation date).
I recommend to add default sorting by name.

**Comment by poikilos** [comment]
@kiswa In the live demo (0.3.1) the boards are only sorted in settings, not in the drop-down box. Did something break after this issue was closed?

**Comment by kiswa** [comment]
It's in v1.0.0 (pending release from the `re-write` branch).
