### ISSUE TITLE
503 error on nginx/php-fpm using your config

### ISSUE THREAD

**Issue by EnMod** [kiswa/TaskBoard#117]
Basically, I have a similar issue as described in https://github.com/kiswa/TaskBoard/issues/71, where I type in admin/admin and get kicked back.  The thing is, I get the "API Error. Ensure api directory is writeable." message above login, checking console shows this:
`POST http://taskboard.mydomain.com/api/login 503 (Service Unavailable)`

Bear in mind, permissions for the api folder are set correctly.  The only things I've changed from your config were what needed to be changed to fit my Arch/nginx/php-fpm setup. here's my conf for the server (domain names changed to protect the innocent):

```
server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    root /path/to/taskboard;
    index index.php index.html;

    # Make site accessible from http://localhost/
    server_name localhost;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location /api {
        if (!-e $request_filename) {
            rewrite ^(.*)$ /api/api.php last; break;
        }
    }

    location /api/taskboard.db {
        rewrite ^(.*)$ /api/api.php last; break;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini

        fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;
        include fastcgi.conf;
    }
}
```

All other components regarding php are going just fine on other sites I host.  Any ideas?

**Comment by weaming** [comment]
@EnMod  Thank you for your config!
@kiswa I think this config should be add to README.md. I use Nginx.
