### ISSUE TITLE
Export everything

### ISSUE THREAD

**Issue by urza** [kiswa/TaskBoard#118]
I like TaksBoard, it looks like the clean simple selfhosted alternative to trello I was looking for. Before I start using it, what options are there when one decides to stop using the app, but wants to take the data? Does it offer any kind of export? For example Boards as folders and tasks as files inside those folders? (file name as task name and content as description and other parameters?) Is this possible or planned?

Thnaks

**Comment by kiswa** [comment]
It's certainly possible, but not yet planned. The database is local (`TaskBoard/api/taskboard.db`) so you'd have access to all your data to do with what you will.

I'll definitely consider a data export feature if there is enough demand for it.

**Comment by sebelk** [comment]
I agree with urza it would be great a data export feature, and even an import feature from Trello for example

**Comment by kiswa** [comment]
If anyone wants to fully define an export, I can start planning something for this.

Also, imports should be relatively simple if sample data is provided. It would just be writing a tool to map from a particular app's export format to TaskBoard's data format.

**Comment by hi2u** [comment]
FYI, **taskboard.db** is just a standard SQLite file.  So if you have any experience with any kind of SQL, you can easily grab and work with your data directly using SQLite.  So you could do whatever you like with a small script if you're interfacing with something else that's self hosted, or just want to export some CSV/XML/HTML files or something.

If you want to take a look at the data with a GUI, I recommend http://dbeaver.jkiss.org/

In terms of moving between TaskBoard and the cloud based systems (Trello etc), it might be worth getting in touch with whoever runs https://todoport.com/ - they already have a migration system that connects to the APIs of six of the cloud services and interchanges between all of them.

So if they added TaskBoard, that would cover both importing and exporting to six services, basically 12 options for conversion all handled in one hit, and by someone else.

For dealing with TaskBoard, there's two ways they could go about it:

1. Allow the taskboard.db file to be uploaded/downloaded.  
2. Or deal with the TaskBoard API directly, as they do for the cloud services.

**Comment by StreakyCobra** [comment]
Without going as far as *export/migrate/import* features, it would already be nice to have a *export/import* feature for backup purposes (or better *backup/restore*). SQLite is a good file format for this, and just backuping/restoring the `taskboard.db` is enough. Having the possibility of doing it from the web interface can help people who have it dockerized. Getting or putting this file on a running docker container is not obvious, so here are the commands:

* Backuping db:

  1. Get the name of the running TaskBoard instance with:

     `docker ps`

  2. Run the command:

    `docker cp <container_name>:/app/api/taskboard.db ./taskboard.db.backup`

* Restoring db:

  1. Get the name of the running TaskBoard instance with:

     `docker ps`

  2. Same as before, but reverse the order of arguments, like:

    `docker cp ./taskboard.db.backup <container_name>:/app/api/taskboard.db`
