### ISSUE TITLE
Remove Unassigned and Ucategorized labels

### ISSUE THREAD

**Issue by urza** [kiswa/TaskBoard#119]
Would it be possible to leave out the "Assigned To: Unassigned" and "Uncategorized" labels at the bottom of the task? Only show when there is somebody assigned (I will be using TaskBoard as single user only so I it is useless info for me)... the same with category. When they are not being used, they only disctract and make the user interface less clean. Thanks

**Comment by kiswa** [comment]
Sorry, no. You're welcome to modify your version to remove those fields. Open `TaskBoard/partials/board.html` and remove lines 68, 69, and 79.
