### ISSUE TITLE
Layout of Board Columns

### ISSUE THREAD

**Issue by kircon** [kiswa/TaskBoard#120]
Hey,
would it be possible in a future update to change the layout of the tasks in a column a bit? At the moment they take up to much space and i think it would be more useful if i could (dependent on the amount of columns on screen) put two tasks next to each other with smaller fonts overall. 
Maybe this could be a setting where you can change font size, column layout etc. in general.

Keep up the good work! I really like it so far!

**Comment by kiswa** [comment]
There is issue #48, scheduled for v0.4.0, which will add a collapsed item layout. Will that meet your needs?

**Comment by kircon** [comment]
Oh that would definitely be useful! But that would still put all tasks vertically beneath each other. I just think maybe the horizontal space could be used more efficiently, e.g. more tasks per "row". Of course this is dependent on the amount of columns present. 
Sorry for the english i hope you understand what i mean.

**Comment by kiswa** [comment]
Your English is fine; I understand what you're saying.

I'll look into an option to display items side-by-side in columns so users with only a couple columns will be able to make better use of the space.

**Comment by mlasasa** [comment]
+1 for this. May even be possible to use it a some sort of prioritizing. Items in the same 'row' share the same priority.

**Comment by brendantay** [comment]
Is there any ETA on this?
Setup a copy of TaskBoard lastnight now I am populating and finding it feels a little cluttered only being able to see ~6/7 tasks in each column is a bit painful :(

**Comment by kiswa** [comment]
@brendantay Unfortunately, no. The ETA is whenever the `re-write` is finished. It looks like this, so far:

![Imgur](http://i.imgur.com/UbRosu9.png)

**Comment by brendantay** [comment]
Not a worry @kiswa appreciate all the effort you're putting in! It definitely looks a lot more 'busy person' friendly with that new layout, I'm looking forward to it.

**Comment by timconsidine** [comment]
I agree that items on boards can take up too much space, especially if the first line of description has a H1 title.  Looking forward to seeing v0.4.0. as this is a great project and very impressed with functionality and accessible coding - thank you @kiswa 

But in advance of that for users like @brendantay here is my simple hack in the hope it can help others

In partials/board.html :- 
- comment out line 66 (to not destroy original code)

- add a new line afterwards
<span data-ng-if="item.description.length" class="fa fa-list-alt"></span>

I made some other tweaks to produce a very compact summary of item attributes :- 
- moved description icon to following section
- moved icons for comments attachment and due date so category name has more room
- shortened default words "Assigned to" to "Who" and "Uncategorized" to "Misc" (need to run build/build-all again to be reflected)
- summary code is now (line breaks not displaying):- 
`                      <p class="assignee">
                            <span data-ng-show="currentUser.options.showAssignee">
                                <span data-ng-if="userNames[item.assignee]">Who : </span>
                                {{ userNames[item.assignee] }}
                            </span>
  			<span>
		                &nbsp;<span data-ng-if="item.description.length" class="fa fa-list-alt"></span>
                                &nbsp;<span data-ng-if="item.ownComment.length" class="fa fa-comments-o"
                                      title="{{ item.ownComment.length }} Comments"></span>
                                &nbsp;<span data-ng-if="item.ownAttachment.length" class="fa fa-paperclip"
                                      title="{{ item.ownAttachment.length }} Attachments"></span>
                                <span data-ng-if="item.due_date" data-ng-class="{'dateNear': item.dateNear, 'datePast}">
                                    {{ item.due_date }}
                                </span>
							</span>
                            <span class="pull-right">
                                <span class="category" title="Category">{{ categories[item.category] }}</span>
                            </span>
                        </p>
`
