### ISSUE TITLE
First log in failure

### ISSUE THREAD

**Issue by hobbsogblin** [kiswa/TaskBoard#123]
Trying to log in to task board for the first time with 'admin' credentials, nothing seems to happen. Checked the browser console, found:

"Failed to load http://localhost/taskboard/api/login resource: the server responded with a status of 404 (Not Found)"

Changed apache config to set "AllowOveride All" and restarted apache. When I tried taskboard again I got an error:
"API Error. Ensure api directory is writable."
And in the console:
"http://localhost/taskboard/api/login 503 (Service Unavailable)"

The taskboard directory is entirely writable and executable (777). Mod_rewrite is enabled.

I'm running Fedora 20, PHP 5.5.20, taskboard v0.2.7. Any ideas?

**Comment by kiswa** [comment]
Is php5-sqlite installed and enabled in your php.ini?

**Comment by hobbsogblin** [comment]
Yes, I have pdo_sqlite.so and sqlite.so in my php.ini.

**Comment by kiswa** [comment]
I did notice an issue on one install I tested where I had to change `api.php` to default the sqlite setup, then set it back and everything was working. I'm assuming this is a bug in RedBeanPHP, but did not have time to research it.

If you want to try it, just change line 32.
From: `R::setup('sqlite:taskboard.db');`
To: `R::setup();`
Login once (this creates a default sqlite db in /tmp), then change that line back and it worked for me.

Let me know if this helps.

**Comment by hobbsogblin** [comment]
Thanks for the reply,
I tried your suggestion and was able to log in after removing the 'sqlite:taskboard.db' parameter. However after logging out and changing it back, I ran into the same error:
"API Error. Ensure api directory is writable."

**Comment by kiswa** [comment]
Looks like I have some research to do. If you come up with anything on your end, please let me know!

**Comment by kiswa** [comment]
Would you try out the dev branch and let me know how that works? It's currently stable, just doesn't have everything planned for v0.3.0 in it yet.

I ask because one of the changes it has is including the stack trace with those API Error messages.

**Comment by flyingfisch** [comment]
I am having this exact same problem...

I have Ubuntu Server 14.04 with `sqlite` and `php5-sqlite` installed. I tried checking out `dev` and this was the output of /api/login:

~~~


{
  "message": "API Error.",
  "data": "Could not connect to database (?).",
  "alerts": null,
  "trace": [
    {
      "file": "/home/taskboard/public_html/api/lib/rb.php",
      "line": 598,
      "function": "connect",
      "class": "RedBeanPHP\\Driver\\RPDO",
      "type": "->",
      "args": []
    },
    {
      "file": "/home/taskboard/public_html/api/lib/rb.php",
      "line": 785,
      "function": "runQuery",
      "class": "RedBeanPHP\\Driver\\RPDO",
      "type": "->",
      "args": [
        "SELECT COUNT(*) FROM `user`  -- keep-cache",
        []
      ]
    },
    {
      "file": "/home/taskboard/public_html/api/lib/rb.php",
      "line": 808,
      "function": "GetAll",
      "class": "RedBeanPHP\\Driver\\RPDO",
      "type": "->",
      "args": [
        "SELECT COUNT(*) FROM `user`  -- keep-cache",
        []
      ]
    },
    {
      "file": "/home/taskboard/public_html/api/lib/rb.php",
      "line": 3113,
      "function": "GetCol",
      "class": "RedBeanPHP\\Driver\\RPDO",
      "type": "->",
      "args": [
        "SELECT COUNT(*) FROM `user`  -- keep-cache",
        []
      ]
    },
    {
      "file": "/home/taskboard/public_html/api/lib/rb.php",
      "line": 4524,
      "function": "getCell",
      "class": "RedBeanPHP\\Adapter\\DBAdapter",
      "type": "->",
      "args": [
        "SELECT COUNT(*) FROM `user`  -- keep-cache",
        []
      ]
    },
    {
      "file": "/home/taskboard/public_html/api/lib/rb.php",
      "line": 6497,
      "function": "queryRecordCount",
      "class": "RedBeanPHP\\QueryWriter\\AQueryWriter",
      "type": "->",
      "args": [
        "user",
        [],
        "",
        []
      ]
    },
    {
      "file": "/home/taskboard/public_html/api/lib/rb.php",
      "line": 7701,
      "function": "count",
      "class": "RedBeanPHP\\Repository",
      "type": "->",
      "args": [
        "user",
        "",
        []
      ]
    },
    {
      "file": "/home/taskboard/public_html/api/lib/rb.php",
      "line": 10268,
      "function": "count",
      "class": "RedBeanPHP\\OODB",
      "type": "->",
      "args": [
        "user",
        "",
        []
      ]
    },
    {
      "file": "/home/taskboard/public_html/api/helpers.php",
      "line": 305,
      "function": "count",
      "class": "RedBeanPHP\\Facade",
      "type": "::",
      "args": [
        "user"
      ]
    },
    {
      "file": "/home/taskboard/public_html/api/api.php",
      "line": 33,
      "function": "createInitialUser",
      "args": []
    }
  ]
}
~~~

**Comment by kiswa** [comment]
@flyingfisch, @hobbsogblin, have you guys been able to get things working? Or do you have any additional information?

**Comment by marcsoler** [comment]
Sadly I have the same problem. I was using lighttpd and switched to apache with the correct settings.
chmod -R 777 taskboard and chmod -R www-data taskboard didn't helped.
mod_rewrite enabled.

**Comment by naught101** [comment]
Also having this problem on kubuntu 14.04, PHP 5.5.9, Apache 2.4.7, php5-sqlite installed, `rewrite` and `expires` enabled, and `AllowOverride All` on. 

There is no feedback when the login fails, but when I look in the console, it says there is a 404 error at http://localhost/TaskBoard/api/login. Maybe there's a problem with the rewrite rules in api/.htaccess? I haven't changed anything in any .htaccess files...

**Comment by kiswa** [comment]
@naught101 I'm actually very confident about `api/.htaccess` as I'm using it in another project.

The only location that should require any changes is the `api` directory itself. @marcsoler you may have meant `chown -R www-data taskboard`.

I still have no idea why anyone is getting a 404 for the login. Would you mind trying the `dev` branch and let me know if it has the same problem?

**Comment by indiealexh** [comment]
Same issue. Tried dev branch. 
```
API Error. Ensure api directory is writable.
```

main folder is 755. API is 777.

**Comment by marcsoler** [comment]
I tryed it on a local xampp installation and it worked. So it must be a apache/php configuration beside AllowOverride All that must be different from the default

**Comment by iamthemuffinman** [comment]
This docker [build](https://github.com/mirweb/taskboard-docker) works for me. Is there anything in there that can help you troubleshoot?

**Comment by kiswa** [comment]
Thanks @iamthemuffinman hopefully that helps someone figure out the settings.

Just so everyone knows, I did a clean install and all I did was make `api` writable and everything worked. I'm going to close this as a local settings issue.

If you do figure out what was missing from your setup, please reply here and I'll update the readme to help others that may have the same problem.

**Comment by AlexBoorman** [comment]
I will test on my local dev server and a heroku and digital ocean vm when I get off work but just so you know it appears whatever configuration issue we have your demo server has as well. The same thing is happening there.

http://taskboard.matthewross.me/demo/#/

**Comment by naught101** [comment]
Is there some kind of logging we can enable to help troubleshoot it? I don't really have much to go off...

**Comment by kiswa** [comment]
@AlexBoorman Thanks for pointing that out to me! I moved things around on the server the other day and it had a permissions error.

@naught101 Any errors in the API should be logged wherever you have PHP setup to log them. Errors that are captured by the API are provided in the return object with the `dev` branch so you could try that and see if it sheds any light on things.

**Comment by AlexBoorman** [comment]
I didn't get an opportunity to check it out last night but I will try tonight to insure all is well

**Comment by torwag** [comment]
Hi I have the exact same problem
Running on an arch linux system which already runs pydio and owncloud I guess the config should be ok. API is writeable. However, I noticed that I can't access the website as written in the wiki. Index.html just points me to a blank page. Manually using indexDev.html points me to the login with the usual problem. 
Furthermore, accessing api does not result in a empty page (as written elsewhere) but in 
{"message":"API Error.","data":"Could not connect to database (?).","alerts":null}
but I guess that is normal since I did not manage to set-up anything database related yet?!

Would be glad if we find a solution to this.

**Comment by JetUni** [comment]
I'm also having this same problem on Ubuntu 14.04 and I've tried everything that has been suggested here and nothing works!!

**Comment by JetUni** [comment]
This seemed to work:
```
sudo a2enmod expires
```
And adding a new conf file for apache2 in /etc/apache2/conf-available (on Ubuntu 14.04 at least) with this in it.

```
Alias /TaskBoard "/var/www/TaskBoard/"

<Directory "/var/www/TaskBoard">
    Options +FollowSymLinks
    AllowOverride All
        Options All
        Require all granted
</Directory>
```

**Comment by fercb17** [comment]
Hello,

Sorry to bring up this issue after it being closed for so long but I may have a possible solution for those still having this problem:
<blockquote>
"message":"API Error.","data":"Could not connect to database (?).","alerts":null,"trace":
</blockquote>

The issue for me was that I was missing my sqlite3 path in my php.ini file:

<blockquote>
[sqlite]
sqlite3.extension_dir =
</blockquote>

Should be:

<blockquote>
[sqlite]
sqlite3.extension_dir = /sbin/sqlite3
</blockquote>

*I am using Linux so the package names and directories may vary from os to os.

**Comment by nitinraghav** [comment]
I got around this by changing permissions of Taskboard/api directory to 777.

**Comment by thbor** [comment]
> 尝试使用“管理员”凭据首次登录任务板，似乎没有任何事情发生。检查浏览器控制台，发现：
> 
> “无法加载[http：// localhost / taskboard / api / login](http://localhost/taskboard/api/login)资源：服务器响应状态为404（未找到）”
> 
> 更改了apache配置以设置“AllowOveride All”并重新启动apache。当我再次尝试任务板时，我收到一个错误：
> “API错误。确保api目录是可写的。” 
> 在控制台中：
> “ [http：// localhost / taskboard / api / login](http://localhost/taskboard/api/login) 503（服务不可用）”
> 
> 任务板目录是完全可写和可执行的（777）。Mod_rewrite已启用。
> 
> 我正在运行Fedora 20，PHP 5.5.20，任务板v0.2.7。有任何想法吗？



> Trying to log in to task board for the first time with 'admin' credentials, nothing seems to happen. Checked the browser console, found:
> 
> "Failed to load http://localhost/taskboard/api/login resource: the server responded with a status of 404 (Not Found)"
> 
> Changed apache config to set "AllowOveride All" and restarted apache. When I tried taskboard again I got an error:
> "API Error. Ensure api directory is writable."
> And in the console:
> "http://localhost/taskboard/api/login 503 (Service Unavailable)"
> 
> The taskboard directory is entirely writable and executable (777). Mod_rewrite is enabled.
> 
> I'm running Fedora 20, PHP 5.5.20, taskboard v0.2.7. Any ideas?

environment:ubuntu16.0.4,apache2,sqlite3,php7.0
i may solve the problems,you may try,do not execute  sudo a2ensite taskboard,sudo a2enmod expires
sudo a2enmod rewrite again

first:sudo apt-get purge apache2
second:sudo apt-get install apache2
third:connet your server like this:php -S 127.0.0.1:8080 devrouter.php
and log in

**Comment by thbor** [comment]
environment:ubuntu16.0.4,apache2,sqlite3,php7.0
i may solve the problems,you may try,do not execute sudo a2ensite taskboard,sudo a2enmod expires
sudo a2enmod rewrite again

first:sudo apt-get purge apache2
second:sudo apt-get install apache2
third:connet your server like this:php -S 127.0.0.1:8080 devrouter.php
and log in

**Comment by asgimenez** [comment]
Just run:

docker run --name my-tasks -p 8100:80 -v $PWD/taskboard.db:/var/www/html/api/taskboard.db rubmorgade/taskboard

and can't login. Error:

API Error. Ensure api directory is writable.

Any help? Thank you

**Comment by ginesdelpan** [comment]
i got the same error message running the rubmorgade docker image running it with the persisten 
form, and it is because (i dont know why), the "taskboard.db" is created as a directory, so "touching" /
creating this file before the "docker run...." command it works (for me :)

rm -rf taskboard.db
touch taskboard.db
docker run --name my-tasks -p 8100:80 -v $PWD/taskboard.db:/var/www/html/api/taskboard.db rubmorgade/taskboard
