### ISSUE TITLE
First Use - Exponential Admin Users

### ISSUE THREAD

**Issue by KooshiGovno** [kiswa/TaskBoard#124]
I logged in for the first time and changed my password,
I then added a board and selected "admin" under users
I created the board.  The page may have frozen up at some point during this, don't remember.

I created a second board, and saw that their were 2 users named "admin" that I could select, I selected neither.
Hit finish on that, and their were then 4 users named admin under the users section.

I deleted the extras, and I can no longer replicate the issue.

**Comment by kiswa** [comment]
Interesting. Since you can't recreate, I have to assume it was something local to your setup that caused a temporary hiccup. I'll look into it, but I'm going to close this issue. If I can make it happen, I'll re-open.

**Comment by brammeleman** [comment]
I also have two admin users in the database. Only the admin user with id 1 is used. Im not able to remove the one with an higher id.

**Comment by kiswa** [comment]
I have been unable to recreate this. @brammeleman, if you get something like [SQLiteBrowser](http://sqlitebrowser.org/) you can edit the database manually to clean up the extra user.
