### ISSUE TITLE
View of board is periodically reset, occasionally undoes changes

### ISSUE THREAD

**Issue by KooshiGovno** [kiswa/TaskBoard#125]
When I'm looking at a board, and I have many tasks in a column, to the point where I need to scroll down to see them all, the page will periodically reset itself, scrolling to the top of the column.
This seems to happen every 12 - 15 seconds.
If I'm dragging a task when this happens, the task is dropped from my cursor, and returns to where it was.

Occasionally, after I have already moved a task, it will move back to where It was moved from. This seems to coincide with the reset of the columns.

This seems like an issue of synchronizing data to and from the server.

**Comment by kiswa** [comment]
Yeah, this is planned for v0.4.0 (see #34).
