### ISSUE TITLE
Voting 

### ISSUE THREAD

**Issue by daniele-niero** [kiswa/TaskBoard#127]
It would be nice, like in Trello, to let users voting an item

**Comment by daniele-niero** [comment]
this should be a feature request, but I have no idea how to assign the "enhancement" label. Sorry about that

**Comment by kiswa** [comment]
Not having used Trello, could you explain this to me in more detail?

**Comment by daniele-niero** [comment]
Yes,

Imagine to have many users and a lot of things to do. How to decide which one should be done first?
Well obviously the due date is a hint, but also knowing what the other users feel as a priority would be a great piece of information.
This is what will happen if each user could give a vote or a point to a single task. One vote per user per task.

Have a look at how EpicGames uses Trello for they road map (https://trello.com/b/gHooNW9I/ue4-roadmap).
There, any Unreal Engine user can give their vote to a feature that is in progress, so that the guys at Epic have an idea of what their users want the most.

**Comment by captainwasabi** [comment]
Allow this to be turned off!

On February 9, 2015 11:46:45 AM EST, daniele-niero <notifications@github.com> wrote:
>Yes,
>
>Imagine to have many users and a lot of things to do. How to decide
>which one should be done first?
>Well obviously the due date is a hint, but also knowing what the other
>users feel as a priority would be a great piece of information.
>This is what will happen if each user could give a vote or a point to a
>single task. One vote per user per task.
>
>Have a look at how EpicGames uses Trello for they road map
>(https://trello.com/b/gHooNW9I/ue4-roadmap).
>There, any Unreal Engine user can give their vote to a feature that is
>in progress, so that the guys at Epic have an idea of what their users
>want the most.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kiswa/TaskBoard/issues/127#issuecomment-73542866

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kiswa** [comment]
I'll consider this. And don't worry @captainwasabi, it will be optional. ;)

**Comment by kiswa** [comment]
After further consideration, I don't think this really fits with my idea of what TaskBoard is.
