### ISSUE TITLE
Setting: Make new tasks appear at top of column

### ISSUE THREAD

**Issue by Kernle32DLL** [kiswa/TaskBoard#128]
Hi there, would it be possible, to integrate an board option to make new tasks appear at the top rather than the bottom of a column? The reason beeing that we have a rather long list of tasks, and we tend to "forget" tasks, that are newly created and thus far down the list.

At any rate: +1 for this cool application!

**Comment by kiswa** [comment]
Actually, I'm pretty sure there's an issue to allow sorting tasks by creation date, due date, etc. Let me see... found it #77 and it's scheduled for v0.4.0.

**Comment by Kernle32DLL** [comment]
Well, I think #77 aims for a different thing. As it should always be possible to "sort-by-hand", this comes into play when adding a long list of tasks. You wish to sort by hand.

But no problem- was just an suggestion :D

**Comment by kiswa** [comment]
I think I see what you're saying. There should be an option to use with the default sort (user-determined position) that makes new items start at position 0 instead of position items+1.

Right?

**Comment by Kernle32DLL** [comment]
Jep. For starters you could add a simple option like this:

![newitemattop](https://cloud.githubusercontent.com/assets/1338408/6186146/39196b96-b376-11e4-812a-62b43aa06468.png)

Of course this only makes sense when sorting "manually" (or user-determined as you said).

**Comment by sebelk** [comment]
+1
