### ISSUE TITLE
Action trigger 'category change' missing

### ISSUE THREAD

**Issue by maxstricker** [kiswa/TaskBoard#130]
I did a fresh install of TaskBoard (v0.2./) from git and the action trigger 'category change' is missing.
According to the docs it should be available. The board I use has categories assigned.
Here is a screenshot:
![Screenshot](https://cloud.githubusercontent.com/assets/5141020/6124827/122d39a2-b111-11e4-9fa2-1d178ecfb54c.png)
How can I activate the missing trigger?

**Comment by kiswa** [comment]
It should automatically appear if the selected board has categories. I'll look into this!
