### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by Johnstone-Tech** [kiswa/TaskBoard#133]
I keep getting this error when i visit the application

![taskboard_-_settings](https://cloud.githubusercontent.com/assets/3208498/6217274/2daf586a-b60a-11e4-8cbf-5ecbeca00687.png)

**Comment by kiswa** [comment]
I was hoping to get this fixed before it got anyone! Until I do, the workaround (if it's the problem I think it is) is to open F12 tools and go to Resources > LocalStorage and delete the token for your TaskBoard.

Let me know if that helps.

**Comment by Johnstone-Tech** [comment]
Appreciate the suggestion, i went to try it a minute ago and now i can login to the application.

The developer tools log is giving me a 404 on /api/login/

I am fairly confident the server is setup correctly, however i would not say i was a professional so it may be a misconfiguration on my part causing this.

**Comment by kiswa** [comment]
A 404 on `api/login`? Have you had a look through Issues #3 and #7?

**Comment by kiswa** [comment]
Any update on this @Johnstone-Tech?

**Comment by kiswa** [comment]
Closing due to lack of information. Will re-open if needed.

**Comment by urza** [comment]
This is happening to me as well. I just downloaded v0.2.7 and uploaded it to my hosting. I logged as admin, and I see exactly the same thing as in screenshot above - loading, loading, loading...

I dont have any token in Chrome-F12-Resources for my site..

Thanks for any help.
