### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by torwag** [kiswa/TaskBoard#134]
Hi,
I really like the simplified and easy to use design of TaskBoard. 
We use some other services already and managed to get all authorized on a single LDAP instance. That allows us to add a user once and he will get access to all kind of services. 
I would love to see LDAP support for TaskBoard, thus it could be well integrated among other tools.
Thanks for the nice work.

**Comment by woodworker** [comment]
i also would like to see a authentication infrastructurewith an ldap backend

**Comment by torwag** [comment]
Well that could be merged with #49
Sorry did not see this before. But having LDAP in the headers helps ;) Maybe one could merge and change the header of #49 to External Users (LDAP)

**Comment by kiswa** [comment]
I updated the title of #49 to make it easier to find for alternate authentication methods.
