### ISSUE TITLE
UI Overhaul?

### ISSUE THREAD

**Issue by kiswa** [kiswa/TaskBoard#138]
I'd like some input from users of TaskBoard on this one. I'm considering reworking the UI to remove Bootstrap and change the way I've done a few things.

The impetus behind this is to allow for a more flexible Dashboard/Overview page to include some of the many features requested so far (email, charts, _etc._).

What do you think about reworking the UI, and do you have any recommendations if this happens?

**Comment by iamthemuffinman** [comment]
You can still use Bootstrap and accomplish all this if you wanted to. If you were gonna switch the UI framework to something else. I like these two: [Semantic-UI](http://semantic-ui.com/kitchen-sink.html), and [Material CSS](http://materializecss.com/about.html). I think reworking the UI is a good idea though. Good luck!

**Comment by torwag** [comment]
Be prepared to have some people hating it and other loving it ;)
Seriously, I like the idea of an Dashboard for each user. However, even more I would like to see 
LDAP and Email support ;)

**Comment by kiswa** [comment]
Yeah, that's the danger of UI changes. I've been thinking about this, and I may have presented it poorly.

I think what I really want to do is front-end framework changes. I also want to do UI changes, but I'll probably make those ideas into a theme for #126 (I do want a Material-style theme).

And don't worry, LDAP and email are on the list of things to add!

**Comment by iamthemuffinman** [comment]
Found something you might like since you use Angular. https://material.angularjs.org/#/

**Comment by kiswa** [comment]
I was looking at that this morning!

I think I'm going to avoid any framework changes, and just use #126 as a way to provide optional looks for now. Thanks to everyone for your input!
