### ISSUE TITLE
Suggestion: Generic tagging items

### ISSUE THREAD

**Issue by captainwasabi** [kiswa/TaskBoard#140]
Where the tag can be anything, and you can filter by tags (single or multiple)

**Comment by kiswa** [comment]
Could you provide some more detail about this. I'm not seeing much difference from the existing categories and I want to know what you're thinking of.

**Comment by kiswa** [comment]
@captainwasabi I'd like some more details here so I can understand what you have in mind.

**Comment by morvy** [comment]
I think he wants to assign multiple keywords to items, so item "New Logo" can be in category "web design" and also "outsourced tasks".
I'd like to see this feature too, for users too (so one task can have more than 1 owner)

**Comment by kiswa** [comment]
See #214
