### ISSUE TITLE
Currently Broken?

### ISSUE THREAD

**Issue by AlexBoorman** [kiswa/TaskBoard#141]
It seems that maybe the current build is broken? All login attempts seem to fail on both the demo and my local copy.

**Comment by kiswa** [comment]
If you're using `master` it hasn't changed in a while. I'll run a test install myself to be sure.

In the meantime, what errors are showing up in F12 developer tools?

**Comment by AlexBoorman** [comment]
jquery-1.11.1.min.js:3 The specified value '!' does not conform to the required format.  The format is '#rrggbb' where rr, gg, bb are two-digit hexadecimal numbers.

**Comment by AlexBoorman** [comment]
thats the only error that I can find that shouldn't stop anything from running though

**Comment by AlexBoorman** [comment]
ahh looks like the router is failing to resolve /api/login

**Comment by AlexBoorman** [comment]
![image](https://cloud.githubusercontent.com/assets/1124343/6560645/be0cd32e-c659-11e4-9f20-4505c982bd6f.png)

**Comment by iamthemuffinman** [comment]
This docker [build](https://github.com/mirweb/taskboard-docker) works for me. Is there anything in there that can help you troubleshoot?

**Comment by kiswa** [comment]
Sounds like you're experiencing whatever configuration error is happening to the guys in #123. I'm closing this one for now, please chime in over there if you figure this out!
