### ISSUE TITLE
Automatic transitions

### ISSUE THREAD

**Issue by angeldeejay** [kiswa/TaskBoard#142]
- **Workflows implementation:** Task may follow rule sets to restrict task states change (Feature).
- **Automatic transitions**: Events and triggers should change tasks states/columns (Feature)

**Comment by kiswa** [comment]
Going to need a description here so I know what you're looking for.

**Comment by angeldeejay** [comment]
## Important!!
- Workflows implementation
- Automatic transitions: Events and triggers should change tasks states/columns (May a feature)

**Comment by kiswa** [comment]
Sorry, but that didn't really clarify anything. Also, I removed the obnoxious header. If you want to try again, I'm willing to give you another shot.

**Comment by kiswa** [comment]
Closing due to lack of response.
