### ISSUE TITLE
Feature request: outgoing webhooks

### ISSUE THREAD

**Issue by liger1978** [kiswa/TaskBoard#143]
It would pretty cool if you allowed "outgoing webhooks" so that TaskBoard can integrate with things like Slack.  Basically whenever a change is made, TaskBoard will send some info to a particular URL.

**Comment by kiswa** [comment]
I'll have to look into a way to do this. Interesting idea, thanks.

**Comment by liger1978** [comment]
Great.  Good luck!

**Comment by sanPuerquitoProgramador** [comment]
Hi! I think this a great idea!! Is there any update about this? How can I help? I really love your work

**Comment by kiswa** [comment]
@sanPuerquitoProgramador It's on my list of things to look at for the re-write I'm currently working.

You can take a look at the [re-write branch](https://github.com/kiswa/TaskBoard/tree/re-write) to see how things are coming along (it's very much a work in progress still).
