### ISSUE TITLE
General Interface for different backends

### ISSUE THREAD

**Issue by torwag** [kiswa/TaskBoard#144]
Hi,

I would like to summarize different already posted tickets. I believe that TaskBoard would make a large step forward and provide an unique feature, if it would provide a general interface for different backends, which might be developed even by third parties.
Creating a general interface could help to support different backends people wish for
- web-hooks or REST interface
- interface via email
- interface to other web-applications
- interface to desktop applications
- interface to mobile apps

I found this a much more appealing goal rather then creating an own iOS and Android application. There are plentiful mobile apps and I would assume many people would like to stick to it rather then needing to use just another app on top. Same might be true for web applications. E.g. people might love to use owncloud and hence would love to integrate taskboard into owncloud. Many use an email-based workflow to distribute tasks among a working group and hence would love to integrate taskboard within this email-based system.

Finally, all those backends can come from different parties with different interests and the main developer(s) can focus on core feature. 

If agreed, I will try to add all related issues to this one just to keep this issue as a collection of possible backends for an general interface.

**Comment by kiswa** [comment]
If the community is interested in contributing this kind of thing, I'm all for it.

Note that there is a REST interface that is used by the web app. It's just not documented at this time.

**Comment by SyntaxRules** [comment]
:+1: For swappable backends. I'd like to be able to swap it with a nodejs one. An interface for this would be great!

**Comment by iamthemuffinman** [comment]
+1
