### ISSUE TITLE
Installing on Linux Mint (17)

### ISSUE THREAD

**Issue by rvireday** [kiswa/TaskBoard#145]
Hi, I've been trying to install TaskBoard on my server.  Mint 17. 
I'm at the point that it logs me in, but I can't do anything.  Eventually it errors out.

To get it to run, this is what I had to finish doing.  This is for both 0.27 and 0.3 Dev
$ apt-get install sqlite php5-sqlite
$ a2enmod expires rewrite
$ service apache2 restart

Most important is to create the following files it expects, but are not there.in the api/ dir
$ cp /dev/null boards
$ mkdir users
$ cp /dev/null users/current
$ cp /dev/null authenticate
$ cp /dev/null autoactions
$ chown -R www-data: .

Do you have blank/example versions of these that you can include or share somewhere????

BTW, Minor nit
jquery-1.11.2.min.js:3 The specified value '!' does not conform to the required format.  The format is '#rrggbb' where rr, gg, bb are two-digit hexadecimal numbers.

So THE PROBLEM.
I login as admin, but when I go to Settings, I get "Something went wrong while loading [users|boards]. Please refresh".   And it continually spins "Loading Boards".  Never finishes.  So I can't create new ones.

The Java Console in Chrome says
GET http://server/tbrd/api/users/ 404 (Not Found)
angular.js:9818 GET http://server/tbrd/api/users/ 404 (Not Found)
angular.js:9818 GET http://server/tbrd/api/users/ 404 (Not Found)
angular.js:9818 GET http://server/tbrd/api/users/ 404 (Not Found)
angular.js:9818 GET http://server/tbrd/api/users/ 404 (Not Found)angular.js:9818 (anonymous function)angular.js:9619 sendReqangular.js:9335 $get.serverRequestangular.js:13175 processQueueangular.js:13191 (anonymous function)angular.js:14388 $get.Scope.$evalangular.js:14204 $get.Scope.$digestangular.js:14493 $get.Scope.$applyangular.js:10380 tick

I will try this on an Ubuntu box, but right now my primary system is this Mint Server.
But wondered if you had something beyond some blank/example files for the missing ones.  I am so close.
--Richard Vireday

**Comment by kiswa** [comment]
Unfortunately, by adding files in there you've nullified the API. Those are not expected to exist, as the `.htaccess` in the `api` directory maps them to `api.php` and it processes the requests.

I'd start by removing the empty files/directories you created and going to `http://yourTaskBoardInstall/api/` and let me know what you get there (should be an empty page if all is well).

You may also want to take a look through #3 and #7 and see if anything in there helps.

As for the jQuery thing, yeah that annoys me too. Maybe an updated version of jQuery will stop that (whenever they release one).

**Comment by rvireday** [comment]
End of Friday.  I'll have to work on it next week.  Thanks for the suggestions.

1) Removed the files.  
2) Modified the /etc/apache2/sites-enabled/000-default.conf
<Directory /var/www/tbrd>
  Options Indexes MultiViews
  AllowOverride All
  Order allow,deny
  Allow from all
</Directory>

3) And verified api/ directory write privileges
drwxr-xr-x 10 www-data www-data 4096 Mar 19 16:17 ./
drwxr-xr-x 10 www-data www-data 4096 Mar 19 16:11 ../
drwxrwxrwx  3 www-data www-data 4096 Mar 20 09:20 api/

Now I get a Post error.  Won't even let me in.
POST http://orsepsie005.jf.intel.com/tbrd/api/login 403 (Forbidden)angular.js:9818 (anonymous function)angular.js:9619 sendReqangular.js:9335 $get.serverRequestangular.js:13175 processQueueangular.js:13191 (anonymous function)angular.js:14388 $get.Scope.$evalangular.js:14204 $get.Scope.$digestangular.js:14493 $get.Scope.$applyangular.js:21427 (anonymous function)jquery-1.11.2.min.js:3 m.event.dispatchjquery-1.11.2.min.js:3 m.event.add.r.handle

$ php -v
PHP 5.5.3-1ubuntu2.6 (cli) (built: Jul  7 2014 16:54:32) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2013 Zend Technologies
    with Zend OPcache v7.0.3-dev, Copyright (c) 1999-2013, by Zend Technologies

**Comment by rvireday** [comment]
Ah, now I see I'm getting permission denied to access /tbrd/api/ on this server.

And
[Fri Mar 20 11:58:42.220395 2015] [rewrite:error] [pid 25016] [client 10.23.51.93:65085] AH00670: Options FollowSymLinks and SymLinksIfOwnerMatch are both off, so the RewriteRule directive is also forbidden due to its similar ability to circumvent directory restrictions : /var/www/tbrd/api/

**Comment by rvireday** [comment]
In the /tbrd/.htaccess I put the following,
Options +FollowSimLinks +SymLinksIfOwnerMatch +RewriteRule +MultiViews

And now I see the dir listing for the api/.    Get a 404 (Not Found) Sign in
Hmmm....  Night.

**Comment by kiswa** [comment]
Well, I'm glad you're moving forward on this! A directory listing means the `.php` extension is not being parsed correctly. If you go to `tbrd/api/api.php` does it show the contents of the file? If so it's a PHP setup issue. Let me know how you progress and I'll help where I can.

**Comment by rvireday** [comment]
No, tbrd/api/api.php shows nothing.   Is there a simple argument to /api.php& that I can try with too?

Still getting 404 error in Chrome
POST http://server/tbrd/api/login 404 (Not Found)angular.js:9818 (anonymous function)angular.js:9619 sendReqangular.js:9335 $get.serverRequestangular.js:13175 processQueueangular.js:13191 (anonymous function)angular.js:14388 $get.Scope.$evalangular.js:14204 $get.Scope.$digestangular.js:14493 $get.Scope.$applyangular.js:21427 (anonymous function)jquery-1.11.2.min.js:3 m.event.dispatchjquery-1.11.2.min.js:3 m.event.add.r.handle

In IE, I get a Loading... spinner?
That console shows
HTML1202: http://SERVER/tbrd/ is running in Compatibility View because 'Display intranet sites in Compatibility View' is checked. 
tbrd
TypeError: Object expected
   at Anonymous function (http://SERVER/tbrd/lib/angular.js:9367:11)
   at processQueue (http://SERVER/tbrd/lib/angular.js:13175:11)
   at Anonymous function (http://SERVER/tbrd/lib/angular.js:13191:27)
   at $eval (http://SERVER/tbrd/lib/angular.js:14388:9)
   at $digest (http://SERVER/tbrd/lib/angular.js:14204:15)
   at $apply (http://SERVER/tbrd/lib/angular.js:14493:13)
   at done (http://SERVER/tbrd/lib/angular.js:9650:36)
   at completeRequest (http://SERVER/tbrd/lib/angular.js:9840:7)
   at requestLoaded (http://SERVER/tbrd/lib/angular.js:9781:9) 

Settings gets me loading, then "Something went wrong loading users".   Curiouser and Curiouser, said the cat.

**Comment by rvireday** [comment]
I'm thinking its the Rewrite rules?    Getting the 404 error, login /tbrd/api/login not found.
But, they are on in the local .htaccess.   However, I can't put those options in the top-level apache2.conf.  Complains when I turn it on at the top, so maybe that is the problem?

   Illegal option RewriteRule
   Action 'configtest' failed.

**Comment by kiswa** [comment]
Sounds like an issue with the permissions for `mod_rewrite`.

Try using this:
```
<Directory "/var/www/tbrd">
    AllowOverride All
    Options All
    Require all granted
</Directory>
```

**Comment by rvireday** [comment]
That helped to get closer.  Getting unauthorized messages for current, boards and authenticate.  
Navigating to tbrd/api, I get 404 (Not found).   tbrd/api/api.php, 404 as well.

I'll keep poking at it a bit, but am running out of time.  Still want to try on another system, a true Ubuntu.  BTW, thanks for all your help so far!

   GET http://SERVER/tbrd/api/users/current 
   401 (Unauthorized)angular.js:9818 (anonymous function)angular.js:9619 sendReqangular.js:9335 $get.serverRequestangular.js:13175 processQueueangular.js:13191 (anonymous function)angular.js:14388 $get.Scope.$evalangular.js:14204 $get.Scope.$digestangular.js:14493 $get.Scope.$applyangular.js:9650 doneangular.js:9840 completeRequestangular.js:9781 requestLoaded angular.js:9818 
GET http://SERVER/tbrd/api/boards  401 (Unauthorized)angular.js:9818  ...snip...
GET http://SERVER/tbrd/api/authenticate  401 (Unauthorized)angular.js:9818 ...snip... 
TypeError: undefined is not a function
    at angular.js:9367
    at processQueue (angular.js:13175)
    at angular.js:13191
    at Scope.$get.Scope.$eval (angular.js:14388)
    at Scope.$get.Scope.$digest (angular.js:14204)
    at Scope.$get.Scope.$apply (angular.js:14493)
    at done (angular.js:9650)
    at completeRequest (angular.js:9840)
    at XMLHttpRequest.requestLoaded (angular.js:9781)angular.js:11598 (anonymous function)angular.js:8548 $getangular.js:13183 processQueueangular.js:13191 (anonymous function)angular.js:14388 $get.Scope.$evalangular.js:14204 $get.Scope.$digestangular.js:14493 $get.Scope.$applyangular.js:9650 doneangular.js:9840 completeRequestangular.js:9781 requestLoaded

**Comment by kiswa** [comment]
I'm going to close this since it's been a week now. Let me know if you're still stuck.
