### ISSUE TITLE
Activity log as RSS/Atom channel

### ISSUE THREAD

**Issue by morvy** [kiswa/TaskBoard#149]
Is it possible to enhance TaskBoard to show all activity on selected board as RSS channel ? If there are multiple boards, then multiple RSS channels could be available.

**Comment by kiswa** [comment]
I'll have to look into this. My first thought is that it should be doable, but it may require some significant changes.

Is this something the community is interested in?

**Comment by morvy** [comment]
well, that's the question, if community is interested :) me and my team are all using RSS, we used Collabtive before, but that's too complex tool for our needs.
I was thinking about chekbox on add/edit/delete items (checked by default) to include this action in Board RSS, so just visual change to item will not get into RSS feed. Feeds can be password protected, so using user name/pass or just some kind of board name + generic board pass. I would help, but this is just a big magic how you did the tool :D I would simply use generic select and make RSS file with simple htaccess rewrite rss.php to rss.xml :)
