### ISSUE TITLE
Rewrite API for public consumption

### ISSUE THREAD

**Issue by kiswa** [kiswa/TaskBoard#152]
The API needs to be rewritten for the following reasons:
1. Consistent names
2. Encapsulate access into classes
3. Improve logging/activity reporting

**Comment by hesco** [comment]
And by public consumption, I am imagining integration using hooks and triggers with our ticketing system (we use RT by Best Practical) and long term with an ldap driven single sign-on system for user authentication and authorization queries.  -- Hugh
