### ISSUE TITLE
Automatic color change issue

### ISSUE THREAD

**Issue by k4r7u** [kiswa/TaskBoard#153]
![image](https://cloud.githubusercontent.com/assets/8782287/6913737/df7f13ba-d783-11e4-8d8c-98bc510d26ad.png)

After adding rules to change the item color, the automatic change does not work as expected.
Sometimes moving an item immediately changes the color, sometimes there is a delay and sometimes the color doesn't change at all.
I checked the database and if no color change happens, the color-value for this item isn't changed in the database, even though the item has been moved and a rule should apply and change the color.

Unfortunately there are no errors in the webserver or php logs.
Has anybody else detected this behavior?

**Comment by kiswa** [comment]
I'll look into this.

**Comment by iamthemuffinman** [comment]
@k4r7u I've noticed it when I move a task back to where it was. Say I move a task from Waiting to Done, the color changes as expected. If I move it back however, the color stays the same as it was in the Done column.

**Comment by kiswa** [comment]
@iamthemuffinman That would make sense, unless you also have an automatic action to change the color when it moves to the previous column. Automatic actions are one-way and not automatically reversed.

**Comment by iamthemuffinman** [comment]
@kiswa So that's how they work. I understood it as all items under a column would be such and such color so long as the item exists in that column. Thanks for the enlightenment!

**Comment by drammelt** [comment]
The actions state when item is moved to column, it does not indicate direction the item is being moved. It should change colour regardless of direction.
The current behaviour is not really acceptable, for instance what if you have moved the item to the next column by accident.

**Comment by kiswa** [comment]
@drammelt Re-read what you posted.

When an item is moved **to** a column that item's color is changed by an automatic action. When you move that item to another column, it's color will not change unless that column has an automatic action set for it.

**Comment by drammelt** [comment]
All column have automatic actions to change colours. Yet only moving them left to right will change the colour. If you move the item right to left the colour does not change.
If you how ever move the item right to left and then pick it up and re-drop it on the same column the colour will be changed to the correct one.

My board has 4 columns, each one has an action to change colour...
![Actions](http://iforce.co.nz/i/w2betpqg.s1f.png)

1. When I create an item in Proposed it is #c3f4b5 (green)
2. I move the item to column Progress it changes to #ffbaba (red)
3. I move the item back to Proposed it stays #ffbaba (red)

As you can see I have an action for the Proposed column yet the colour does not change.

**Comment by kiswa** [comment]
@drammelt That provides a lot more information and I now understand what you were getting at. This is probably what the original issue was posted about.

Either way, I'll make sure automatic actions are fully functional!

**Comment by sonictk** [comment]
Just like to add that I found this project by chance since I was looking at OSS project management solutions, and could immediately reproduce this bug as well.

**Comment by kiswa** [comment]
Yeah, it's a bug I'm working on figuring out! Cool that you happened across this though; hope you're enjoying it (quirks and all).
