### ISSUE TITLE
Allow to hide the header

### ISSUE THREAD

**Issue by k4r7u** [kiswa/TaskBoard#154]
It would be great to have a button to hide the header bar, similar to "Activity" when clicking on an item.
This would allow a more focused working.
Something similar to what Atlassian implemented in Jira:
![image](https://cloud.githubusercontent.com/assets/8782287/6918136/2f982d88-d7ab-11e4-96a1-18b79c87d041.png)

**Comment by kiswa** [comment]
Nice idea, thanks.
