### ISSUE TITLE
Drag items to minimized columns

### ISSUE THREAD

**Issue by hi2u** [kiswa/TaskBoard#155]
I assume that a good chunk of people using TaskBoard have a "Done" column on the left or right of their board that is usually kept minimized?

It would be great if we could drag items to the minimized list.  It would be more efficient than using the right-click menu or having to maximize & minimize the column every time.

**Comment by kiswa** [comment]
This is not possible with the current state of things (see #9).

If someone wants to undertake it, best of luck to them.

**Comment by morvy** [comment]
If you remove the dropdown and leave lanes as list in edit item, it's at least 1 step less, there is plenty of space for right click menu + it would be easier to move items on tablets/smartphones
