### ISSUE TITLE
Install problems 

### ISSUE THREAD

**Issue by torwag** [kiswa/TaskBoard#159]
Hi,
I still face the same installation problems as described earlier.

#123 

I followed the entire thread and double-checked all suggestions to no avail.
Would be glad if we could reactivate the old issue and merge this ticket with the older thread.

Thanks

Torsten

Sorry for the duplication, seemed nobody checked for the closed issue anymore and hey, you get the nice warm feeling for marking this one as solved and closed ;)

**Comment by kiswa** [comment]
Did that include going through #3 and #7 for more info?

I'm not entirely sure what the problem you're having is. Can you re-clone the repo and start fresh?

Here's what I do to setup a new instance (I'm on Arch as well, FWIW):
 1. Clone the repo
 2. Enter `TaskBoard` directory and `chmod 0777 api`
 3. Log into the site

However, from my first install, I did set the following in `/etc/httpd/conf/httpd.conf`
```
<Directory "/the/parent/directory/">
    AllowOverride All
    Options All
    Require all granted
</Directory>
```
I also enabled these modules
```
LoadModule mpm_prefork_module modules/mom_mpm_prefork.so
LoadModule rewrite_module modules/mom_rewrite.so
LoadModule php5_module modules/libphp5.so
```

As well as enabling the following in `/etc/php/php.ini`
```
extension=bz2.so
extension=pdo_sqlite.so
extension=sqlite3.so
extension=zip.so
```

That is everything I can think of that may be different from a default setup of Apache and PHP5.

**Comment by torwag** [comment]
Hi,
I got it working. What was mainly missing was 
```
extension=pdo_sqlite.so
extension=sqlite3.so
```
in php.ini
and I had to install the package 
```php-sqlite```

I reverted the settings and got the same error message about the API and to make sure it is writable.  Thus, the error message is maybe a bit misleading. I use owncloud on the same machine and for that it uses 
```
extension=pdo_mysql.so
extension=mysql.so
```
and I thought that should be sufficient.
Your above comment, might be a worse to be added to the readme install section.
I am not sure the current solution is the best (using two sql modules). Can I configure taskboard to use mysql as well?
Thanks for the help and have fund marking this as solved and closing this issue ;)

**Comment by kiswa** [comment]
You can absolutely configure it to use MySQL. Just go into `api/api.php` and change line 33 so instead of `R::setup('sqlite:taskboard.db');` it is `R::setup( 'mysql:host=localhost;dbname=mydatabase', 'user', 'password' );` with your MySQL settings. See here for more details: http://www.redbeanphp.com/connection
