### ISSUE TITLE
Connection to owncloud

### ISSUE THREAD

**Issue by torwag** [kiswa/TaskBoard#161]
Hi,
Adding an owncloud link (both shared and from the file view within owncloud) in a item description works very well. I believe this  nicely combines capabilities of owncloud and Taskboard. It might be worse to add this as an example. In case the owncloud user is logged in clicking the link will start a download. If not logged in, the owncloud login window will appear and after that the download will be started. 
E.g.
```
[https://demo.owncloud.org/index.php/apps/files/ajax/download.php?dir=%2F&files=Demo%20Image%20-%20ccc.jpg](Owncloud Demo Server Image)
```
will allow to directly download an image from the owncloud demo server.

**Comment by kiswa** [comment]
This is more of a 'learning to use Markdown' thing. Maybe I can update the documentation to point out how useful Markdown can be and emphasize following the link to learn more about it.

**Comment by torwag** [comment]
Well I agree it is not an issue.
However, I was happy to notice that the interaction with other programs works via links rather well. You can also link against online mailers like gmail.
You are right, it might be worse to add this to the documentation.
However, it might be somehow related to #160  if you consider adding a toolbar to the description field
