### ISSUE TITLE
Bug - loading boards, users..

### ISSUE THREAD

**Issue by urza** [kiswa/TaskBoard#162]
I am experiencing the issue of  #133 (I posted it there, but it is closed, so I dont know if it notifies someone at all).

It is the first time, i uploaded TaskBoard to my php hosting, so it may be that they do not support some dependecy?

Thanks for any help.

**Comment by kiswa** [comment]
It does notify me, but no problem. I don't know what level of access you have to your server, but look through #3 #7 and #159 and let me know if anything in there helps.

**Comment by sonictk** [comment]
Hi, I just tried doing an installation of Taskboard as well, and I'm also running into this issue.

A screenshot of the settings page where it's stuck at along with some traceback information:
http://i.imgur.com/UCVRmiD.png

**Comment by kiswa** [comment]
Thank you for the details! I've been rather out of TaskBoard development, but I'm getting back on it so hopefully this will be addressed soon.
