### ISSUE TITLE
Idea for Overview

### ISSUE THREAD

**Issue by urza** [kiswa/TaskBoard#163]
Hi, I have an idea for planned overview page.

I would like to use TaskBoard for my personal projects (one board one project) and I would like to see some overall progress on all projects. Maybe something similar to how github displays milestone issues.

![github_progress](https://cloud.githubusercontent.com/assets/189804/7153162/f16cc4a8-e347-11e4-817f-df130ddd202d.png)

It is psychologically very rewarding to see some progress.. that is why people like to check their todo as done and get the little dopamine shot.

I am aware that kanban boards may have different columns, so maybe just show percentage of tasks in each column? And progressbar devided into sections by this percentage? Would it be possible to specify color for some columns so that "done" could be green on that progressbar?

Or is it overkill?

**Comment by kiswa** [comment]
I think that sounds do-able, and I agree that having a visual indicator like that would be nice to see.
