### ISSUE TITLE
/api/login not being downloaded

### ISSUE THREAD

**Issue by Kickball** [kiswa/TaskBoard#164]
When I clone the repo:

>  sudo git clone https://github.com/kiswa/TaskBoard.git

and then navigate to the machine in a web browser I am given the following error while trying to log in.

> Failed to load resource: the server responded with a status of 404 (Not Found) http://URLtoTaskBoard/TaskBoard/api/login

What could I have done wrong? 

This is the contents of the api folder if it helps:

user@server:/var/www/html/TaskBoard/api$ ls
api.php          helpers.php     jsonResponse.php  userRoutes.php
boardRoutes.php  itemRoutes.php  lib

**Comment by kiswa** [comment]
Take a look through #3, #7, and #159 (maybe start with this one) and let me know if you still need assistance.

**Comment by Kickball** [comment]
I solved the following error:


> Failed to load resource: the server responded with a status of 404 (Not Found) http://taskboard.domain.com/TaskBoard/api/login

I solved it by setting the following in /etc/apache2/apache2.conf

    <Directory /var/www/html/TaskBoard>
        AllowOverride All
        Options All
        Require all granted
    </Directory>

**Comment by Kickball** [comment]
I've ran into another problem, when I tried to create a new user I had these errors in the development log: http://i.imgur.com/emoSPLI.png

Any suggestions on fixing them?

**Comment by Kickball** [comment]
I fixed the issue by giving the www-data group control of the TaskBoard directories.

**Comment by kiswa** [comment]
Glad you worked it out!

**Comment by bevinhex** [comment]
I'm seeing the same error here, My configuration is like this:
```
<VirtualHost *:80>
        ServerName test.vsfas.info
        DocumentRoot /opt/TaskBoard
        <Directory />
                AllowOverride All
                Options All
                Require all granted
        </Directory>
</VirtualHost>
```
````
ls -l /opt
drwxr-xr-x 12 www-data www-data 4096 Jan 11 11:39 TaskBoard
```

**Comment by bevinhex** [comment]
Never mind now, solved it by
```
sudo a2enmod expires
```

**Comment by kiswa** [comment]
@bevinhex I have modified the `.htacess` in the `re-write` branch to remove the need for the expires module, so this won't be an issue in the future (whenever I finally get the re-write done).
