### ISSUE TITLE
Install - unauthorized access? Bumps back to login.

### ISSUE THREAD

**Issue by rvireday** [kiswa/TaskBoard#169]
So, I created a new instance, got it from Github directly. 

Tried first with sqlite, but still not working, so I switched it to the MySQL interface.
Because [HY000] - SQLSTATE[HY000]: General error: 8 attempt to write a readonly database
Yes, the entire TaskBoard tree is owned by my apache2 user, www-data:
Yes, the api/ directory is writable.  But obviously not totally correctly writable for some reason.

Since MySQL seems to work, I start the login process and it creates the tables.   Then, it blows me back to the login prompt.   And I'm supposedly logged in, but ain't.

/etc/apache2/apache2.conf and /etc/apache2/sites-enabled/000-default.conf 
both have the directive.
\<Directory /var/www/TaskBoard\>
        AllowOverride All
        Options All
        Require all granted
\</Directory\>

This is the console output below.   Any clues??  Thanks.

GET http://server/TaskBoard/api/boards 401 (Unauthorized)(anonymous function) @ libs.min.js:486ea @ libs.min.js:481g @ libs.min.js:479p @ libs.min.js:507(anonymous function) @ libs.min.js:509l.$eval @ libs.min.js:519l.$digest @ libs.min.js:516l.$apply @ libs.min.js:520h @ libs.min.js:480t @ libs.min.js:485r.onreadystatechange @ libs.min.js:486
libs.min.js:486 
a	@	libs.min.js:486
ea	@	libs.min.js:481
$get.g	@	libs.min.js:479
l.promise.then.p	@	libs.min.js:507
(anonymous function)	@	libs.min.js:509
$get.l.$eval	@	libs.min.js:519
$get.l.$digest	@	libs.min.js:516
$get.l.$apply	@	libs.min.js:520
h	@	libs.min.js:480
t	@	libs.min.js:485
r.onreadystatechange	@	libs.min.js:486

GET http://server/TaskBoard/api/users/current 401 (Unauthorized)(anonymous function) @ libs.min.js:486ea @ libs.min.js:481g @ libs.min.js:479p @ libs.min.js:507(anonymous function) @ libs.min.js:509l.$eval @ libs.min.js:519l.$digest @ libs.min.js:516l.$apply @ libs.min.js:520h @ libs.min.js:480t @ libs.min.js:485r.onreadystatechange @ libs.min.js:486
libs.min.js:486 
GET http://server/TaskBoard/api/authenticate 401 (Unauthorized)(anonymous function) @ libs.min.js:486ea @ libs.min.js:481g @ libs.min.js:479p @ libs.min.js:507(anonymous function) @ libs.min.js:509l.$eval @ libs.min.js:519l.$digest @ libs.min.js:516l.$apply @ libs.min.js:520h @ libs.min.js:480t @ libs.min.js:485r.onreadystatechange @ libs.min.js:486
libs.min.js:500 TypeError: a is not a function
    at libs.min.js:479
    at n (libs.min.js:508)
    at n (libs.min.js:508)
    at libs.min.js:509
    at l.$eval (libs.min.js:519)
    at l.$digest (libs.min.js:516)
    at l.$apply (libs.min.js:520)
    at h (libs.min.js:480)
    at t (libs.min.js:485)
    at XMLHttpRequest.r.onreadystatechange (libs.min.js:486)

**Comment by ToeiRei** [comment]
This looks like an apache/php issue to me. Could you provide more detail about your system? (apache version, php version,...)

**Comment by kiswa** [comment]
If you haven't already, look through #3 and #7 as they seem to help most people with initial issues.

**Comment by kiswa** [comment]
Closing due to lack of response.

Let me know if this needs to be re-opened.
