### ISSUE TITLE
Create a CONTRIBUTING file

### ISSUE THREAD

**Issue by woodworker** [kiswa/TaskBoard#170]
I really like your project and may also want to contribute a bit with bugfixing/features
but my first PR was not accepted because you wanted to have PR agains the dev branch.

To make it easier for other please create a CONTRIBUTING file for all the others that may want to help.

See: https://github.com/blog/1184-contributing-guidelines

**Comment by kiswa** [comment]
I actually have the basics listed in [the Wiki](https://github.com/kiswa/TaskBoard/wiki) and the main description has "Don't forget to read the Wiki page!"

Though I guess this shows how much that gets looked at.

**Comment by kiswa** [comment]
Whoops, wrong button!

**Comment by woodworker** [comment]
Yes, the nice thing about the contributing file is that github always shows the link to the file when you want to create a PR, this may help a bit more

**Comment by kiswa** [comment]
Yeah, seeing that integration makes it seem worth adding. Though it'll basically be a copy of the wiki page. ;)
