### ISSUE TITLE
PHP-Problem

### ISSUE THREAD

**Issue by jazzcrack** [kiswa/TaskBoard#174]
TaskBoard have the known "Bumps back to login"-problem. The solution is to use Mod-PHP.

With Fast-CGI, CGI or SuPHP you have the "Bumps back to login" after login problem.

**Comment by kiswa** [comment]
Is this just posted for future searchers? I'm not seeing an actual issue, just a statement.

**Comment by woodworker** [comment]
is it maybe because your fsstcgi, cgi or suphp is running under a different user then the taskboard.db file was created with?

**Comment by jazzcrack** [comment]
Using MySQL   

---Sent from Boxer | http://getboxer.com

On 26. April 2015 16:50:59 MESZ, Martin Holzhauer <notifications@github.com> wrote:is it maybe because your fsstcgi, cgi or suphp is running under a different user then the taskboard.db file was created with?  —Reply to this email directly or view it on GitHub.
