### ISSUE TITLE
Drop down boxes offset by 1 when editing item.

### ISSUE THREAD

**Issue by drammelt** [kiswa/TaskBoard#176]
Version: 0.3 (dev)

All selection boxes are offset by 1 when editing items.
- Eg. If I select the third item in the drop down box it will result in item number 2 being selected.
  
  0 - Item 1
  1 - Item 2
  2 - Item 3

So I select Number 3, your code is returning 2 so I am guessing you are not correcting for zeroed list?

**Comment by kiswa** [comment]
What browser and could you give a visual so I understand exactly what you mean?

**Comment by drammelt** [comment]
Firefox 37.0.2

![Selection Image](http://iforce.co.nz/i/0j0t235k.yqa.png)

**Comment by kiswa** [comment]
Interesting. Thanks for the additional info, I'll look into this.
