### ISSUE TITLE
Auto color for categories

### ISSUE THREAD

**Issue by Matthias84** [kiswa/TaskBoard#177]
Hi, I use the category to tag tasks that relate to projects. Sadly currently I can't automaticly assign a colour to the single category via an custom action. As this is allready possible for user and column , could you please add actions that can change the color for categories?

**Comment by kiswa** [comment]
I feel like this was a bug that has been corrected in v0.3.0 (`dev` at the moment). Let me know if you're using `dev` so I know if this still needs fixing.

**Comment by Matthias84** [comment]
Thanks @kiswa No I'm not using Dev already, but will wait for 0.3 final release and check it out!
