### ISSUE TITLE
Automatic action "Item moves to column" triggers error

### ISSUE THREAD

**Issue by FWmaster** [kiswa/TaskBoard#179]
When automatic action of type "Item moves to column" is added, the app triggers the following error in google chrome console at every call of /api/autoactions script :
TypeError: Cannot read property 'ownLane' of undefined
    at g (http://[domain]/js/app.min.js:25:338)
    at http://[domain]/js/app.min.js:27:74
    at Array.forEach (native)
    at k (http://[domain]/js/app.min.js:26:337)
    at http://[domain]/js/app.min.js:27:192
    at http://[domain]/lib/libs.min.js:479:374
    at l.promise.then.p (http://[domain]/lib/libs.min.js:507:469)
    at http://[domain]/lib/libs.min.js:509:126
    at l.$get.l.$eval (http://[domain]/lib/libs.min.js:519:393)
    at l.$get.l.$digest (http://[domain]/lib/libs.min.js:516:489)

tasks of type "item assigned to user" work fine

**Comment by kiswa** [comment]
I'll look into this.

**Comment by Djcd** [comment]
Hello kiswa,
thanks for your efforts on TaskBoard :). 

I think the error is created by the following Scenario: Creating a new Board, adding some auto Actions and deleting the Board. The File boardRoutes.php  does not clean the Autoactions for this specific deleted board. I hope i made this fix right.

Greetings from Germany
David

**Comment by kiswa** [comment]
Thanks for the additional info, I'll look into it!
