### ISSUE TITLE
Feature request : Allow users to delete tasks without being admin

### ISSUE THREAD

**Issue by Dark-Fenix** [kiswa/TaskBoard#180]
Hi,

I think it could be useful if users could delete by themselves the tasks of the boards they are assigned to. Or give a special right to do so, for example "standard users" (no rights to delete) and "board manager". IMHO, the "admin" right is too permissive, allowing everyone to change users passwords ! :)

Thank you for this great new alternative to Trello, as light as needed for our projects !

**Comment by olaulau** [comment]
in fact, standard users can remove an item. they just got "Insufficient user privileges." error in the JSON response, which is disconnecting them. but the item is still removed !
