### ISSUE TITLE
Feature request : Give the ability to users to create their own boards

### ISSUE THREAD

**Issue by Dark-Fenix** [kiswa/TaskBoard#181]
Hi,

For the same reason of my previous feature request (IMHO, "admin" is too persmissive for just managing boards), I would appreciate in such a tool that users could create their own boards and share it with the users they want, becoming immediately the manager of this board.

Thanks and good luck ! I'm not good enough to help you working on the code, but I'm in if you need some tests !

**Comment by hdrrizvi** [comment]
its important, i second
