### ISSUE TITLE
Is it possible to handle subtasks ?

### ISSUE THREAD

**Issue by LoucIsZbib** [kiswa/TaskBoard#182]
It would be great if TaskBoard can handle sub-tasks.
I don't know how it could be done : either allowing to create items in another item, or by linking to an other board (I do such way with the url of the other board, but using a board for 3 item isn't really pertinent) or just a check-list in description (with box to check)

For example, I have a project with ten items, each items can be itself cut into 3 items, and sometimes I can't process all the 3 (sub)items to move the main item to another column. It goes fast into something fuzzy to remember what has been done or not when not moving the items.

PS maybe there is a way to do such thing with comments ? but how ? I take all your ideas :) 

PS' TaskBoard is a great tool by the way !

**Comment by Dark-Fenix** [comment]
+1 :)

**Comment by kwijk** [comment]
I would like to provide an argument here in support of this feature request. 

Tasks used in a kanban tool like TaskBoard are often connected hierarchically. For me, as a Product Manager for a software company I create epic stories. The epics are split into user stories during discussions with the development team. Each User Story again is divided into (implementation) Tasks. It would be great to put all the tasks of a user story on the TaskBoard. Once all the tasks are done the User Story (the parent task) is done. 
For me as a Product Manager I am only interested to know when all Tasks for a Story are done, so i can start testing and demoing it.

**Comment by sunrez** [comment]
+100 !  Sub-task support is very important.  While one can add bullets with markdown, it's hard to either check these off, or assign due dates.

**Comment by hubutz** [comment]
Yeah, subtasks would come in really handy!

**Comment by devnewton** [comment]
It would be a nice implementation of http://toolsforagile.com/blog/archives/598/multi-tier-kanban

**Comment by rh-programm** [comment]
Hey, you could simply add markdown checkpoxes - as well as on github: https://help.github.com/articles/about-task-lists/

**Comment by kiswa** [comment]
@rh-programm That has actually been implemented in the re-write branch!
