### ISSUE TITLE
5 or 5.5

### ISSUE THREAD

**Issue by reimaginemedia** [kiswa/TaskBoard#183]
hi...

In the front of your page, I thought it could run via php 5 - any at that, but then I installed on 5.3 and saw some elements just not working. So read-on and saw that it needed 5.5. No chance for 5.3 on this I am understanding correctly?

**Comment by reimaginemedia** [comment]
anyhow it just keeps - not showing boards or users...

**Comment by fuzzy76** [comment]
PHP 5.3 has been unsupported for 9 months now, which means it has known unfixed security holes. You really shouldn't be using it. http://php.net/eol.php

**Comment by kiswa** [comment]
You are correct, PHP 5.3 does not work with TaskBoard (or most of its dependencies).
