### ISSUE TITLE
Loading Boards & Users

### ISSUE THREAD

**Issue by schesnel** [kiswa/TaskBoard#187]
Hi,

I have this message just after install: Loading Boards and Loading Users.
Current Actions work.

Could you help me ?

**Comment by Fla77y** [comment]
I have the same problem... :(

**Comment by kiswa** [comment]
Sounds like something is missing in the setup. Tale a lok at #3 and #7 and see if anything there helps.

I'm going to close this assuming those help. If not, let me know and I'll re-open.
