### ISSUE TITLE
NOTICE: There has been a death in the family. I do not know when I will get back to TaskBoard work.

### ISSUE THREAD

**Issue by kiswa** [kiswa/TaskBoard#188]
I'm hoping to get back to "normal" in the next few weeks, whatever that means now.

If you were thinking about donating to TaskBoard, please [make a donation to the Wounded Warrior Project instead](https://support.woundedwarriorproject.org/default.aspx?tsid=72) (in honor of my brother, Christopher Traver).

Thank you.

**Comment by captainwasabi** [comment]
My condolences to you and your family. :(
