### ISSUE TITLE
Doesn't seem to create the /login folder during install

### ISSUE THREAD

**Issue by turbo-toni** [kiswa/TaskBoard#190]
I get this error after following the installation instructions and trying to log in using 'admin' 'admin':

POST http://mrpjenkins.wtf.nap/api/login 404 (Not Found)
a @ libs.min.js:486
ea @ libs.min.js:481
$get.g @ libs.min.js:479
l.promise.then.p @ libs.min.js:507
(anonymous function) @ libs.min.js:509
$get.l.$eval @ libs.min.js:519
$get.l.$digest @ libs.min.js:516
$get.l.$apply @ libs.min.js:520
(anonymous function) @ libs.min.js:602
g.event.dispatch @ libs.min.js:92
g.event.add.p.handle @ libs.min.js:86

I know it's something I've done wrong but I can't figure it out.  I've tried creating the folder but that just produces a different error.  

Help anyone?

**Comment by kiswa** [comment]
There is no `api/login` folder, as it is a rewrite for the API. If you're getting a 404, then something is off with either Apache (or nginx) or with your PHP install.

Take a look at #3, #7, and #102 to see if anything in there helps.

I'm going to close this, but please reply if you don't get what you need from previous issues and I'll re-open.
