### ISSUE TITLE
color doesn't update

### ISSUE THREAD

**Issue by lizurd** [kiswa/TaskBoard#196]
Hi there

Sorry to bug you, I really like the ease of use of TaskBoard so far!  I've looked through all of the issues and solved most of my install problems, but the one remaining issue is that the color doesn't update -- no matter whether I use automatic actions or if I just manually try to set the color of an item.  I can update the individual tasks, no problem.  

I made sure the TaskBoard directory has the correct privileges, re-looked at issues #3, #7, and #159.

Using Apache 2.4 on Windows 8 (just a prototype machine for trying these things out), the only difference I can see to what you listed on other issues is that I am missing these options within Apache:

LoadModule mpm_prefork_module modules/mom_mpm_prefork.so

and this within PHP 5.6:
extension=zip.so

Did I grab the wrong version of Apache or PHP, or both?

**Comment by kiswa** [comment]
Are you on v0.3.0? PHP and Apache versions seem fine.

Can you bring up F12 developer tools and let me know if any error messages show up when you try changing a task's color?

**Comment by kiswa** [comment]
Closing due to lack of response.

Let me know if this needs to be re-opened.
