### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by heenameena** [kiswa/TaskBoard#197]
I copied the taskboard folders and files to the location that I want to use taskboard. I updated api folder with write permissions, however I am unable to login using admin as username and password. When I enter admin as username and password and click sign in, neither it throws an error or let me login in. Please advise.
Thanks,
Heena

**Comment by kiswa** [comment]
Take a look through #3 and #7 and see if those help.

**Comment by heenameena** [comment]
I tried all options indicated in #3 and #7 but didn't help. 
I am on PHP 5.5.9, sqlite 3.8.2, apache 2
I changed permissions of api directory to 777
I enabled rewrite and expires apache modules

I am still not be able to login, from chrome dev tools I noticed 500 internal server error.

Please help me what could be wrong and how I can fix this issue. Thanks for your help and time.

Thanks,
Heena

**Comment by heenameena** [comment]
Here is the error from apache error.log file:

PHP Fatal error:  require_once(): Failed opening required '/var/www/html/api/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/api/api.php on line 3

I didn't find autoload.php or vendor folder.

Does it ring a bell what could be the issue?

Thanks,
Heena

**Comment by heenameena** [comment]
captured same error from chrome dev tools:

Warning: require_once(/var/www/html/api/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/api/api.php on line 3

Fatal error: require_once(): Failed opening required '/var/www/html/api/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/api/api.php on line 3

Please help to resolve the issue.

**Comment by kiswa** [comment]
That sounds like you haven't install the PHP dependencies via Composer.

>Install the PHP dependencies via composer. Open TaskBoard/build/ in a terminal and run .composer.phar install

Let me know if that fixes it for you!

**Comment by nevtum** [comment]
This same problem happens with the dockerized version:

1. go into build folder
2. docker build -t taskboard-img .
3. docker run -d -p 80:80 taskboard-img
4. try sign in with u:admin, pw:admin

500 internal server error seen from chrome dev tools

**Comment by heenameena** [comment]
Yes, I didn't run the composer. Does it need access to the internet?  The server where taskboard is located doesn't have access to internet. Is there any way I can get dependencies downloaded on my desktop (which has internet access) and copy them over to taskboard server? If so how, and where I can find those dependencies? Thanks again for your help.

**Comment by kiswa** [comment]
It does need internet access, yes. Here's a copy of the latest `vendor` directory with everything in it: https://www.dropbox.com/s/tkdftobzlze02uw/vendor.tar.gz?dl=0 I'll leave it up for a little while.

For future posterity, you could always run the install from a web-connected machine and copy the contents of the `vendor` directory to your disconnected machine.

**Comment by kiswa** [comment]
@nevtum I've never used the Docker setup. It was provided in a PR. I imagine it needs updating since TaskBoard moved to using Composer to install PHP dependencies. Feel free to submit a PR against `dev` if you can fix it.
