### ISSUE TITLE
@TaskBoard's */api/users/current is Broken... 

### ISSUE THREAD

**Issue by IGitSylvia** [kiswa/TaskBoard#202]
Hey Matt, I just wanted to let you know that your TaskBoard is currently not working very well... it looks like by the an issue which affected the RESTfulness. Check out the Headers Error I copied Chrome's Console below. 

Perhaps data "corruption" caused by someone overloading or "testing" the parsing|validation|vulnerabilities of your app? Either way I just wanted to let you know. 

Remote Address:104.131.221.216:80
Request URL:http://taskboard.matthewross.me/demo/api/users/current
Request Method:GET
Status Code:500 Internal Server Error

**Comment by kiswa** [comment]
Thanks for reporting this. Turns out I didn't update the DB it restores from every hour to have the new table needed in v0.3.0. I'll try to fix it this afternoon.

**Comment by kiswa** [comment]
So... not this afternoon, but I'll fix it soon.
