### ISSUE TITLE
Loading in Settings screen, can't edit anything

### ISSUE THREAD

**Issue by oliverh72** [kiswa/TaskBoard#204]
Hi,

I've checked the previous issues that seemed to have the same problem, such as #162 and #133 . Those seem to be due to the php5_sqlite extension not working. I've checked with site5 (where I'm hosted) and it seems to fit the prereqs. Here's the phpinfo for their servers: http://s1-dallas.accountservergroup.com/phpinfo.php

I'm actually running 5.4.41 and sqlite 3.3.6.

To mitigate that, as you mentioned in an earlier issue, I went in and changed api.php to use a mysql db I set up on the server, then deleted the token, but still no go.

If I check it out using developer tools in the network section, I get this on each of the processes: Fatal error: require_once(): Failed opening required '/serverpath/api/../vendor/autoload.php' (include_path='.:/usr/local/php53/lib:/usr/lib/php:/usr/local/lib/php') in /serverpath/api/api.php on line 3

...obviously 'serverpath' is just what I replaced the full path with. :)

Thoughts?

I'm also getting this error in angular.js, which doesn't surprise me as it clearly isn't able to connect to the db.

TypeError: Cannot read property 'options' of undefined
    at loadOptionsData (settings.js:31)
    at settings.js:24
    at angular.js:9408
    at processQueue (angular.js:13248)
    at angular.js:13264
    at Scope.$get.Scope.$eval (angular.js:14466)
    at Scope.$get.Scope.$digest (angular.js:14282)
    at Scope.$get.Scope.$apply (angular.js:14571)
    at done (angular.js:9698)
    at completeRequest (angular.js:9888)

**Comment by kiswa** [comment]
It sounds like you haven't run the composer install so the vendor directory exists with all the dependencies for the API.

2. Install the PHP dependencies via composer. Open `TaskBoard/build/` in a terminal and run `./composer.phar install`

**Comment by oliverh72** [comment]
I have no idea how I missed that. Thanks for your quick response. Works well now!!

**Comment by kiswa** [comment]
No problem!
