### ISSUE TITLE
Bugs: Actions not working, can't assign user, settings not updating

### ISSUE THREAD

**Issue by oliverh72** [kiswa/TaskBoard#205]
Hi,

So I got it installed fine once I actually followed the instructions. :)

Here's a few bugs I've found:

* I can't assign myself to a task, even if I'm the only user created. It stays unassigned
* Settings don't update automatically - for instance, I edit a board then click save, the modal just sits there. I then have to close it - on occasion, I have to refresh the settings to see the changes as well
* When I create a new task, I have to refresh the page to see it
* I can't create an action to change the color of a task upon setting the category

It looks like it's got something to do with the js in the api folder - I've set it all to 777, so I'm not sure what's going on. I'm getting 500 (internal server error) in the inspector, both on angular.js as well as jquery. 

Thanks.

**Comment by camael24** [comment]
I have same things , i run `chmod 0777 api/taskboard.db` after the first run (ie after creating the database)

Cheers.

**Comment by kiswa** [comment]
I'd need more information to figure out what's going on here. There is no JS in the API directory, so I'm not sure what you meant by that. The only thing you should need to make `0777` is the `api` directory and everything should work from there.

**Comment by kiswa** [comment]
Closing due to lack of response. Please let me know if this needs to be reopened.
