### ISSUE TITLE
TaskBoard and API Client

### ISSUE THREAD

**Issue by camael24** [kiswa/TaskBoard#206]
Hi,

Its not really an issue :D 

I use the TaskBoard to do an Desktop API, I put my code here https://github.com/camael24/taskapp
I use it in professionnal context where is so long to open the navigator go the instance ...

I plan to implement an systray icon, and the app can be available in all time :) my app don't replace you webapp its just an complement in a specific context.

I am happy to present it to you, and maybe it will good for you :) , in all case thanks to your work on TaskBoard and for the API :+1: 

Camael
Ps: (Sorry for my english)

**Comment by kiswa** [comment]
That's excellent! I'll have to keep an eye on it. Now that I know there are other projects depending upon the API, I'll have to make sure I keep it stable!

Thanks for sharing this.

PS Your English was fine. ;)
