### ISSUE TITLE
Upgrade failed / We need an upgrade guide resp. path

### ISSUE THREAD

**Issue by torwag** [kiswa/TaskBoard#209]
Hi, 
I tried to upgrade from 0.2.7 to 0.3.0. Moved the old taskboard to an bak folder. Copied the new build in place and copied taskboard.db and the upload folder from the old to the new version. In addition I made sure that the rights and owners of the files are the same.
After that I can log into the new version. However, the Board pane is empty. 
Going into settings, I can see all boards and can also open them. However, all User settings are grayed out and can not be accessed.  I tried a normal user and the admin account without luck. 
Is there any other file/setting I need to copy over from the old to the new installation?
Another way how to perform the upgrade?
How about an update script?

**Comment by torwag** [comment]
The error.log of httpd screams about:
exception 'ErrorException' with message 'Undefined offset: 0' in /usr/share/webapps/taskboard/api/userRoutes.php:143
Stack trace:
#0 /usr/share/webapps/taskboard/api/userRoutes.php(143): Slim\Slim::handleErrors(8, 'Undefined offse...', '/usr/share/weba...', 143, Array)
#1 [internal function]: {closure}()
#2 /usr/share/webapps/taskboard/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#3 /usr/share/webapps/taskboard/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#4 /usr/share/webapps/taskboard/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#5 /usr/share/webapps/taskboard/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#6 /usr/share/webapps/taskboard/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#7 /usr/share/webapps/taskboard/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#8 /usr/share/webapps/taskboard/api/api.php(51): Slim\Slim->run()
#9 {main}
Not sure this is related or helps ;)

**Comment by kiswa** [comment]
Please see #200.
