### ISSUE TITLE
Problem with new users

### ISSUE THREAD

**Issue by CIJeu** [kiswa/TaskBoard#210]
Hi,

So I got taskboard installed fine. Everything seems to work but when I created a user things went wrong. 
When the new user logged in he doesn't see any taskboard. The user can't logout etc.

This is the console output:
GET http://----------.----.net/api/users/current 500 (Internal Server Error)(anonymous function) @ libs.min.js:507
q @ libs.min.js:503
g @ libs.min.js:500
(anonymous function) @ libs.min.js:532
q.$eval @ libs.min.js:546
q.$digest @ libs.min.js:543
q.$apply @ libs.min.js:547
g @ libs.min.js:501
u @ libs.min.js:505
w.onload @ libs.min.js:506

I'm running this on Apache, PHP/5.5.9, pdo_sqlite is loaded , AllowOverride is on etc. 
I have read and done #3 and #7

The same problem is in your own demo version on your site http://taskboard.matthewross.me/demo/#/boards 
When I create there a new user I got the same problem.

Thanks.

Christian

**Comment by kiswa** [comment]
I just duplicated this, and it seems to be an issue when the user is created without a default board. I'll get it fixed soon!
