### ISSUE TITLE
User default board error

### ISSUE THREAD

**Issue by xanghe** [kiswa/TaskBoard#212]
This is a great project! I'm up and running, still learning the ins and outs of the interface, trying to replicate what I think are "bugs" before I post them here :)

When I create a new user and assign a default board to them, then click on the "Boards" button in the top right, no board is displayed. In chrome dev tools, the error is thrown when requesting `api/users/current` and this is the error: 

### Slim Application Error
The application could not run because of the following error:

#### Details
Type: ErrorException
Code: 8
Message: Undefined offset: 0
File: C:\wamp\www\taskboard\api\userRoutes.php
Line: 143

#### Trace
```
#0 C:\wamp\www\taskboard\api\userRoutes.php(143): Slim\Slim::handleErrors(8, 'Undefined offse...', 'C:\wamp\www\tas...', 143, Array)
#1 [internal function]: {closure}()
#2 C:\wamp\www\taskboard\vendor\slim\slim\Slim\Route.php(468): call_user_func_array(Object(Closure), Array)
#3 C:\wamp\www\taskboard\vendor\slim\slim\Slim\Slim.php(1357): Slim\Route->dispatch()
#4 C:\wamp\www\taskboard\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
#5 C:\wamp\www\taskboard\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
#6 C:\wamp\www\taskboard\vendor\slim\slim\Slim\Middleware\PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#7 C:\wamp\www\taskboard\vendor\slim\slim\Slim\Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#8 C:\wamp\www\taskboard\api\api.php(51): Slim\Slim->run()
#9 {main}
```

Is this a local settings thing?

Note: I did check out #210 and I did initially create the user with a default board, and the default board shows in their settings.

Thanks!

**Comment by kiswa** [comment]
This may be due to changes in the latest version on RedBeanPHP. I'll look into it.

**Comment by youssman** [comment]
Hi ! I'm running the same issue and I'd tried using an older version of RedBeanPHP, but still getting the same error.

It work nicely with one user, but I hope that I can use it with multiple users :)
