### ISSUE TITLE
No visible boards

### ISSUE THREAD

**Issue by Demesthones** [kiswa/TaskBoard#213]
So after some trial and error, and a lot of time reading up on apache, I finally got this working...mostly. 

The issue I'm running into now is that when I'm not logged in as admin, there are no visible boards for the user.  I've created a user and given it access to a board, and set that board as default, but when I load the Boards page, the board is not shown.  I can access it by going to the Settings page and then clicking on the board however.  

I read that there was an issue with creating users and not setting a default board at the time of creation, so I tried that as well and had the same issue.

Also, even though I had both of those users created as admins, neither of them are able to edit any settings, change passwords, create boards, etc.

Everything else looks great so far though!

**Comment by kiswa** [comment]
Sorry for the delay. I'm not entirely sure what's going on here. Can you provide some more detail?

**Comment by Demesthones** [comment]
I've created a few accounts using the built in admin account and given them administrator rights as well as access to view a couple boards I've put together.  When logged in as admin, everything works as it should.  
However, when logged in as any of those users, they are missing a few things.  The first is that they don't seem to actually have administrator rights as they are unable to change any of the User Settings or create new boards.  
The other thing that's missing for those users is on the main Boards page.  Even though they had been given access to one or more boards, they don't show up.
![taskboard_-_kanban_board_app_-_google_chrome_2015-09-02_10-01-51](https://cloud.githubusercontent.com/assets/4081585/9633337/5950d264-515a-11e5-907a-a7a155024f88.png)
It is possible to access them, you just have to go to the Settings page and click on a board.  Then once it opens the board, you can switch between them by using the drop down.  But if you click on the Boards button at the top, everything disappears again.

**Comment by Demesthones** [comment]
I just tried again on one of the other accounts and it also seems like they aren't able to actually add/edit any tasks.  When logged in as admin, when you click Save/Add Item/Submit, it sits on the screen with whatever it is you've submitted for a bit, then you can see it get added to the board.  When logged in as one of those users however, it sits on the submission screen and then nothing happens.

**Comment by yvschmid** [comment]
I have a vagrant box here showing the same behaviour: https://github.com/yvschmid/taskboard-vagrant

**Comment by arborrow** [comment]
I am seeing this same behavior on a local install (Ubuntu 15.04) - let me know what information I can provide to help track down this issue. Peace - Anthony

**Comment by kiswa** [comment]
Just letting everyone know I'm getting back into TaskBoard development and I'll be looking into this as part of the bugfixes that seem to be needed around user accounts.
