### ISSUE TITLE
Feature request: Allow more tags at the bottom of Item

### ISSUE THREAD

**Issue by AndyCoach** [kiswa/TaskBoard#214]
Points, due date are very useful. Would like to add admin-user-defined tags, maybe even a calculated tag. For example, if I use TaskBoard to manage projects, Items are tasks. Each task might have % complete. Or, total sample collected / total required = a ratio.

**Comment by kiswa** [comment]
That's an interesting idea. I'll look into it.

**Comment by SebastianZ** [comment]
I guess that also covers labels like here on GitHub, right?

Sebastian
