### ISSUE TITLE
Hard reset password for user?

### ISSUE THREAD

**Issue by taikedz** [kiswa/TaskBoard#215]
After not using TaskBoard for a while I decided to return to it and update it to see what it was currently like.

I've found that I cannot remember what creds I registered my user as....

What's the procedure to look up users and reset passwords via database? I checked the redBeanPhp docs but I'm getting errors on trying to findAll from the userRoutes/php file - surely there's a way that doesn't involve a hack dump......?

**Comment by Knorkebrot** [comment]
For the time being:
```sh
> cd taskboard/api/
> sqlite3 taskboard.db
sqlite> SELECT salt FROM user WHERE username = 'you';
[SALT]
sqlite> ^D
> php -r 'require_once "lib/password.php"; echo password_hash("foobar", PASSWORD_BCRYPT, array("salt" => "[SALT]"));'
[NEW PASSWORD]
> sqlite3 taskboard.db
sqlite> UPDATE user SET password = '[NEW PASSWORD]' WHERE username = 'you';
sqlite> ^D
>
```

Remember to escape the dollar signs in the salt using a backslash.

**Comment by taikedz** [comment]
Hi Knorkerbrot - thanks that works for me.

Alas now I have the unfortunate situation where my user has lost its rights (view boards, etc even though it's the only user and shows in the settings dashboard as having admin - it can't even change its own password), but I now know where the database is so I can keep prodding.

For future reference, the lib/password.php is in `(taskboard_directory)/vendor/ircmaxell/password-compat/lib/password.php`

So you first need to cd to the password-compat directory

**Comment by kiswa** [comment]
The inability to change anything is likely related to the bugs about user behavior that have been reported. #210 #212, #213
