### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by taikedz** [kiswa/TaskBoard#216]
I just wanted to confirm what the correct procedure to update was?

I checked git status in the main taskboard folder, it lists a number of files have changed - not sure how integral they are to the state of the app?

Knowing this, I did:

	git stash
	git pull origin master
	build/composer.phar install

Is this the correct procedure? What am I likely to have lost?

Here's what I was told had changed before I stashed:

	root@helpuse-it:/var/www/html/test/tasks# git status
	On branch master
	Your branch is behind 'origin/master' by 100 commits, and can be fast-forwarded.
	  (use "git pull" to update your local branch)
	
	Changes not staged for commit:
	  (use "git add/rm <file>..." to update what will be committed)
	  (use "git checkout -- <file>..." to discard changes in working directory)
	
		modified:   index.html
		deleted:    indexProd.html
	
	Untracked files:
	  (use "git add <file>..." to include in what will be committed)
	
		css/styles.min.css
		indexDev.html
		js/app.min.js
		lib/css/combined.min.css
		lib/libs.min.js

**Comment by kiswa** [comment]
That should take care of the code side of things. You'll want to have a look at #200 for the DB updates.
