### ISSUE TITLE
Cannot Login after install 

### ISSUE THREAD

**Issue by Mathboy19** [kiswa/TaskBoard#217]
After fixing a few other problems with my install, I came upon this error when trying to login with "admin" and "admin" 
 
    POST http://192.168.1.201/api/login 500 
    (Internal Server Error)(anonymous function) @ angular.js:9866
    sendReq @ angular.js:9667
    $get.serverRequest @ angular.js:9383
    processQueue @ angular.js:13248
    (anonymous function) @ angular.js:13264
    $get.Scope.$eval @ angular.js:14466
    $get.Scope.$digest @ angular.js:14282
    $get.Scope.$apply @ angular.js:14571
    (anonymous function) @ angular.js:21571
    m.event.dispatch @ jquery-1.11.3.min.js:4
    m.event.add.r.handle @ jquery-1.11.3.min.js:4

And apache2/error.log returns

    `[:error] [pid 25334] [client 192.168.1.139:34977] PHP Fatal error:  require_once(): Failed opening   required '/var/www/TaskBoard/api/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/TaskBoard/api/api.php on line 3, referer: http://192.168.1.201/`

System info:

Ubuntu 14.04
PHP 5.5.9
SQLite version 3.8.2
Apache/2.4.7

Any ideas? I have 777'd the entire api directory. Also I have looked at #102 #3 #7 #159, no luck with any of them.

**Comment by kiswa** [comment]
Sorry I've not replied sooner. That sounds like you skipped step 2 of the install:

> Install the PHP dependencies via composer. Open TaskBoard/build/ in a terminal and run ./composer.phar install

**Comment by bong0** [comment]
@kiswa I have the same Issue despite following the "install guide" (which is not accurate btw, you need to run composer phar in the application root dir instead of build). There is no PHP error showing up anywhere for me. Just the 404. I also checked Apache AllowOverride of course

**Comment by kiswa** [comment]
This should be fixed with the v0.3.1 changes.
