### ISSUE TITLE
Loading Users and Loading Boards

### ISSUE THREAD

**Issue by hansln** [kiswa/TaskBoard#219]
I installed TaskBoard at Domainfactory in my webspace. php5.6 with sqlite3 is active. 
I can login an see the startpage with no board.
If i go to settings, page is loading and loading users and loading boards is pending and nothing happend.
I have only a limited access to the Webserver. 
Any ideas what is wrong?

**Comment by kiswa** [comment]
Sorry for the delayed reply.

TaskBoard requires pretty complete access to the hosting as you have to install dependencies via Composer and change the `api` directory to have full read/write permissions.

I imagine these are the main blockers in your situation.

**Comment by MarioLiebisch** [comment]
Having the same issue here. There's most likely something going wrong when doing the Ajax request. Try opening `/api/users` and see if you get any PHP errors, in my case I get:

    Parse error: syntax error, unexpected '[' in ~/tb/api/jsonResponse.php on line 20

I already forced it using PHP 5.5, yet this doesn't seem to help. I also don't see any problem with the mentioned line (or anything above):

    $this->alerts[] = ['type' => $type, 'text' => $text];
