### ISSUE TITLE
Issues during installation

### ISSUE THREAD

**Issue by Moeryn** [kiswa/TaskBoard#222]
The second step did not work:

    2.    Install the PHP dependencies via composer. Open TaskBoard/build/ in a terminal and run ./composer.phar install
    Open TaskBoard/build/ in a terminal and run ./build-all.

I got the following error:

    Composer could not find a composer.json file in /home/caneill/Travail/TaskBoard/build

Indeed the composer.json is in TaskBoard/ and not in TaskBoard/build/

Secondly curl seems to also be a dependency.

**Comment by lukassup** [comment]
Try `$ cd TaskBoard/` and then `$ ./build/composer.phar install`

**Comment by kiswa** [comment]
Yeah, @lukassup has it. I'll update the README to clarify. Thanks for pointing this out.

**Comment by kiswa** [comment]
Fixed by ea871e65cc in bugfixes branch.
