### ISSUE TITLE
No composer.json file under TaskBoard/build

### ISSUE THREAD

**Issue by saadismail** [kiswa/TaskBoard#223]
There is no composer.json file under TaskBoard/build so 2nd step of installation with command "./composer.phar install" generates this error:
Composer could not find a composer.json file in /var/www/TaskBoard/build

In order to run this command successfully you need to copy /var/www/composer.json to /var/www/TaskBoard/build/composer.json

**Comment by MarioLiebisch** [comment]
Had the same. Just install the latest version of "composer.phar" and run it from TaskBoard's root. Ignore the build directory.

**Comment by saadismail** [comment]
I simply copied composer.json into build directory & that worked.

**Comment by kiswa** [comment]
This is a duplicate of #222.
