### ISSUE TITLE
Add Item

### ISSUE THREAD

**Issue by agehring** [kiswa/TaskBoard#227]
Perhaps I'm missing something, as I've encountered the other bugs such as no default Board, but I can't add or update an item unless I'm 'the' administrator (vs 'a "Admin"')

I've setup the software, created users, a board with column and categories, and assigned users. However, as a user with or without admin privileges I can't change/add/delete anything...

What am I missing?

Regards...

**Comment by morvy** [comment]
I had the same problem, recreated all from scratch and it's working now. Also I'm using adminer to manage sqlite db, and I had problems with it too, after recreating taskboard/db I had no problems in adminer

**Comment by agehring** [comment]
Interesting but not really helpful.

Waht does "recreate from  scratch" mean? You downloaded the tar, or checked it out of git? perhaps you can list the steps you took here?

I'm not familiar with adminer - what steps did you follow to "recreate" the db?

**Comment by morvy** [comment]
I mean, that I deleted whole board and recreated all users and columns.. I don't know why it happened, but I had no time to investigate. I'm using multiple installations, some of them created by git (and build-all executed) and some of them just extracted from zip file, all of them work fine

**Comment by agehring** [comment]
Are you running on Linux? 

If so, what distribution/version?

What version of php? 

are you running under apache or nginx?

Any other specifics that may not be "normal' or common?

**Comment by morvy** [comment]
I use all of them online, linux systems with php 5.4, 5.5 and one with 5.6, all on apache. Only local copy that I use is running on my Windows10 with USBWebServer 8.6. Maybe there is a problem with permissions or some dependencies ? but that should be visible in error log, right?

**Comment by agehring** [comment]
I haven't made any progress, but turning on php errors results in:

exception 'ErrorException' with message 'Undefined offset: 0' in /var/www/tasks/api/helpers.php:397
Stack trace:
#0 /var/www/tasks/api/helpers.php(397): Slim\Slim::handleErrors(8, 'Undefined offse...', '/var/www/tasks/...', 397, Array)
#1 /var/www/tasks/api/itemRoutes.php(18): getNextItemPosition('4')
#2 [internal function]: {closure}('2')
#3 /var/www/tasks/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#4 /var/www/tasks/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#5 /var/www/tasks/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#6 /var/www/tasks/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#7 /var/www/tasks/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#8 /var/www/tasks/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#9 /var/www/tasks/api/api.php(51): Slim\Slim->run()
#10 {main}

**Comment by agehring** [comment]
I've now attempted to get this working on Ubuntu 12.04, 14.04, and CentOS 7: All had the same issue as above (ErrorException) in the helpers.php file...

Any insight would be appreciated

**Comment by morvy** [comment]
try to check db, if you have table "option" there with 5 columns, you can use phpliteadmin or adminer for that

**Comment by kiswa** [comment]
See #200 for the upgrade path to add the options table. Alternately, you may want to try out the bugfixes branch to get the latest updates (v0.3.1 in-progress).
