### ISSUE TITLE
Cannot login after install

### ISSUE THREAD

**Issue by alex3137** [kiswa/TaskBoard#228]
Hello.

I installed Taskboard on a fresh VM. I have access to the login page but cannot login (nothing happens when I click on sign in).

I downloaded the archive, extracted it and setup a simple Nginx server with php-fpm and gave write permissions to the api folder.

Here is the content of the virtualhost:

```
server {
        listen   80;


        root /var/www/taskboard;
        index index.php index.html index.htm;
        error_log /var/log/nginx/taskboard-error.log;
        access_log /var/log/nginx/taskboard-access.log;

        #server_name example.com;

        location / {
                try_files $uri $uri/ /index.html;
        }

        error_page 404 /404.html;

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
              root /usr/share/nginx/www;
        }

        # pass the PHP scripts to FastCGI server listening on /var/run/php5-fpm.sock
        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;

        }

}
```

**Comment by kiswa** [comment]
I have not tried TaskBoard with nginx, the support for that was added by another user. However, there are several reports of issues with the latest version so you may want to try a previous release for now (I'm working on bug fixes to release a v0.3.1).
