### ISSUE TITLE
Fonts and Icons not loaded

### ISSUE THREAD

**Issue by cheesebricks** [kiswa/TaskBoard#232]
Hi!

First of all thank you for this great product - I'm looking for a Kanban board for a long time (checking a lot of the other candidates) and decided to give this on a try :)

I was able to go through the install process and load the page (login and all) but when I open settings screen I don't see any of the icons (trash, edit, change position etc..).

When checking the developer mode I see the fonts are loading (seem there some issue with the woff font?)..The error I get is 404 (although when going to the file without the "?v=4.3.0" i do get to the font file) - but in any case I'm not sure it's relevant to the icons.

Will be happy for your help!

Thanks,
Ohad

**Comment by cheesebricks** [comment]
Seem to be some Mime type definition error but still didn't find where and what to add/change.

**Comment by cheesebricks** [comment]
Ok - 

I removed the "?v=4.3.0" from the combined.min.css and now it works. (although I'm aware it's an ugly patch) :)

**Comment by kiswa** [comment]
I'm not sure why there's a `?v4.3.0` at all. I'll look into it.
