### ISSUE TITLE
Vendor Folder required not found

### ISSUE THREAD

**Issue by EJBye7** [kiswa/TaskBoard#233]
Hello

TB ok when I was in v0.27.

I downloaded v0.30 and replace old files (except .db). I have now this following error.

Apache2 error logs : PHP Fatal error:  require_once(): Failed opening required
'C:\\Users\\ME\\Server\\Bitnami\\wordpress-4.2.2-2\\apps\\taskboard\\htdocs\\api/../vendor/autoload.php' (include_path='.;C:/Users/ME/Server/Bitnami/wordpress-4.2.2-2/php/PEAR') in C:\\Users\\ME\\Server\\Bitnami\\wordpress-4.2.2-2\\apps\\taskboard\\htdocs\\api\\api.php on line 3, referer: http://localhost/taskboard/

Vendor folder is indeed missing.

Windows 7 Pro SP1
Apache2 under Bitnami

Thank you
Regards
EJB

**Comment by camael24** [comment]
Did you try to run the command "composer install" to get all dependencies ?
Help for [composer](https://getcomposer.org/doc/00-intro.md#using-the-installer)

**Comment by kiswa** [comment]
@camael24 has answered this. Closing unless you have more to add.

**Comment by EJBye7** [comment]
Hi

Did this but my Companie network prevents something somewhere...
With my shared connection (phone) everything is OK (just do it).
Thanks a lot and sorry for the delay (need holidays...)

Regards


E.J.BAYSSETTE

mob : 06 28 84 16 70
fix : 095 123 26 36
http://www.bayssette.fr

<http://fr.viadeo.com/fr/profile/eric-james.bayssette>
<http://fr.linkedin.com/in/ericjamesbayssette>





2015-11-30 19:06 GMT+01:00 Matthew Ross <notifications@github.com>:
