### ISSUE TITLE
Inexplicably bad $app->run()/Slim performance

### ISSUE THREAD

**Issue by bf-ckiendl** [kiswa/TaskBoard#234]
Good day,

after originally running into #217 and its friends and having to deal with #200, I finally got TaskBoard 0.3.0 running.
I did, however, still have issues with modal dialogs seemingly not going away after I performed most actions.
Since there is an issue for that (#220) in the system and it's marked as fixed, I re-did the installation with a git clone checked out to the bugfixes branch (0.3.1).

Alas, the issue remained.

It turned out that the modal dialogs were, in fact, automatically going away, once they got their response from the server.
That part, however, took exceedingly long.

Long story short, after some debugging and profiling I found that the issue is the runtime of `$app->run();` in api.php. For some reason, it consistently takes more than a minute to return when I POST new data.
Both crude syslog statements in the code as well as profiling with xdebug paint the same picture: The run method takes ages to complete.

```
Dec  1 10:36:12 lamp TaskBoard-API: RE.DA.CT.ED api.php entered
Dec  1 10:36:12 lamp TaskBoard-API: RE.DA.CT.ED Before $app->run()
Dec  1 10:37:17 lamp TaskBoard-API: RE.DA.CT.ED After $app->run()
Dec  1 10:37:17 lamp TaskBoard-API: RE.DA.CT.ED api.php exited

Dec  1 10:40:30 lamp TaskBoard-API: RE.DA.CT.ED api.php entered
Dec  1 10:40:30 lamp TaskBoard-API: RE.DA.CT.ED Before $app->run()
Dec  1 10:41:35 lamp TaskBoard-API: RE.DA.CT.ED After $app->run()
Dec  1 10:41:35 lamp TaskBoard-API: RE.DA.CT.ED api.php exited

Dec  1 11:37:00 lamp TaskBoard-API: RE.DA.CT.ED api.php entered
Dec  1 11:37:00 lamp TaskBoard-API: RE.DA.CT.ED Before $app->run()
Dec  1 11:38:05 lamp TaskBoard-API: RE.DA.CT.ED After $app->run()
Dec  1 11:38:05 lamp TaskBoard-API: RE.DA.CT.ED api.php exited

Dec  1 11:38:57 lamp TaskBoard-API: RE.DA.CT.ED api.php entered
Dec  1 11:38:57 lamp TaskBoard-API: RE.DA.CT.ED Before $app->run()
Dec  1 11:40:12 lamp TaskBoard-API: RE.DA.CT.ED After $app->run()
Dec  1 11:40:12 lamp TaskBoard-API: RE.DA.CT.ED api.php exited

Dec  1 11:43:07 lamp TaskBoard-API: RE.DA.CT.ED api.php entered
Dec  1 11:43:07 lamp TaskBoard-API: RE.DA.CT.ED Before $app->run()
Dec  1 11:44:18 lamp TaskBoard-API: RE.DA.CT.ED After $app->run()
Dec  1 11:44:18 lamp TaskBoard-API: RE.DA.CT.ED api.php exited
```

I have checked the server's resource usage while the request runs, and it barely even registers. Three quarters of the CPU are idle, a third of the RAM is unused (and executing the request didn't actually allocate more RAM) and iotop doesn't even show writing to the DB file.
Other requests, like the periodic XHR pings for new content, complete quickly - the /api/boards ping typically takes around 250ms, the /api/autoactions ping around 80ms.

I am therefore certain that neither the connection nor the general server resources are the issue.

Since the installation is new, the number of boards and tasks is small. Currently, after all tests, I have 4 boards and 42 tasks.

Quite frankly, it seems to me like the code is just slow.

On the other hand, considering that the total number of calls to deal with adding a single task is 42,750, maybe that's not surprising. xD

I am going to hazard a guess that this kind of performance isn't typical for 0.3.1, otherwise I wouldn't be the first one filing an issue.
I would appreciate any hint as to what might cause this massive slowdown.

Attached are screenshots from *cachegrind output as well as one of the cachegrind files. I had to add a .txt extension so GitHub would let me upload it.

Thank you for your help. :)
# Uploads

[cachegrind.out.15253.txt](https://github.com/kiswa/TaskBoard/files/48469/cachegrind.out.15253.txt)
## Callgraph without duplication detection

![bf_callgraph_no_duplication_detection](https://cloud.githubusercontent.com/assets/16099588/11500205/e2ac4274-982b-11e5-8414-857598eb5a60.png)
## Callgraph with duplication detection

![bf_callgraph_with_duplication_detection](https://cloud.githubusercontent.com/assets/16099588/11500203/e24ca7b0-982b-11e5-98bb-f62f1ee43dd5.png)
## Time usage ordered by line in file

![bf_time_distribution_line](https://cloud.githubusercontent.com/assets/16099588/11500202/e24b8970-982b-11e5-916c-2066ef5de2a1.png)
## Time usage ordered by time share

![bf_time_distribution_function](https://cloud.githubusercontent.com/assets/16099588/11500204/e252a8b8-982b-11e5-8c09-1a20b8a6194c.png)
## Client Devtools View showing the time distribution regarding the request

![bf_devtools_adding_one_board](https://cloud.githubusercontent.com/assets/16099588/11500756/7c26ab3a-982f-11e5-8885-fe119f21f7d9.png)

As a sidenote, the number of automatic XHR requests seems a bit excessive - I cleared the list before I sent the request, which means the 210 requests logged were all done in the <70 seconds it took for the request to complete, plus a few seconds for taking the screenshot.

**Comment by sash85** [comment]
Hello,
i have the same issue, running a fresh installation of v0.3.1. Is there already a solution?

**Comment by kiswa** [comment]
I have been unable to duplicate this. It may be a local setup issue (PHP version?).

I'm still trying to figure it out.

**Comment by bf-ckiendl** [comment]
```
# php5 --version
PHP 5.4.45-1~dotdeb+6.1 (cli) (built: Sep  5 2015 00:09:17)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with XCache v3.2.0, Copyright (c) 2005-2014, by mOo
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
    with XCache Cacher v3.2.0, Copyright (c) 2005-2014, by mOo
```

```
# apache2 -V
Server version: Apache/2.2.16 (Debian)
Server built:   Jan 28 2014 21:49:11
Server's Module Magic Number: 20051115:24
Server loaded:  APR 1.4.2, APR-Util 1.3.9
Compiled using: APR 1.4.2, APR-Util 1.3.9
Architecture:   32-bit
Server MPM:     Prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APACHE_MPM_DIR="server/mpm/prefork"
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=128
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_LOCKFILE="/var/run/apache2/accept.lock"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"
```

**Comment by sash85** [comment]
@kiswa Would it help, if you get Access to our TaskBoard? If yes, i will send you an DM.

**Comment by kiswa** [comment]
@sash85 It might. Give me a bit longer to figure it out though - the holidays make it difficult to do much side development. ;)

**Comment by sash85** [comment]
No Problem! Thanks for your fast reply and the great tool :-).

**Comment by KrischanKeitsch** [comment]
@kiswa I really like this app. Nice interface. Great work!
I also have problems with the performance of version 0.3.1. Saving a Task tages more than a minute. Changing the color sometimes works, sometime it does not.
I am running taskboard on a raspberrry pi 2 with debian. While I interact with the taskboard, htop shows barely any activity.
Sorry that I can not provide more accurate information.

**Comment by kiswa** [comment]
This may be an issue with email. Did you setup an email address on your account?

**Comment by FiSHYsolutions** [comment]
noticed the same behaviour in fresh v0.3.1, removed the email-address from my account and can report this tweak speeds it up a lot!
