### ISSUE TITLE
TaskBoard will not allow me to login. 

### ISSUE THREAD

**Issue by davidbird** [kiswa/TaskBoard#235]
I am using the correct username and password, but I am kicked back to the login window every time I submit. If I use the wrong password, the incorrect password dialog is presented. I am forever brought back to domain.com/TaskBoard/#/ no matter what I do.

**Comment by davidbird** [comment]
Well, I figured out what was wrong, SELinux contexts... Marking as closed.

**Comment by mitpro** [comment]
got same problem... how to fix it?
