### ISSUE TITLE
it's possible using CalDav for calendar?

### ISSUE THREAD

**Issue by manuelsongokuh** [kiswa/TaskBoard#238]
It's possible using CalDav for calendar?

**Comment by sunrez** [comment]
I think if TaskBoard supported an iCal *feed* (like Kanboard) then any tasks with due dates would automatically appear in a user's calendar which is high desirable.  I think supporting an iCal feed is fairly straightforward with all the existing frameworks out there to create iCal files.

**Comment by poVoq** [comment]
CalDav would have the advantage that it also allows writing from external apps, like for example marking a task done from your Android tasks applications or adding new tasks to the first column. Similarly it would work with Thunderbird (&Lightning) as a desktop application.

It would also allow partial interoperability with other server based systems that use it, for example you could view and edit your tasks and calendars from within your Owncloud installations.

**Comment by makayabou** [comment]
Yes, caldav integration would be great, mostly for tasks, so you can access your cards written on taskboard on another caldav client, and vice-versa. It could be connected to a sabreDav server as implemented in Nextcloud.
