### ISSUE TITLE
First Login not working

### ISSUE THREAD

**Issue by metzbernhard** [kiswa/TaskBoard#240]
Hello,

I tried hosting TaskBoard on my Raspberry Pi, all dependencies should be up and running, have other things using PHP & sqlite running fine. Problem is, when I enter first login (admin/admin) it loops back to the login screen, no error message no "wrong password" just again the login screen with admin/admin still in the form. 
I tried different setups for debugging but had the exact same issue on four different setups:
Raspbian/Apache
CENTOS/Apache
Debian/Nginx
Windows/XAMPP
Found via online search to enable AllowOverride All and to remove the sqlite path from the .php file, so Taskboard would generate a new one. Both did not help. Any ideas what I'm doing wrong?
Happens both on master and dev build.

**Comment by kiswa** [comment]
Is there any output in the browser dev tools?

**Comment by metzbernhard** [comment]
Solved, below what I did, for future reference: 

Original error: 
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
https://URL/tasks/api/login and some libs.min.js:9866 (not sure about the number)
```

Looked for fixes regarding this error, one was enabling a2enmod rewrite (which was already done) but also tweaking the .htaccess file adding RewriteEngine on (but this is not necessary in the end) I also increased the max memory limit in the php.ini. 

After that I got the following in the Dev Tools: 
```
POST https://URL/tasks/api/login 500 (Internal Server Error) libs.min.js:507
(anonymous function) @ libs.min.js:507
q @ libs.min.js:503
g @ libs.min.js:500
(anonymous function) @ libs.min.js:532
q.$eval @ libs.min.js:546
q.$digest @ libs.min.js:543
q.$apply @ libs.min.js:547
(anonymous function) @ libs.min.js:636
e.event.dispatch @ libs.min.js:92
h.handle @ libs.min.js:86
```

looking for this I found issue #210 but that only says that the issue has been fixed, But I still had the problem with both Dev & Master build, so  I went into the apache-log and found that Apache didn't like a setting in the .htaccess:
```Invalid command ‘ExpiresActive’, perhaps misspelled or defined by a module not included in the server configuration```

As resolution for that I ran:
```
ln -s /etc/apache2/mods-available/expires.load /etc/apache2/mods-enabled/
```

This solved the problem in my Raspbian/Debian setup, on not-Debian-based systems you may have to additionally edit your apache2.conf (or httpd.conf) and add / uncomment the following line
```
LoadModule expires_module modules/mod_expires.so
```
On Debian-based systems this will prevent the apache-service from restarting.
