### ISSUE TITLE
Update installation guide

### ISSUE THREAD

**Issue by Troglobitten** [kiswa/TaskBoard#244]
I followed the installation guide on the website http://taskboard.matthewross.me/docs/intro.html
and ran into the same issue as #162 

Turns out that the guide is missing a vital step that is listed in the README.md

> Install the PHP dependencies via composer. Open TaskBoard/ in a terminal and run ./build/composer.phar install

A small sidenote. Some shared hosts (such as my own) are not capable of running phar files, I had to execute it with

> php -d extension=phar.so ./build/composer.phar install

**Comment by kiswa** [comment]
I need to update a few things on that site. Thanks for reminding me!

**Comment by michael1maass** [comment]
Hi, I did the update and no change...
<html debug="true" adlesseunifierdata="["{\"w\":false,\"id\":\"com.kwizzu.fastesttube\",\"name\":\"FastestTube\",\"isComponentMode\":true}"]">

**Comment by kiswa** [comment]
@michael1maass  Sorry, I have no idea what you posted. Care to elaborate?

**Comment by michael1maass** [comment]
hi Matthew, 

sorry: 

I installed TaskBoard on my MacBook within the sites Folder. 
the subfolder /TaskBoard/api has the rights set to 777 (everybody, everything) 
Calling the site with localhost/~username/TaskBoard/ opens the login window
entering admin , password admin does not do anything but shake the box
checking the errorlist I see, that the URL …/TaskBoard/api/login is called. 
The request results in an error 500, resource not available.
checking the api folder, I do not find any file named login, so the error seems logical. 
I updated the installation as described, but no gain. Symptoms are still the same. 

regards 

Michael 

server error 500 weht trying to open ../Taskboard/api/login which is not present within the api folder. 
api has has all set  to 777 (local machine)

**Comment by kiswa** [comment]
I'm not familiar with running things from OSX Sites, so I imagine the issue is that it's meant to run on an Apache or nginx server.

There is not an `api/login` file because that is an API endpoint which is translated to the appropriate call when run on the aforementioned servers.

Maybe someone with more familiarity can let you know the equivalent to `.htaccess` for Sites folders.

**Comment by michael1maass** [comment]
Hi Matthew, 

actually the Mac Framework comprises an Apache Webserver. 

regards Michael

**Comment by sorinsfirlogea** [comment]
Hi Kiswa,
I'm having a similar problem: cannot login with admin/admin after installing TaskBoard. The browser console says: POST http://[myServerIP]/taskboard/api/login 404 (Not Found).

Context: Apache = 2.4.7, PHP = 5.5, Server API = FPM/FastCGI, pdo_sqlite = 3.8.2

Are there some specific modules or configuration in Apache that I need to check? It is obvious that the API endpoint call is not working for some reason...
Thanks.

**Comment by srdco** [comment]
Have you checked the Apache config to make sure AllowOverride All is set for the taskboard install? That is what seems to trigger the problem was with the 404 Error more often than not. Also, I ended up having to set AllowOverride All for the taskboard parent folder (a subfolder of www) before it would work.

**Comment by sorinsfirlogea** [comment]
Thanks, that helped apparently, but not enough. I set AllowOverride All for the folder where TaskBoard is installed and its parent. Now the error moved to:
GET http://[myServerIP]/taskboard/api/boards 401 (Unauthorized)
GET http://[myServerIP]/taskboard/api/users/current 401 (Unauthorized)
GET http://[myServerIP]/taskboard/api/authenticate 401 (Unauthorized)

The user running the Apache process has 775 rights on all the folder structure. Any ideea?

**Comment by kiswa** [comment]
Have a look at #7 and #295 and see if anything in there helps.

**Comment by eric-maria** [comment]
Hello I am very new to this, so sorry up front, but I tried to follow the steps in the readme file, but get stuck at step 2. I installed composer and xampp and started composer in a terminal (power shell). I typed in "./build/composer.phar install". It then askes me with which app I want to open this file. What do I choose?

**Comment by ninsbl** [comment]
Have been struggling a bit too. A full step-by-step guide (ideally in for of shell code) would be great!

**Comment by palitu** [comment]
Or a docker container that encapsulate everything :)
