### ISSUE TITLE
Timeout adding boards/items/etc.

### ISSUE THREAD

**Issue by fauno** [kiswa/TaskBoard#246]
I've made a few changes to taskboard to make it support mysql and they worked ok, though I noticed any popup form wouldn't close when pressing the "add" button.  The item/board/comment is added, but the popup form is greyed and stays put.

So I changed back to sqlite and it seemed to be working correctly, but now is happening again.

By debugging with firefox's web developer tools, I see the form is POSTed but the API never replies.  On nginx's error.log I see a timeout error after a while.

**Comment by EvilRenegade** [comment]
I don't do nginx, but check PHP's maximum execution time against issue #234.

e.g. if your Backend also needs a minute to complete but nginx is set to give up after 30 seconds, you would get the picture you describe.

**Comment by kiswa** [comment]
What changes did you make exactly?
MySql (MariaDB) should work just by changing the `setup` line in `api/api.php` (currently line 28).

See here for an example: http://www.redbeanphp.com/index.php?p=/connection

**Comment by fauno** [comment]
Matthew Ross <notifications@github.com> writes:

> What changes did you make exactly?
> MySql (MariaDB) should work just by changing the `setup` line in `api/api.php` (currently line 28).
>
> See here for an example: http://www.redbeanphp.com/index.php?p=/connection

yes i did that, but as i said later, i changed it back to sqlite and i
started to have the same timeouts.

here are my changes:

https://github.com/kiswa/TaskBoard/compare/master...fauno:mysql

-- 
}(:=

**Comment by kiswa** [comment]
This may be an issue with email. Did you setup an email address on your account?

**Comment by kiswa** [comment]
Closed due to inactivity. Comment and I'll re-open if necessary.

**Comment by Spyneur** [comment]
Hello @kiswa,

I had the same problem, setup an email adress on my account, i removed it, everything works again.

Thank you so much !
