### ISSUE TITLE
setup not working

### ISSUE THREAD

**Issue by FritzGumbmann** [kiswa/TaskBoard#247]
I want to evaluate TaskBoard and therefore tried it with XAMPP portable for Windows. By using http://localhost:8080/TaskBoard-master  the login screen shows up but after typing admin  admin nothing happens. I tried master and dev version with XAMPP PHP 5.6.15  and 7.0.1. All the same.  I skipped step 2 of http://taskboard.matthewross.me/docs/intro.html  but it should be optional.
What did I miss? What could be the reason
br
Fritz

**Comment by kiswa** [comment]
Sorry, I really need to update the companion website.

Try using the steps in [README.md](https://github.com/kiswa/TaskBoard/blob/master/README.md) instead.

**Comment by FritzGumbmann** [comment]
Thanks, it was one missing module. Now I can start evaluation.
