### ISSUE TITLE
Add Item dialog does not close

### ISSUE THREAD

**Issue by FritzGumbmann** [kiswa/TaskBoard#248]
When I add an item to a board, the dialog is not closed when click ADD. All fields become gray and the item appears at the board. The only thing that works is x. After doing it a few times the colour picker of the dialog does not work any more.
Version TaskBoard-master

**Comment by kiswa** [comment]
Open F12 dev tools and let me know if any errors appear when you add an item.

**Comment by mgkeeley** [comment]
I found the same issue. It seems to be due to the mail config in api/mainConfig.php having some default/bogus SMTP settings. api/mailFactory.php creates a mail object and always uses these values (perhaps, by default, it shouldn't!).  I resolved the issue by commenting out the smtp setup lines in api/mailFactory.php:createMailObject.
...
    /*
    $mail->isSMTP();
    $mail->Host = $MAIL_HOST;
    $mail->SMTPAuth = true;
    $mail->Username = $MAIL_USERNAME;
    $mail->Password = $MAIL_PASSWORD;
    $mail->SMTPSecure = $MAIL_SMTPSECURE;
    $mail->Port = $MAIL_PORT;
    */
...

**Comment by mgkeeley** [comment]
See also #246 #234

**Comment by kiswa** [comment]
That was contributed code, which I didn't really delve into (my bad).

@mgkeeley Is there any reason to have that commented out block of code? If not, want to send a PR against `dev`?

**Comment by mgkeeley** [comment]
Hi, no, I just commented it out as a minimal workaround to "get it working", and so others could do the same if they wanted to. I don't really have time to put together a better solution sorry. Maybe by default the properties in mailConfig should be commented out, and the mailFactory checks to see if those SMTP vars are set or not before configuring the mail item as sending via SMTP.
