### ISSUE TITLE
Dates displayed with fraction glyphs on edit page in Safari

### ISSUE THREAD

**Issue by heptal** [kiswa/TaskBoard#249]
Oddly enough the cursor can select in the middle of the glyph as if they were separate chars (which they are of course).

<img width="322" alt="screen shot 2016-01-13 at 6 34 41 am" src="https://cloud.githubusercontent.com/assets/1241082/12294426/f9384258-b9bf-11e5-9729-3a463daf53e2.png">

<img width="213" alt="screen shot 2016-01-13 at 6 34 49 am" src="https://cloud.githubusercontent.com/assets/1241082/12294423/f4c0b0ac-b9bf-11e5-93c5-642e2d11147c.png">

<img width="305" alt="screen shot 2016-01-13 at 6 35 21 am" src="https://cloud.githubusercontent.com/assets/1241082/12294417/ef5eaf74-b9bf-11e5-8006-d0a135f103cc.png">

<img width="301" alt="screen shot 2016-01-13 at 6 35 40 am" src="https://cloud.githubusercontent.com/assets/1241082/12294410/e744cb0c-b9bf-11e5-8f1f-3e8e529d86c9.png">

**Comment by kiswa** [comment]
That is very odd. Does this help? https://discussions.apple.com/thread/1147391?tstart=0

**Comment by heptal** [comment]
I don't have that font installed. I've never seen anything like that anywhere else and outside the edit page the date renders normally. So wtf basically.
