### ISSUE TITLE
Cannot login?

### ISSUE THREAD

**Issue by newland8x** [kiswa/TaskBoard#251]
Hi, I use Windows with Xampp.
I copy TaskBoard folder and file to htdocs and lunch it.
But cannot login with user/password: admin/admin
Do you have any experience about this case?
Thank you.

**Comment by kiswa** [comment]
Have a look at #197, #3, and #7. Let me know if those help.

**Comment by kapil-vyas** [comment]
I cannot login either. Says - cannot find "api/login" - 500 Internal Server Error (libs.min.js). I followed all the steps (in CentOS). Ran the build-all script, followed by the composer.phar (from root directory of the app). Both went successful. Updated php version to 5.5 - enabled Apache mod on root dir (var/www/html/TaskBoard) to "AllowOverride All". None of these helped. I looked at each of the above issues.

**Comment by the-real-john-smith** [comment]
A 500 sounds like a php problem. Have a look in the apache error log for your web site. You should see a php error in there. Maybe you're missing the PDO drivers?

**Comment by kiswa** [comment]
Closing due to lack of response from OP.

@kapil-vyas Did you follow the steps in the README on GitHub, or the documentation website? Because the documentation site is not up-to-date (sorry).

**Comment by cirilfab** [comment]
Hi there, 
I have this issue as well on a fresh install on the hoster. Have followed the instructions for the install and even checked on the other posts on htaccess.
Any ideas how to fix it?
Thanks
