### ISSUE TITLE
ExpiresActive not allowed here Error

### ISSUE THREAD

**Issue by kissmethode** [kiswa/TaskBoard#253]
Hello everyone,

I'm having difficulties getting the TaskBoard website running and keep getting a 500 error page.
Apache's error log says:
> [Tue Jan 26 12:52:37.392660 2016] [core:alert] [pid 17322] [client 172.18.3.34:53690] /var/www/html/taskboard/.htaccess: ExpiresActive not allowed here

Some extra info:
- My Ubuntu server has Apache 2.4.7 and PHP 5.5.9 installed.
- I succesfully run the build-all.
- All files are owned by www-data
- rewrite en expires mods are enabled

Could someone please help me with this?

**Comment by kiswa** [comment]
Seems like the simplest solution is to edit `[.htaccess](https://github.com/kiswa/TaskBoard/blob/master/.htaccess)` and comment out the expires section.

It's not absolutely necessary, so removing it won't hurt anything.

**Comment by kissmethode** [comment]
That seems to fix it!
Thank you for the help.
