### ISSUE TITLE
Just loading, no functionality

### ISSUE THREAD

**Issue by brandy000** [kiswa/TaskBoard#254]
Hi!

I just copied the taskboard-files to my server.
When I open the path in the browser I can login with admin/admin, but then there is no functionality - Users and boards are loading and the fields for username and password are grey, so that I can´t click anyhing!

Can you tell me, whats wrong here?
Thank you!

**Comment by kiswa** [comment]
Have you gone through the [Installation steps](https://github.com/kiswa/TaskBoard#installation)?

If so, take a look at #3 and #7 for possible solutions.

**Comment by kiswa** [comment]
Closing due to lack of response.

Let me know if this needs to be re-opened.
