### ISSUE TITLE
Stuck at the login screen

### ISSUE THREAD

**Issue by Edwal** [kiswa/TaskBoard#256]
Hi. I have followed all the steps (I'm in a Mac, BTW). Installed it as told, got the "installed" message. I click on the "index.html" file and enter the login data, but nothing. Where is the program? What's its name?

Regards

**Comment by kiswa** [comment]
Could you open developer tools (<kbd>F12</kbd> usually) and let me know if any errors appear when logging in?

**Comment by Edwal** [comment]
This is the log:

mal formado bootstrap.min.css:1:1
mal formado font-awesome.min.css:1:1
mal formado jquery-ui.min.css:1:1
mal formado jquery-ui.structure.min.css:1:1
mal formado spectrum.css:1:1
mal formado styles.css:1:1
mal formado login.html:3:86
Error: Access to restricted URI denied
createHttpBackend/<@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/angular.js:9866:7
sendReq
@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/angular.js:9667:1
$http/serverRequest
@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/angular.js:9383:16
processQueue
@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/angular.js:13248:27
scheduleProcessQueue/<@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/angular.js:13264:27
$RootScopeProvider/this.$get</Scope.prototype.$eval
@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/angular.js:14466:16
$RootScopeProvider/this.$get</Scope.prototype.$digest
@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/angular.js:14282:15
$RootScopeProvider/this.$get</Scope.prototype.$apply
@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/angular.js:14571:13
ngEventHandler/<@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/angular.js:21571:17
m.event.dispatch
@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/jquery-1.11.3.min.js:4:8497
m.event.add/r.handle
@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/jquery-1.11.3.min.js:4:5235
 angular.js:11655:18

Error: data is null
$scope.logIn/<@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/js/controllers/login.js:31:13
$http/promise.error/<@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/angular.js:9415:11
processQueue
@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/angular.js:13248:27
scheduleProcessQueue/<@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/angular.js:13264:27
$RootScopeProvider/this.$get</Scope.prototype.$eval
@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/angular.js:14466:16
$RootScopeProvider/this.$get</Scope.prototype.$digest
@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/angular.js:14282:15
$RootScopeProvider/this.$get</Scope.prototype.$apply
@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/angular.js:14571:13
ngEventHandler/<@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/angular.js:21571:17
m.event.dispatch
@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/jquery-1.11.3.min.js:4:8497
m.event.add/r.handle
@file:///Users/edwalrospigliosicaceda/Documents/TaskBoard-master/lib/jquery-1.11.3.min.js:4:5235

2016-02-09 16:08 GMT+01:00 Matthew Ross <notifications@github.com>:

**Comment by kiswa** [comment]
You're trying to use TaskBoard by opening the index.html, not connecting to a server that is hosting TaskBoard. That won't work.

To use TaskBoard, it must be installed on an active web server (Apache and nginx are currently supported).
