### ISSUE TITLE
Screen position resets to the top every time boards are auto refreshed (every 10 seconds)

### ISSUE THREAD

**Issue by the-real-john-smith** [kiswa/TaskBoard#257]
Installed TaskBoard yesterday at the free hospital I volunteer at in Cambodia. We're really in need of something free since we can't afford much. Thanks for a great web app!

This problem makes it difficult to have a look at my task list - which do extend beyond one screen.

I've tried latest chrome and firefox and both have the same problem.

**Comment by kiswa** [comment]
This is scheduled to be fixed in v0.4.0 by #34. It's actually a fair bit of effort to fix.
