### ISSUE TITLE
admin Account does not log me in 

### ISSUE THREAD

**Issue by michael1maass** [kiswa/TaskBoard#259]
after Building and upgrading to 0.31 the site starts up with the login screen. unfortunately admin:admin does not get me past the screen. 

System: Mac OS X El Capitan. api is 777, building occurred without errors

**Comment by kiswa** [comment]
Any errors when using <kbd>F12</kdb> dev tools?

**Comment by michael1maass** [comment]
hi, 
Thanks for following this up so quick, 

no errors on F12

Michael

**Comment by michael1maass** [comment]
cancel my last

server error 500 weht trying to open ../Taskboard/api/login which is not present within the api folder. 
api has has all set  to 777 (local machine) 

?!

Michael

**Comment by N-Upchurch** [comment]
Same issue here.

**Comment by kiswa** [comment]
Take a look at #244 and see if that takes care of this for you.

**Comment by folta** [comment]
Using the included nginx config I was having the same error. I looked at the failing request in Firefox Developer tools and the issue stated that it was unable to connect to the database. Installing "php5-sqlite" and restarting fpm fixed it for me.

**Comment by BrunoLindorfer** [comment]
Make sure you meet the perquisites. I had the same problem and enabling the module "expires" for apache2 solved it (a2enmod expires)

**Comment by kiswa** [comment]
Closing due to lack of response.

If you still need help with this, just post here and we can re-open if needed.

**Comment by michael1maass** [comment]
Hi, 

I enabled the expires Module in http.conf   (LoadModule expires_module libexec/apache2/mod_expires.so) 
now it works.  Might need a hint in the Read.me 

thank you all 

regards

Michael
