### ISSUE TITLE
Can't log in: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by N-Upchurch** [kiswa/TaskBoard#260]
I am on a shared host. (Site5 cloud reseller) 
Upon trying to log in for the first time I get the following error:

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Info from hosting support: 

od_fcgid: stderr: PHP Fatal error: require_once(): Failed opening required '/home/(MYACCOUNT)/public_html/taskboard/api/../vendor/autoload.php' (include_path='.:/usr/local/php55/lib:/usr/lib/php:/usr/local/lib/php') in /home/(MYURL)/public_html/taskboard/api/api.php on line 3, referer: http://(MYURL)/taskboard/

**Comment by kiswa** [comment]
It looks like the vendor dependencies were not installed. If you only used the instructions on the doc site, they are in need of updating. Take a look at #244 and see if that helps.

**Comment by N-Upchurch** [comment]
Excellent, thank you. Do you heppen to know how this can be accomplished on cpanel?

**Comment by kiswa** [comment]
Unfortunately, I do not as I haven't used it in quite a while. It's possible you may need shell access to your server.

Alternately, you could do a local install, then upload the vendor directory to your shared host (I think this should work).

**Comment by N-Upchurch** [comment]
ok, next problem, I'm getting this: 

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/php55/lib/php/extensions/no-debug-non-zts-20121212/phar.co' - /usr/local/php55/lib/php/extensions/no-debug-non-zts-20121212/phar.co: cannot open shared object file: No such file or directory in Unknown on line 0
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "./public_html/taskboard/build/composer.phar self-update" to get the latest version.
Composer could not find a composer.json file in /home/(myAccount)
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

**Comment by N-Upchurch** [comment]
You should know, I have no idea how to work the command line. Never had to do this before.

**Comment by kiswa** [comment]
Here's the vendor directory temporarily: https://www.dropbox.com/s/tkdftobzlze02uw/vendor.tar.gz?dl=0

Just unpack it and place it in the root TaskBoard folder so you have `your_taskboard/vendor`

**Comment by kiswa** [comment]
I may go back to having a ready-to-go setup rather than requiring an install of the dependencies.

**Comment by N-Upchurch** [comment]
Was able to get it working thanks to that archive. Thanks so much for your help, the app is great.

**Comment by kiswa** [comment]
Glad you like it, and glad that worked for you.
