### ISSUE TITLE
Action "Set item color" chooses #ffffe0 instead of shown color

### ISSUE THREAD

**Issue by flowli** [kiswa/TaskBoard#264]
To reproduce:
1. goto "automatic actions"
2. add action for any board, trigger "item moves to column"
3. choose a different color
4. add action
Then the list of actions show color #ffffe0, no matter which color was chosen.

Is this a bug or am I just doing it wrong?

**Comment by thomas-mc-work** [comment]
I've encountered the same effect.

**Comment by olaulau** [comment]
has someone a fix for that ??
