### ISSUE TITLE
Clicking outside the item box closes the item without saving

### ISSUE THREAD

**Issue by jx47** [kiswa/TaskBoard#266]
While using Taskboard in version v0.3.1 i encountered the the error that clicking outside the item box closes it without saving the input. Is it a misconfiguration on my part or a bug?

![issue](https://cloud.githubusercontent.com/assets/914863/14140401/06d0cdea-f679-11e5-8628-cff62fe5a9d5.gif)

**Comment by kiswa** [comment]
That is actually as designed. Only clicking the save button will save an item.
