### ISSUE TITLE
Columns no longer collapse

### ISSUE THREAD

**Issue by ivityc** [kiswa/TaskBoard#267]
Hi 

I have a setup with 2 different boards. Both worked fine till yesterday, then after I deleted some users (with no tasks assigned) one of the board stopped to work with respect to the ''collapse'' feature.
If I click on the >> to collapse a lane the only visible change is the reported number of tasks contained in the lane, such number appear and disappear at each click but the lane never collapse.
The problem is affecting only one of the 2 borads, that are sitting on the same system.environment.
Thanks for your support.
Iv
![capture](https://cloud.githubusercontent.com/assets/18171112/14167309/93e7e9ec-f71a-11e5-8ff1-1d3dfc5408ea.PNG)

**Comment by ivityc** [comment]
in addition to collapse issue, i noticed that now if i create in this board a new action, I cannot assign it to someone as the drop-down list of the available users for that board results empty. I have to open/edit an existing task, open the assignee drop-down list ( I can see all users) , close the task editing and then I can re-edit the new task and I can see the assignee list again to select from.
it seems like someting scerw up with ref to the user list in the dB as I noticed that the php code for the collapse function is also ''per user''

**Comment by kiswa** [comment]
Can you open dev tools (<kbd>F12</kbd>) and let me know if you're getting any errors?

**Comment by ivityc** [comment]
Hi, the error is the following (it is partial as I do not want to post contained data) : 

http://errors.angularjs.org/1.3.15/$rootScope/infdig? (http://errors.angularjs.org/1.3.15/$rootScope/infdig?p0=10&p1=[[{%22msg%22%3A%22fn%3A function %28a%29{var b%...
 it seems to be related to 
                    data-ng-class="{'collapsed': lane.collapsed}" 

I also noticed that if I delete several items from the board then it stark to work fine again.
I had almost 40 items in several lanes, I deleted 10 and problem still persisted, then i deleted 10 more items and it started to work. So it seems that there is a limit in the number of items that can be managed .

Thanks

**Comment by kiswa** [comment]
I'll look into this. It seems like it may take a bit of work to reproduce.
