### ISSUE TITLE
I can't login after install

### ISSUE THREAD

**Issue by rbeltranlopez8527** [kiswa/TaskBoard#268]
I can't login with admin - admin after install, Chrome Console shows angular.js:9866 POST http://192.168.1.68/taskboard/api/login 404 (Not Found). Thks.

**Comment by flowli** [comment]
Did you enable mod_rewrite (or similar) in your webserver?

**Comment by srinathh** [comment]
I'm having the similar issues. I'm trying to use the php development server running like this
`php -S 127.0.0.1:8080 devrouter.php

**Comment by srinathh** [comment]
I actually managed to get this working in XAMPP. But it's a pity this program requires such a heavy duty setup to run :-)

Apache settings that had to be changed were to allow mod_rewrite and mod_expire

**Comment by srinathh** [comment]
I also ended up having to pull in the vendored modules that was hosted in dropbox & mentioned in another comment to get this to work. However, I really think vendored modules should be included in the main source tree which is the normal practice in many places. At least the install instructions should be updated to point to the vendored modules.

**Comment by janiosarmento** [comment]
What a shame it requires Apache to work, since Nginx is gaining more and more market share every single day.

**Comment by kiswa** [comment]
@janiosarmento It runs on nginx as well. At least, that's what I'm told by those who contributed the nginx configuration.

**Comment by janiosarmento** [comment]
Yes, it kind runs in Nginx, but it is a real pain to discover ho to configure the vhost accordingly. 

Anyway, it is buggy, and I had to give it up for a while. Sorry. :(

**Comment by kiswa** [comment]
@janiosarmento That's unfortunate. Feel free to contribute to make it better on nginx.

**Comment by janiosarmento** [comment]
I’ve been trying to figure out what’s going wrong (the boards do not appear
on “boards” page), but no success so far.

As soon as I discover something I’ll let you know.

**Comment by kiswa** [comment]
Are you on latest Chrome? If so, something changed - it was reported in issue #275.

**Comment by cadupar** [comment]
I have the same issue in UBUNTU x64, I can't login with admin / admin.

And my build finished OK, mod_write is enabled, api folder security is 777, tested with Chrome and Firefox last versions:

root@abb:/var/www/TaskBoard-master# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

root@abb:/var/www/TaskBoard-master/api# a2enmod rewrite
Module rewrite already enabled

root@abb:/var/www/TaskBoard-master# ./build/build-all
Building...
 Installing dependencies
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "./build/composer.phar self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
 Compiling lib JS files...
 Minifying lib CSS files...
 Compiling app JS files...
 Minifying app CSS files...
 Updating index.html...
Build Complete

**Comment by danielc1234** [comment]
Hi, was this issue ever resolved? I am having the exact issue with my installation.
Thanks

**Comment by AmonBune** [comment]
I have the same issue using PHP 7.0 on Ubuntu 16.04.
I'm getting a 404 error that the "/api/login" site does not exist. And it DOES not exist.
So somehow this file is either missing, referenced wrongly or the build process failed silently in the background.
![indexofapi](https://user-images.githubusercontent.com/15927695/32494168-e53ffbee-c3c0-11e7-88ba-a8522767a940.PNG)
