### ISSUE TITLE
Takes 3-5 seconds on average to post an item

### ISSUE THREAD

**Issue by lakshmanpasala** [kiswa/TaskBoard#269]

**Comment by lakshmanpasala** [comment]
I am using aws free tier servers. Is this because of that?

**Comment by kiswa** [comment]
I suppose that's possible, but it seems unlikely. Have you looked at #234? You may want to comment out the email code (especially if you don't use it).

**Comment by lakshmanpasala** [comment]
I don't think the issue is with the server. Because even on my local machine, once I click on add item, the modal freezes for few seconds and even though the card has been placed in the column the modal doesnt go away.

**Comment by lakshmanpasala** [comment]
Yes, I do use the email code and it is important for my project. 
Is there any workaround for better performance when I POST new data?
