### ISSUE TITLE
Feature Request: Allow users to download the data of cards as .csv file

### ISSUE THREAD

**Issue by lakshmanpasala** [kiswa/TaskBoard#270]
It would make monitoring and taking back-up easy if the admins and/or users can download all the data of all the cards in one go in one .csv file.

**Comment by kiswa** [comment]
Might be worth doing in the future.

In the meantime, you can export a sqlite3 databse to CSV fairly easily. Here's a shell script that will do it:

```
#!/usr/bin/env bash

# obtains all data tables from database
TS=`sqlite3 $1 "SELECT tbl_name FROM sqlite_master WHERE type='table' and tbl_name not like 'sqlite_%';"`

# exports each table to csv
for T in $TS; do

sqlite3 $1 <<!
.headers on
.mode csv
.output $T.csv
select * from $T;
!

done
```

Just call it as `script-name path/to/taskboard.db`
