### ISSUE TITLE
API Error. Could not connect to database

### ISSUE THREAD

**Issue by 1Mpuls3** [kiswa/TaskBoard#272]
Hi,

Just tried to install, so here are a few things:
I'm running nginx, php 5.6 there is already a website in prod using it.

What I've done: 
apt-get install sqlit3, php5-sqlite

I chmod everything, and F12 show some 405 error.

Any idea?

**Comment by kiswa** [comment]
I'm not too familiar with nginx. Could you post the error?

**Comment by 1Mpuls3** [comment]
When trying to connect to the admin the XHR Status Code return 405 Not Allowed.

But i'm quite sure that the problem come from the database not being setup properly.
When accessing devrouter I get: 
`{"message":"API Error.","data":"Could not connect to database (?).","alerts":null,"trace":[{"file":"\/var\/www\/TaskBoard-bfzat\/vendor\/gabordemooij\/redbean\/RedBeanPHP\/Driver\/RPDO.php","line":139,"function":"connect","class":"RedBeanPHP\\Driver\\RPDO","type":"->","args":[]},{"file":"\/var\/www\/TaskBoard-bfzat\/vendor\/gabordemooij\/redbean\/RedBeanPHP\/Driver\/RPDO.php","line":312,"function":"runQuery","class":"RedBeanPHP\\Driver\\RPDO","type":"->","args":["SELECT COUNT(*) FROM `user`  -- keep-cache",[]]},{"file":"\/var\/www\/TaskBoard-bfzat\/vendor\/gabordemooij\/redbean\/RedBeanPHP\/Driver\/RPDO.php","line":349,"function":"GetAll","class":"RedBeanPHP\\Driver\\RPDO","type":"->","args":["SELECT COUNT(*) FROM `user`  -- keep-cache",[]]},{"file":"\/var\/www\/TaskBoard-bfzat\/vendor\/gabordemooij\/redbean\/RedBeanPHP\/Adapter\/DBAdapter.php","line":164,"function":"GetOne","class":"RedBeanPHP\\Driver\\RPDO","type":"->","args":["SELECT COUNT(*) FROM `user`  -- keep-cache",[]]},{"file":"\/var\/www\/TaskBoard-bfzat\/vendor\/gabordemooij\/redbean\/RedBeanPHP\/QueryWriter\/AQueryWriter.php","line":988,"function":"getCell","class":"RedBeanPHP\\Adapter\\DBAdapter","type":"->","args":["SELECT COUNT(*) FROM `user`  -- keep-cache",[]]},{"file":"\/var\/www\/TaskBoard-bfzat\/vendor\/gabordemooij\/redbean\/RedBeanPHP\/Repository.php","line":526,"function":"queryRecordCount","class":"RedBeanPHP\\QueryWriter\\AQueryWriter","type":"->","args":["user",[],"",[]]},{"file":"\/var\/www\/TaskBoard-bfzat\/vendor\/gabordemooij\/redbean\/RedBeanPHP\/OODB.php","line":457,"function":"count","class":"RedBeanPHP\\Repository","type":"->","args":["user","",[]]},{"file":"\/var\/www\/TaskBoard-bfzat\/vendor\/gabordemooij\/redbean\/RedBeanPHP\/Facade.php","line":1171,"function":"count","class":"RedBeanPHP\\OODB","type":"->","args":["user","",[]]},{"file":"\/var\/www\/TaskBoard-bfzat\/api\/helpers.php","line":366,"function":"count","class":"RedBeanPHP\\Facade","type":"::","args":["user"]},{"file":"\/var\/www\/TaskBoard-bfzat\/api\/api.php","line":30,"function":"createInitialUser","args":[]},{"file":"\/var\/www\/TaskBoard-bfzat\/devrouter.php","line":17,"args":["\/var\/www\/TaskBoard-bfzat\/api\/api.php"],"function":"require_once"}]}`

But I've never used sqlite, so maybe I miss something? 
It's properly installed, apt-get didn't return any error. And I can do sqlite --help. Maybe there is a way to use my mySQL server instead?

**Comment by kiswa** [comment]
Is the file `taskboard.db` in the `api` directory? It looks like maybe the nginx user doesn't have permission to create the database.

You can certainly use MySQL instead [see here](http://www.redbeanphp.com/index.php?p=/connection). You just have to edit the setup call on [this line](https://github.com/kiswa/TaskBoard/blob/master/api/api.php#L28).

**Comment by 1Mpuls3** [comment]
You're right, the file isn't in the api directory. I'll look into permissions.

Tried mySQL too, got the same permission problem, I'll keep you updated, thanks for your help!

**Comment by 1Mpuls3** [comment]
Okay, seems like I managed to do it.

So, I just had to add the nginx.conf, which is really obvious, but I somehow didn't think I'd have to do it manually. So eveyrthing is fine now.
