### ISSUE TITLE
How to start TaskBoard

### ISSUE THREAD

**Issue by gujche** [kiswa/TaskBoard#273]
Hi, 

I followed instructions to the point 

>  Open your browser **to the location you put TaskBoard** and log into the site with the username admin and password admin. 

and here I don't understand what should I put in browser address. Can anybody clarify what should be done?

**Comment by kiswa** [comment]
Let's say your server is at http://localhost/ and that points to `/var/www`. If you have TaskBoard at `var/www/taskboard/` then you would go to http://localhost/taskboard/ to use it.

**Comment by kiswa** [comment]
Is this still an issue for you?

**Comment by gujche** [comment]
Thx for fast replay, I suppose your suggestion would solve the problem, but in the moment it looks quiet cumbersome in comparison with few other nice solutions. Anyway few lines in guide about setting server and running this solution would make it much more attractive, but it is just my opinion.

**Comment by cadupar** [comment]
I have the same issue and I share the same opinion about a guide with settings and steps would make much more attractive this App
