### ISSUE TITLE
Boards not displayed with latest Chrome

### ISSUE THREAD

**Issue by Ashceryth** [kiswa/TaskBoard#275]
Hi,

I am using Chrome Version 50.0.2661.75 m (64-bit) on Win10. When I login to Taskboard the Boards do not get displayed anymore. There is just the top bar and the drop down fields for selecting the board and filtering. The Settings section works without any issue. With Firefox everything is working fine.

Can anyone confirm this behaviour?

**Comment by martinfrnka** [comment]
I confirm that - same here - in IE all looks fine, In chrome (50.0.2661.75) only top bar as described in previous post.

**Comment by kiswa** [comment]
Well, that's no good. I'll look into this.

**Comment by sash85** [comment]
It seems google has fix the problem. After a Browser restart, taskboard works (on OSX El Captian).

**Comment by kiswa** [comment]
Confirmed, it works in latest Chrome!
