### ISSUE TITLE
[Feature] Integration with Bug Tracking systems

### ISSUE THREAD

**Issue by ZM-git** [kiswa/TaskBoard#277]
Hi @Kiswa,

I wrote a feature that I would like to bring in.  It allows users to integrate links to bug tracking tool(s) into the board's items similarly to TortoiseSVN [BugTraq](https://tortoisesvn.net/docs/release/TortoiseSVN_en/tsvn-dug-bugtracker.html). The tools can be configured on the board's setting/edit page.

All the changes to 'dev' are in this commit [commit](https://github.com/ZM-git/TaskBoard/commit/dd97919b5f6df935fc34e119e0a220c40a5cf0b2) and seem to behave just fine.

I'm not native in Angular (or any web development at all) so I didn't want to just propose pull request without a review of some sort.

**Comment by kiswa** [comment]
The code looked reasonable from a quick read-through. Go ahead and submit the PR and I'll take a closer look.

Thanks for the contribution!

**Comment by andrewdmaclean** [comment]
@kiswa I don't want to reopen an issue unnecessarily, but do you have any idea if this feature is working?

**Comment by kiswa** [comment]
@andrewdmaclean It should be functional, yes. In the settings for a board, the last item let's you setup a way for tasks in your board to automatically link elsewhere. The tooltip provides an example.

**Comment by andrewdmaclean** [comment]
Ah yes, that definitely makes sense - but I think perhaps the default RegExp for Github isn't working?

I have tried 4 different expressions and I am still not seeing any issues created in the Github Issues for the repository in question.

**Comment by kiswa** [comment]
Ah, yeah, it's not an integration. It's just a convenience for automatically linking to existing issues. @andrewdmaclean
