### ISSUE TITLE
Backup Data in Docker Container

### ISSUE THREAD

**Issue by TheReal1604** [kiswa/TaskBoard#281]
Hey,

i installed the Taskboard via docker with the line:

docker run -p 8088:80 -d devcrea/taskboard

How i can backup the data that i create in that application?

Thank you very much.

Greets
TheReal

**Comment by kiswa** [comment]
I really have no idea. I assume you can connect to a Docker container and pull files from it. That should be all you need to backup the `taskboard.db` file.

Maybe someone familiar with Docker can chime in.

**Comment by kiswa** [comment]
Closing due to lack of response. Let me know if this needs to be re-opened.
