### ISSUE TITLE
Installing TaskBoard

### ISSUE THREAD

**Issue by mdkrishan** [kiswa/TaskBoard#282]
Hi,

While executing the taskboard I'm getting the following error message.
How can I resolve this?

> ./build/composer.phar install
-bash: ./build/composer.phar: No such file or directory

Please help me ASAP.

Thanks & BR,
Krishan Perera

**Comment by kiswa** [comment]
Have you verified that the `build/composer.phar` file exists and is executable?

**Comment by kiswa** [comment]
Closing due to lack of response. If assistance is still needed let me know and I can re-open.
