### ISSUE TITLE
Installing in a server production

### ISSUE THREAD

**Issue by JonathanDel** [kiswa/TaskBoard#283]
Hi,
When I try to run it Is necessary to use the php internal server? Because I get this error when log in, actually I'm using apache.
![issue](https://cloud.githubusercontent.com/assets/5846320/15087656/774515be-13b0-11e6-9921-9c7cde32d87e.png)

**Comment by kiswa** [comment]
That error looks like the `api` directory is not writable. See #7 for some troubleshooting options.

**Comment by JonathanDel** [comment]
All files and folders have 777 permissions

**Comment by kiswa** [comment]
Is Apache setup to allow that directory to override settings? Something like:

```
<Directory /var/www/html/TaskBoard>
    AllowOverride All
    Options All
    Require all granted
</Directory>
```

**Comment by JonathanDel** [comment]
Thanks that was the problem, I haven't added it :)
