### ISSUE TITLE
Login not allowed with KeePass

### ISSUE THREAD

**Issue by JetUni** [kiswa/TaskBoard#285]
I saved my credentials in KeePass, and I know that they are the correct ones, but Task Board won't allow me to use them to login. It tells me "Invalid username or password." To log in, I have to delete the username AND password that KeePass has filled in for me and type it in myself, after which I'm able to log in. I'm not sure why it would do this as I'm typing the exact same thing as what KeePass is typing for me (in conjunction with KeePassHttp and ChromeIPass). Happens in latest version of Chrome on Windows 10, but I haven't tried any other browsers.

**Comment by mitpro** [comment]
Hello,
got the same Problem with KeePass(X) but it is a KeePass-Problem with the Auto-Fill-In-Function.
Use copy and paste for log in... Some special character will not fill in correct... you can try it with an empty text document.

**Comment by kiswa** [comment]
I'm going to assume @mitpro has answered this sufficiently for @JetUni to get things working.

If not, please let me know.

**Comment by JetUni** [comment]
No, not really. There are no special characters in my password just 2 letters and 1 number...

**Comment by kiswa** [comment]
Did you try using copy/paste for login (I'm assuming that's a KeePass setting - never used it)?
