### ISSUE TITLE
Task Board integration with HP Service Manager

### ISSUE THREAD

**Issue by s3cur3n3t** [kiswa/TaskBoard#286]
Hi guys,

We are about to install Task Board on our network, and we would like to know if there's a way to integrate it with HP Service Manager. I haven't look yet to the source code of TaskBoard, but will do in timely manner.

Thanks in advance.

Keep up the good work.

**Comment by kiswa** [comment]
TaskBoard does not have any specific integration with other products. It should be possible to do so, but I wouldn't know where to start as I have never even see HP Service Manager.

If you use the `dev` branch, there is a set of changes from a PR that will let you have a board link to issues on an external site. Maybe that'll do what you need?

Also, no 'guys', just me. ;)

**Comment by s3cur3n3t** [comment]
Hi kiswa,

Look the idea is to receive on a specific board and column, the incidents, changes, problems assigned to my team.. That's the kind of integration we are looking for.. 

Thanks.

Keep up the good work.

**Comment by kiswa** [comment]
Unfortunately there is no such integration in TaskBoard. Contributions are welcome!
