### ISSUE TITLE
Error during installation (Ubuntu 14) - git@github.com:firebase/php-jwt.git, git was not found

### ISSUE THREAD

**Issue by cadupar** [kiswa/TaskBoard#287]
When i run the Build command line i´m receiving this issue:

> git@github.com:firebase/php-jwt.git, git was not found

root@abbegroup201:/var/www/TaskBoard-master# ./build/build-all
Building...
 Installing dependencies
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "./build/composer.phar self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing firebase/php-jwt (1.0.0)
    Downloading: 100%
    Downloading: 100%
    Downloading: 100%
    Failed to download firebase/php-jwt from dist: The "https://api.github.com/repos/firebase/php-jwt/zipball/58c1e61d0dff797f2989c54415229f4016d57a6d" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known
failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known
    Now trying to download from source
  - Installing firebase/php-jwt (1.0.0)
    Cloning 58c1e61d0dff797f2989c54415229f4016d57a6d

  **[RuntimeException]
  Failed to clone git@github.com:firebase/php-jwt.git, git was not found, check that it is installed and in your PATH env.
  sh: 1: git: not found**

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [packages1] ... [packagesN]

**Comment by kiswa** [comment]
The answer is in the error:

> git was not found, check that it is installed and in your PATH env.

You need to install git to clone git repositories (I'm guessing you downloaded TaskBoard rather than cloning it).

If that doesn't work, you can always just try running the build again. It's possible there was a temporary connectivity issue as the download link in the error message just downloaded for me when I clicked it to test.
