### ISSUE TITLE
[Feature Request] Localization

### ISSUE THREAD

**Issue by hirnwunde** [kiswa/TaskBoard#290]
Hi all,

is there a way (in course of the re-write) to add localization.
ATM i had forked and translated the hardcoded strings.

**Comment by kiswa** [comment]
I am planning localization as part of the re-write! Right now, I'm just going to have a bunch of string constants that are loaded by user language - if you know a better way, let me know!

I'd really appreciate those translations you made as well. What language?

**Comment by hirnwunde** [comment]
Since PHP5.3 there is [intl] (php.net/manual/en/book.intl.php) but I don't have any experince with.
IMHO simple header-parse for **Accept-Language** and decide which languagefile is loaded should be enough to this _little_ project. (*Please do not misunderstand - this should not sound pejorative!*)

I have translated to german. But ATM only the old master-Branch.

**Comment by kiswa** [comment]
The header parsing is what I was planning. And don't worry, I know what you meant - there's not a huge amount of things to translate.

Of course, your current translations wouldn't work with the re-write - not sure why I even thought that. Would you be willing to contribute German translations once the re-write is complete?

**Comment by hirnwunde** [comment]
Of couse, I will! ;)
It's the least i can do.

**Comment by kiswa** [comment]
Excellent, thank you!

**Comment by altayevrim** [comment]
Hi, It's a good simple system and I want to contribute. Still making progress on Localization?

**Comment by kiswa** [comment]
The `re-write` branch actually has localization for the front end in place. The API doesn't use it yet though, so notifications of changes are all English, but it's on the list to get done. There's a wiki page that describes it (I'd link but I'm on my phone).

**Comment by altayevrim** [comment]
I'm on my pc. I'll look for it. Thanks. It's a really cool system that I
want to participate.
