### ISSUE TITLE
demo DB

### ISSUE THREAD

**Issue by snipesn** [kiswa/TaskBoard#291]
Hi, RedBeanPhp don't work for me, it is not create a empty structure database. Can you add sql structure to the repo and send me, thanks

**Comment by kiswa** [comment]
Is the `api` directory writable by the server? If Linux, `api` needs to be set to `777` permissions to allow anyone to read/write.

**Comment by snipesn** [comment]
Sorry for no answer. I solved problem, problem not in permissions, it is in library RedBeanPHP. They are not correct catch DB exception. Solved by deactivate plugin xdebug
