### ISSUE TITLE
Installed on server - Can't edit settings, add boards, add users etc.

### ISSUE THREAD

**Issue by goldsteinmedia** [kiswa/TaskBoard#293]
So I installed TaskBoard at http://s3th.me/taskboard

Strangely it logged me in right away. It's strange, because I didn't even setup a UN/PW.

When I go into Settings it doesn't let me edit anything and I can't even edit a board.

Please advise.

Thanks!

**Comment by kiswa** [comment]
I logged into your site, and saw that the API was erroring out when trying to include the vendor files.

Take a look at Step 2 of the install steps in [README.md](https://github.com/kiswa/TaskBoard#install) to get what you need.

**Comment by goldsteinmedia** [comment]
Darn. I don't remember how to do this. Help?

**Comment by kiswa** [comment]
If you just need the vendor files, I have them on DropBox: https://dl.dropboxusercontent.com/u/75313861/vendor.tar.gz

Just extract that so there is a `vendor` directory at the same level as the `api` directory (not inside `api`).

**Comment by goldsteinmedia** [comment]
Thanks
