### ISSUE TITLE
Can't loginto taskboard (after installation on Synology DS916+)

### ISSUE THREAD

**Issue by hubutz** [kiswa/TaskBoard#294]
Hi there,

I'm trying to instal taskboard on my Synology DS916+ (DSM 6.1). I've copied all the files and run the two commands that I should run. I can see the login screen when I open "nas/taskboard". But it shows me the login screen over and over if I enter admin:admin.
Any ideas?

Best
hubutz

**Comment by kiswa** [comment]
Any errors in the developer tools (<kbd>F12</kbd>)?

**Comment by hubutz** [comment]
Didn't know there is this thing. F12 didn't work but I got it activated.
Error is:

[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (login, line 0)

**Comment by kiswa** [comment]
Do you have TaskBoard setup with a web server, or did you just copy it to a NAS? It needs an actual server like Apache or NGINX.

**Comment by hubutz** [comment]
Well, it's copied into the /web folder of my NAS, there is an apache running.

**Comment by kiswa** [comment]
Thanks, I'm not familiar with how that NAS works, so I wanted to be sure.

Can you access server logs to see what errors it gave? The `line 0` bit is what's making me think something is missing. Does the server also have PHP installed?

**Comment by hubutz** [comment]
I'm not really familar with all that kind of stuff - which log file do you need? And do you have any clue where I can find it?
PHP is installed. I've just tryed to install kanboard and this just worked. I'll redownload the files and see if this helps.

**Comment by kiswa** [comment]
I would assume a `php_error.log` of some kind, and not really no, since I don't know how those NAS setups are working.

I don't really have enough info to figure out exactly what's going on here, so if you found another solution that works for you, don't feel obligated to spend time on this one (I actually contributed to Kanboard before creating TaskBoard).

**Comment by hubutz** [comment]
One thing I'm wondering: he tells me that the ressource: http://xxxl/taskboard/api/login is missing. There is no file/folder named api login in api.

**Comment by kiswa** [comment]
No, anything beyond `api/` doesn't actually exist. The `.htaccess` file provides redirection for those paths to the `api.php` file with the correct route to be used.

It's possible the Apache setting is not allowing `mod_rewrite` to do its job. Take a look at [these issue comments](https://github.com/kiswa/TaskBoard/issues/7#issuecomment-59827181) and see if that helps.

**Comment by hubutz** [comment]
Hi,
I figured that there is no mod_rewrite enabled. It seem that it's no apache but nginx running. But nevermind - I can have a depper look into kanboard - sorry, woul dhave liked to try yours!

**Comment by kiswa** [comment]
For the record, there is an NGINX config that should be working, though I've never used it myself. It's at `build/nginx.conf`.
