### ISSUE TITLE
Cannot load boards and users?

### ISSUE THREAD

**Issue by IniZio** [kiswa/TaskBoard#295]
I extracted the Taskboard to my apache and set api folder to be writable, following Taskboard site instructions. However the log shows "Error: fn is not a function" and the site shows error loading users, with no board info displayed also. Did I miss any steps ?

**Comment by kiswa** [comment]
Possibly. Did you follow the steps from the TaskBoard website or the README on GitHub? I haven't updated the site since v0.3.1 (sorry! - I've been distracted by the re-write) and you need to follow the README here to install PHP dependencies.

If you've done the steps here, then let me know.

**Comment by IniZio** [comment]
It seems like I did not install the composer dependencies according to README.md, however this time the page is blank after the instructions... Sorry if it bothers but should it work if I install the composer dependencies locally then upload to a server? Since it is a virtual host without ssh. Thanks!

**Comment by kiswa** [comment]
That should work, yes.

Is it giving any new errors in <kbd>F12</kbd> dev tools?

**Comment by IniZio** [comment]
weird it does not show any errors but display blank page after I installed composer... If I havent installed composer tho it does show the page but fails to fetch users and boards

**Comment by kiswa** [comment]
Just to be sure, here are the vendor files: https://dl.dropboxusercontent.com/u/75313861/vendor.tar.gz

Extract that so the `vendor` directory is one level up from `api` then let me know what you get..

**Comment by IniZio** [comment]
Rly sorry for bothering again it shows 'api/login 403 (Forbidden) error ' when I try to login.

**Comment by kiswa** [comment]
There are a few possibilities.  First, make sure the username/password entered was good. ;)

If you navigate directly to `http://your.taskboard.tld/api/` you should see a blank page. Do you?

Also, verify the Apache directory for TaskBoard has [this setup](https://github.com/kiswa/TaskBoard/issues/7#issuecomment-59831887) (and maybe look through #7 for other ideas).

**Comment by IniZio** [comment]
Hmm it shows a 404 page instead of blank page when i access `/api/`. I tried to copy the vendor directory to under root directory as it showed error `cannot find /api/../vendor/autoload.php`. now its showing 503 error... Sorry if it is getting annoying D:

**Comment by IniZio** [comment]
Hmm it shows a 404 page instead of blank page when i access `/api/`. I tried to copy the vendor directory to under root directory as it showed error `cannot find /api/../vendor/autoload.php`. now its showing 503 error... Sorry if it is getting annoying D:

**Comment by IniZio** [comment]
Just found it was because I did not make the setup for Apache directory, as you mentioned last response. Works like a charm thanks! :+1:
