### ISSUE TITLE
404 Error on Login

### ISSUE THREAD

**Issue by srdco** [kiswa/TaskBoard#296]
Trying to install on localhost / 127.0.0.1 on an intranet server running Ubuntu 12.04 LTS.
- Login page shows up but doesn't respond to login (just refreshes page)
- Firefox dev tools shows a 404 error being returned for [mylink]/taskboard/api/login

Done:
- already went to localhost virtual host file and added AllowOverride All for the taskboar directory
- php5-sqlite and sqlite are both installed

Any ideas?

**Comment by kiswa** [comment]
Have a look at #295 to see if anything we just went through there helps you.

Let me know if that doesn't solve it and I'll get into more detail with you.

**Comment by srdco** [comment]
Poked through it ... 
- I had already looked at that, tried tweaking lots of things ... no go

But ... checked the Apache error logs and there was this error:
"Invalid command 'ExpiresActive', perhaps misspelled or defined by a module not included in the server configuration, referer: [my url]"

Looked it up and found the answer at: http://www.bensprotips.com/2011/01/apache-error-invalid-command-expiresactive/

The Expires module wasn't activated. All set now!

**Comment by kiswa** [comment]
Glad you figured it out! Not sure why that was the problem (the `.htaccess` has a guard to make sure that mod is enabled before using those rules). I'll have to look into that.
