### ISSUE TITLE
Error on first login

### ISSUE THREAD

**Issue by holvaa** [kiswa/TaskBoard#297]
I have installed TaskBoard by just copying the folder to the httpdocs folder of my shared webhosting account.
On trying to login first time after installation with admin/admin nothing happens. Firebug console says: "NetworkError: 500 Internal Server Error - MyDomain/TaskBoard/api/login"
I've alread read the realted posts but none of the hints worked for me.

**Comment by kiswa** [comment]
You have the `vendor` folder as well? See #295 or #293 for example.

**Comment by holvaa** [comment]
That solved the problem! I didn't have the vendor folder. Noe that I've uploaded is everything runs fine.
Thank you very much
