### ISSUE TITLE
Feature request: Subscribe / Newsletter on TaskBoard website

### ISSUE THREAD

**Issue by fernandodiacenco** [kiswa/TaskBoard#298]
I just wanted to receive an email when a new version is released or something interesting happened

Perhaps an RSS feed would do.

**Comment by kiswa** [comment]
That's certainly an option I will consider.

In the meantime, whenever I put out a new release it goes on [my Twitter](https://twitter.com/kiswa00) (for example, [v0.3.0](https://twitter.com/kiswa00/status/607240277380759552) was announced).
