### ISSUE TITLE
Buttons not showing correctly

### ISSUE THREAD

**Issue by s3cur3n3t** [kiswa/TaskBoard#305]
Hi,

The buttons on TaskBoard, not appearing correctly, any suggestions?

Tahnk very much
![taskboard_bug](https://cloud.githubusercontent.com/assets/9367773/17939736/dc2323c6-6a23-11e6-85a2-b0c8936b8317.png)

**Comment by kiswa** [comment]
Looks like the fonts aren't downloading. Are you getting any 404 errors in dev tools?

**Comment by kiswa** [comment]
Closing due to lack of response.
