### ISSUE TITLE
Issue with IIS installation

### ISSUE THREAD

**Issue by Zipelkopf** [kiswa/TaskBoard#306]
Hi,
I would like to use TaskBoard under IIS but I'm having an issue on first login.

The IIS server has PHP 5.x installed and SQLite enabled (see screenshot) as per requirements.
![capture](https://cloud.githubusercontent.com/assets/21308710/18049636/68d4afea-6de1-11e6-96ec-50b30af9c83d.PNG)

I can display correctly the login page (see screenshot) but nothing happens when I use the default login credentials (**admin**/**admin**).
![capture2](https://cloud.githubusercontent.com/assets/21308710/18049718/d1cb0148-6de1-11e6-8aec-f3438bc7debe.PNG)

I have attached here also the **phpinfo** page for your review.
What do you think I'm doing wrong? Anything missing or miss-configured?
[phpinfo.pdf](https://github.com/kiswa/TaskBoard/files/442279/phpinfo.pdf)

Thanks for any help!

**Comment by kiswa** [comment]
The PHP side looks fine. You probably have to implement the IIS equivalent of what's in the `.htaccess` files (the main one and the one in `api/`).

A quick search [found this](https://akrabat.com/zend-framework-url-rewriting-in-iis7/), but I've never done this before myself. Let me know how it goes!

**Comment by Zipelkopf** [comment]
Hi, thanks for your quick reply.

I have now installed URL Rewrite for IIS and I'm trying to import the rules and conditions taken from the .htaccess file as you have suggested.

Following are the rules to import at the API level... there are no rules to import instead at the root level:
```
RewriteCond %{REQUEST_URI}::$1 ^(.*?/)(.*)::\2$
RewriteRule ^(.*)$ - [E=BASE:%1]
RewriteRule ^taskboard.db$ %{ENV:BASE}api.php [QSA,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ %{ENV:BASE}api.php [QSA,L]
```

When I import the rules in IIS get the following error messages, I believe because they need to be converted into the IIS model:
1) Unsupported flag E (line 2 to import above)
2) Unsupported ENV:BASE (lines 3 and 5 to import above)
![capture](https://cloud.githubusercontent.com/assets/21308710/18052657/8d83088e-6df3-11e6-9e01-17b0d1e9a4ed.PNG)

Can you please help on finding the equivalent statements for IIS?
Thanks again

**Comment by kiswa** [comment]
Those two lines it complains about are so it will work wherever a user has installed TaskBoard. Since you already know where the API files are, you can be specific and remove those lines.

```
RewriteCond %{REQUEST_URI}::$1 ^(.*?/)(.*)::\2$
RewriteRule ^taskboard.db$ /your/path/to/api.php [QSA,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ /your/path/to/api.php [QSA,L]
```

**Comment by Zipelkopf** [comment]
Great! :+1: 
the URL Rewrite seems to work now... by the way, I am returning a 500 error.

So, I have started debugging the code and the third line of the **api.php** file requires the **autoloader.php** file which I couldn't find... also I couldn't locate the entire **vendor/** folder

`require_once(__DIR__.'/../vendor/autoload.php');`

Can you please provide it? Or where can I found it?

If I comment that line, then the 500 error doesn't show up but I get a blank page ;-(
Any idea? Thanks again.

**Comment by kiswa** [comment]
It just so happens I have [a copy on Dropbox](https://dl.dropboxusercontent.com/u/75313861/vendor.tar.gz).

Normally, you would run the build scripts to get it installed.

**Comment by Zipelkopf** [comment]
Thanks for the package, I'm going to try and let you know.

I have tried running the build script as per documentation... but I believe it works in a Linux environment only, isn't it? Can I instead run it under Windows as well, in order to get any benefit?
> Optional: Minify everything for better performance in production. (Requires that everything but compiler.jar in build/ is executable.)
> Open the TaskBoard directory in a terminal
> Run ./build/build-all

Thanks

**Comment by Zipelkopf** [comment]
Hi again :-)

I have good and bad news... the good one is that I can see now requests going trough in the server log... see below.
Te bad one is that the very last **POST** request points to **/TaskBoard/api/login** which is a resource that does not exist... the **api/** folder doesn't have a **login/** one inside... what am I missing?

Then all I see is a blank page...
FYI, no errors logged in PHP since I added the **vendor/** folder.

> 2016-08-30 11:57:24 ::1 GET /TaskBoard/lib/jquery-1.11.3.min.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 25
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/lib/angular.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 18
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/lib/angular-route.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 18
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/lib/jquery-ui.min.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 18
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/lib/jquery.noty.min.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 18
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/lib/bootstrap.min.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 18
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/lib/angular-sanitize.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 56
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/lib/ng-context-menu.min.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 56
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/lib/marked.min.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 30
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/lib/prefixfree.min.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 30
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/lib/spectrum.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 30
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/app.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 30
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/controllers/boards.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 8
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/controllers/settings.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 8
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/controllers/boardsItemForm.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 8
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/controllers/boardsItemView.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 8
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/controllers/files.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 13
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/controllers/settingsAutoActions.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 12
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/controllers/settingsUser.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 7
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/controllers/settingsUserForm.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 7
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/controllers/settingsBoard.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 13
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/controllers/settingsBoardForm.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 13
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/controllers/login.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 7
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/controllers/header.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 5
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/services/token.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 10
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/services/user.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 10
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/services/board.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 13
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/services/auth.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 13
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/services/alerts.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 13
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/directives/includeReplace.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 8
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/directives/clickToEdit.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 5
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/directives/onLoadCallback.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 5
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/directives/focus.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 3
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/js/directives/fileUpload.js - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 3
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/images/bg.png - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 4
> 2016-08-30 11:57:24 ::1 GET /TaskBoard/partials/login.html - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 304 0 0 2
> 2016-08-30 11:57:42 ::1 **POST /TaskBoard/api/login** - 80 - ::1 Mozilla/5.0+(Windows+NT+6.1)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36 404 0 0 91

**Comment by kiswa** [comment]
The `.htaccess` rules are what redirect anything after `api/` to the proper endpoint. Nothing exists on the filesystem beyond `api/`.

IIS was never a target for TaskBoard, so I'm not really able to directly help - but I can try pointing you in the right direction. The API uses SQLite and the `api/` directory should be writable by SQLite. It's possible [this article](https://alephnull.uk/content/getting-php-and-sqlite-running-iis-6) will help you out.

**Comment by Zipelkopf** [comment]
Ok, thanks for that, I appreciate every help... :+1: 
I will continue investigating and keep you posted on progress.

Cheers

**Comment by Zipelkopf** [comment]
Hi Kiswa,
I made it!!! :100: 

I'm going to write up a step-by-step guide on how to use TaskBoard under **ISS** for Windows... I hope it can be useful to someone else too, I will keep in touch shortly :-)

Attached below is a screenshot of a dummy test board, just to test and prove it's working:
![capture](https://cloud.githubusercontent.com/assets/21308710/18126444/161ee200-6f73-11e6-9c59-d4b6d7c39de6.PNG)

**Comment by kiswa** [comment]
Glad you got it working!

I'll be looking forward to your guide so it can be included with TaskBoard for future IIS users.
