### ISSUE TITLE
401 response when trying to log in

### ISSUE THREAD

**Issue by tkjacobsen** [kiswa/TaskBoard#308]
Hi,

When trying to log in, I get a 401 response for the following files:
* boards
* current
* authenticate

Each response contains an "invalid token" message. Any ideas?
![capture](https://cloud.githubusercontent.com/assets/201986/18179117/579939a6-7081-11e6-9115-1ef74d171109.PNG)

**Comment by kiswa** [comment]
Assuming you've logged in before, there's probably a bad token in your localStorage. You'll have to open Settings for the dev tools and enable Storage, then go in there and look for Local Storage, then delete the token for where you have TaskBoard (it will match whatever your domain is).

If that doesn't take care of it, let me know.

**Comment by tkjacobsen** [comment]
localStorage is empty. If trying with a different browser (firefox, IE and chrome) problem is the same

**Comment by tkjacobsen** [comment]
I changed the following in apache config:
Options Indexes FollowSymLinks MultiViews

to 

Options Indexes FollowSymLinks

and the issue went away after apache restart..

**Comment by kiswa** [comment]
Glad you figured it out. Thanks for sharing the solution!
