### ISSUE TITLE
Crash when running on php 7.0

### ISSUE THREAD

**Issue by tkjacobsen** [kiswa/TaskBoard#309]
Hi,

When running on php 7.0, I observe a crash that blocks me from logging in. From apache error log:

>ErrorException: password_hash(): Use of the 'salt' option to password_hash is deprecated in /usr/home/xxx/src/TaskBoard/api/userRoutes.php:17
>Stack trace:
>#0 [internal function]: Slim\Slim::handleErrors(8192, 'password_hash()...', '/usr/home/xxx/s...', 17, Array)
>#1 /usr/home/xxx/src/TaskBoard/api/userRoutes.php(17): password_hash('admin', 1, Array)
>#2 [internal function]: {closure}()
>#3 /usr/home/xxx/src/TaskBoard/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
>#4 /usr/home/xxx/src/TaskBoard/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
>#5 /usr/home/xxx/src/TaskBoard/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
>#6 /usr/home/xxx/src/TaskBoard/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
>#7 /usr/home/xxx/src/TaskBoard/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
>#8 /usr/home/xxx/src/TaskBoard/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
>#9 /usr/home/xxx/src/TaskBoard/api/api.php(52): Slim\Slim->run()
>#10 {main}

As you can see, the crash is triggered by the exception due to php 7.0 having deprecated use of salt in password_hash. 

Deleting all instances of use of salt in password_hash and commeting out passwork checking code works around the crash (and makes the solution completely insecure). 

Correct solution would be to use the salt returned by password_hash to store in the database and then to use password_verify in all cases where password is to be verified (rather than hashing again and doing string comparison). (I might try creating a patch but will take some time for me to get up to speed)

**Comment by kiswa** [comment]
I wouldn't worry about it unless it's very important to you.

The re-write branch has already removed this behavior (salts aren't stored at all anymore, and `password_verify` is used).

PHP 7 is supported in the new TaskBoard, but not in any existing release.

**Comment by cscholz** [comment]
Is it possible to test the new branch? I've taken a look into the re-write branch but it seems that there are files missing.

**Comment by kiswa** [comment]
There should not be anything missing in the re-write branch, however it is also not a functional replacement yet.

Right now it has:

 * API
 * Authentication
 * User Maintenance (for logged in user settings and options)
 * User Administration (add/edit/remove users)
 * Board Administration - Partial (add/edit boards so far)
 * Mockups for Boards and a new Dashboard page
