### ISSUE TITLE
Install on Windows IIS

### ISSUE THREAD

**Issue by bradstrittmatter** [kiswa/TaskBoard#311]
I tried to install this on windows IIS with PHP 5.6 and when i try to login for the first time it's giving me a 404 error code that login.php does not exist.  Any thoughts on what could be wrong or how i can fix it?

Love the project, but I can only run it on IIS... so any help in getting that working would be greatly appreciated!

Thanks!

**Comment by kiswa** [comment]
Your timing is excellent.

Another user just did this and wrote up a nice how-to. I [added it to the wiki here](https://github.com/kiswa/TaskBoard/wiki/TaskBoard-on-IIS).

If that doesn't get it going for you, let me know and we can re-open this.
