### ISSUE TITLE
PHP 7 support in logon route

### ISSUE THREAD

**Issue by andresmihkelson** [kiswa/TaskBoard#313]
I could not get TaskBoard working on PHP 7.0.9.

The problem I encountered was following:
Message: password_hash(): Use of the 'salt' option to password_hash is deprecated
File: api/userRoutes.php
Line: 17

Current logon check is using password_hash in a way that is deprecated in PHP7 and throws an error level exception on my server platform.

**Comment by kiswa** [comment]
Take a look at #309.

PHP 7 is not supported by the current version of TaskBoard; however the re-write does support it so this is only temporary.
