### ISSUE TITLE
Db structure missing

### ISSUE THREAD

**Issue by stephenmap** [kiswa/TaskBoard#314]
DB structure mission as you have given source .

**Comment by kiswa** [comment]
I have no idea what you mean, can you elaborate?

**Comment by bbichero** [comment]
Like @kiswa said in #315  

> The database file is generated the first time you log into TaskBoard, this is why the `api` directory needs writepermissions.

If you want to use Mysql, MariaDB or whatever other database like, edit line 28 of `api/api.php` file and follow [http://www.redbeanphp.com/index.php?p=/connection](url) to enter correct informations.

**Comment by kiswa** [comment]
Closing due to lack of response.
