### ISSUE TITLE
taskboard.db missing

### ISSUE THREAD

**Issue by muruganmap** [kiswa/TaskBoard#315]
taskboard.db file missing 

https://github.com/kiswa/TaskBoard

**Comment by kiswa** [comment]
I have no idea what you mean, can you elaborate?

Also, is this a duplicate of #314?

**Comment by muruganmap** [comment]
I have checked and tried to install your taskboard script from my server but I couldn't able to find you taskboard related database file. Can you provide me Taskboard(taskboard.db) database? 

 Is it possible to use MySQL database instead of sqllite?

**Comment by kiswa** [comment]
The database file is generated the first time you log into TaskBoard, this is why the `api` directory needs write permissions.

And yes, you can use any of several different database options that RedBeanPHP supports. See #105.

**Comment by muruganmap** [comment]
Ok I will check and let you know status. Thanks for your support.

**Comment by bbichero** [comment]
@muruganmap, everythink good ? Does the dabase correctly generated when compiling `./build-all` ?

**Comment by kiswa** [comment]
Closing due to lack of response. Will re-open if needed.

Thanks @bbichero for bumping these old issues so I can close them.
