### ISSUE TITLE
invalid username or password  on live server and  how can i run project without http://127.0.0.1:8080/

### ISSUE THREAD

**Issue by ak84513** [kiswa/TaskBoard#316]
![screeen](https://cloud.githubusercontent.com/assets/22544212/19012050/4132168a-87c7-11e6-8830-b736beb062be.png)

how run on Apache,IIS means without php -S 127.0.0.1:8080 devrouter.php

**Comment by kiswa** [comment]
Please provide details.

**Comment by bbichero** [comment]
On which OS run you TaskBoard ?
If it's on a Unix like OS, I suggest to install apache2 package and create a virtual host, it's easy.
```
<VirtualHost *:80>
	DocumentRoot /path/to/TaskBoard
	ServerName task_board

	<Directory /path/to/TaskBoard>
		DirectoryIndex index.html
        	Require all granted
        	Options -Indexes +FollowSymLinks +MultiViews
              	AllowOverride All
        </Directory>

	ErrorLog ${APACHE_LOG_DIR}/task_board.log

    	# Possible values include: debug, info, notice, warn, error,
    	# crit,
    	# alert, emerg.
    	LogLevel warn

</VirtualHost>
```
Active mandatory apache2 modules
`sudo a2enmod rewrite expires`

Active new virtual host
```
sudo a2ensite task_board
sudo service apache2 restart
```

**Comment by kiswa** [comment]
Closing due to lack of response.
