### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by GaneshKandu** [kiswa/TaskBoard#318]
Hi 
I am Trying to Install `TaskBoard v0.3.1` on my linux machine but getting `Internal Server Error`  in response of  api/login when trying to login with admin:admin pass:admin

Installing on PHP Version 5.5.31
Apache 2.2.31 (Unix) Server and tested on Apache 2.4.18 (win) also
I have sqlite3 installed on my machine
and `AllowOverride All` is on

I have installed Composer and build too

```
php  build/composer.phar install
sh  build/build-all
```

**Comment by kiswa** [comment]
Can you let me know what details come up for that 500 response in dev tools (<kbd>F12</kbd> usually)?

**Comment by GaneshKandu** [comment]
![dxzsgfbvxc](https://cloud.githubusercontent.com/assets/12833130/19210550/a384cf86-8d43-11e6-8308-c48ef9a64af1.png)
.
.
.
.
.
![dfh](https://cloud.githubusercontent.com/assets/12833130/19210552/a7b29b9c-8d43-11e6-9b65-982e78debf6c.png)

**Comment by GaneshKandu** [comment]
[ip] - - [14/Oct/2016:15:50:39 +0530] "POST /manual/taskboard/api/login HTTP/1.1" 404 - "[url]/manual/taskboard/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0"

its my access.log file getting 404 error on accessing api/login

**Comment by kiswa** [comment]
Is the `api` directory writable for the Apache user?

**Comment by GaneshKandu** [comment]
yes its writable , same error getting on windows also

**Comment by GaneshKandu** [comment]
I Think error is in htaccess configuration it Redirect to api.php its right but there is somethink wrong in .htaccess

```bat
ExpiresActive Off
RewriteEngine On

RewriteCond %{REQUEST_URI}::$1 ^(.*?/)(.*)::\2$
RewriteRule ^(.*)$ - [E=BASE:%1]

RewriteRule ^taskboard.db$ %{ENV:BASE}api.php [QSA,L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ %{ENV:BASE}api.php [QSA,L]

```

**Comment by kiswa** [comment]
If you're running it on Windows (IIS), then make sure you import the .htaccess rules as explained in [the wiki page](https://github.com/kiswa/TaskBoard/wiki/TaskBoard-on-IIS).

**Comment by GaneshKandu** [comment]
I am using Apache 2.4.18

**Comment by kiswa** [comment]
Do you have `mod_rewrite` enabled?

`a2enmod rewrite`

**Comment by GaneshKandu** [comment]
i think i got the error

this .htaccess should work fine if u have installed ``` expires_module ``` and i have not that's why i am getting Internal server error 

```
ExpiresActive Off
RewriteEngine On

RewriteCond %{REQUEST_URI}::$1 ^(.*?/)(.*)::\2$
RewriteRule ^(.*)$ - [E=BASE:%1]

RewriteRule ^taskboard.db$ %{ENV:BASE}api.php [QSA,L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ %{ENV:BASE}api.php [QSA,L]
```
this is a solution, if you check for module if exist then only execute this ```ExpiresActive Off``` then it should work fine even this module is not installed

```
<IfModule mod_expires.c>
	ExpiresActive Off
</IfModule>
RewriteEngine On

RewriteCond %{REQUEST_URI}::$1 ^(.*?/)(.*)::\2$
RewriteRule ^(.*)$ - [E=BASE:%1]

RewriteRule ^taskboard.db$ %{ENV:BASE}api.php [QSA,L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ %{ENV:BASE}api.php [QSA,L]
```

**Comment by kiswa** [comment]
Good find! That should definitely be wrapped in a guard as you have done.

**Comment by kiswa** [comment]
Closing due to age and inactivity. If you still need help, comment and I can re-open.
