### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by kennethjhim** [kiswa/TaskBoard#319]
When I try to login, it shows the following error under the Chrome Developer Tools console

![image](https://cloud.githubusercontent.com/assets/22592384/19221229/c58da9fc-8e71-11e6-9745-a3d4ddc9483b.png)

**Comment by rogermsw** [comment]
Unable to login chrome returned:
angular.js:9866 POST http://127.0.0.1:8079/TaskBoard-master/api/login 500 (Internal Server Error)

**Comment by GaneshKandu** [comment]
Check #318

**Comment by kiswa** [comment]
Alternately, install the mod `a2enmod expires`.

Let us know if this fixes the issue.

**Comment by ccw1996** [comment]
@rogermsw hello ,i'm sorry that i have similar problem,but it's not 500,it's 404.
i upload to azure.and not other step. i can't deal with

**Comment by ccw1996** [comment]
and it show undefined Ensure api directory is writable. sometimes show 503

**Comment by sorinsfirlogea** [comment]
Hi, same problem here. I do have mod_rewrite and mod_expires enabled, but I keep getting the same error as kenethjim. You should maybe know that I'm running PHP with proxy_fcgi module. That might create the problem?

**Comment by kiswa** [comment]
Yeah, the module could be causing the problem. I'm not really familiar with running PHP that way.

**Comment by GaneshKandu** [comment]
Check it ,I didn't tested it ,I think it should work

'''
<IfModule mod_expires.c>
    ExpiresActive Off
</IfModule>
RewriteEngine On

RewriteCond %{REQUEST_URI}::$1 ^(.*?/)(.*)::\2$
RewriteRule ^(.*)$ - [E=BASE:%1]

RewriteRule ^taskboard.db$ %{ENV:BASE}api.php? [QSA,L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ %{ENV:BASE}api.php? [QSA,L]
'''

**Comment by gremy91** [comment]
Hi, I have the same issue.
My developer Tools say : 
```
POST http://127.0.0.1:4567/TaskBoard/api/login 500 (Internal Server Error)
(anonymous function)	@	libs.min.js:507
```
I already read #7 , #318  , and this curent ticket ... but I don't now what can i do.
I follow step by step the process descibe on the git pages.
I change my .htaccess on api folder.
I make sure the folder have chmod 777

Can someone help me ?

**Comment by GaneshKandu** [comment]
check ``` expires_module ``` and ```mod_Rewrite``` is enable
in Apache using ```php phpinfo(); ``` check in ```Loaded Modules``` list 
![gdfhjk](https://cloud.githubusercontent.com/assets/12833130/19965646/0d38c784-a1ee-11e6-82af-250f9b23890d.png)
on fast CGI using this command ``` httpd -t -D DUMP_MODULES```

dont give 777 chmod on fast cgi only chown

**Comment by gremy91** [comment]
Module expires and rewrite are enable : 
![image](https://cloud.githubusercontent.com/assets/23237010/19967942/9d5328f8-a1d2-11e6-9420-29536b53eae5.png)

**Comment by GaneshKandu** [comment]
I Think you are using PHP5.3 upgrade to PHP 5.3 doesn't support ```[]``` Array

**Comment by gremy91** [comment]
Many thank @GaneshKandu .
Ok it working good now.
But I re-install everything on an another system version.

For information, I install this solution on : 
ubuntu trusty64
Apache/2.4.7
PHP 5.5.9-1 ubuntu 4.20

**Comment by kiswa** [comment]
Closing due to lack of response from OP.

Glad everyone else in here seems to have found their fixes though!
