### ISSUE TITLE
Is there a way to have it so that I don't get logged out ever 5 minutes

### ISSUE THREAD

**Issue by phillycodehound** [kiswa/TaskBoard#321]
I LOVE Your app. But getting signed out all the time is very frustrating. How can I stop this from happening.

**Comment by trieq** [comment]
`    $expires = ($data->rememberme)
        ? (2 * 7 * 24 * 60 * 60) /* Two weeks */
        : (1.5 * 60 * 60) /* One and a half hours */;
`
is this the code that timesout the login?

**Comment by kiswa** [comment]
@trieq Yes, that sets the timeout. You could always just set it to a ridiculous number and stay logged in forever.

FYI - In the re-write the default timeout has been changed, as well as the behavior of the tokens so as long as you do something within a time limit (an hour or two, I think) you get a new token good for that length of time again. Using the remember option activates tokens for like 4 days or something.
