### ISSUE TITLE
ajax tasks pending for a very long time

### ISSUE THREAD

**Issue by deligant** [kiswa/TaskBoard#323]
some ajax tasks are in pending mode for ages (items and autoactions)

and basically every time you create/edit something the dialog does not disappear.

**Comment by deligant** [comment]
After fiddling around I solved the issue...

in /api there is a file mailConfig.php that needs to be configured with the correct credentials so that the board can send mails.

I suggest to include this instruction into the readme(s) and the wiki Installation procedures, as at the moment there is no evidence of this step!

**Comment by kiswa** [comment]
Yeah, this has been reported before. I was hoping the re-write of TaskBoard would go faster than it has so I wouldn't have to change the current setup, but I'll at least mention the email issue in the wiki.
