### ISSUE TITLE
unable to send email from taskboard

### ISSUE THREAD

**Issue by Karunakartiwari** [kiswa/TaskBoard#324]
Hi Kiswa,

Greeting !

first of all thank you so much for making such a wonderful platform 
I have setup taskboard ,setup a board .when i add a task and assign to a user email notification does not go to user,user  added with valid email ID .also I given SMTP details of Gmail as per field in mailConfig.php.
for your info i have enable less secure app support in Gmail.
please advise a solutions.

Warm Regards
Karunakar

**Comment by kiswa** [comment]
I have never used the email functionality - it was provided by a PR - so I'm not really familiar with setting it up for anything other than using the hosting server's email functionality.

Maybe someone else can chime in on this one?

**Comment by kiswa** [comment]
PHP mail function as far as I know.

**Comment by Karunakartiwari** [comment]
Hi,
Thanks i have enable PHP mail function as well but email does not sent.is there any specific settting for this during taskboard install.I followed all standard process to implement.

**Comment by deligant** [comment]
I think gmail uses TLS and not SSL, so if you didn't already do, edit the api/mailConfig.php file and change 
`
$MAIL_SMTPSECURE = 'ssl';                            // Enable TLS encryption, `ssl` also accepted
$MAIL_PORT = 465;                                    // TCP port to connect to
`
into
`$MAIL_SMTPSECURE = 'tls';                            // Enable TLS encryption, `ssl` also accepted
$MAIL_PORT = 587;                                    // TCP port to connect to
`

**Comment by kiswa** [comment]
If @deligant's answer doesn't help, try to contact @Shattenjagger as they contributed the email PR.

I have it on my list for the re-write branch to learn the mail functionality and make some tweaks so I will be able to support it in the future.

**Comment by Karunakartiwari** [comment]
@Shattenjagger Greeting !!
 can you please advise how to use this email PR setting ,i have setup taskboard everything seems fine except email alert when we add a task and assign to user.I have done all setting in mailConfig.php as per @delihant's Guide  but still this module is not working we don't get any alert when we edit add new task.
Thanks 
Karunakar

**Comment by vvdimako** [comment]
I have the same problem. Please keep us posted on any solutions.
@deligant gmail uses ssl (currently using it with no problems e.g. for dokuwiki)

**Comment by deligant** [comment]
As another user suggested, you can comment out the entire content and mails should go out throught the normal MTA of your server (at least on linux).
this article may help you in setting up Google SMTP account
http://www.serversmtp.com/en/smtp-gmail-configuration

Third point is... sender email should exists (in order to receive the complaints of the mail servers implied in the process)

**Comment by vvdimako** [comment]
@deligant third point was right on target! I just filled the whole email address in $MAIL_FROM and it worked immediately. Thank you!

**Comment by kiswa** [comment]
Is this issue resolved?
