### ISSUE TITLE
emails are not "MarkDown"-formatted

### ISSUE THREAD

**Issue by deligant** [kiswa/TaskBoard#325]
First of all, thank you for this great tool!

While items containing MarkDown content are correctly formatted when shown on board, the email sent are bare textual...
Will it be possible to have them formatted as well?
Fiddling around I think the "translation" is done via a JS plugin... if this is correct, I could try to implement in the mailfactory the same "translation" in PHP and send you the code to patch this situation!

**Comment by kiswa** [comment]
I think that's an excellent idea for the re-write. I'll add it to my list of things to accomplish.

I wouldn't worry about contributing to the current TaskBoard, as I'm not updating it so I can focus on the re-write effort.
