### ISSUE TITLE
EMail templates need re-working

### ISSUE THREAD

**Issue by vvdimako** [kiswa/TaskBoard#327]
Hello there.
The email templates in api/mail_templates follow this simple pattern:
`<a href="http://%hostname%/#/boards/%boardid%">Navigate to board!</a>`
This does not generate correct addresses when https is used and/or when the taskboard installation is in a subdirectory of the server's document root.
Best regards

**Comment by kiswa** [comment]
Yeah, the entire email setup is getting re-written. Thanks for pointing this out though; I'll add it to my re-write list.
