### ISSUE TITLE
Create a Board or a Task take more than 1 minute

### ISSUE THREAD

**Issue by loclamor** [kiswa/TaskBoard#329]
Is it normal that creating board or creating Tasks take more than 1 minute to process ?
I can see the new element behind the cration modal before the query ends and close the modal.
Others api query took just a few milliseconds.

**Comment by kiswa** [comment]
This is a known issue when the email settings are not right. See #248 and let me know if that solves it for you.

**Comment by loclamor** [comment]
Yeah, that works for me.
Thank you !
