### ISSUE TITLE
Installing on a shared hosting ?

### ISSUE THREAD

**Issue by Ratatoskk** [kiswa/TaskBoard#332]
Hi, 
I copied by FTP the TaskBoard files in a folder on my server, I gave the write access to api folder, but when I go in a web browser and use the admin-admin login/password, I can't do nothing in Board or Settings... What is the problem, please ?
Thank you for your great work, best regards

**Comment by kiswa** [comment]
You probably need the vendor files for the back end if you didn't do that before uploading.

You can get a (somewhat outdated) copy here: https://dl.dropboxusercontent.com/u/75313861/vendor.tar.gz

**Comment by alexlunadev** [comment]
Hi Ratatoskk,

You need to download the dependencies via composer by running this command in terminal (first you have to navigate to the build folder using cd command then execute)  $ **php composer.phar install**   this will download the dependencies and creates a new folder "vendor" in build "/vendor/" copy the vendor folder to the parent folder. Try to open in the browser it should be working.

**Comment by kiswa** [comment]
Closing due to lack of input from OP. If you still need help, let me know.

**Comment by pcapelo** [comment]
same issue here, I don't have shell access to run the install. 
it would be nice to have a PHP install that I could run form the browser.
