### ISSUE TITLE
unable to change password and no buttons are working in setting page...

### ISSUE THREAD

**Issue by minise** [kiswa/TaskBoard#333]

**Comment by kiswa** [comment]
Can't help without details.

**Comment by alexdevgithub** [comment]
Same here. Buttons are not clickable.
![capture](https://cloud.githubusercontent.com/assets/13272766/21971719/34102818-dbee-11e6-8df6-34437ae96629.PNG)

**Comment by kiswa** [comment]
That looks like something went wrong with getting data from the API.

Use the <kbd>F12</kbd> developer tools and post any errors.

**Comment by alexlunadev** [comment]
After downloading the dependencies via composer and moving to root folder /TaskBoard/vendor the button now were clickable and I can add new boards.

**Comment by kiswa** [comment]
@alexlunadev Glad you figured it out!

Closing due to lack of input from OP. If you still need help, let me know.
