### ISSUE TITLE
recurring tasks

### ISSUE THREAD

**Issue by atsepkov** [kiswa/TaskBoard#336]
I love the simplicity of the app, thank you for building it.

I'm using the board as a personal planner and was wondering if it's possible to add recurring tasks? For example, say I want to remember to do an activity on a monthly basis without having to manually put it there.

Thanks

**Comment by kiswa** [comment]
This was suggested in [a comment](https://github.com/kiswa/TaskBoard/issues/288#issuecomment-229764103) of #288.

I plan to include it in the re-write effort!
