### ISSUE TITLE
Copy board

### ISSUE THREAD

**Issue by avtomatron** [kiswa/TaskBoard#337]
Hi. Thanks for app!
Please, tell me - how can i copy or clone board? I want to build reference board and then clone it for each project. How can i clone\copy?

**Comment by kiswa** [comment]
This is an upcoming feature. Right now, the only way to do it would be in the database.

**Comment by poikilos** [comment]
@kiswa Should this issue be reopened as a feature request? I don't see the feature in the live demo (0.3.1) or the documentation.

**Comment by kiswa** [comment]
It's planned for the v1 series.
