### ISSUE TITLE
Can't save login username and password

### ISSUE THREAD

**Issue by davidshenmue** [kiswa/TaskBoard#339]
Chrome is not auto filling saved passwords.

**Comment by kiswa** [comment]
This seems like a browser issue. There's nothing in TaskBoard preventing that.

**Comment by davidshenmue** [comment]
Yeah, it's on latest chrome, saves password in Firefox though.  It might be
that I have a login saved at the root domain, and /taskboard doesn't want
to save another login?

 I'd wait to see if anyone else has the problem before closing this.
