### ISSUE TITLE
Update interval causes scrollbar to jump back

### ISSUE THREAD

**Issue by alex3305** [kiswa/TaskBoard#34]
I don't know if this is an AngularJS specific issue and can even be fixed, but I notice that when the page refreshes, it goes back to the top of the page. This should be no problem, but can be pretty annoying when you are reading an issue which doesn't fit in a task.

Is there another way of refreshing the notes? Or is it possible to use an Angular plugin to retain the position of the scrollbar? Do you have any ideas about this?

**Comment by taikedz** [comment]
+1 from me. TaskBoard is a great app but the periodic jump is a bane to the workflow...

I'm not much of a developer so trying to wade through someone else's angularjs code is a bit much for me; just wanted to however suggest looking at this thread where it seems some form of workaround has been mooted...

https://github.com/angular-ui/ui-router/issues/110

Dunno if that helps...

**Comment by kiswa** [comment]
That looks very helpful, thank you!

**Comment by Kernle32DLL** [comment]
+1 from me

**Comment by FiSHYsolutions** [comment]
To whom it may concern: it's possible to reduce the refresh-interval in v0.3.1 until this issue is fixed. modify line 143 in `boards.js` from 10000 to 60000 (or whatever you want) milliseconds:

    bash$ diff /var/www/TaskBoard/js/controllers/boards.js*
    143c143
    <     $scope.boardInterval = $interval($scope.loadBoards, 60000);
    ---
    >     $scope.boardInterval = $interval($scope.loadBoards, 10000);

this will also decrease your pagetraffic significant.

**Comment by alex3305** [comment]
Closed for inactivity.
