### ISSUE TITLE
Adding Attachements to a Task fails 

### ISSUE THREAD

**Issue by kaipaysen** [kiswa/TaskBoard#340]
My TaskBoard instance uses a pretty low php upload_max_filesize setting of 2MB. 
When I add a file to a task by using the file-upload button which is larger than 2MB I'd expect an error message. Instead TaskBoard tells me everything is fine by showing the file in the attachment list.
But: The file is not available.

**Comment by kiswa** [comment]
I will add that to my list for the re-write. Thanks for reporting!

**Comment by kaipaysen** [comment]
May I add something related?
It's not possible to delete a nonexisting attachement from a task.

Btw, TaskBoard is just marvellous - I love it! 
Thank you very much.

**Comment by altayevrim** [comment]
Can we change the Max Upload Size? Because I am a bit generous about that settings in php.ini but it seems the system blocks me to upload more than 2MB? It says File Too Large.

**Comment by pwinch** [comment]
I got the same error, but when I looked in my error log I got this:
exception 'ErrorException' with message 'Undefined index: file' in /var/www/taskbar2/taskboard_master/api/itemRoutes.php:269
Stack trace:
#0 /var/www/taskbar2/taskboard_master/api/itemRoutes.php(269): Slim\Slim::handleErrors(8, 'Undefined index...', '/var/www/taskba...', 269, Array)
#1 [internal function]: {closure}('38')
#2 /var/www/taskbar2/taskboard_master/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#3 /var/www/taskbar2/taskboard_master/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#4 /var/www/taskbar2/taskboard_master/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#5 /var/www/taskbar2/taskboard_master/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#6 /var/www/taskbar2/taskboard_master/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#7 /var/www/taskbar2/taskboard_master/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#8 /var/www/taskbar2/taskboard_master/api/api.php(52): Slim\Slim->run()
#9 {main}

**Comment by kiswa** [comment]
This is fixed in the `re-write` branch with a default setting for max upload size of 80MB
