### ISSUE TITLE
TaskBord on IIS

### ISSUE THREAD

**Issue by KuanTi** [kiswa/TaskBoard#341]
Hi, i have problem with first login. 
I put taskbord on IIS and made step-by-step from this link -> [https://github.com/kiswa/TaskBoard/wiki/TaskBoard-on-IIS](url).
Taskbord version v0.3.1
First problem was when I import 1 rule in URL Rewrite. 
I import C:\inetpub\wwwroot\TaskBoard\api\\.htaccess but got errors. 
Then i delete what was impotred from file and put 1 rule from /wiki/TaskBoard-on-IIS:
ExpiresActive Off
RewriteEngine On
RewriteCond %{REQUEST_URI}::$1 ^(.*?/)(.*)::\2$
RewriteRule ^taskboard.db$ /TaskBoard/api/api.php [QSA,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ /TaskBoard/api/api.php [QSA,L]

2 rule was ok and IIS take it after import from C:\inetpub\wwwroot\TaskBoard\vendor\slim\slim\\.htaccess
Then enable php_pdo_sqlite.dll, php_sqlite3.dll but still can't log in inside. 

In atachment i add my php.ini file, snap from iis rewrite 

![slim_rewrite](https://cloud.githubusercontent.com/assets/25607720/22692218/46982b00-ed3e-11e6-9a92-f1938964edc2.JPG)
![api_rewrite](https://cloud.githubusercontent.com/assets/25607720/22692217/46983780-ed3e-11e6-9556-e09f2a5749e2.JPG)
[php.zip](https://github.com/kiswa/TaskBoard/files/757325/php.zip)
Maybe i make some wrong step in install 

Best Regards 
Mariusz

**Comment by KuanTi** [comment]
I install appach for windows and all works fine. 
Btw problem with IIS still open ;)
Best Regards
Mariusz

**Comment by kiswa** [comment]
You should not need to import any `.htaccess` rules from any of the `vendor` locations. That's probably what messed it up.

I don't have access to IIS, so I can't test this and I technically don't support it.
