### ISSUE TITLE
Project still active? Some feature request status/roadmap

### ISSUE THREAD

**Issue by 2Belette** [kiswa/TaskBoard#342]
Hi,
I am testing a **lot** of kanban tools and I found your tool pretty interesting!
I am a kanboard user and try to find some alternative (lighter)...

Just wondering it you have any roadmap to share or any status of TaskBoard as I don't see any update for more than one year...
I also found your post [here](https://matthewross.me/blog/posts/taskboard-progress-report), could we expect some moves soon and if yes if you have any roadmap to share..?

On my side the only missing pieces would be:
-limit number of task per column, like #173 
-having checklist (subtask) with progression bar indication on the task, you already replied on #288 
-having swimlanes to separate/organize stuff, like #139 

Many thanks!

**Comment by kiswa** [comment]
Swimlanes are not a priority but the others are on the list for TaskBoard in [the re-write branch](https://github.com/kiswa/TaskBoard/tree/re-write) (take a look, the latest commit was 2 days ago).

Unfortunately, the re-write branch is not in a usable state yet.

In lieu of a roadmap, here is a screenshot of my private TaskBoard on my TaskBoard Re-Write board:

![TaskBoard Re-Write Board](https://i.imgur.com/WF6HXZ7.png)

**Comment by 2Belette** [comment]
Awesome !!!
Thanks for sharing your TaskBoard!
I will definitely have a look on the re-write branch and will test it!

Btw nothing related but before I open an issue as it is perhaps solved on this branch but on the master branch, unticking the 'Show Assignee on item card?' option in Setting is not working for me, the Assigned to on the task is still here 

Many thanks for your great work

**Comment by kiswa** [comment]
Odd that the show assignee option isn't working for you. Maybe check for errors in the <kbd>F12</kbd> dev tools?

Feel free to test the re-write branch, but it's **very** limited right now.

The only things fully functional are the login and settings pages. I'm currently starting on the boards pages, but I need to get my unit test coverage up before I go any further.

**Comment by 2Belette** [comment]
You are right I got a Internal Server Error when I click on it
Here are the Debugging view if it can help to find the guilty :)
![2017-02-10-11 20 37](https://cloud.githubusercontent.com/assets/2325706/22824038/8f2b89d0-ef86-11e6-9cb1-c832226edddd.png)
![2017-02-10-11 21 19](https://cloud.githubusercontent.com/assets/2325706/22824042/942142c2-ef86-11e6-9838-910a32c23d6a.png)
![2017-02-10-11 21 48](https://cloud.githubusercontent.com/assets/2325706/22824054/9a34bfd6-ef86-11e6-97a3-f96fcdfbade3.png)
![2017-02-10-11 21 57](https://cloud.githubusercontent.com/assets/2325706/22824059/9c73f316-ef86-11e6-97db-13c2e94978c5.png)

**Comment by kiswa** [comment]
I've only seen that error when upgrading from a prior version of TaskBoard. It means the default user options did not get created for your user.

I'd have to do some research to figure out a solution, but if you don't have anything important in your install (you did mention you were just testing it out) you can try deleting the `api/taskboard.db` file and see if that helps.

**Comment by 2Belette** [comment]
Thanks for the suggestion, I tried to delete 'tasboard.db' and I got the same issue..
I also tried to create a new user to see if it is related to the fact that the board has some 'Selected users' during the creation phase but it is the same issue if I select or not some user...

Perhaps something solved on the re-write branch? btw I am unable to make re-write branch works.
Curious to see the Settings page but I have not been able to do it.

My steps are very simple : I git clone the repository on another folder on my apache DocumentRoot, I have added this in my httpd.conf

```
<Directory /http/TaskBoardReWrite>
    AllowOverride all
</Directory>
```

I already got all the dependencies installed and tested with master branch but when I navigate to the rewrite folder my apache is not showing me anything, I tried to navigate to test or src folder in any subfolder but I am not able to see anything, if you have a tip don't hesitate :)

**Comment by kiswa** [comment]
The `re-write` branch is very different and has a completely different way of getting it running. The plan is to eventually have a release build which will be a simple drop-in solution.

Until then, here's what you do:

 1. Clone the repo and open the location in a terminal
 2. Run `npm i` to install dependencies
 3. Run 'gulp' to build everything (you may see errors about not having the SCSS linter, but ignore those)

The `dist` folder will have the final output to run.

**Comment by 2Belette** [comment]
Thanks for your reply.
I tried but I had some issues with packages dependencies version..
I have been able to get a step further with changing manually some packages version in package.json (all angular from 2.4.7 to 2.4.3 and angular/router from 3.4.7 to 3.4.3), and get the dist folder created but at the end I was only able to see a web page with TaskBoard is Loading...
Any idea on what I did wrong-missed? It is like I am pretty close..

**Comment by kiswa** [comment]
Were there any errors in the <kbd>F12</kbd> dev tools console?

**Comment by 2Belette** [comment]
It is like there are some static path in the code and it tries to search at the the root path the dist directory.
I copied it to the root path of my apache and now I can see the background but still stay to Taskboard is Loading...

GET http://xxx/alpha/TaskBoardReWrite/dist/ [HTTP/1.1 304 Not Modified 2ms]
GET http://xxx/dist/css/styles.css [HTTP/1.1 200 OK 2ms]
GET http://xxx/dist/js/vendor.js [HTTP/1.1 200 OK 6ms]
GET http://xxx/dist/js/bundle.js  [HTTP/1.1 404 Not Found 1ms]

And indeed bundle.js is not present

**Comment by kiswa** [comment]
No errors when running the `gulp` command? The `bundle.js` file is created by the `system-build` task, which you can run alone as `gulp system-build` if everything else worked fine.

**Comment by 2Belette** [comment]
I thought it was not the case but after taking a deep look I realize that I add an error in gulp even if it didn't fail (ruby was missing)
Now after installing everything correctly, doing a gulp gave me an error : (during the system-build)
```

[23:48:29] Using gulpfile /srv/http/alpha/TaskBoardReWrite/gulpfile.js
[23:48:29] Starting 'vendor'...
[23:48:29] Starting 'ts-lint'...
[23:48:29] Starting 'tsc'...
[23:48:29] Starting 'html'...
[23:48:29] Starting 'images'...
[23:48:29] Starting 'scss-lint'...
[23:48:29] Starting 'fonts'...
[23:48:29] Starting 'scss'...
[23:48:29] Starting 'api'...
[23:48:30] gulp-imagemin: Minified 1 image (saved 0 B - 0%)
[23:48:30] Finished 'images' after 1 s
[23:48:30] Finished 'vendor' after 1.02 s
[23:48:30] Finished 'fonts' after 1.36 s
[23:48:30] Finished 'scss' after 1.4 s
[23:48:31] Finished 'scss-lint' after 2.23 s
[23:48:31] Finished 'html' after 2.77 s
[23:48:32] Finished 'ts-lint' after 2.91 s
[23:48:34] Finished 'tsc' after 5.06 s
[23:48:34] Starting 'system-build'...
<--- Last few GCs --->

[5505:0x1a7c9b0]    15934 ms: Scavenge 740.0 (781.9) -> 732.5 (782.9) MB, 12.8 / 0.0 ms  allocation failure 
[5505:0x1a7c9b0]    15995 ms: Scavenge 742.3 (783.9) -> 738.4 (789.9) MB, 21.1 / 0.0 ms  allocation failure 
[5505:0x1a7c9b0]    16057 ms: Scavenge 749.6 (790.9) -> 743.2 (796.9) MB, 23.2 / 0.0 ms  allocation failure 
[5505:0x1a7c9b0]    16464 ms: Scavenge 755.9 (797.9) -> 748.8 (2653.9) MB, 19.7 / 0.0 ms  allocation failure 


<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: NewSpace::Rebalance Allocation failed - process out of memory
 1: node::Abort() [gulp]
 2: 0xf4df3c [gulp]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [gulp]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [gulp]
 5: 0x75dd4b [gulp]
 6: v8::internal::MarkCompactCollector::EvacuateNewSpaceAndCandidates() [gulp]
 7: v8::internal::MarkCompactCollector::CollectGarbage() [gulp]
 8: v8::internal::Heap::MarkCompact() [gulp]
 9: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [gulp]
10: v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, char const*, char const*, v8::GCCallbackFlags) [gulp]
11: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [gulp]
12: v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
13: 0x3108971063a7
[1]    5505 abort (core dumped)  gulp

```

It is like I am out of memory...(my VM has 1GB of memory), but I am not sure it is really the case?..

**Comment by kiswa** [comment]
I have no idea what could be causing that. I frequently work on the re-write using c9 in a VM with only 512MB RAM and haven't had that problem (though it can be a bit slow sometimes).

**Comment by kiswa** [comment]
I just realized what you posted earlier.

> GET http://xxx/alpha/TaskBoardReWrite/dist/ [HTTP/1.1 304 Not Modified 2ms]
> GET http://xxx/dist/css/styles.css [HTTP/1.1 200 OK 2ms]
> GET http://xxx/dist/js/vendor.js [HTTP/1.1 200 OK 6ms]
> GET http://xxx/dist/js/bundle.js [HTTP/1.1 404 Not Found 1ms]

I'm confused how you got 200s from styles and vendor since you would have needed to update the index.html to set the `base href="/dist/"` to your path, *e.g.* `/alpha/TaskBoardReWrite/dist/`

**Comment by 2Belette** [comment]
:) Yep at the beginning I copied the dist 'folder' to my rootpath as I mentioned previously and then I realized that there was a base href where I did exactly what you advised :)

I have added 1BG to my VM and now...

```
[10:03:12] Using gulpfile /srv/http/alpha/TaskBoardReWrite/gulpfile.js
[10:03:12] Starting 'vendor'...
[10:03:12] Starting 'ts-lint'...
[10:03:12] Starting 'tsc'...
[10:03:12] Starting 'html'...
[10:03:12] Starting 'images'...
[10:03:12] Starting 'scss-lint'...
[10:03:12] Starting 'fonts'...
[10:03:12] Starting 'scss'...
[10:03:12] Starting 'api'...
[10:03:13] gulp-imagemin: Minified 1 image (saved 0 B - 0%)
[10:03:13] Finished 'images' after 1.1 s
[10:03:13] Finished 'vendor' after 1.12 s
[10:03:13] Finished 'fonts' after 1.27 s
[10:03:13] Finished 'scss' after 1.43 s
[10:03:14] Finished 'scss-lint' after 2.69 s
[10:03:15] Finished 'html' after 2.98 s
[10:03:17] Finished 'ts-lint' after 5.46 s
[10:03:17] Finished 'tsc' after 5.49 s
[10:03:17] Starting 'system-build'...
[10:03:29] Finished 'system-build' after 12 s
[10:03:30] Finished 'api' after 18 s
[10:03:30] Starting 'default'...
[10:03:30] Finished 'default' after 929 μs
(node:356) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```
And now it is working :) :) 
many thanks for your help kiswa

And WHOO!! the Dashboard and Settings are impressive :)
If you'll add some feature requests to the Boards to enhance from the previous version it will be awesome!

**Comment by kiswa** [comment]
Yeah, I still have a lot to do, but I'm pretty happy with the Settings page. Also, if you have latest, the boards page is partially functional (it will actually display the columns you've added to a board, but that's about it).
