### ISSUE TITLE
Email Help

### ISSUE THREAD

**Issue by ChrisObie** [kiswa/TaskBoard#343]
Hey Everyone,

Just looking for some help with the Email settings. I have it successfully emailing our users, but does anyone know how I can set it to only email Tasks to users they are assigned to? 

Also, on the New Board template is puts the username of the person who it is sending the email alert to, not the person who actually created the new board. 

Any tips are appreciated.
-Co

**Comment by kiswa** [comment]
I can't really support the email functionality as it was contributed code and I never took the time to get into it (my bad). That said, once the `re-write` branch is functional I will have improved email functionality.

As for the username thing, it looks like [this line](https://github.com/kiswa/TaskBoard/blob/a835aa7bb83bfe0b7aa2136e864ca3ff76e60419/api/boardRoutes.php#L25) should be changed from `$user->username` to `$actor->username` to match the template.

**Comment by kiswa** [comment]
The user thing would be similar, but more work. It's centered around [this loop](https://github.com/kiswa/TaskBoard/blob/a835aa7bb83bfe0b7aa2136e864ca3ff76e60419/api/itemRoutes.php#L34).

**Comment by ChrisObie** [comment]
Awesome thanks Kiswa! I will look into those features, can wait for the re-write. 👍
