### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by DanyDisccom** [kiswa/TaskBoard#344]
Hi,
installed in IIS server, i can connect to the Taskboard but login doesn't seem to work. tried admin/admin as explained in the documentation.

What did i do wrong ?

**Comment by kiswa** [comment]
Did you follow [the Wiki page](https://github.com/kiswa/TaskBoard/wiki/TaskBoard-on-IIS) when setting it up?

I don't have a way to check IIS since I run Linux, but posting errors from the browser might help.

**Comment by kiswa** [comment]
Closing due to lack of response.
