### ISSUE TITLE
Page and Columns scrollbars

### ISSUE THREAD

**Issue by domrim** [kiswa/TaskBoard#345]
If a column has more tasks than it could show in the browser window, there are 2 changes which aren't really nice.
1. The column gets a scroll-bar, but only a little one, so the add-Button is half out of the frame. Screenshot:
![cols](https://cloud.githubusercontent.com/assets/15873147/23579687/9da9a0f0-00f2-11e7-95d5-85b579a0aaa6.png)
2. The full window gets a scroll bar. But when you scroll down, after a few seconds, the window automaticaly moves to the top.
![complete](https://cloud.githubusercontent.com/assets/15873147/23579697/daaaa602-00f2-11e7-846c-f821f4f70427.PNG)

I think one of this behaviours isn't right. Personally i would prefer to have the window height static, and the single columns get scrollbars if they get to long. If you need any further information, just say ;)

**Comment by kiswa** [comment]
For some reason I thought I had already replied to this, sorry!

These issues are currently handled in the `re-write` branch and will be addressed once the v1.0.0 release is ready.

![image](https://cloud.githubusercontent.com/assets/419663/23904439/3c91485a-089e-11e7-8477-38b6863c1d6b.png)
