### ISSUE TITLE
Taskboard reverts to fresh install after reboot - all user entered data lost

### ISSUE THREAD

**Issue by xmac911** [kiswa/TaskBoard#346]
I am running v.0.3.1 Taskboard on Ubuntu 16.04LTS. After setting everything including users and boards, all was lost after a reboot. When I log back in to the server, the only user that works is the default admin. I tried it a second time after only creating a new user and new board. After reboot, same results. 

Any ideas?

**Comment by kiswa** [comment]
I'm not sure why the database would be deleted on reboot.

Are you using the default SQLite database? If so, check the permissions on `api\taskboard.db` and make sure it exists before a reboot. If that files goes away on reboot, there's something odd about your setup/permissions.

**Comment by xmac911** [comment]
Thanks. Before seeing your suggestion,  I deleted the taskboard folder and started as if from a fresh install and all works fine now including after reboots.
