### ISSUE TITLE
Settings disabled

### ISSUE THREAD

**Issue by addagencia** [kiswa/TaskBoard#348]
I copied the files to the server and when access is all the fields are disabled. And any login and password access the list of boars. See print
![fireshot screen capture 006 - taskboard - settings - addagenciadigital_com_task_ _settings](https://cloud.githubusercontent.com/assets/7864147/24212849/6966e78c-0f0f-11e7-973e-df190570c6c1.png)

**Comment by kiswa** [comment]
Please see #293. If that doesn't fix it, let me know and I'll re-open.

**Comment by addagencia** [comment]
Thanks, but don't work. The link to vendors file is broken. How  I put TaskBorad in server without composer?

**Comment by kiswa** [comment]
You must run composer to install the PHP dependencies.

Here's an updated link to those old vendor files: https://www.dropbox.com/s/tkdftobzlze02uw/vendor.tar.gz?dl=1

**Comment by addagencia** [comment]
Thanks so much, now it is working perfectly
