### ISSUE TITLE
Taskboard on Synology NAS

### ISSUE THREAD

**Issue by Amadeus1756** [kiswa/TaskBoard#349]
I've installed the latest version of TaskBoard on my Synology DS1515.  In summary, the login page comes up but I can't login.  F12 shows an HTTP 500.

My initial problem was that I didn't have mod_expires loaded.  Got that loaded.
Now I get the following error:

2017-03-28T20:09:16+01:00 DiskStation1515 [Tue Mar 28 20:09:16 2017] [error] [client 10.1.1.100] FastCGI: server "/php56-fpm-handler" stderr: PHP message: PHP Fatal error:  require_once(): Failed opening required '/volume1/web/taskboard/api/../vendor/autoload.php' (include_path='.') in /volume1/web/taskboard/api/api.php on line 3, referer: http://10.1.1.17/taskboard/

Indeed, this autoload.php file doesn't exist.
Can someone suggest how to solve this?  Looking at the source code (I don't know PHP to any level of competency) it looks to me as if this file should come with the zip but if it was something that obvious, I'd have thought someone else would have noticed before now! :-)

Many thanks

Many thanks

**Comment by kiswa** [comment]
You have to run  composer to get the vendor files. That said, you can use the line in #348 to download the files directly.

**Comment by Amadeus1756** [comment]
Thanks.  The files you pointed to didn't work for me but once I discovered that I had to use composer, that kind of worked.  Trying to work through a few different issues now.  

rgds

**Comment by kiswa** [comment]
Well, glad you got it somewhat working. There are some older issues that may have information that helps if you search the repo.

FYI, this kind of thing will no longer be an issue once the re-write is complete; there will be ready-to-use releases.
