### ISSUE TITLE
could this be a plugin in kibana?

### ISSUE THREAD

**Issue by Echolee-L** [kiswa/TaskBoard#354]
I want to put this taskBoard in kibana as a plugin,but I don't know how to connect with elasticsearch,could this been done?thanks in advance.

**Comment by kiswa** [comment]
I have absolutely no idea.

I'll leave this open for a bit to see if anyone else has any input.

**Comment by Echolee-L** [comment]
Thanks for your quick update. I tried another way with using iframe to embed taskboard into kibana. Thank you anyway.
