### ISSUE TITLE
CSS stops loading (i guess)

### ISSUE THREAD

**Issue by spiffzilla** [kiswa/TaskBoard#355]
Fresh install of TaskBoard.

It works fine for ~30 minutes, i can add boards and tasks etc. then all of a sudden the CSS files seems to dissapear, see attached image.

I've installed as the instrux says.
./composer.phar install
./build-all
apache mods, sqllite php5-sqlite... 

no errors in apache logs

Anyone seen this before? Only way to get it running again (from my knowledge level) is reinstall... then it works for a short while again

![tb](https://cloud.githubusercontent.com/assets/3751145/25264662/9c8187ba-2668-11e7-9fc6-faf9bd2380fb.JPG)

**Comment by spiffzilla** [comment]
Update:
I looked in the file ./lib/css/combined.min.css

And all it contains is:
502 Bad Gateway

That sounds like a problem to me, not sure why it's broken though

**Comment by kiswa** [comment]
Well that's not cool.

I was hoping to be able to leave `master` alone until I was able to publish `re-write` as v1.0.0.

Maybe I'll just create a pre-built version for download instead of cloning and running the build.

**Comment by sijemss** [comment]
mr kiswa, can you make step installation with video you tube.?

**Comment by kiswa** [comment]
This should be okay, now that the site is up again.

However, if it happens in the future, just comment out [these lines](https://github.com/kiswa/TaskBoard/blob/master/build/build-all#L29-L32) to skip that part of the build. and adjust the index.html to point to the unminified css.

@sijemss I don't do YouTube, sorry.

**Comment by muramasatheninja** [comment]
Ok so I just tried to install TaskBoard and ran into this same issues. I ended up just changing the build script to copy the unminified css over the minified ones.

`#!/bin/bash
set -e

echo Building...
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

echo ' Installing dependencies'
cd ..
./build/composer.phar install
cd build

echo ' Compiling lib JS files...'
./minify-libs

echo ' Minifying lib CSS files...'
cd ../lib/css/
cat bootstrap.min.css > combined.css
cat font-awesome.min.css >> combined.css
cat jquery-ui.min.css >> combined.css
cat spectrum.css >> combined.css
cp combined.css combined.min.css
cd ../../build/

echo ' Compiling app JS files...'
./minify-app

echo ' Minifying app CSS files...'
cd ../css/
cp styles.css styles.min.css
cd ../build/

echo ' Updating index.html...'
cd ../
if [ -f indexProd.html ]; then
    mv index.html indexDev.html
    mv indexProd.html index.html
fi
cd build/

echo Build Complete
`
