### ISSUE TITLE
Setting Disabled

### ISSUE THREAD

**Issue by s878l** [kiswa/TaskBoard#356]
Hello,

I know that this issue has been reported before but none of the solution seems to work for me.

After I install TaskBoard it logs me into automaticly and when I click on settings I am unabled to modify anything since everything is gray out. (See screen shot)

![screenshot from 2017-05-11 10-06-33](https://cloud.githubusercontent.com/assets/8786611/25953561/c92c855c-3631-11e7-9900-8fc09aa5ee79.png)

**Comment by s878l** [comment]
Figured out the issue.
forgot to install the apache php lib
ubuntu command: sudo apt-get install libapache2-mod-php

**Comment by kiswa** [comment]
Glad you figured it out. My first thought was that PHP wasn't installed, since it was treating the files as XML.
