### ISSUE TITLE
 Installation is successful but can not login

### ISSUE THREAD

**Issue by sijemss** [kiswa/TaskBoard#357]
I want to ask me to install taskboard using linux ubuntu lts 4.2 as usual from the initial stage all goes smoothly from installing debian update, composer installation, curl, php5, sqlite3 and jdk ver 8.
After that i run the command .build / build-all this also works but after i type localhost / taskboard login page there is no css and i can not login.

Can mention any steps so I can use your taskboard application. And what recommendation of whether the operating system should I use for the installation to succeed without failure.

**Comment by kiswa** [comment]
TaskBoard should run fine on Ubuntu. What is the 4.2 you're referring to?

**Comment by bbichero** [comment]
How to you run TaskBoard ?
You said there isn't css, but on which url was you exactly ? 
Because `http://localhost/taskboard/login` insn't exist, type only `http://localhost`
I suggest you to install apache2 package and create a virtual host, it's easy.
```
<VirtualHost *:80>
	DocumentRoot /path/to/TaskBoard
	ServerName task_board

	<Directory /path/to/TaskBoard>
		DirectoryIndex index.html
        	Require all granted
        	Options -Indexes +FollowSymLinks +MultiViews
              	AllowOverride All
        </Directory>

	ErrorLog ${APACHE_LOG_DIR}/task_board.log

    	# Possible values include: debug, info, notice, warn, error,
    	# crit,
    	# alert, emerg.
    	LogLevel warn

</VirtualHost>
```
Active mandatory apache2 modules
`sudo a2enmod rewrite expires`

Active new virtual host
```
sudo a2ensite task_board
sudo service apache2 restart
```

**Comment by bbichero** [comment]
@sijemss Can you give us some news please ?

**Comment by sijemss** [comment]
@bbichero  
I successfully install taskboard by way of this link ->  https://hostpresto.com/community/tutorials/how-to-install-taskboard-on-ubuntu-14-04/

.please try that way, it works for me. Hopefully be useful.

**Comment by bbichero** [comment]
Thanks for update and for the tutorial link! 
Have fun with Taskboard. 

@kiswa can you close the issue please?
