### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by wberod** [kiswa/TaskBoard#358]
all files have permissions set to 666 and do not take permissions changes. not able to install.

vagrant@vagrant:/var/www/TaskBoard-master/TaskBoard-master$ ./build/composer.phar install
bash: ./build/composer.phar: Permission denied

**Comment by Scramasax** [comment]
I get this as well:

ubuntu@ip-xxx-xx-xx-xx:/var/www/html/TaskBoard-master$ ./build/build-all
Building...
 Installing dependencies
./build/build-all: line 10: ./build/composer.phar: Permission denied

**Comment by kiswa** [comment]
In the `build` directory, the following files should be set to `755`: `build-all`, `clean`, `composer.phar`, `minify-app`, and `minify-libs`.
