### ISSUE TITLE
Dependancies error when bulding re-write

### ISSUE THREAD

**Issue by 2Belette** [kiswa/TaskBoard#360]
Hi, 
not the first time but now I don't find the right version combination for dependencies to make it work...any idea?
```

npm -i
npm WARN ng2-dragula@1.3.1 requires a peer of @angular/compiler@2.4.3 but none was installed.
npm WARN ng2-dragula@1.3.1 requires a peer of @angular/forms@2.4.3 but none was installed.


```

**Comment by bbichero** [comment]
How have you install TaskBoard ? Please give us some details.
You don't need to do this. Have you follow [https://taskboard.matthewross.me/docs/intro.html](url) ?

**Comment by 2Belette** [comment]
I am trying to install the re-write branch, as for the master I have no issue following the procedure.
For example if I checkout to re-write branche I don't have the build folder anymore, this is the reason I tried the npm method.
Excuse me to not clarify it before that I was talking about the re-write (I did put it in the title but not on the explanation)

**Comment by bbichero** [comment]
I have the same issue when build the re-write branch.
I saw on [https://github.com/valor-software/ng2-dragula/issues/636](url) that is still an issue
on ng2-dragula repository.
Nothing to do for @kiswa, so issue can be close.

**Comment by kiswa** [comment]
You can safely ignore that warning from npm.

After `npm -i` completes (even with warnings) just run `gulp` and it will build everything and place it in a `dist` directory.

Keep in mind, the `re-write` branch is very much a work in progress and does not have all the features of `master`.

**Comment by 2Belette** [comment]
Hi,
I have tried to update to your latest re-write version, following a npm i and gulp, no issue there, dist is generated but trying to access I got multiple 404 and only got "TaskBoard is Loading..." on my browser.

```
10.20.100.1 - - [29/Jul/2017:00:18:17 +0200] "GET /dist/css/styles.css HTTP/1.1" 404 1147
10.20.100.1 - - [29/Jul/2017:00:18:17 +0200] "GET /dist/js/vendor.js HTTP/1.1" 404 1147
10.20.100.1 - - [29/Jul/2017:00:18:17 +0200] "GET /dist/js/bundle.js HTTP/1.1" 404 1147
10.20.100.1 - - [29/Jul/2017:00:18:17 +0200] "GET /dist/js/bundle.js HTTP/1.1" 404 1147
```
my dist/js:
```
-rw-r--r-- 1 http http  27K Jul 29 00:14 Reflect.js.map
-rw-r--r-- 1 http http 555K Jul 29 00:14 vendor.js
```

my dist/css:
```
drwxr-xr-x 2 http http 4.0K Jul 28 23:53 fonts
-rw-r--r-- 1 http http  59K Jul 29 00:14 styles.css
```

any ideas?
many thanks

**Comment by kiswa** [comment]
Edit the index.html and change the base href to match the url you're accessing it from.

For example, it's `/dist/` by default (this will change in the future). Basically, what's in there should be anything after `http://localhost/` when you go to the dist folder.

So, if your copy is at `http://localhost/dev/TaskBoard/dist/` then you should edit the base href to be `dev/TaskBoard/dist/`.

**Comment by 2Belette** [comment]
I remember now doing this in the past thanks!
Now it is better, I can see the grey background so the css is loaded but I don't have more...
```

[29/Jul/2017:15:59:09 +0200] "GET / HTTP/1.1" 200 703
[29/Jul/2017:15:59:10 +0200] "GET /css/styles.css HTTP/1.1" 200 60008
[29/Jul/2017:15:59:10 +0200] "GET /js/bundle.js HTTP/1.1" 404 1117
[29/Jul/2017:15:59:10 +0200] "GET /js/vendor.js HTTP/1.1" 200 567507
[29/Jul/2017:15:59:10 +0200] "GET /images/bg.png HTTP/1.1" 200 2126
[29/Jul/2017:15:59:10 +0200] "GET /js/bundle.js HTTP/1.1" 404 1117
```
It is not loading the rest of the modules/page

![2017-07-29-15 53 02](https://user-images.githubusercontent.com/2325706/28745303-15407ee4-7476-11e7-9bb9-0aa563355081.png)

**Comment by bbichero** [comment]
Please tell us do you edit the base href in you `index.html` file ?

**Comment by kiswa** [comment]
Looks like the bundle wasn't generated correctly. Try running `gulp` again, or just `gulp app`.

**Comment by 2Belette** [comment]
well done :) after a `gulp app` it is better!
I am progressing ... now I got the login but Sign In has no effect...

![2017-07-29-19 56 26](https://user-images.githubusercontent.com/2325706/28747128-10ea2b5c-7498-11e7-90f3-b1d67cb0e368.png)

**Comment by 2Belette** [comment]
Congratulations for the progression by the way!!
I am not able to move task from column to column yet but I guess it is normal.
By the way the menu when I right click on a task disappears if I don't hold my click.
You re-write seems very promising :)

**Comment by kiswa** [comment]
Thanks!

Yeah, I'm still working on that context menu behavior. You can currently only move tasks by using that menu (or editing them and selecting another column).

I'm pretty happy with what I have done so far, but there's still a good ways to go. Have you tried entering a task with a checklist (use ` - [ ]` for to-do items, ` - [x] ` for done)? When you have some complete, it shows a progress bar across the bottom of the task.

**Comment by 2Belette** [comment]
@kiswa : hey! I just updated it from 3 months ago and please to see your improvements! seems great! I found a lot of little details changed and theyr are very welcome !
By the way I tried the - [ ] and  - [x] and they are nicely displayed into the comment area but I don't see the progress bar at the bottom of the task?
By the way, more a general question and because I see you seems close to get a working version, what would be a estimated ETA for the final release of the re-write?
Many thanks :)

**Comment by kiswa** [comment]
You don't have this?
![untitled](https://user-images.githubusercontent.com/419663/32029515-09a8ea98-b9c3-11e7-86aa-002c2e98ee3d.png)

Glad you're liking the work that's been done. Unfortunately, I don't have an ETA. I have considered releasing v1.0.0 without the dashboard page, and saving that for v1.1.0 which would move release forward a fair bit as almost everything else is complete.

**Comment by 2Belette** [comment]
now I understood!
![2017-10-26-10 15 06](https://user-images.githubusercontent.com/2325706/32042080-b9d0eec0-ba36-11e7-87fa-7a6f04639e70.png)

I thought it was in the Comment area and not in the Description area :)
The only downside is that the task can take a lot of room if there are multiple sub-tasks, would be nice to get the same progression bar in case the sub-tasks are use in the Comment area: thanks to that the Board keeps clean and at a glance it is easy to the the progression bar and clicking on the task we can see the sub-tasks..

That's nice! Would be nice if we would click on the box from the Board without the need to Edit the task to check the sub-tasks.

Good idea for v1.0! the Dashboard can come later on, how far are you to release the 1.0? I remember in the past you shared your kanban of you tasks, glad to see it if you are ready to share it :)
