### ISSUE TITLE
Can't get login to work.  

### ISSUE THREAD

**Issue by Scramasax** [kiswa/TaskBoard#361]
I'm sorry to bother you guys again but I'm getting a 404.  I'm a game programmer but not really a web coder.  What does this mean?  
![image](https://cloud.githubusercontent.com/assets/1518398/26525005/530c591e-42fd-11e7-836d-23bba4452fb4.png)

**Comment by MANewhall** [comment]
Just went through this.  The code doesn't use relative links.  It expects to be at the root of a domain.
like example.com/  example.com/TaskBoard/ won't work.

Don't forget perms on the api directory.

And I'm 90% the directions are wrong in the README and right on the web.  You need to run the ./build-all successfully for it to work.

**Comment by Scramasax** [comment]
I'm not sure what you mean by a root domain?

http://www.geolan1024.com/TaskBoard-master/#/

**Comment by Scramasax** [comment]
![image](https://cloud.githubusercontent.com/assets/1518398/26525620/ff3c838a-4311-11e7-86fc-d749446aae3f.png)

**Comment by MANewhall** [comment]
The root of your site.
like www.google.com/  (or google.com) is the root of google's website.   google.com/somestuff/ is not.  There can't be directories in the URL.  The code uses absolute links.

**Comment by Scramasax** [comment]
Hate to be a pain, but I'm still getting this same error.  I created a new instance on aws of ubuntu.  Created a Lamp server. Put TaskBoard in the root directory and did a ./build/build-all.  

http://taskboard.geolan1024.com/#/

**Comment by kaebmoo** [comment]
same error 404 login not found. 
![error_404](https://cloud.githubusercontent.com/assets/3021700/26572830/94484b50-4545-11e7-8eb3-ff0bbe39f6cc.PNG)

**Comment by kiswa** [comment]
Sub-domains and sub-directories should both work, see [the demo](https://taskboard.matthewross.me/demo/#/boards), for example.

That 404 error is a result of either wrong permissions on the `api` directory, or not having `mod_rewrite` enabled in Apache.

**Comment by Scramasax** [comment]
So I think this is progress.  I really appreciate the help btw and am sorry for being such a pain in the ass.
![image](https://cloud.githubusercontent.com/assets/1518398/26611727/f7f3e74e-4564-11e7-8cf8-a7315f28351e.png)

**Comment by bbichero** [comment]
Have you configure correctly the database in TaskBoard/api/api.php ?
If you use mysql instead of SQLite you must change code.
If it's the case see the last post #362

**Comment by Scramasax** [comment]
What version of sqlite should I install?

**Comment by bbichero** [comment]
Install the last stable version on your system, you must install `php5-sqlite` too.
Like I said, if you have already mysql, it's not necessarry to use SQLite.

**Comment by Scramasax** [comment]
Bummer thing is, is I will have to punt soon and use Trello.  I'll get back to it once I upgrade my other partition which is Ubuntu and see how I'm messing up the install.

![image](https://cloud.githubusercontent.com/assets/1518398/26659368/01541c8a-4625-11e7-8a56-91dad9e30434.png)

**Comment by bbichero** [comment]
Sorry it's php5-sqlite3, but check if sqlite 3 is currently install.

**Comment by Scramasax** [comment]
ubuntu@ip-172-31-2-67:~$ sudo apt-get install php7.0-sqlite3
Reading package lists... Done
Building dependency tree
Reading state information... Done
php7.0-sqlite3 is already the newest version (7.0.18-0ubuntu0.16.04.1).
php7.0-sqlite3 set to manually installed.

**Comment by Scramasax** [comment]
Some firefox debug screens:
![image](https://cloud.githubusercontent.com/assets/1518398/26661224/54f4c996-4631-11e7-992f-2131cc5faa89.png)

![image](https://cloud.githubusercontent.com/assets/1518398/26661240/710a98ae-4631-11e7-8264-daf63aec9462.png)

![image](https://cloud.githubusercontent.com/assets/1518398/26661289/a3276330-4631-11e7-80b7-91fdaf3dcda0.png)
