### ISSUE TITLE
admin not admin

### ISSUE THREAD

**Issue by contrepub** [kiswa/TaskBoard#362]
Hi,
I'm very new using taskboard. 
In my first trying to setup it fails because the user admin (admin) doesn't work. I'stack in the login form.
I uploaded the files in a folder in my hosting space. I'm using a sub-domain to access Taskboard : 
Exemple: Mydomaine.com  ====> Task.Mydomaine.com
I read that I must put the files in the root. But I would like to use in this way. Is it correct? 
And my folder is in 777
Thanks for your help.

**Comment by contrepub** [comment]
To give you more information;
1) I follow the first step: "Copy the folders and files ... to the location you want to use TaskBoard"
2) I didn't minified the files (it's optional)
3) Open Firefox and URL mytasks.MYDOMAINE.COM and try to sign in with "admin" "admin" ID and Password.

The structure I'm using in may host space is:
hostRoot/MyDomaines/myTask/ 
and here I have the files
To access this folder I create a sub-domaine, as explained before: mytasks.MYDOMAINE.com

I think TaskBoard will be perfect for what I need.
 Thanks for your help.

**Comment by bbichero** [comment]
Please provide exactly error do you have. I think you probably have the same as me the first time a was installing TaskBoard, It was a 500 Internal error when trying to login with credentials: admin/admin
Have you install sqllite ?
The subdomain isn't a probleme at all.
In my opinion TaskBoard directory must be own by the user you use and www-data (for apache).
So 755 is good. (But perhabs there a better permission level access)
I'm 90% sure it's a database probleme (database can't create itself) because of miss step configuration.

**Comment by contrepub** [comment]
Thanks Bbichero,
There's no error message because it shows the login form, and when I click the sign in button it stays in the same page.
Anyway, your reply gave me a very good indication. As I said, I'm very new and I didn't catch that I should install SQLite. 
Ok... I'll read about how to get it installed in my Host where MySQL is the principal database system.
Please, if you have any suggestion about it it'll be usefull for me.
Thanks a lot.

**Comment by bbichero** [comment]
You can use MySql to !
Please do the folowing:
`mysql -u root -p`
```
GRANT ALL PRIVILEGES ON db-name.* TO 'mysql-user'@'localhost' IDENTIFIED BY 'mysql-user-password';
FLUSH PRIVILEGES;
CREATE DATABASE db_name;
```

`vi TaskBoard/api/api.php`
-R::setup('sqlite:'.__DIR__.'/taskboard.db');
+R::setup( 'mysql:host=localhost;dbname=db-name', 'mysql-user', 'mysql-user-password' ); //for both mysql or mariaDB

Of course you must change 'db-name', 'mysql-user and 'mysql-user-password' by your values.

**Comment by bbichero** [comment]
@contrepub Can you give us some news please ? Have you been succefully log in into Taskboard ?

**Comment by kiswa** [comment]
Closing due to lack of response. If you still need help, comment here and I will re-open.
