### ISSUE TITLE
api 

### ISSUE THREAD

**Issue by zcrews** [kiswa/TaskBoard#364]
I am getting api error- make sure api directory is writeable. I have done chmod -R 777 api , chmod -R 777 api/* and chown -R www-data:www-data api and every combination of those things, am I doing something wrong

**Comment by bbichero** [comment]
Please provide the exactly error.
Is that a 500 internal error ? (You can see that on your browser, right-click and inspect)

You can already check if `sqlite3` and `php5-sqlite` are installed.

Please let me know if after that an error occured.

**Comment by bbichero** [comment]
@zcrews Can you give us some news please ?

**Comment by kiswa** [comment]
Closing due to lack of response. Comment here if you still need help and I will re-open.
