### ISSUE TITLE
Cannot login, problem with api

### ISSUE THREAD

**Issue by blueiced56** [kiswa/TaskBoard#365]
After installation the login process is not working. After some testing I found out that when I make a call to the login process, I get a response '500 Internal Server Error'. The request I made was:

> POST /TaskBoard/api/login HTTP/1.1
> Host: sql16-tst-1067
> Content-Type: application/json
> Cache-Control: no-cache
> Postman-Token: f2803cc1-1a7b-9ed9-14e9-f5c12f32941f
> 
> {"username":"admin","password":"admin","rememberme":false}

I tried this on both Windows using [IIS](https://github.com/kiswa/TaskBoard/wiki/TaskBoard-on-IIS) and on linux using the instructions and all the extra's I could find in the other issues like Rewrite, sqlite and even tried the solution with MySQL. However the problem persists. Is it possible that the login call cannot be found? By the way, when I make a similar request to your demo environment Postman does return a 200 Status Ok response.

**Comment by blueiced56** [comment]
Regarding to linux I found out that the [vendor ](https://github.com/kiswa/TaskBoard/files/455143/vendor.tar.gz) directory was not present. I am still having issues with IIS to get it running.

**Comment by blueiced56** [comment]
And fixed the IIS issue as well. PHP needs some extra configurations as wel. The instructions can be found [here](https://stackoverflow.com/questions/12492908/sqlite-does-not-work-on-localhost-in-windows-7-php).

**Comment by bbichero** [comment]
Thanks for resolv your issue and give us some details.
Have a nice day.
