### ISSUE TITLE
How different will Taskboard re-write will be from Kansha?

### ISSUE THREAD

**Issue by 2Belette** [kiswa/TaskBoard#366]
Hi,
I am following your great work and I like it :) 
I am just wondering how far Taskboard would be different from [Kansha](https://github.com/Net-ng/kansha)?
On my point of view it seems very close.
Just want to get your opinion.
many thanks

**Comment by kiswa** [comment]
I had never heard of Kansha before, interesting.

TaskBoard will definitely have things in common with Kansha, as they are both kanban-style boards.

I just messed around with their demo, and found it very different from TaskBoard in the way it behaves and presents itself to the user. Which one is better is a matter for the user to decide.
