### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by tsunamitreats** [kiswa/TaskBoard#371]
So, I've been reading through the past cases, and I'm having issues installing TaskBoards.

I've tried on Amazon Linux and multiple versions of Ubuntu with multiple versions of PHP.

I've been focusing on the latest stable release of PHP5 and sqlite3 with PDO.  This has been successfully installed, and when I go to the host I get a login prompt, but I get a 404 for /login again and again.

This is my latest attempt: http://ec2-54-144-205-248.compute-1.amazonaws.com/#/  As you can see, things appear to be operating normally, but admin login doesn't work (still default).

Tailing the apache2 error log isn't providing any evidence, but http://ec2-54-144-205-248.compute-1.amazonaws.com/api/api.php appears to be having difficulty with connecting to the DB.

That being said, when I run 'php -m | grep sqlite'
php -m | grep sqlite
pdo_sqlite
sqlite3

I'm not sure where to turn from here.

**Comment by bbichero** [comment]
Have you install `php5-sqlite`, and install `rewrite` and `expires` Apache modules ?

Like TaskBoard `README.md` say too :

> Note: For Apache v2.3.9 and later, virtual host for a site should have AllowOverride All for TaskBoard root directory. Otherwise, .htaccess files will be completely ignored.

Also this can be a bad permission for `TaskBoard/api/` directory.
Please let us know if everythink i've said is good on your side.

**Comment by tsunamitreats** [comment]
> php5-sqlite
yes, "php5-sqlite is already the newest version."

> rewrite and expires Apache modules?
no, but after enabling these modules, this doesn't seem to have fixed the issue.

> AllowOverride
So I thought I had enabled this, but I think I was a bit confused.  I've since gone into apache2.conf file and enabled this configuration.  Before I was trying to add it into the local .htaccess file, which wasn't right.

> bad permission for TaskBoard/api directory
I've set the permissions to 777 while I work through my installation issues.

Still no luck after all the above changes.

**Comment by bbichero** [comment]
Can you connect to database throw sqlite ?
Do you see some tables ?
Your link is unreachable can you enable it ? If you don't want to open for all, I will give you my IP to authorize only me.

**Comment by tsunamitreats** [comment]
I accidentally blew it away, so I had to make a new one. I've documented all my steps and shared the host name here.  I'm not concerned about locking it down, as I'll go back and rebuild this once I have the process down.

On a fresh Ubuntu 14 Image, I've run the following commands:
- sudo su
- apt-get update
- apt-get upgrade
- apt-get install php5
- apt-get install php5-sqlite
- a2enmod rewrite
- a2enmod expires
I then downloaded a copy of the SW from here: https://github.com/kiswa/TaskBoard/archive/master.zip
Unzipped the folder and copied over the directory to my Ubuntu box.  I then run the following commands:
- mv /home/ubuntu/TaskBoard-master/* /var/www/html/
- cd /var/www/html/
- chmod +x build/*
- chmod -R +w api/* (I think this step is overkill)

At this point, I've taken a snapshot of my image -- so I can 'reset' everything easily.  

```
ubuntu@:~$ php -v
PHP 5.5.9-1ubuntu4.21 (cli) (built: Feb  9 2017 20:54:58)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
ubuntu@:~$ php -m | grep sqlite
pdo_sqlite
sqlite3
```

I haven't run the build-all script at this point.  It appears to be optional, when looking through the documentation, but I now run:
```
./build/composer.phar install
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "./build/composer.phar self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing firebase/php-jwt (1.0.0)
    Downloading: 100%

  - Installing gabordemooij/redbean (v4.2.0)
    Downloading: 100%

  - Installing ircmaxell/password-compat (v1.0.4)
    Downloading: 100%

  - Installing phpmailer/phpmailer (v5.2.14)
    Downloading: 100%

  - Installing slim/slim (2.6.1)
    Downloading: 100%

phpmailer/phpmailer suggests installing league/oauth2-client (Needed for XOAUTH2 authentication)
phpmailer/phpmailer suggests installing league/oauth2-google (Needed for Gmail XOAUTH2)
slim/slim suggests installing ext-mcrypt (Required for HTTP cookie encryption)
Generating autoload files
```

At this time, I would expect TaskBoards to be working, but I'm still seeing the same issue.

The login is here: http://ec2-34-230-10-42.compute-1.amazonaws.com/

To answer your questions, no, I can't seem to connect to throw or find any record of that DB.

**Comment by bbichero** [comment]
I see, thanks for all details.
You miss something:
`sudo apt install sqlite3`

And now in `Taskboard/buildl`
`./build-all`

**Comment by tsunamitreats** [comment]
I think sqlite3 was installed with php5-sqlite, no?

When I run, 'apt-get install sqlite3", I get the following:
```
sudo apt-get install sqlite3
Reading package lists... Done
Building dependency tree
Reading state information... Done
sqlite3 is already the newest version.
sqlite3 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
It's possible I could have run this and forgot to note it...

Then a build-all:
```
./build/build-all
Building...
 Installing dependencies
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "./build/composer.phar self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
 Compiling lib JS files...
 Minifying lib CSS files...
 Compiling app JS files...
 Minifying app CSS files...
 Updating index.html...
Build Complete
```

**Comment by bbichero** [comment]
Now you got everythink.
Sorry but I can't see what's wrong, perhabs upgrade your composer and update package ...

This is my configuration file for TaskBoard installation, but you don't need step after line 32 :
[taskBoardStep](https://github.com/Roger-skyline/documentations/blob/master/Installation_process/taskBoard.txt)
This is my apache conf file : [apache.conf](https://github.com/Roger-skyline/documentations/blob/master/Installation_process/config_files/task-board.conf)

I hope this will work ...

**Comment by tsunamitreats** [comment]
Long story short, nothing has worked.

I used your install.txt to make sure I had completed all the same things you have.  I even deployed a virtual server so :8000 is also an active port that is using your conf file.  http://ec2-34-230-10-42.compute-1.amazonaws.com:8000/#/

I also updated composer.phar.  I will note that it seems to break the way css is deployed (you can see that the login page isn't displayed appropriately now, after I reran build-all post composer update.

Let me know if you think of anything else.

**Comment by bbichero** [comment]
Ok, so the best I can do know, I think, is to install myself TaskBoard.
Can you give me a sudoer access to your VM ?
I need a clean VM if you can please.
Send all information to my email : baptiste@bicheron.com

**Comment by bbichero** [comment]
I have find the issue, Amazon AWS itself...
My Taskboard is running in a virtualized VM with a real public IPv4.

But AWS don't give you a real public IPv4, on your VM you have a private IPv4 class 2.
This is why you have all this `301 Moved Permanently` erros in browser.
But this must not be an issue.

I keep you in touch.

**Comment by bbichero** [comment]
Need a user who use AWS for running TaskBoard ! Please.

**Comment by tsunamitreats** [comment]
Bbichero, I would try wekan instead.  I don't know why it won't work, but it doesn't. Wekan installed for me, no problem.
