### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by BSK21** [kiswa/TaskBoard#375]
Hello!

Help me, please. =) What should I do (and which applications should I have installed) in order to run TaskBoard from my local host? Should I somehow compile and build downloaded files? Should I have some web-server running? Should I have some specific compilers? Which are pre-requisites for using TaskBoard? Sorry for this silly question. I'm new to it.
Could you give me some instruction (1. ... ; 2. ...; 3...; etc.).
Thank you so much beforehand and have a nice day!

Best Regards,
Boris

**Comment by bbichero** [comment]
Hi !

Here is what I used to install TaskBoard [installation_step](https://github.com/Roger-skyline/documentations/blob/master/Installation_process/taskBoard.txt), but if you dont use Mysql, stop at line 32.

In which Os would you TaskBoard ?
Have you already a web server, apache, nginx, running on your localhost ?

**Comment by BSK21** [comment]
Hi! Thank you so much for your reply! I'm very grateful to you!
My OS is Windows. And I don't have any web-server running on my localhost. And no specific compiler.

**Comment by bbichero** [comment]
So if you have windows, you must install [WAMP](http://www.wampserver.com/) very easy to install, don't worry.
You must install composer to download all php dependencies.
Follow these steps : [composer-install-windows](https://getcomposer.org/doc/00-intro.md#installation-windows)
And dowload the taskboard package.

**Comment by bbichero** [comment]
Please try to look for form yourself, there are already several issue for windows install.
I can't do all the steps to install on my personal computer taskboard right now.
But if you have a particular issue, let me know, perhabs tomorow I will have time.

**Comment by BSK21** [comment]
Thank you very much. You have helped me a lot! I will write you in case of any questions.:-)

**Comment by BSK21** [comment]
I have istalled both WAMP and composer. I ran script composer.phar in corresponding folder. And I'm not clear about what to do now.

**Comment by bbichero** [comment]
Ok. You must put TaskBoard directory in `C:/wamp/www`
And I think it's all :)
Go to a browser and enter `localhost` or `127.0.0.1`

**Comment by BSK21** [comment]
I have done it. =) But nothing happens. When I try to open wampserver64, he complains, that he can't open the application. Maybe, problem is there and I have to re-install it?

**Comment by bbichero** [comment]
No no you don't need to rebuild-it.
Try to read all issues please.
I will try today to install it in my windows computer.
I keep you in touch

**Comment by BSK21** [comment]
Thank you. Now I can visit localhost. And I have copied TaskBoard to www. Now what? Task board should somehow open, when I access 127.0.0.1? It doesn't happen.

**Comment by kiswa** [comment]
If you want to use the built-in IIS server on Windows, you could also try [this wiki page](https://github.com/kiswa/TaskBoard/wiki/TaskBoard-on-IIS).

**Comment by bbichero** [comment]
I think this is the best solution ! I succefully install TaskBoard with this method.

**Comment by BSK21** [comment]
Thank you very much for your advices! You have helped me a lot. =) Have a nice week!
