### ISSUE TITLE
Incomplete instructions for Installation

### ISSUE THREAD

**Issue by omarahmed** [kiswa/TaskBoard#376]
Hi,
I find [this ](https://taskboard.matthewross.me/docs/intro.html)page quite inadequate. There are missing sections for Pre-requisites, OS needed ,etc 
I am using a Windows machine with no specific setup for PHP, or anything related to LAMP. Where do I begin? I downloaded the project folder and could not run the bash file for instance.
Please make the documentation explicit enough for anyone to understand the requirements at least. I know its an OpenSource project so any effort is appreciated :)

**Comment by kiswa** [comment]
Part of the `re-write` branch is to include better installation documentation, and provide drop-in setups where possible. Updating the companion site will be part of this as well.

That said, there is a wiki page for [installing on windows with IIS](https://github.com/kiswa/TaskBoard/wiki/TaskBoard-on-IIS).
