### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by kaustuva** [kiswa/TaskBoard#377]
Hello Support,

please see the current issue during installation.

OS: Amazon Linux AMI release 2017.03

./build/composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
[jcontreras@ip-172-30-0-84 taskboard]$ ./build/build-all
Building...
 Installing dependencies
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
 Compiling lib JS files...
 Minifying lib CSS files...
 Compiling app JS files...
controllers/settingsBoardForm.js:241: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
            preferredFormat: 'hex3',
                                ^
1 error(s), 0 warning(s)

It's kinda urgent for me. please assist me.

Thanks and regards
Kaustuva

**Comment by rautamiekka** [comment]
Web browser version ?

**Comment by kaustuva** [comment]
hello @rautamiekka 
thank you for your response. I am installing in command line mode where i have encountered this error. May i need to install it in any command line web browser in my linux server? please let me know

Thanks
Kaustuva

**Comment by rautamiekka** [comment]
^ I hope not. Could be I misunderstood something, too.

**Comment by kiswa** [comment]
It looks like the compilation is failing because of a comma at the end of this line: https://github.com/kiswa/TaskBoard/blob/master/js/controllers/settingsBoardForm.js#L241

Edit that file and remove the comma and the build should work

**Comment by kiswa** [comment]
Closing due to lack of response. Comment if this still needs assistance.
