### ISSUE TITLE
Make boards open for public

### ISSUE THREAD

**Issue by petrk94** [kiswa/TaskBoard#378]
Hello,
I would like to know whether in the next time will be come a update, which allow public people to see the boards, without need to login?
Thanks

**Comment by kiswa** [comment]
Absolutely. It's on the roadmap for the `re-write` branch.

**Comment by petrk94** [comment]
@kiswa is there a progress board milestones in github to show?

**Comment by kiswa** [comment]
Not a public one. I'm not being as clear about the work on TaskBoard as I probably should.

Here's a current screenshot of my private TaskBoard that I'm using to track work:

![WIP](https://i.imgur.com/WDMVssz.png)

**Comment by bbichero** [comment]
@kiswa, I can install a TaskBoard on a VM and open it to public if you want. I can use your domain name or mine, this will be great for new user that want to see taskboard feature, but you can't connect with multiple session_id ...
Can you create a branch with no authentification ?

**Comment by kiswa** [comment]
I have a demo board for new users to try out TaskBoard: https://taskboard.matthewross.me/demo/

I just need to take some time on GitHub and create a milestone for the rewrite with better information about what I'm doing, so there's some visibility into progress.

**Comment by bbichero** [comment]
A ok nice for the demo I didn't notice it !
Yes this will be very great.

**Comment by kiswa** [comment]
Actually, I just created a GitHub Project which I'm going to use for this. https://github.com/kiswa/TaskBoard/projects/1

**Comment by bbichero** [comment]
This will be nicer thant a basic milestone.

Your demo taskBoard didn't work for me, page loading with infinite loop ...
