### ISSUE TITLE
View item / Upload file for re-write branch

### ISSUE THREAD

**Issue by halloalexkern** [kiswa/TaskBoard#381]
I guess it's not yet ready, right? at least it's not working for me (doubleclick, rightclick -> view).
Beside that the v1.0 re-write is awesome; fixes all annoying issues from v0.3.1.

:-)

**Comment by kiswa** [comment]
Yeah, the View Item menu does literally nothing (yet). ;)

And thanks, I'm glad you're liking the updates!
