### ISSUE TITLE
Unable to type Task / Item name in the quick add field, cursor leaves the field

### ISSUE THREAD

**Issue by turalo** [kiswa/TaskBoard#382]
Hi guys, 

I just finished a fresh install of the TB, on a clean ubuntu 14.4 server. I have created basic setup, 1 board, with 3 columns, like in the demo. 
When I try to add a task in the column, I click in the quick add field and start typing the words / title of the TASK.  while I'm typing after few letters or 1-2 words the cursor disappears and I'm unable to type, it's like if somebody pressed tab to get out of the field, then I need to click on the field again to be able to type the words.  so , to create one quick task I have to make 5-6 attempts, I must click the field again after each word or sometimes few letters. 
I'm using latest FireFox 54.01. have ABP and Ghostery.  but the extensions are turned off on the TB page. 
I have counted the cursor blinks, it's strange, sometimes it blinks 4 times, sometimes 8 times, and then it's gone. I have tested it also with Chrome. same problem. 
Anybody had the same problems ? any solution for this behavior ?

**Comment by rautamiekka** [comment]
What's your Client OS ?

**Comment by turalo** [comment]
I'm on windows 7, on same network as the ubuntu server.

**Comment by halloalexkern** [comment]
It looses focus, when the view updates every few seconds.
This is fixed in the re-write-branch.

**Comment by kiswa** [comment]
Yeah, it's because of the refresh. While this is fixed in the `re-write` branch, there is still a *lot* of work left before it's ready for daily use.

Until then... my apologies. I'm not going to update v0.3.1 - I want to concentrate on v1.0.0 (the re-write).

Type faster maybe? ;)

**Comment by turalo** [comment]
ok, thanks. will check.
