### ISSUE TITLE
404  error on second logon - IIS 

### ISSUE THREAD

**Issue by LukeWB** [kiswa/TaskBoard#383]
I managed to install and host Taskboard on IIS with PHP 7.1.8 + SQLite  using the instructions on the wiki. First time login with admin/admin worked fine and managed to create a board and a couple of new users. Tested those and still worked ok.

But when I came to log in again about an hour later I started getting a 404 error. I've tried rebooting the local host, reinstalling PHP and all the plugins, and reimported the URL rewrite rules: all with no success.

**Comment by kiswa** [comment]
I'll have to defer to another user with better IIS experience.

**Comment by LukeWB** [comment]
Thanks heaps! Hopefully someone has run into the same issue

**Comment by kiswa** [comment]
Wait a sec, TaskBoard v0.3.1 with PHP 7.1.8?

I think there are some issues that prevent it from working with the latest PHP.

Have you tried installing an older version (something 5.6.x is safest).

**Comment by LukeWB** [comment]
Ok so I have tried with PHP 5.6.9 and its running again! Looks like that was the problem.

**Comment by kiswa** [comment]
Glad I could help!
