### ISSUE TITLE
Does not log in

### ISSUE THREAD

**Issue by amunizp** [kiswa/TaskBoard#384]
I put user name admin and password admin the page seems to flicker but just stays a it is. 

Installation process:
(..)TaskBoard$ ./build/build-all
Building...
 Installing dependencies
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "./build/composer.phar self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing firebase/php-jwt (1.0.0)
    Loading from cache

  - Installing gabordemooij/redbean (v4.2.1)
    Loading from cache

  - Installing ircmaxell/password-compat (v1.0.4)
    Loading from cache

  - Installing phpmailer/phpmailer (v5.2.14)
    Loading from cache

  - Installing slim/slim (2.6.2)
    Loading from cache

phpmailer/phpmailer suggests installing league/oauth2-client (Needed for XOAUTH2 authentication)
phpmailer/phpmailer suggests installing league/oauth2-google (Needed for Gmail XOAUTH2)
slim/slim suggests installing ext-mcrypt (Required for HTTP cookie encryption)
Generating autoload files
 Compiling lib JS files...
./minify-libs: line 3: java: command not found
(...)/TaskBoard$ ./build/composer.phar self-update
Updating to version d9885d5b3bd1b28a6d8c679df848540e565ee818.
    Downloading: 100%         
Use composer self-update --rollback to return to version feefd51565bb8ead38e355b9e501685b5254d0d5

Any

**Comment by bbichero** [comment]
Hi,
Did you make sure that build directory is world writable ?
Have you installed `openjdk-8-jre`, `sqlite` and `php-5-sqlite` ?

**Comment by amunizp** [comment]
I did none of those things. Thank you! Any chance php7-sqlite might work?
Also is it only the build folder that needs to be world writeable, not the children? 
Changing to world writable means going from drwxrwxr-x to drwxrwxrwx, yes? 

I've just done the openjdk-8-jre, sqlite and php7.0-sqlite3 using $chmod 777 build and $chmod -R build and it still does not log in. So my assumption would be that there is not need to make the build children world writeable. And that I need to uninstall php7 and find a ppa (in case of ubuntu debian) that still does php5 and install php5-sqlite.

**Comment by rautamiekka** [comment]
^ `php*-sqlite3` and similar are strictly tied to the used PHP version, where the lib is installed and whether the PHP program can access that lib. While you could fool/force using older than designed versions you'll likely just break something or cause security issues.

>I've just done the openjdk-8-jre, sqlite and php7.0-sqlite3 using $chmod 777 build and $chmod -R build and it still does not log in.

Uh, what paths exactly you did those at ? You're supposed to install from package management, figure out their locations and what is tried to be used from where (the locations are deduced by the structure in the package and the last one by looking at the error log and trying stuff out).

**Comment by amunizp** [comment]
> ^ php*-sqlite3 and similar are strictly tied to the used PHP version, where the lib is installed and whether the PHP program can access that lib. While you could fool/force using older than designed versions you'll likely just break something or cause security issues.

So, since the package requires php-5-sqlite then should php7.0-sqlite3 be OK? because I am going forward rather than backwards?

> Uh, what paths exactly you did those at ? You're supposed to install from package management, figure out their locations and what is tried to be used from where (the locations are deduced by the structure in the package and the last one by looking at the error log and trying stuff out).

Sorry, the paragraph is  all poorly written. I did the following: 
$ apt-get install openjdk-8-jre sqlite php7.0-sqlite3 
because when I $ apt-get install  php5-sqlite 

> Package is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 

I later did $chmod 777 build and $chmod -R build in order to make the "build" folder world writeable. 

This is what I understood with @bbichero comment above and following the [introduction instructions](https://taskboard.matthewross.me/docs/) above.

Currently I am installing it on my desktop ubuntu 16.04. Though I would like to install it on a server ideally.  I have access to a BSD server, a debian Jessie server and one of those "hire for wordpress or similar apps" [server](krystal.co.uk) .

**Comment by rautamiekka** [comment]
^
>$ apt-get install openjdk-8-jre sqlite php7.0-sqlite3

I think you made a mistake there by writing `sqlite` instead of `sqlite3` cuz the former is SQLite 2.8.17 and the latter currently SQLite 3.11.0. It's unlikely you'll be using the interior SQLite2 databases on a modern NIX.

I just noticed the output in OP says you lack Java Runtime Environment which the minification system requires, but you can skip the minification by passing a flag (I don't remember which) at the cost of higher network and probly memory usage.

**Comment by amunizp** [comment]
OK just checked and sqlite in my ubuntu machine defaults to sqlite3 so I have sqlite3 installed. 

Minification system no longer to seems to be a problem. I only get problem with IE8 users which in this case I can safely ignore:

> (~)/TaskBoard$ ./build/build-all

> Building...
>  Installing dependencies
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Nothing to install or update
> Generating autoload files
>  Compiling lib JS files...
>  Minifying lib CSS files...
>  Compiling app JS files...
> controllers/settingsBoardForm.js:241: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
>             preferredFormat: 'hex3',
>                                    ^
> 
> 
>
>1 error(s), 0 warning(s)

But still can't log in.

**Comment by bbichero** [comment]
You have to remove the coma at line 241 from settingsBoardForm.js
Tell me if you got another error after fix this.

**Comment by amunizp** [comment]
> /TaskBoard$ ./build/build-all
> Building...
>  Installing dependencies
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Nothing to install or update
> Generating autoload files
>  Compiling lib JS files...
>  Minifying lib CSS files...
>  Compiling app JS files...
>  Minifying app CSS files...
>  Updating index.html...
> Build Complete
> 

Thanks. no errors on build now after removing the comma on (...)/TaskBoard/js/controllers/settingsBoardForm.js

Still does not log in. user admin pass admin, is there any where I should be looking for a log?

the build folder and children are highlighted in green in my terminal meaning they are world writeable. (I am guessing)

**Comment by geoffmondoux** [comment]
I had to enable mod_expires to apache in order for it to work. The api directory has a .htaccess file that references it.

**Comment by kiswa** [comment]
Thank you guys for providing help. I really appreciate it!

**Comment by bbichero** [comment]
You are welcome @kiswa, @amunizp, have you enable mod_expire and mod_rewrite on apache ?

**Comment by amunizp** [comment]
OK, so maybe I should have done [this](http://howtoubuntu.org/how-to-install-lamp-on-ubuntu) before on my local machine: it obviously has been done on most servers but I forgot that I had an almost fresh install of ubuntu. 

> sudo apt-get install apache2

> sudo apt-get install mysql-server

> sudo apt-get install libapache2-mod-php5

Now apache and php are confirmed to be working. Taskboard still not logging in, I found the hidden file (...)/TaskBoard/api/.htaccess file:

> 
> ExpiresActive Off
> RewriteEngine On
> 
> RewriteCond %{REQUEST_URI}::$1 ^(.*?/)(.*)::\2$
> RewriteRule ^(.*)$ - [E=BASE:%1]
> 
> RewriteRule ^taskboard.db$ %{ENV:BASE}api.php [QSA,L]
> 
> RewriteCond %{REQUEST_FILENAME} !-f
> RewriteRule ^(.*)$ %{ENV:BASE}api.php [QSA,L]
>

So I changed ExiresActive to On and left RewriteEngine On. 

![Log in button just redirects me back](https://user-images.githubusercontent.com/5783911/29862397-5a499dc0-8d64-11e7-9a08-99556145ba08.png)

No difference.

**Comment by kiswa** [comment]
@amunizp You actually want that `.htaccess` to have `ExpiresActive Off`.

What @bbichero was mentioning is that you need to enable the mods with apache:
```
a2enmod rewrite
a2enmod expires
```

**Comment by amunizp** [comment]
OK set ExpiresActive Off. 

> $ sudo a2enmod rewrite
> [sudo] password for amunizp: 
> Enabling module rewrite.
> To activate the new configuration, you need to run:
>   service apache2 restart
> $ service apache2 restart

Same.

> $ sudo a2enmod expires
> Enabling module expires.
> To activate the new configuration, you need to run:
>   service apache2 restart
> $ service apache2 restart

Same. I tried with indexDev.html as well. Same.

Ran 

> $ ./build/build-all
> Building...
>  Installing dependencies
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Nothing to install or update
> Generating autoload files
>  Compiling lib JS files...
>  Minifying lib CSS files...
>  Compiling app JS files...
>  Minifying app CSS files...
>  Updating index.html...
> Build Complete
> 
> 

still no change.

**Comment by kiswa** [comment]
What version of PHP are you running? TaskBoard v0.3.1 doesn't work well with the latest PHP.

PHP 5.6.x or 7.0.x seem to be fine, but 7.1.x tends to break.

**Comment by amunizp** [comment]
Seems Like I am just about in the clear:

> $ php --version
> PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
> Copyright (c) 1997-2017 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
>     with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
>

**Comment by kiswa** [comment]
What errors show up when you use <kbd>F12</kbd> dev tools while accessing the site?

**Comment by amunizp** [comment]
I think This is getting some where F12 and Console I guess is what you requested. 
![screenshot from 2017-09-05 09-13-52](https://user-images.githubusercontent.com/5783911/30051696-e9ce87e8-921a-11e7-9cb2-91dad0b7c0a6.png)

> 
> XML Parsing Error: not well-formed
> Location: file:///home/amunizp/Documents/C4AD/jobs/CRE-8/projectManagement/TaskBoard/lib/css/combined.min.css
> Line Number 1, Column 1:  combined.min.css:1:1
> XML Parsing Error: not well-formed
> Location: file:///home/amunizp/Documents/C4AD/jobs/CRE-8/projectManagement/TaskBoard/css/styles.min.css
> Line Number 1, Column 9:  styles.min.css:1:9
> XML Parsing Error: not well-formed
> Location: file:///home/amunizp/Documents/C4AD/jobs/CRE-8/projectManagement/TaskBoard/partials/login.html
> Line Number 3, Column 86:  login.html:3:86
> Error: a is null
> b.logIn/<@file:///home/amunizp/Documents/C4AD/jobs/CRE-8/projectManagement/TaskBoard/js/app.min.js:25:62
> fa/x.error/<@file:///home/amunizp/Documents/C4AD/jobs/CRE-8/projectManagement/TaskBoard/lib/libs.min.js:501:132
> g/<@file:///home/amunizp/Documents/C4AD/jobs/CRE-8/projectManagement/TaskBoard/lib/libs.min.js:532:343
> $eval@file:///home/amunizp/Documents/C4AD/jobs/CRE-8/projectManagement/TaskBoard/lib/libs.min.js:546:246
> $digest@file:///home/amunizp/Documents/C4AD/jobs/CRE-8/projectManagement/TaskBoard/lib/libs.min.js:543:324
> $apply@file:///home/amunizp/Documents/C4AD/jobs/CRE-8/projectManagement/TaskBoard/lib/libs.min.js:547:10
> g@file:///home/amunizp/Documents/C4AD/jobs/CRE-8/projectManagement/TaskBoard/lib/libs.min.js:501:336
> u@file:///home/amunizp/Documents/C4AD/jobs/CRE-8/projectManagement/TaskBoard/lib/libs.min.js:505:469
> f@file:///home/amunizp/Documents/C4AD/jobs/CRE-8/projectManagement/TaskBoard/lib/libs.min.js:507:46
>  libs.min.js:523:50
> 
        
But this seems to be errors on the mininimizing CSS thing. It should work without?

**Comment by kiswa** [comment]
So, the problem is that you're accessing TaskBoard from the filesystem. You should be using a web server (Apache is the norm) to access TaskBoard.

Your URL should not start with `file:///home/` it should start with `http://localhost/` or similar.

**Comment by amunizp** [comment]
I am so embarrassed right now.

So sorry! I'll move the files where they belong.

Can I build in a home user folder and then copy to /...var...www...html ?

**Comment by rautamiekka** [comment]
^
>Can I build in a home user folder and then copy to /...var...www...html ?

Shouldn't matter where. Login as the User the Web Server runs under and perform it there, which is even better than as another User and moving.

**Comment by amunizp** [comment]
OK thank you. Hopefully I can help others if I recollect what I have done up to now (might make it to install guide?). My current objective is to install it in a local server so that people in the network (office) can access the board. It will not be accessible from outside.

# Dependencies for ubuntu 16.04

```
$ sudo apt-get install openjdk-8-jre sqlite3 apache2 mysql-server libapache2-mod-php7.0 curl
$ sudo apt-get update && sudo apt-get upgrade

```
# Modifications currently needed

Rename folder TaskBoard-Master to TaskBoard
remove  comma on line 241 (...)/TaskBoard/js/controllers/settingsBoardForm.js
 ```
$ ./build/composer.phar self-update
 $ ./build/build-all
```

# move to server.

` $ sudo cp -r TaskBoard/ /var/www/html/`

Point browser to http://localhost/TaskBoard/ or http://machinename.local/TaskBoard
 to see if you see the login page.

Next check is to see if your local network find out your IP address:
` $ ifconfig
` 
look at inet addr:xxx.xxx.x.xx

point browser to http://xxx.xxx.x.xx/TaskBoard and you should see the same screen as on your local machine.

Make the build folder world writable:
```

 /var/www/html/TaskBoard$ sudo chmod 777 -R build/
 /var/www/html/TaskBoard$ ls

```
Should show the build folder world writeable (green). Note your world is currently the local network.

Seems api folder needs to be writeable as well.
`
 /var/www/html/TaskBoard$ sudo chmod 777 -R api/
`
# Where it starts to fail

Tried to log into the Taskboard with admin:admin

Did not work so tried .build/build-all
` $ .build/build-all`
Found several errors which I attempted to solve:

```
 $ sudo chmod 777 -R vendor/composer/ (to access installed.json)
 $ sudo chmod 777 -R vendor/  (to access autoload.php)

```

```
/var/www/html/TaskBoard$ ./build/build-all 
Building...
 Installing dependencies
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
 Compiling lib JS files...
java.io.FileNotFoundException: libs.min.js (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.filenameToOutputStream(AbstractCommandLineRunner.java:1153)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.fileNameToLegacyOutputWriter(AbstractCommandLineRunner.java:1126)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.createDefaultOutput(AbstractCommandLineRunner.java:741)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.outputSingleBinary(AbstractCommandLineRunner.java:926)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.processResults(AbstractCommandLineRunner.java:885)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:826)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:400)
	at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:1206)

```

Attempted:
```
 /var/www/html/TaskBoard$ sudo a2enmod rewrite
 /var/www/html/TaskBoard$ sudo a2enmod expires
 /var/www/html/TaskBoard$ service apache2 restart 
```
Still did not work. 

F12 on the browser. Console Net output is:
```
POST 
XHR 
http://192.168.1.47/TaskBoard/api/login [HTTP/1.1 404 Not Found 1ms]

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /TaskBoard/api/login was not found on this server.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at 192.168.1.47 Port 80</address>
</body></html>

```  

On the CSS it has more outputs, I think maybe to large to post directly. 
[taskboard.txt](https://github.com/kiswa/TaskBoard/files/1281005/taskboard.txt)

Thanks for all of your time, I hope this is helpful?

**Comment by ryanmac8** [comment]
I followed your same steps and also got a 404 at the login screen. I was able to fix it by editing the apache2.conf file. (/etc/apache2/apache2.conf). You should see around line 166 that the directory /var/www/ is set to AllowOverride None. You should change None to All. Restart Apache and it should work.

**Comment by kiswa** [comment]
Closing due to lack of response. Comment if this still needs assistance.
