### ISSUE TITLE
Build of app.min.js file generated error on excution time

### ISSUE THREAD

**Issue by jjf-zero** [kiswa/TaskBoard#385]
After build and minify de app, the tasks no show with all the content. I don't see the description or title of tasks.

The app.min.js file is generated with error on time of execution.

**Comment by bbichero** [comment]
Please can you provide the error you got ?

**Comment by jjf-zero** [comment]
I run the build-all command to get the production environment, I have done what is stated in bug #384 377, but after that I received the following message in the navigation console after the login and the items did not display all the information

Error: hyperlink is not defined
a.marked@http://to-do.xx.xx/js/app.min.js:16:625
zc.prototype.functionCall/<@http://to-do.xx.xxl/lib/libs.min.js:619:424
l/<@http://to-do.inventa.cl/lib/libs.min.js:528:188
Vc/this.$get</q.prototype.$digest@http://to-do.xx.xx/lib/libs.min.js:543:450
Vc/this.$get</q.prototype.$apply@http://to-do.xx.xx/lib/libs.min.js:547:10
e/t.$$intervalId<@http://to-do.xx.xx/lib/libs.min.js:510:488

**Comment by kiswa** [comment]
Sounds like something went wrong during the build process. hyperlink is a contributed JS file that should be in the final output for marked to use.

Run the build again and see if that helps?

**Comment by kiswa** [comment]
Closing due to lack of response. Comment if this still needs assistance.
