### ISSUE TITLE
Title and description are not displayed, modal doesn't close.

### ISSUE THREAD

**Issue by medienverbinder** [kiswa/TaskBoard#387]
When I create or edit an item, the following problem occurs: The title and description are not displayed, and the modal window is not closed after saving.

![taskboard](https://user-images.githubusercontent.com/4519686/30099888-52c9bbc4-92e7-11e7-9d6f-c9c389460122.jpg)

I'm not sure if there is a connection, but I get the following error message in the browser console:

```javascript
Error: hyperlink is not defined
a.marked@http://taskboard.local/js/app.min.js:16:625
functionCall/<@http://taskboard.local/lib/libs.min.js:619:424
l/<@http://taskboard.local/lib/libs.min.js:528:188
$digest@http://taskboard.local/lib/libs.min.js:543:450
$apply@http://taskboard.local/lib/libs.min.js:547:10
e/t.$$intervalId<@http://taskboard.local/lib/libs.min.js:510:488
```

@kiswa => Thanks for the great project, exactly what I was looking for :-)

**Comment by kiswa** [comment]
So, I've realized there's an issue with the build scripts. In `minify-libs` it does not include `hyperlink.js`.

There are two options for you to correct this: add the file to the list of files in `minify-libs` and run the build until you have `index.html` and `indexDev.html` files; or run `./build-all/clean` so you have `index.html` and `indexProd.html` files (this doesn't use the minified library).

And I'm glad you're enjoying TaskBoard!

**Comment by medienverbinder** [comment]
Both solutions work. Thanks for the quick help!
