### ISSUE TITLE
Apache Password Protection

### ISSUE THREAD

**Issue by bkoffler** [kiswa/TaskBoard#390]
Hi - i am trying to throw an additional password protection scheme in front of the log-in screen and i keep getting prompted to log in - i never get to the program. Has anyone tried this/found success?

**Comment by bbichero** [comment]
Hi,
Are you sure that isn't a problem from your .htaccess file ?
What password schema are you trying to add please ?

**Comment by bkoffler** [comment]
This is what I used:

 

<Directory "xxx/xxx">

AuthType Basic

AuthName "Restricted Content"

AuthUserFile /etc/apache2/.htpasswd

Require valid-user

</Directory>

 

Also, this is in my virtual host file, not htaccess as this is how I have done it on other sites in the past which work fine..

**Comment by bbichero** [comment]
Sorry but a can't reproduce the issue I don't have time to try it.
@kiswa Have you ever use a similar approach for double authentification ?
Can you tag some help please ?

**Comment by kiswa** [comment]
I have never tried this, but it shouldn't be needed. TaskBoard already requires a login to do anything.

It's possible there's a conflict since TaskBoard uses the Authorization header.

**Comment by bkoffler** [comment]
Right - anyway I ended up switching to a different program. The constant reloading was killing me!

**Comment by redge76** [comment]
Just to add I have the same issue here. I use traefik as a reverse proxy with basic authentication in front of taskboard to add anther layer of security (so my kanban can't be indexed by google...).
The fact that taskboard use this header conflict with the basic authentication of traefik.

**Comment by rautamiekka** [comment]
As far as my little knowledge about Apache's advanced features goes, couldn't this problem be circumvented by adding a rewrite script that runs before you're allowed to access TaskBoard, setting a special private flag to the requests which'll allow normal access to TaskBoard if set (meaning you've successfully logged in through Apache's pw screen) ?

Don't ask me about the specifics, Apache's rewrite is still something I don't understand.
