### ISSUE TITLE
Settings Dashboard won't work on LEMP stack

### ISSUE THREAD

**Issue by gitbugged** [kiswa/TaskBoard#393]
I'm trying to setup taskboard (looks awesome!) for a small project over my LAN , and I'm having a bit of trouble.

What works/info:
- Platform is RPi3, version is "master.zip" (stable)
- PHP and SQLite confirmed working per phpinfo()
- Nginx properly loads the login screen, and I can login.

What doesn't work:
Settings Dashboard is totally greyed out. Browser console shows:
`Error: $scope.currentUser is undefined
loadOptionsData@http://192.168.1.10/js/controllers/settings.js:31:9
$scope.loadCurrentUser/<@http://192.168.1.10/js/controllers/settings.js:24:13
$http/promise.success/<@http://192.168.1.10/lib/angular.js:9408:11
processQueue@http://192.168.1.10/lib/angular.js:13248:27
scheduleProcessQueue/<@http://192.168.1.10/lib/angular.js:13264:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://192.168.1.10/lib/angular.js:14466:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://192.168.1.10/lib/angular.js:14282:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://192.168.1.10/lib/angular.js:14571:13
done@http://192.168.1.10/lib/angular.js:9698:36
completeRequest@http://192.168.1.10/lib/angular.js:9888:7
requestLoaded@http://192.168.1.10/lib/angular.js:9829:9`

I tried several things to ensure php-fpm is working, and it definitely seems to be. I also checked similar bug reports, but none of them mentioned this specific error. I also ran composer and it installed all successfully. Any ideas?

**Comment by kiswa** [comment]
I'm not sure why `$scope.currentUser` would be undefined. Would you log out of TaskBoard, then use <kbd>F12</kbd> dev tools on the Network tab and do the following?

Log into TaskBoard.
Navigate to Settings.
Screencap the network tab and any console errors and post it here.

Thanks!

**Comment by gitbugged** [comment]
Thanks for the tip. Upon viewing it, I noticed several hundred API error 500s. I decided to switch to a LAMP stack, again using php-fpm, and experienced the same issue. Upon switching to php7_module modules/libphp7.so (described here: https://wiki.archlinux.org/index.php/Apache_HTTP_Server#PHP) the issue resolved itself. There appears to be an incompatibility with php-fpm.
