### ISSUE TITLE
Task Board sometimes bad display

### ISSUE THREAD

**Issue by hendratmokosudarto** [kiswa/TaskBoard#394]
I has successfuly installed Task Board on my server. But sometimes Task Board bad display . How fix it ? please help me .
![t](https://user-images.githubusercontent.com/32389781/31014777-f2cf2674-a546-11e7-9e14-45b3e99afacb.PNG)

**Comment by kiswa** [comment]
Bring up <kbd>F12</kbd> dev tools and post any errors it displays when this happens.

**Comment by hendratmokosudarto** [comment]
Like bellow. how fix ?
![1](https://user-images.githubusercontent.com/32389781/31121020-c7972a20-a860-11e7-8bfb-3371fa2b6885.JPG)

**Comment by kiswa** [comment]
What about the Network tab? Any 404 or 500 errors?

**Comment by hendratmokosudarto** [comment]
![1](https://user-images.githubusercontent.com/32389781/31164491-a4f4969a-a911-11e7-9d79-d84c316eb79c.PNG)

![2](https://user-images.githubusercontent.com/32389781/31164497-accb8374-a911-11e7-9a57-8c87ae5c8f26.PNG)

Like above ..

**Comment by kiswa** [comment]
Everything seems fine... have you tried another browser?

**Comment by hendratmokosudarto** [comment]
Still the same. Have you ever encountered that way ?

**Comment by kiswa** [comment]
I have not, that's why I'm trying to get something to show up to help figure out the cause.

Right now, I'm at a loss.

**Comment by kiswa** [comment]
Closing due to lack of response. Comment if this still needs assistance.
