### ISSUE TITLE
TaskBoard Needs Your Input!

### ISSUE THREAD

**Issue by kiswa** [kiswa/TaskBoard#396]
Originally, my plan for v1.0.0 was to do a complete re-write and include an entirely new page - the Dashboard - for an overview of everything.

Considering how long the re-write effort has taken, I'm thinking about finishing up just the re-write portion (which already includes a lot of new features) and pushing the Dashboard to v1.1.0.

What do you think of this idea? In my estimation, not waiting for the Dashboard will move the release up significantly.

Either way, a v1.0.0 release is still a few months away at my current pace (which is unusually slow lately). 😞

**Comment by captainwasabi** [comment]
I like it

**Comment by bbichero** [comment]
Best option :) Good job !

**Comment by 2Belette** [comment]
+1

**Comment by Brendantay86** [comment]
Good idea mate! 👍

**Comment by triode3** [comment]
Good idea.

**Comment by kiswa** [comment]
Okay, this is the way I'm going with the release then!

Thanks for the input everyone.
