### ISSUE TITLE
Rename "Lane" to "Column"

### ISSUE THREAD

**Issue by orenbenkiki** [kiswa/TaskBoard#4]
In common Kanban terminology, "lane" is used to describe a horizontal partition of the board (as in "swimming lane"). Simple boards have one lane, but sometimes you have several (e.g., a 2nd one for high-priority tasks, or for bug fixes, etc.). The vertical partition are typically called "columns" (or "stages"). WIP limits are per-column-per-lane.

Nit picking, I know :-) but it pays to be consistent with the common terminology.

**Comment by orenbenkiki** [comment]
The image in the README (URL : https://camo.githubusercontent.com/d8e6f7ed05a3260bb7d22397bb6b05bf3d5a2f9f/687474703a2f2f7461736b626f6172642e6d617474686577726f73732e6d652f646f63732f696d616765732f73657474696e67732d7374616e646172642e706e67 ) still says "Lanes" and not "Columns" :-)

**Comment by kiswa** [comment]
Yeah, I'm going to be changing the look of the Settings page with v0.3.0 so I figured I'd update all the screenshots then. But good eye!
