### ISSUE TITLE
Step by Step send notifcation 

### ISSUE THREAD

**Issue by amoyat** [kiswa/TaskBoard#402]
Hi, I would like to know if someone would be so kind as to explain to me where I should enable the email notifications function, and where I can configure Google's SMTP as a gateway.

Thankssss

**Comment by Jay2k1** [comment]
In case anyone sees this and has the same problem, you have to edit `api/mailConfig.php` to suit your needs.

**Comment by thbor** [comment]
i edit api/mailConfig.php,but makes o effects

**Comment by kiswa** [comment]
You also have to have an email address in your user settings.
