### ISSUE TITLE
MySQL and Postgres support

### ISSUE THREAD

**Issue by dgonzf** [kiswa/TaskBoard#404]
A suggestion, in this moment TaskBoard only supports SQLite databases, I think it would be interesting to be able to use other databases such as MySQL/MariaDB  and Postgres likes Kanboard.

**Comment by kiswa** [comment]
TaskBoard *defaults* to SQLite. You can alter the settings in [api.php](https://github.com/kiswa/TaskBoard/blob/master/api/api.php#L28) to use [any database supported by RedBeanPHP](https://redbeanphp.com/index.php?p=/connection).

**Comment by gusarg81** [comment]
Hi, this can be done still in latest release?

**Comment by kiswa** [comment]
It can, and correct on doing it.

**Comment by gusarg81** [comment]
> It can, and correct on doing it.

Ok, and does not need previous SQL structure?

**Comment by kiswa** [comment]
Nope, the database is created when accessed, as that's what RedBeanPHP does.
