### ISSUE TITLE
Missing Dependencies in Vendor Folder

### ISSUE THREAD

**Issue by fprisse** [kiswa/TaskBoard#405]
[Fri Dec 22 19:35:37.926865 2017] [:error] [pid 24803:tid 140696325375744] [client 83.162.148.163:59878] FastCGI: server "/home/users/kh_34614/cgi-bin/php-fcgi" stderr: PHP message: PHP Fatal error:  require_once(): Failed opening required '/home/users/kh_34614/www/taskboard/api/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/users/kh_34614/www/taskboard/api/api.php on line 3, referer: http://www.linkbook.eu/

Cannot run composer on Hosted ISP, would be happy with Vendor folder with relevant dependencies, can you help ?

**Comment by BlackEdder0815** [comment]
I think, you have to build the stuff on your working station, and then, you can upload the distribution to your hosted server.
Depending on, which of the versions you want to build, the effort is not too big.

**Comment by kiswa** [comment]
Assuming this is resolved.
