### ISSUE TITLE
Taskboard on Windows NGINX - Error: $scope.currentUser is undefined

### ISSUE THREAD

**Issue by brookd2404** [kiswa/TaskBoard#407]
Hi,

i am trying to get Taskboard wonrking on Windows with NGINX, so far i have over come some of my issues by browsing your issues page. However I cannot seem to find a resolution to this;

Error: $scope.currentUser is undefined
loadOptionsData@http://localhost/taskboard/js/controllers/settings.js:31:9
$scope.loadCurrentUser/<@http://localhost/taskboard/js/controllers/settings.js:24:13
$http/promise.success/<@http://localhost/taskboard/lib/angular.js:9408:11
processQueue@http://localhost/taskboard/lib/angular.js:13248:27
scheduleProcessQueue/<@http://localhost/taskboard/lib/angular.js:13264:27
$eval@http://localhost/taskboard/lib/angular.js:14466:16
$digest@http://localhost/taskboard/lib/angular.js:14282:15
$apply@http://localhost/taskboard/lib/angular.js:14571:13
done@http://localhost/taskboard/lib/angular.js:9698:36
completeRequest@http://localhost/taskboard/lib/angular.js:9888:7
requestLoaded@http://localhost/taskboard/lib/angular.js:9829:9

I am running NGINX whith PHP 5.6, i have the Vender folder a level above the API.

Do you know of any resolutions.

Thanks

**Comment by kiswa** [comment]
I have almost no experience with Nginx, and none with it on Windows.

Hopefully someone can chime in to assist.

**Comment by brookd2404** [comment]
If i move the vendor folder to the same directory as the API directory Taskboard will then log in and then kick the session off and reports and error;

Error: fn is not a function
$http/promise.error/<@http://localhost/lib/angular.js:9415:11
processQueue@http://localhost/lib/angular.js:13248:27
scheduleProcessQueue/<@http://localhost/lib/angular.js:13264:27
$eval@http://localhost/lib/angular.js:14466:16
$digest@http://localhost/lib/angular.js:14282:15
$apply@http://localhost/lib/angular.js:14571:13
done@http://localhost/lib/angular.js:9698:36
completeRequest@http://localhost/lib/angular.js:9888:7
requestLoaded@http://localhost/lib/angular.js:9829:9

I have been trying to get this going for a while, i would be interested in using your re-write however it doesnt appear to be the full package yet.

**Comment by kiswa** [comment]
Not sure why the angular.js lib would be throwing an error.

Can you post a screenshot of the console/network in dev tools? Maybe that'll give me something more to go on.

**Comment by kiswa** [comment]
Sorry, I still have no idea what's setup incorrectly to cause this to happen. There's also #408 with the same kind of problem.

I'm hoping someone with experience on Windows can chime in to either of these.

Also, did you run `build.build-all`? I'm pretty sure you'll need a *nix environment for it to work though....

The re-write will eliminate that dependency.
