### ISSUE TITLE
Help with initial setup of re-write branch

### ISSUE THREAD

**Issue by BlackEdder0815** [kiswa/TaskBoard#409]
Hi,
maybe you can help my with the setup of the rewrite-branch.
I want to try out the new stuff and may be help with feedback, but for now I'm stuck during the setup.
I checked the branch out and initialized all with "npm install". The script runs fine without any error.

What I'm currently missing, is, how to place it on the web-server. I'm using IIS under windows, the legacy version runs smoothly.
To setup the new on, I have to understand: 
* where the correct root of the web-app? Folder "src" ?
* what is the rule of the index.html in folder src? It's quite empty with some broken dependencies (js/vender.js; js/bundle.js)
* how should I set-up the url-rewrite, that I got it to work? So what is the intention/logic behind this?

I'm willing to write some howto to your wiki, when I successfully got it ready, but for now, I think I need some support. Thank you!

**Comment by kiswa** [comment]
I can only guess with the IIS stuff, but I can let you know what the general setup should be.

First, run `gulp`. This will build all the output files and have everything in a `dist/` directory. That is the location you want to be serving from your web server.

The build should make sure `dist/api` is writeable, but double-check since you're on Windows.

The `.htaccess` rules should be able to be imported into IIS as done for the previous version in the [wiki page](https://github.com/kiswa/TaskBoard/wiki/TaskBoard-on-IIS).

Let me know if there's anything else that doesn't go as planned.

**Comment by BlackEdder0815** [comment]
Perfect, thank you. I got it flying :-)
To build and run it with windows, it's a bit of tooling-stuff, what you are need:
Here my steps for reproducing, if someone want to go the same way:

- download and install git
- download and install node js (in my case v8.9.4-x64)
- download and install python (v2.7.14)
- download and install ruby (v2.4.3.1-x64)
- checkout the rewrite-branch with git: 
`git clone -b re-write https://github.com/kiswa/TaskBoard.git`
- install gulp
`npm install gulp --global`
- install saas
`gem install sass --no-user-install`
- install scss-lint
`gem install scss-lint --no-user-install`
- install dependencies for taskboard
go into task-board dir
`npm install`
- build taskboard
`gulp clean`
`gulp`
- copy created directory "dist" into you IIS folder (maybe rename, in my case "TaskBoard_new")
- convert this folder to an application (in IIS)
- edit the index.html and adopt the tag <base href=/dist/> to  your renamed folder (if you renamed it)
- import the following rewrite-rules into IIS (refer WIKI: https://github.com/kiswa/TaskBoard/wiki/TaskBoard-on-IIS):
for root-folder and adopt the application name
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ /TaskBoard_new/index.html [QSA,L]
```
for api-folder
```
RewriteCond %{REQUEST_URI}::$1 ^(.*?/)(.*)::\2$

RewriteRule ^taskboard.sqlite$ /TaskBoard_new/api/index.php [QSA,L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ /TaskBoard_new/api/index.php [QSA,L]
```
- check, that IUSR and IIS_USER have writing-permissions on api-folder
- that's all: go to http://localhost/TaskBoard_new and enjoy your next-gen TaskBoard ^^

**Comment by kiswa** [comment]
Nice, glad you got it working!

**Comment by Opzet** [comment]
IIS Install Steps

[IIS MissingFiles .zip](https://github.com/kiswa/TaskBoard/files/4249361/IIS.MissingFiles.zip)

1. Copy 0.31 to IIS directory, give  IIS_IUSER permissions
2. Install PHP v5 and Register handler mapping for C:\Program Files (x86)\PHP\v5.6\php-cgi.exe (wonto work with php 7 can register handler mapping for downgrade in directory
3. Copy Web.config to directories  (api & for url rewrite rules)
4. Copy vendor directory ( has vendor\slim\web.config)
5. Install missing deploy using .\build\install_depends.cmd
6. Log on as admin/admin
