### ISSUE TITLE
Delete of task not possible

### ISSUE THREAD

**Issue by BlackEdder0815** [kiswa/TaskBoard#410]
Hi,
I just tested the new re-write branch. Setup and creation/moving of tasks is working pretty good.
But I cannot delete a task.
There is no message appearing (after confirming the deletion).
The dev-tools (Chrome) are reporting an 405 (method not allowed)

Maybe it's a problem in my url-rewrite? But the rest is working pretty well

Here is a screenshot:
![grafik](https://user-images.githubusercontent.com/25084261/35502155-54110156-04dc-11e8-9d2f-75e8c521e307.png)

**Comment by kiswa** [comment]
I don't speak German, but that does look like a server issue. The delete calls actually use HTTP DELETE, and your server seems to only support GET or POST.

Not sure how to address that.

**Comment by BlackEdder0815** [comment]
perfect catch, thank you for the hint!
I enabled the DELETE verb in "Handler Mappings" in the PHP-module. After this, the deletion worked like a charm.
Thank you, for you support.
