### ISSUE TITLE
Changing default-color of board will not be stored

### ISSUE THREAD

**Issue by BlackEdder0815** [kiswa/TaskBoard#411]
If you change the default color of a board, this color will not be stored:

![grafik](https://user-images.githubusercontent.com/25084261/35502525-96986824-04dd-11e8-98a0-f3fa39deda1f.png)

After selecting color and clicking "Save Board", the color remains as it was.

**Comment by kiswa** [comment]
That is the default task color for a task set to the specified category.

Having a default board color is an interesting idea though. At the moment it is always that light yellow unless you change it in the task, or by adding a category.
