### ISSUE TITLE
Can't login: Error 500 and return to login screen

### ISSUE THREAD

**Issue by LadyFuzztail** [kiswa/TaskBoard#413]
I have Apache 2.4, PHP 7.1.14 and Sqlite 3 installed, I have the rewrite and expires modules installed and loaded, as well as ran the composer install script, as well as ensure that the API directory is writable under Vista. However, when I restarted Apache 2.4, I have been unable to log in to my own Taskboard site. Entering admin in both user and pass fields just causes the login screen to fidget and return to the login screen.

Looking at the dev console, I found this:

```
VM39:1 POST http://183.178.37.2/Taskboard/api/login 500 (Internal Server Error)
(anonymous) @ VM39:1
(anonymous) @ angular.js:9866
sendReq @ angular.js:9667
serverRequest @ angular.js:9383
processQueue @ angular.js:13248
(anonymous) @ angular.js:13264
$eval @ angular.js:14466
$digest @ angular.js:14282
$apply @ angular.js:14571
(anonymous) @ angular.js:21571
dispatch @ jquery-1.11.3.min.js:4
r.handle @ jquery-1.11.3.min.js:4
09:35:25.100 VM39:1 XHR failed loading: POST "http://183.178.37.2/Taskboard/api/login".
```

What am I missing here?

**Comment by LadyFuzztail** [comment]
Update: After some research, I found that Taskboard-Master doesn't support the latest PHP versions, so I downgraded to PHP 5.6.33 and I got this mess of an error when trying to log in: (Yes i reconfigured everything, and rebuilt with composer.phar)

https://pastebin.com/dsbQ7m2c

**Comment by kiswa** [comment]
Try deleting the `taskboard.sqlite` file in the `api` directory.

**Comment by LadyFuzztail** [comment]
I still get the same errors as in my first reply. I am gonna try switching to the rewrite branch and see if it works

**Comment by LadyFuzztail** [comment]
Okay, so I found out something interesting. Apparently the salt option is deprecated, and so I decided to comment out all instances of ",array('salt' => $*-salt)" in UserRoutes.php and Helpers.php. This changed the error into a 401 - Invalid Username or password. I will attach the minified code that it threw up, the error seems to be in line 38.
[VM1372-formatted.txt](https://github.com/kiswa/TaskBoard/files/1700542/VM1372-formatted.txt)

**Comment by kiswa** [comment]
Based on your first reply, I'm guessing the problem is that `sqlite` is not running with PHP 5.6.

You'll have a fair bit of work to do if you want to get it working with PHP 7.x.

Yes, the salt is deprecated, and not useful, but it also does not cause any problems (it's gone in the `re-write` branch though).

**Comment by LadyFuzztail** [comment]
What do you recommend I try?

I have attempted to install Taskboard-Rewrite but going into the directory just gives me an index listing of the files. Going into /src/ shows a "Taskboard is loading..." message and then it aborted in the console, as it seems that /dist/css/styles.css, /dist/js/vendor.js and /dist/js/bundle.js appear to be missing? I think there may be a build step that is missing from the readme.md.

**Comment by LadyFuzztail** [comment]
Okay, as it turns out, I can't use Taskboard-Rewrite either because it requires Node.js, which is not compatible with Vista. That leaves me with the master branch as my only remaining option, since none of the other self-hosted solutions have dependencies that can even run on my hosting machine. What do I need to do to get SQlite running on PHP 5.6.33?

**Comment by kiswa** [comment]
I couldn't tell you off-hand - I run Linux at home. Try [this search](https://www.google.com/search?newwindow=1&safe=off&ei=xrGBWvujOqaOgAaYjK6wBQ&q=sqlite+php+5.6+windows+vista&oq=sqlite+php+5.6+windows+vista&gs_l=psy-ab.3...9007.9854.0.10117.6.6.0.0.0.0.252.529.0j2j1.3.0....0...1.1.64.psy-ab..3.2.277...33i22i29i30k1j33i21k1.0.9VAdxFx4dzk)?

**Comment by LadyFuzztail** [comment]
Reopening this issue because I recently figured out how to get node.js working on my system.

Same deal. PHP 5.6.33 with Apache 2.4 and Sqlite3, this time I get an error 401 when trying to log in. 
Browser log : https://pastebin.com/eLFYECPx
