### ISSUE TITLE
Taskboard-Rewrite doesn't work

### ISSUE THREAD

**Issue by rh-programm** [kiswa/TaskBoard#414]
Hello,
I want to try TaskBoard rewrite.

When I visit my website `xyz.com/TaskBoard-re-write/src/`, only `TaskBoard is Loading ...` is displayed.

The webserver runs under `PHP 7.0`, has `sqlite3` and `php7-sqlite` installed and the `api` folder is writable.

**Comment by kiswa** [comment]
To use the `re-write` branch in its current state you must build the project.

1. Run `npm i` to install dependencies.
2. Run `gulp` to build.
3. Copy contents of `dist` directory to your server and open a browser to it.

**Comment by 2Belette** [comment]
I got the same issue even after npm i & gulp

**Comment by gistambo** [comment]
> Hello,
> I want to try TaskBoard rewrite.
> 
> When I visit my website `xyz.com/TaskBoard-re-write/src/`, only `TaskBoard is Loading ...` is displayed.
> 
> The webserver runs under `PHP 7.0`, has `sqlite3` and `php7-sqlite` installed and the `api` folder is writable.

I am having the same problem. javascript is enabled on the client side, but for some reason, none of the js files in the index.html file of the taskboard re-write are being rendered. I even changed the index.html file by misspelling the name of a javacript file, and it doesn't affect the outcome: The browser just displays "Taskboard is Loading ..."

Not sure how to troubleshoot this, as it may not be a problem with Taskboard.
