### ISSUE TITLE
No Title in Item

### ISSUE THREAD

**Issue by BartVanEynde** [kiswa/TaskBoard#416]
I had a working clean install for 15 min 
After then I was playing around I came into this situation where Item Title are no longer visible 
Both Chrome and IE on Windows
(it is possible that I has multiple items with the same title, but I assume this is ok?)

I tried removing the api/...db file and re-running ./build/build-all without success (again a working default situation, but titles are not restored...)

suggestions what I can do/try?
many thanks,
Bart
![taskboard no titles](https://user-images.githubusercontent.com/8719821/36468240-e2835462-16e2-11e8-8bcc-36fa41f60826.png)

**Comment by kiswa** [comment]
Can you right-click and inspect the empty area? I'm wondering if the title text is there but hidden by something.

**Comment by BartVanEynde** [comment]
the info seems to be in the json answer
![taskboard no titles debug](https://user-images.githubusercontent.com/8719821/36480704-9321bae6-170d-11e8-86ed-0915fb558dd6.png)

**Comment by BartVanEynde** [comment]
assigned to and category are correctly filled in, but div class=itemheader h4 is not filled in here
![taskboard no titles inspect](https://user-images.githubusercontent.com/8719821/36480839-fc575412-170d-11e8-83a5-1955d83f756d.png)

**Comment by kiswa** [comment]
Any errors in the console?

It looks like the problem might be that `marked` is missing.

**Comment by stebill** [comment]
Hello
may be this is not the right way, but I have solved this problem by changing  board.html and adding 
{{ item.title }} at line 63

`<h4><span data-ng-bind-html="marked(item.title)"></span>{{ item.title }}</h4>`

I also changed boardItemViewModal.html in the same way at line 11

`<h3 class="modal-title" id="itemViewLabel">{{ viewItem.title }}`


this solved the problem for me.

Stephan

**Comment by BartVanEynde** [comment]
indeed errors ref to marked on the console
![taskboard no titles console](https://user-images.githubusercontent.com/8719821/36494770-60ecb37a-1733-11e8-831d-aac1adfc15d3.png)

the two css files exist, and are not in the zip, so build-all got them?

**Comment by BartVanEynde** [comment]
can I re-get/re-gen the styles.min.js and combined.min.css ?

**Comment by kiswa** [comment]
Looks like an error in the build scripts.

Edit `build/minify-libs` to add `hyperlink.js` in the list after `marked.min.js`.

Not sure how this has gone unnoticed for so long, but I won't be fixing it as I want to get the re-write branch out soon.

**Comment by stebill** [comment]
Hello,

works for me. Thank you!!

**Comment by BartVanEynde** [comment]
this solution also works for me !
Many thanks everyone !
