### ISSUE TITLE
Editing Comment just after creating it fails (re-write)

### ISSUE THREAD

**Issue by Algorithmus** [kiswa/TaskBoard#418]
After you create a comment in a task and try to edit it without closing the task and try to save it, it will fail with an error message. If you close the task and re-open it though, you can edit the comment freely. Deleting works though.

I haven't looked into this too much, but it appears the comment somehow isn't being recognized as existing when you try to edit it immediately after it gets created.

**Comment by kiswa** [comment]
I have this on my list to check now that I am getting back into TaskBoard development.
