### ISSUE TITLE
Automatic Actions not loading

### ISSUE THREAD

**Issue by Zipelkopf** [kiswa/TaskBoard#422]
Hi, it's over a year I have been using TaskBoard and all was running fine... until recently when I realised that the **Automatic Actions** got stuck under the **Settings** page... the loading icon is just spinning forever (see screenshot).
Any suggestion on how to fix it?
Is it possible to reset the Automatic Actions without loosing the entire database?

Thanks a mill!
![image](https://user-images.githubusercontent.com/21308710/37345417-cf89a982-26c4-11e8-9d44-e8a5d423ba52.png)

**Comment by kiswa** [comment]
Before looking into DB changes, what errors do you see when using <kbd>F12</kbd> tools?

**Comment by Zipelkopf** [comment]
Hi, it shows the same error repeating about every second or so...

![image](https://user-images.githubusercontent.com/21308710/37360078-1d999156-26e7-11e8-845d-f6d6e9515240.png)

Cheers

**Comment by Zipelkopf** [comment]
If it helps I made a quick test... I deleted the **taskboard.db** after having taken a full backup and the **Automatic Activities** started working again. I wonder what software can I use to read and edit the database file? Perhaps it's just matter of finding a broken activity record and delete it. 
Thank you

**Comment by kiswa** [comment]
Just search for a SQLite browser for your OS. Should be relatively easy to locate the problem area.

Let me know how it goes.

**Comment by kiswa** [comment]
Closing due to lack of response.
