### ISSUE TITLE
Taskboard-Master : Error 401 after fresh install

### ISSUE THREAD

**Issue by LadyFuzztail** [kiswa/TaskBoard#423]
I recently figured out how to get node.js on my hosting PC running Vista SP2, and I decided to give installing this another chance. This time I get an error 401 when trying to log in.

I have PHP 5.6.33 with Apache 2.4 and Sqlite3 installed.
Browser log : https://pastebin.com/eLFYECPx
PHP Info : [phpinfo().pdf](https://github.com/kiswa/TaskBoard/files/1809243/phpinfo.pdf)

**Comment by kiswa** [comment]
Two questions: which branch is this for? and is the `api` directory writable?

**Comment by LadyFuzztail** [comment]
Taskboard-Master and yes, I made sure that api is given full read/write permissions.

**Comment by kiswa** [comment]
And you ran `./build/build-all`? I ask because the error partway down of `fn is not a function` is usually from missing dependencies. I think the 401 is a red herring.

**Comment by LadyFuzztail** [comment]
I'll try that and give you an update soon.
