### ISSUE TITLE
GoDaddy

### ISSUE THREAD

**Issue by pwinch** [kiswa/TaskBoard#424]
Need I say more.  I have a godaddy vps.  they don't allow terminal access.  They also only have MySQL or Microsoft SQL.  Since this needs sqlite, it is not just clone and run

**Comment by kiswa** [comment]
You'll need to run the build locally and copy the resulting files to your host.

You can change the database used by editing the `api.php` file [at line 28](https://github.com/kiswa/TaskBoard/blob/master/api/api.php#L28). See [RedBeanPHP's documentation](https://redbeanphp.com/index.php?p=/connection) for that.
