### ISSUE TITLE
Just type ./build/build-all

### ISSUE THREAD

**Issue by pwinch** [kiswa/TaskBoard#426]
./build/build-all
Building...
 Installing dependencies
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "./build/composer.phar self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing firebase/php-jwt (1.0.0)
    Downloading: 100%         

  - Installing gabordemooij/redbean (v4.2.1)
    Downloading: 100%         

  - Installing ircmaxell/password-compat (v1.0.4)
    Downloading: 100%         

  - Installing phpmailer/phpmailer (v5.2.14)
    Downloading: 100%         

  - Installing slim/slim (2.6.2)
    Downloading: 100%         

phpmailer/phpmailer suggests installing league/oauth2-client (Needed for XOAUTH2 authentication)
phpmailer/phpmailer suggests installing league/oauth2-google (Needed for Gmail XOAUTH2)
slim/slim suggests installing ext-mcrypt (Required for HTTP cookie encryption)
Generating autoload files
 Compiling lib JS files...
./minify-libs: line 3: java: command not found

**Comment by kiswa** [comment]
Looks like you need to install Java.
