### ISSUE TITLE
Change the Date to UK Format

### ISSUE THREAD

**Issue by brookd2404** [kiswa/TaskBoard#428]
Hi,

Is it possible to change the date on the Card to UK Fromat, See below;

![image](https://user-images.githubusercontent.com/34675757/37818252-730401b2-2e71-11e8-881a-98ca9c6aa892.png)

See the Due Date, can this be 28/02/2018 instead of 02/28/2018

**Comment by kiswa** [comment]
It will be possible once the rewrite is completed.
