### ISSUE TITLE
Social icons on TaskBoard website cover text

### ISSUE THREAD

**Issue by milkmiruku** [kiswa/TaskBoard#429]
![taskboard](https://user-images.githubusercontent.com/108225/37870886-ef6c6740-2fd8-11e8-9709-8c7f19f2fe15.png)

**Comment by kiswa** [comment]
This should be on the [taskboard.matthewross.me repo](https://github.com/kiswa/taskboard.matthewross.me).

It's a known issue, which I plan to address once I finish the `re-write` branch as the entire site will need to be redone anyway.

But thanks for the contribution!
