### ISSUE TITLE
Login screen hangs when logging into Taskboard Re-write

### ISSUE THREAD

**Issue by aheinricy** [kiswa/TaskBoard#430]
My Taskboard instance stopped working. When I try and log in the login screen just hangs and I see the following error.  

[Thu Apr 19 20:18:55.046975 2018] [php7:error] [pid 8088] [client 73.140.215.124:58440] PHP Fatal error:  Uncaught PDOException: Could not connect to d
atabase (?). in /opt/TaskBoard/dist/api/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php:314\nStack trace:\n#0 /opt/TaskBoard/dist/api/vendor/gab
ordemooij/redbean/RedBeanPHP/Driver/RPDO.php(140): RedBeanPHP\\Driver\\RPDO->connect()\n#1 /opt/TaskBoard/dist/api/vendor/gabordemooij/redbean/RedBeanP
HP/Driver/RPDO.php(338): RedBeanPHP\\Driver\\RPDO->runQuery('SELECT `user`.*...', Array)\n#2 /opt/TaskBoard/dist/api/vendor/gabordemooij/redbean/RedBea
nPHP/Adapter/DBAdapter.php(93): RedBeanPHP\\Driver\\RPDO->GetAll('SELECT `user`.*...', Array)\n#3 /opt/TaskBoard/dist/api/vendor/gabordemooij/redbean/R
edBeanPHP/QueryWriter/AQueryWriter.php(832): RedBeanPHP\\Adapter\\DBAdapter->get('SELECT `user`.*...', Array)\n#4 /opt/TaskBoard/dist/api/vendor/gabord
emooij/redbean/RedBeanPHP/Repository/Fluid.php(299): RedBeanPHP\\QueryWriter\\AQueryWriter->queryRecord('user', Array)\n#5 /opt/TaskBoard/dist/api/vend
or/gabordemooij/redbean/RedBeanPHP/OODB.php(390): RedBeanPHP\\Repository\\Fluid->load('user' in /opt/TaskBoard/dist/api/vendor/gabordemooij/redbean/Red
BeanPHP/Driver/RPDO.php on line 314, referer: 

Any idea why I might be getting this error?

Thanks.

**Comment by kiswa** [comment]
That is usually from the `dist/api` directory not being writable by the web server.

Make sure it's writable with `chmod a+w /path/to/api`.

**Comment by kiswa** [comment]
Assuming this is resolved.
