### ISSUE TITLE
Raspberry PI 3 B+ - the server responded with a status of 503

### ISSUE THREAD

**Issue by Kiwidev147** [kiswa/TaskBoard#431]
Hello,

I try to install TaskBoard on : Raspberry PI 3 B+ with
- PHP Version 7.0.27-0+deb9u1  
- SQLite3  
- on localhost  

but when I go on localhost/taskboard, I have this error :   
"API Error. Ensure api directory is writable"
Of course, the directory API is writable

When I see the console message in the web browser, I have : 
Failed to load resource: the server responded with a status of 503 (Service Unavailable)

I thought it was about a problem of database with sqlite which is now sqlite3, so I changed in api.php file, the line ('sqlite' => 'sqlite3') : 
R::setup('sqlite3:'.__DIR__.'/taskboard.db');
but it's always wrong with the same error message

I search a solution since several days but I don't find it.

If you can help me, thank's in advance

**Comment by kiswa** [comment]
Are you using the `master` branch or the `re-write` branch? The `master` branch doesn't support PHP 7.

**Comment by Kiwidev147** [comment]
Thank you for your answer

I used master :(

So I have downloaded the re-write branch. 

But now in the web browser in http://localhost/taskboard/ I have the :  Index of /taskboard (the directory with the list of the files).

**Comment by kiswa** [comment]
Yeah, with the `re-write` branch you need to run `npm i` to install dependencies, then `npm run build` to build a release.

That will create a `dist` directory with everything in it. Those are the files you want to have hosted. If you're going to have it in a sub-directory you should also update the `index.html` file so the `<base href="./">` is `<base href="your-dir/">`.

Hope that helps! Also, keep in mind that the `re-write` branch is not full-featured yet. As of right now, it's better than `master` in several ways, but doesn't have functioning attachments on stories, or email support.

**Comment by kiswa** [comment]
I'm assuming this is resolved.
