### ISSUE TITLE
Sandstorm package?

### ISSUE THREAD

**Issue by xarinatan** [kiswa/TaskBoard#432]
Hey there! I'm really digging this little kanban, it's very flexible and fast and lightweight and has just the right amount of features for my daily needs.
It would be amazing if Taskboard was available through Sandstorm, which would allow anyone to create new instances and share them with other people easily without having to think about user or server management, etc. Seeing how easy it is to install it should be really easy to create a Sandstorm container for Taskboard.
I've considered creating it myself, but I haven't done so before and I figured it'd be best to start with making an enhancement ticket for it :) 
Information for packaging apps for Sandstorm can be found here https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial/ it's mostly a matter of creating a container/VM with vagrant and creating some metadata files for Sandstorm.

**Comment by kiswa** [comment]
I've never even heard of that before. I'll look into it!
