### ISSUE TITLE
Icons not displaying on Firefox

### ISSUE THREAD

**Issue by sansloi** [kiswa/TaskBoard#436]
It's running out of Debian on Firefox. The following screenshot explains things. 3 columns on a board and none of them seem to be displaying icons. This problem persists in the settings menu as well. It could be a browser display error. Suggestions?

![screenshot from 2018-05-29 00-32-32](https://user-images.githubusercontent.com/10382385/40644506-4e8f1628-62d8-11e8-886a-e8ff2892727d.png)

If I run it on Google Chrome (Debian) it works as shown  below. 

![screenshot from 2018-05-29 00-41-07](https://user-images.githubusercontent.com/10382385/40644797-1bd6ec64-62d9-11e8-8c95-bd223f600fc1.png)

**Comment by kiswa** [comment]
Does the dev tools console or network tab show any errors?

**Comment by kiswa** [comment]
You'll need to run the build again after getting latest.
