### ISSUE TITLE
apache_request_headers for Lifecycle token

### ISSUE THREAD

**Issue by cheva** [kiswa/TaskBoard#438]
if(function_exists(apache_request_headers()) && apache_request_headers() && array_key_exists("LifeCycleToken", apache_request_headers())) {
    $lifeCycleToken->unserialize(apache_request_headers()["LifeCycleToken"]);
}

The apache_request_headers function exists only for apache servers, if it is launched on Nginx, its call results in an error. You need to implement an alternative option for storing the token.

**Comment by kiswa** [comment]
Duplicate of #317.
