### ISSUE TITLE
Is there a way to see all tasks across all boards assigned to specific user

### ISSUE THREAD

**Issue by captainwasabi** [kiswa/TaskBoard#44]
So I want to see all tasks that are assigned to me, no matter what board they are on.

Oh, maybe this doesn't make sense in a general usage case, because then you'd have to display all the "lanes" since, in general lanes don't have to be named Tasks, Working, Done, and Archive for all boards.

**Comment by torwag** [comment]
This could be maybe a part of a user dashboard? Together with other meta-data like recent changes among all boards, progresses, etc.

**Comment by ninsbl** [comment]
That sort of overview would be very useful! See also #163
