### ISSUE TITLE
How to install it on a webserver without terminal?

### ISSUE THREAD

**Issue by therealmaxmoon** [kiswa/TaskBoard#440]
I would like to install taskboard on a webserver, which I only have ftp access to it.

Is it possible to install it without a terminal?

**Comment by kiswa** [comment]
You could set it up locally, then copy the functioning directory over FTP. Should work the same on the server as on a local setup.

**Comment by kiswa** [comment]
Once you've run the build script, just copy the entire TaskBoard contents to wherever you're hosting it.

If you want to pare it down to necessary only, then the `index.html` file and every directory except `build` should do.
