### ISSUE TITLE
XAMPP config - help needed

### ISSUE THREAD

**Issue by Pieteros** [kiswa/TaskBoard#442]
Hi, 

I am stuck at the point "Run ./build/build-all"

How does one do that in XAMPP ? I have no idea.

I can load the page, login but then it says no boards, click on settings and all it shows is 
" Loading Boards..."

If i add the composer.phar to the URL all I get is the file content
http://127.0.0.1/TaskBoard/build/composer.phar

> #!/usr/bin/env php
> <?php
> /*
>  * This file is part of Composer.
>  *
>  * (c) Nils Adermann <naderman@naderman.de>
>  *     Jordi Boggiano <j.boggiano@seld.be>....

Any help for a novice is really appreciated.
Jim

**Comment by palesaj** [comment]
Same problem here. I hope there will be an answer soon.

**Comment by kiswa** [comment]
I also have no idea (don't run Windows). If anyone wants to contribute, please chime in!

In the (near?) future this will no longer be an issue as the project will be a drop-in setup.

**Comment by Opzet** [comment]
You need to launch composer.phar  with php

` > php composer.phar`

Working windows install with instructions at  [https://github.com/Opzet/TaskBoard](https://github.com/Opzet/TaskBoard)
