### ISSUE TITLE
app is not working 

### ISSUE THREAD

**Issue by ahmedfatnassi** [kiswa/TaskBoard#443]
after first authentication (admin) page 'boards' opened and suddenly redirected to the sign in page again

**Comment by sfrankli** [comment]
I see the same issue. 
From firebug I can see that the authenticate call is failing and the error is
"{"message":"Invalid token.","data":null,"alerts":[{"type":"error","text":"Unable to load user. Please try again."}]}"
Is there any logs being written which can provide more information about this.

**Comment by ahmedfatnassi** [comment]
this is the log written by apache
AH01630: client denied by server configuration: C:/apache/Apache24/htdocs/TaskBoard-master/.htaccess, referer: http://localhost/

**Comment by PatrickCaneloDigital** [comment]
I made the teste on my own machine with a simple php instance:

[Fri Jan 18 14:16:00 2019] PHP Deprecated:  password_hash(): Use of the 'salt' option to password_hash is deprecated in /Volumes/Data-Partition/BoxSync/Websites/taskboard/api/helpers.php on line 395
[Fri Jan 18 14:16:00 2019] PHP Stack trace:
[Fri Jan 18 14:16:00 2019] PHP   1. {main}() /Volumes/Data-Partition/BoxSync/Websites/taskboard/devrouter.php:0
[Fri Jan 18 14:16:00 2019] PHP   2. require_once() /Volumes/Data-Partition/BoxSync/Websites/taskboard/devrouter.php:17
[Fri Jan 18 14:16:00 2019] PHP   3. createInitialUser() /Volumes/Data-Partition/BoxSync/Websites/taskboard/api/api.php:30
[Fri Jan 18 14:16:00 2019] PHP   4. password_hash() /Volumes/Data-Partition/BoxSync/Websites/taskboard/api/helpers.php:395
ErrorException: password_hash(): Use of the 'salt' option to password_hash is deprecated in /Volumes/Data-Partition/BoxSync/Websites/taskboard/api/userRoutes.php:17
Stack trace:
#0 [internal function]: Slim\Slim::handleErrors(8192, 'password_hash()...', '/Volumes/Data-P...', 17, Array)
#1 /Volumes/Data-Partition/BoxSync/Websites/taskboard/api/userRoutes.php(17): password_hash('admin', 1, Array)
#2 [internal function]: {closure}()
#3 /Volumes/Data-Partition/BoxSync/Websites/taskboard/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#4 /Volumes/Data-Partition/BoxSync/Websites/taskboard/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#5 /Volumes/Data-Partition/BoxSync/Websites/taskboard/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#6 /Volumes/Data-Partition/BoxSync/Websites/taskboard/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#7 /Volumes/Data-Partition/BoxSync/Websites/taskboard/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#8 /Volumes/Data-Partition/BoxSync/Websites/taskboard/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#9 /Volumes/Data-Partition/BoxSync/Websites/taskboard/api/api.php(52): Slim\Slim->run()
#10 /Volumes/Data-Partition/BoxSync/Websites/taskboard/devrouter.php(17): require_once('/Volumes/Data-P...')
#11 {main}

**Comment by shorto** [comment]
Having the same issue. Anyone figure it out?
