### ISSUE TITLE
Can't Sign In

### ISSUE THREAD

**Issue by LornaWiles** [kiswa/TaskBoard#455]
Good morning
I am trying to login to Taskboard without success. I am double clicking on the index.html file and the login screen opens. I have tried using user name and password as ‘admin’ and ‘demo’ but neither works. I have also downloaded the setup files to a different pc with the same results. I have tried opening with both Morzila and Internet Explorer.  The online demo version worked perfectly. Do you have any suggestions as to what I may be doing wrong?
Path in browser to Taskboard v0.3.1 is: file:///E:/Taskboard/index.html#/
Any help would be greatly appreciated.
Many thanks.

**Comment by alialghamdi** [comment]
I have the same issue as well.

**Comment by kiswa** [comment]
If you're all having an issue and the path to TaskBoard is "file:///"anything then it isn't running in the correct environment. TaskBoard is meant to be run in a web server (Apache is assumed) with PHP.

**Comment by alialghamdi** [comment]
Hey, mine was running on Apache latest version on Ubuntu, and all PHP and Apache needed requirements are met.

**Comment by jlwallen** [comment]
It's running with Apache on Ubuntu Server 18.04. I've installed all PHP requirements.

**Comment by goldphnx** [comment]
I am running Apache on a CentOS 7 vps. I can get to the login screen but the username and password of "admin" does nothing.
