### ISSUE TITLE
Loading board - I need help

### ISSUE THREAD

**Issue by xseoxin** [kiswa/TaskBoard#456]
I tried to install the script on several web hosts with the same effect: loading board ... I installed according to the guidelines, I tried the ways of other users and nothing more. I do not create a vendor folder at all. When calling the api folder Fatal error: require_once (): Failed opening required '/home/webxseox/websites/crm/api/../vendor/autoload.php' (include_path = '.: / Opt / alt / php55 / usr / share / pear: / opt / alt / php55 / usr / share / php ') in /home/webxseox/websites/crm/api/api.php on line 3

![loading_board](https://user-images.githubusercontent.com/45876949/50011386-3ef55480-ffbc-11e8-96a7-d3e0734597a6.jpg)

**Comment by kiswa** [comment]
You're missing the vendor files for the PHP API. Follow step 2 here: https://github.com/kiswa/TaskBoard#install
