### ISSUE TITLE
New Taskboard-0.3.1 setup permanently "Loading ..."

### ISSUE THREAD

**Issue by jacobidiego** [kiswa/TaskBoard#457]
I have just starting to test TaskBoard.
In Settings menu, "Loading Boards...." and "Loading Users..." never ends, and never enables an Add button.

**Comment by jacobidiego** [comment]
![capture](https://user-images.githubusercontent.com/25246225/50085738-aa683d80-01d9-11e9-8e65-50ed3390fe12.JPG)

**Comment by Jovannino** [comment]
Hello , did you fix this problem ? I got the same issue on just installed application.

**Comment by maxeyb** [comment]
Hello,

I am having the same issue could someone please respond and help with this. 

Thanks

**Comment by barichello** [comment]
same here
