### ISSUE TITLE
No response from application

### ISSUE THREAD

**Issue by BigGingerTabby** [kiswa/TaskBoard#458]
I have installed the application on a CentOS platform.  I see the sign-in screen and enter admin/admin to set it up, but I get no response from the screen.  I've tried launching the app on Firefox and Chrome, even IE.  No response.  I've checked the apache error logs and no complaints.

Can you give me a hint?

**Comment by PatrickCaneloDigital** [comment]
I made the test on my local machine with a simple php instance:

[Fri Jan 18 14:16:00 2019] PHP Deprecated: password_hash(): Use of the 'salt' option to password_hash is deprecated in /Volumes/Data-Partition/BoxSync/Websites/taskboard/api/helpers.php on line 395
[Fri Jan 18 14:16:00 2019] PHP Stack trace:
[Fri Jan 18 14:16:00 2019] PHP 1. {main}() /Volumes/Data-Partition/BoxSync/Websites/taskboard/devrouter.php:0
[Fri Jan 18 14:16:00 2019] PHP 2. require_once() /Volumes/Data-Partition/BoxSync/Websites/taskboard/devrouter.php:17
[Fri Jan 18 14:16:00 2019] PHP 3. createInitialUser() /Volumes/Data-Partition/BoxSync/Websites/taskboard/api/api.php:30
[Fri Jan 18 14:16:00 2019] PHP 4. password_hash() /Volumes/Data-Partition/BoxSync/Websites/taskboard/api/helpers.php:395
ErrorException: password_hash(): Use of the 'salt' option to password_hash is deprecated in /Volumes/Data-Partition/BoxSync/Websites/taskboard/api/userRoutes.php:17
Stack trace:
#0 [internal function]: Slim\Slim::handleErrors(8192, 'password_hash()...', '/Volumes/Data-P...', 17, Array)
#1 /Volumes/Data-Partition/BoxSync/Websites/taskboard/api/userRoutes.php(17): password_hash('admin', 1, Array)
#2 [internal function]: {closure}()
#3 /Volumes/Data-Partition/BoxSync/Websites/taskboard/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#4 /Volumes/Data-Partition/BoxSync/Websites/taskboard/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#5 /Volumes/Data-Partition/BoxSync/Websites/taskboard/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#6 /Volumes/Data-Partition/BoxSync/Websites/taskboard/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#7 /Volumes/Data-Partition/BoxSync/Websites/taskboard/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#8 /Volumes/Data-Partition/BoxSync/Websites/taskboard/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#9 /Volumes/Data-Partition/BoxSync/Websites/taskboard/api/api.php(52): Slim\Slim->run()
#10 /Volumes/Data-Partition/BoxSync/Websites/taskboard/devrouter.php(17): require_once('/Volumes/Data-P...')
#11 {main}

**Comment by shorto** [comment]
Any resolve for this? I'm having the same issue.

**Comment by PatrickCaneloDigital** [comment]
I tried locally to modify the password_hash() calls. And although that made the error disappear, i wasn’t able to login with the default user/passworf

**Comment by shorto** [comment]
At the time of reading your output I was using PHP 7.2; then I saw "ErrorException: password_hash(): Use of the 'salt' option to password_hash is deprecated" so I simply downgraded to PHP 5.6. The only thing that did was for the script to take it a step further and warn me that the api folder was not chmoded correctly. I chmoded it and then the same thing again; login just redirects to login.

**Comment by PatrickCaneloDigital** [comment]
The salt option issue is something which apparently comes from a now deprecated function in one of the external plugins.
As i removed literally this option from the code, i actually understood the redirect (because suddenly i got an errormessage, stating incorrect login or password).
So i guess this is the underlying reason for the redirect.
I just do not yet understand why exactly, so i wasn’t able to fix it neither.

**Comment by olaulau** [comment]
works with PHP5.6, fails from PHP 7.0

**Comment by bbichero** [comment]
On which branch are you running TaskBoard ?
Only the re-write support PHP 7.0

**Comment by olaulau** [comment]
master :-/
you know that PHP 5.6 and 7.0 are no more supported ?
need any helpg oing out of those old versions ??

**Comment by bbichero** [comment]
I know, when I said PHP 7.0, it's PHP >= 7.0
Yes @kiswa is look for maintainers :)

**Comment by kiswa** [comment]
I'm currently in the process of a complete re-write using Angular (not AngularJS). I've had some delays the last few months with life getting in the way, but am hoping to get back into it very soon.

The re-write will only have official support for non-EOL PHP version (currently 7.1, 7.2, and 7.3, though 7.1 is only until Dec.).

While I would like to bring in some other maintainers, I'm not really ready to do that until I get the re-write done and release at least `v1.0.0`.

**Comment by olaulau** [comment]
ok, I can help for the PHP part if you need.
try to keep us informed of re-write advance. good luck !

**Comment by kiswa** [comment]
https://github.com/kiswa/TaskBoard/projects/1

**Comment by Dafexy1** [comment]
i downloaded it and it just showing white page
