### ISSUE TITLE
Add board and users buttons missing

### ISSUE THREAD

**Issue by Jovannino** [kiswa/TaskBoard#460]
Hello,
I've just installed Taskboard under local WAMP and login using admin user.
Now in setting screen I can't find the Add board and Add users buttons ?
Did I make some mistakes ? I'm not a programmer and I hope I don't need to code something...;-)

Excuse my ignorance but which is the database used ? May I use mysql db in a hosting server ?
Thanks
Giovanni

![image](https://user-images.githubusercontent.com/7689181/51670990-3daa4500-1fc8-11e9-9bd9-0f854c634e5b.png)

**Comment by Jovannino** [comment]
Hello...... nobody can help me ?

**Comment by pillerbee** [comment]
Same problem with my instance.

**Comment by spanishhighs** [comment]
Same problem here
