### ISSUE TITLE
404 error trying to login ?

### ISSUE THREAD

**Issue by SheepDomination** [kiswa/TaskBoard#462]
All the HTML files for Taskboard are located in this path; `~/taskboard/Taskboard-master/partials`.  Although when I visit the `http://domain/taskboard/Taskboard-master/partials/login.html` I get a `404` error ?

**Comment by kiswa** [comment]
You only need to navigate to `http://domain/taskboard/Taskboard-master/` and the rewrite rules should handle everything else (assuming a correct Apache setup).

**Comment by kiswa** [comment]
https://github.com/kiswa/TaskBoard#requirements

**Comment by SheepDomination** [comment]
What are the files or folders which have what rewrite rules ? 
Most of the folders are showing full read/write privileges, except for one file; `composer.json`.
