### ISSUE TITLE
Strange Login Screen ?

### ISSUE THREAD

**Issue by SheepDomination** [kiswa/TaskBoard#464]
Why does my login page look as such ?
![Taskboard_login](https://user-images.githubusercontent.com/6827459/54156673-1ba43f00-441d-11e9-9db0-c5e71fc4abcf.jpg) 
When I enter `admin` & `admin` for the login, it simply keeps asking me to re-enter ?
I suppose I have to use a redirect as to not use the `/partials/login.html` path as to login to *taskboard* ?

**Comment by kiswa** [comment]
You have to have your server setup to allow mod_rewrite to handle paths. You should only have to navigate to `host:port/taskboard_location` to get the login screen (you're directly viewing the template, which means the AngularJS app isn't getting loaded so you see those template placeholders).
