### ISSUE TITLE
taskboard don't show javascript

### ISSUE THREAD

**Issue by thbor** [kiswa/TaskBoard#465]
i install curl,jre.and run step 3 ./build-all 
but my taskboard have not show javascript,why is that?

**Comment by bbichero** [comment]
Can you show us your apache / nginx conf ?
What log have you in the browser console ?
Thanks

**Comment by thbor** [comment]
oh，thanks for your response firstly。
my apache model rewrite and expries can't load,when i do  
sudo a2enmod expires
sudo a2enmod rewrite
and service active，then sudo service apache2 reload.
it  refer to me that apache fail to  LSB WEB。i don't know why。and my email function can;t work.....

**Comment by bbichero** [comment]
What is the output of the command `sudo journalctl -xe` after executing
```
sudo a2enmod expires
sudo a2enmod rewrite
```
Thanks.

**Comment by thbor** [comment]
when i active 
sudo a2enmod expires
sudo a2enmod rewrite
and execute service apache2 restart
it refer to me that 
Unit apache2.service has finished shutting down     
Unit apache2.service has finished start-up
when i execute sudo service apache2 reload
it says apache2.service is not active, cannot reload.

**Comment by thbor** [comment]
sudo journalctl -xe says 
-- Unit apache2.service has finished shutting down.
Mar 31 20:33:00 taskboard systemd[1]: Starting LSB: Apache2 web server...
-- Subject: Unit apache2.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit apache2.service has begun starting up.
Mar 31 20:33:00 taskboard apache2[12253]:  * Starting Apache httpd web server apache2
Mar 31 20:33:00 taskboard apache2[12253]: (98)Address already in use: AH00072: make_sock: could not bind to
Mar 31 20:33:00 taskboard apache2[12253]: (98)Address already in use: AH00072: make_sock: could not bind to
Mar 31 20:33:00 taskboard apache2[12253]: no listening sockets available, shutting down
Mar 31 20:33:00 taskboard apache2[12253]: AH00015: Unable to open logs
Mar 31 20:33:00 taskboard apache2[12253]: Action 'start' failed.
Mar 31 20:33:00 taskboard apache2[12253]: The Apache error log may have more information.
Mar 31 20:33:00 taskboard apache2[12253]:  *
Mar 31 20:33:00 taskboard apache2[12270]:  * Stopping Apache httpd web server apache2
Mar 31 20:33:00 taskboard apache2[12270]:  *
Mar 31 20:33:00 taskboard systemd[1]: Started LSB: Apache2 web server.
-- Subject: Unit apache2.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit apache2.service has finished starting up.
-- 
-- The start-up result is done.

**Comment by thbor** [comment]
after execute sudo journalctl -xe,it says
-- Unit apache2.service has finished shutting down.
Mar 31 20:33:00 XXX systemd[1]: Starting LSB: Apache2 web server...
-- Subject: Unit apache2.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit apache2.service has begun starting up.
Mar 31 20:33:00 XXX apache2[12253]:  * Starting Apache httpd web server apache2
Mar 31 20:33:00 XXX apache2[12253]: (98)Address already in use: AH00072: make_sock: could not bind to
Mar 31 20:33:00 XXX apache2[12253]: (98)Address already in use: AH00072: make_sock: could not bind to
Mar 31 20:33:00 XXX apache2[12253]: no listening sockets available, shutting down
Mar 31 20:33:00 XXXapache2[12253]: AH00015: Unable to open logs
Mar 31 20:33:00 XXXapache2[12253]: Action 'start' failed.
Mar 31 20:33:00 XXXapache2[12253]: The Apache error log may have more information.
Mar 31 20:33:00 XXXapache2[12253]:  *
Mar 31 20:33:00 XXXapache2[12270]:  * Stopping Apache httpd web server apache2
Mar 31 20:33:00 XXXapache2[12270]:  *
Mar 31 20:33:00 XXXsystemd[1]: Started LSB: Apache2 web server.
-- Subject: Unit apache2.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit apache2.service has finished starting up.

**Comment by bbichero** [comment]
There are multiple same port listening.
Execute:   
`grep Listen /etc/apache2/ports.conf`    

If there are multiples same line, edit your configuration.
After that if the problem persist execute:
```
sudo systemctl stop apache2
netstat -nl
```

Please can you provide more information about your environment.
Execute:   
```
cat /etc/*release
uname -a
```

Please when you send output in github issue, use an appropriate syntax, enclose your command output with \`\`\`        \```

**Comment by thbor** [comment]
i execute grep Listen /etc/apache2/ports.conf,there are two same ports,and i change one.then i execute,but apache fail to start.
the information about cat /etc/*release is
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by thbor** [comment]
> 有多个相同的端口监听。
> 执行：
> `grep Listen /etc/apache2/ports.conf`
> 
> 如果有多个相同的行，请编辑您的配置。
> 之后如果问题仍然存在，执行：
> 
> ```
> sudo systemctl stop apache2
> netstat -nl
> ```
> 请您提供有关您的环境的更多信息。
> 执行：
> 
> ```
> cat /etc/*release
> uname -a
> ```
> 请在github问题中发送输出时，使用适当的语法，用`````括起命令输出

i do appreciate your reply,thanks a lot

**Comment by bbichero** [comment]
Ok but please provide the new output of the command:   
```
sudo systemctl restart apache2
```
Can you show me your apache configuration please ?
