### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by davidmind** [kiswa/TaskBoard#468]
Hi, @kiswa am a graphics designer. I contribute to open source project by making a logo for open source project. Below is what i made for your project, if you like i will proceed to make other file size. You can also make suggestion based on color and design.
![taskboard-presentation.png](https://cdn.steemitimages.com/DQmf8kCwWvHSH2j9WHZv5jkkLsN8pZsveCSShXrCpw9Bpbp/taskboard-presentation.png)

**Comment by kiswa** [comment]
I like the concept, however it gives me the impression of a calendar. The one without the empty boxes feels nicer to me.

If you want to give it another pass and match the upcoming color scheme for TaskBoard, have a look at this screenshot: https://raw.githubusercontent.com/kiswa/TaskBoard/re-write/.github/settings.png

I appreciate the offer of a logo!

**Comment by davidmind** [comment]
@kiswa i have change the color based on the screenshot you share above. Below is the new changes made
![taskboard-1.png](https://cdn.steemitimages.com/DQmeSLbEbwpBvHnBWmFshH2x2ziQPuYgJJ8C3zBaCrWpUXy/taskboard-1.png)

**Comment by davidmind** [comment]
@kiswa are you there?

**Comment by kiswa** [comment]
Yeah, I like the look of that. Will you be contributing an SVG to TaskBoard?

**Comment by davidmind** [comment]
Yes, I will provide all editable files, SVG, AI, PDF and PNG. I will submit a link to all the files as soon as I make all necessary sizes and logo type

**Comment by kiswa** [comment]
Very cool, thank you!

**Comment by davidmind** [comment]
hi, @kiswa sorry for the late response. I was a little bit hooked up. [here](https://drive.google.com/open?id=10U2B1QE9UibhAwvCO_GrHJFNSsH3M7gE) is a link to editable files. i have also make a pull request with the png files

**Comment by davidmind** [comment]
@kiswa are you there?

**Comment by kiswa** [comment]
I was out of town for the weekend. Thank you for the link and PR! I'll get them in the project soon!

**Comment by davidmind** [comment]
I taught i already create the pull request before that should be network issue, i just create a new one

**Comment by davidmind** [comment]
@kiswa am still waiting for the merge pull request

**Comment by davidmind** [comment]
@kiswa are you still interested in the logo?

**Comment by kiswa** [comment]
Of course. I do have a question about the PR, but I'll add that to the PR instead of here.

**Comment by davidmind** [comment]
OK, but already submit a link to editable file https://github.com/kiswa/TaskBoard/issues/468#issuecomment-489273049

**Comment by kiswa** [comment]
I know, but I wanted to be certain that the links you provided were meant as a contribution to TaskBoard. I didn't want to assume that was the case, then get hit with a copyright violation in the future. ;)

**Comment by davidmind** [comment]
OK best of luck.
If you have any other project that need a graphics work, either UI/UX design or logo I will always be available to help.
