### ISSUE TITLE
Ambiguous description and setup question 

### ISSUE THREAD

**Issue by RebelCoderRU** [kiswa/TaskBoard#471]
Point 4. says this:

**_Visit the site and log in with the username and password admin (and don't forget to change the password once you're in!)._**

What site is is that exactly ? After we run ./build-all, is it suppose to run a daemon in the background and we supposed to connect to it in the browser? If yes,  which port?

**Comment by bbichero** [comment]
You are right the url isn't precise, but if you look for in [nginx conf file](https://github.com/kiswa/TaskBoard/blob/master/build/nginx.conf) that expose port is 80, so you need to go to [http://localhost](http://localhost)
