### ISSUE TITLE
Deploying TaskBoard on Azure Web App

### ISSUE THREAD

**Issue by oneosurce** [kiswa/TaskBoard#475]
### Prerequisites ###

* [x] Are you running Taskboard with the same requirements as describe in [README.md](https://github.com/kiswa/TaskBoard/blob/master/README.md)?
* [x] Did you [perform a cursory search](https://github.com/kiswa/TaskBoard/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?
* [ ] Are you sure your problem come from the Taskboard project and not your environment ? Google is your friend :)

### Description ###

Hello,

I am trying to deploy TaskBoard on an Azure Web App instance.  I already have it running but when trying to login with the admin/admin creds, doesn't work.

How can you help me?

### Steps to Reproduce ###

1. Go to https://osboard.azurewebsites.net
2. Login with default admin/admin creds

**Expected behavior:**

Login to configure the environment.

**Actual behavior:**

Loads for a few minutes then displays API Error.

![Capture](https://user-images.githubusercontent.com/53099841/61570505-a0017100-aa52-11e9-85c7-c350fd5b45aa.PNG)

**Comment by Opzet** [comment]
IIS/Azure compatible build committed at [https://github.com/Opzet/TaskBoard](https://github.com/Opzet/TaskBoard)
