### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by GroupMaster** [kiswa/TaskBoard#476]
### Prerequisites ###

* [x] Are you running Taskboard with the same requirements as describe in [README.md](https://github.com/kiswa/TaskBoard/blob/master/README.md)?
Checked with phpinfo(), all deps are in and working.

* [x] Did you [perform a cursory search](https://github.com/kiswa/TaskBoard/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?
* [x] Are you sure your problem come from the Taskboard project and not your environment ? Google is your friend :)
I looked in the Issues, could't find anything.
 
### Description ###
Installed, chown'ed and chmod'ed, PHP 7.3 is current version on Apache, no virtual host configurations used, admin/admin entered. When Sign in is pressed, nothing happens. notta. OS is Debian.

### Steps to Reproduce ###

1. git clone repo
2. Updated composer if needed
3. chown to www-data and chmod ./api to 774 AND 777 (tried both)
4. build
5. click log in, brick wall.
**Expected behavior:**

log in to main page

**Actual behavior:**

After pressing log in, nothing happens.
``` lua
No errors found
```

``` lua
-- Separate them if you have more than one.
```

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: n/a
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**Installed AddOns:**

[List of installed addons which may conflict with the Aurora skin]

**Comment by kiswa** [comment]
This is a known issue... but I don't recall what ticket had the resolution.

Basically, the `master` branch doesn't work right on modern PHP. However, the `re-write` branch does (and has many improvements) but is still missing file attachments and emails.

If those two features aren't a deal breaker, I'd recommend switching to that branch.

**Comment by GroupMaster** [comment]
Perfect. They don't matter for my use. Thanks!
