### ISSUE TITLE
Login not working after install

### ISSUE THREAD

**Issue by goldphnx** [kiswa/TaskBoard#479]
I installed to a CentOS 7 vps server according to instructions, checking dependencies and receiving no errors along the way.
After using admin as the username & password the screen does not change when I clicked submit.

**Comment by nvillabona** [comment]
Same here

**Comment by kiswa** [comment]
Which branch? `master` is outdated and does not support PHP 7, `re-write` does, and is a slightly different install process (in the README).

**Comment by ggombos** [comment]
My solution, maybe help:
a2enmod rewrite
systemctl restart apache2
/TaskBoard$ composer install
