### ISSUE TITLE
Collapsable items

### ISSUE THREAD

**Issue by captainwasabi** [kiswa/TaskBoard#48]
Would be nice to be able to collapse items to just a title/assigned to/category header

**Comment by yojolo** [comment]
Hi. Sorry for the stupid question, but it's my first time trying to contribute on a Gihub project.
I thought this issue could be a good one to start dev on the project.
So I did the collapse item stuff (by imitation of the lane collapse that was already done). And it works well.
But... hum... I can't push it or make pull request or something.
Please help me ! (Or if you don't want my help, feel free to kick my ass !)
