### ISSUE TITLE
rewrite ETA

### ISSUE THREAD

**Issue by olaulau** [kiswa/TaskBoard#481]
Hi ;
We are using TaskBoard, and are waiting for the rewrite. some bugs aren't resolved because you are rewrite the whole app, I can understand.
Could you provide an ETA for the firs release ?
I cannot see any commit since more than one year ...

**Comment by kiswa** [comment]
Yeah, sorry, I've had a busy year and kind of lost motivation to work on TaskBoard for a while.

I've started working on updating it to the latest version of Angular, in preparation for getting back into it.

That said, the rewrite branch is quite usable as-is. The only missing items right now are emails and attachments.

**Comment by olaulau** [comment]
Hi ;
the install instructions seems to be outdated.
no .htaccess, neither ./build/composer.phar, neither composer.json / composer.lock file .
so all I have is a white screen with "TaskBoard is Loading..."
any advice ?

**Comment by kiswa** [comment]
Yeah, the README of the `re-write` branch is written as if it's been released, but that hasn't happened yet. Just clone the repo, check out the `re-write` branch, run `npm i` then `npm run build:prod`. At that point there will be a `dist` directory ready to be served by your server.

**Comment by olaulau** [comment]
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
npm ERR! 404 
npm ERR! 404  'event-stream@3.3.6' is not in the npm registry.

**Comment by kiswa** [comment]
Try running `npm update` before `npm i`.

**Comment by olaulau** [comment]
seems to work fine ... thanks !
so for those who want to test :
```
npm update
npm i
npm run build:prod
```
then point your php webserver to the `dist` folder.
