### ISSUE TITLE
Project Title ("TaskBoard") app in Google Play Store

### ISSUE THREAD

**Issue by kuerious** [kiswa/TaskBoard#482]
### Prerequisites ###

* [Yes] Are you running Taskboard with the same requirements as describe in [README.md](https://github.com/kiswa/TaskBoard/blob/master/README.md)?
* [Yes] Did you [perform a cursory search](https://github.com/kiswa/TaskBoard/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?
* [Yes] Are you sure your problem come from the Taskboard project and not your environment ? Google is your friend :)

### Description ###

Someone has 'sniped' your project name in the Google Play store.

### Steps to Reproduce ###

1. Go to Google Play Store
2. See the evil sniper's identical [program name](https://play.google.com/store/apps/details?id=com.velocityappsdj.taskboard&hl=en_US)
3. Make Angry Fist...

**Expected behavior:**

People are unique.

**Actual behavior:**

People can be buttheads.

``` lua
-- If you recived an error, place it here.
```

``` lua
-- Separate them if you have more than one.
```

### Additional information ###

**Screenshots and GIFs**

[Evil sniper!](https://i.imgur.com/xrzNpoI.png)

**Comment by kiswa** [comment]
Interesting.

I'll definitely consider reaching out to them. It's nothing like TaskBoard though (they certainly could've come up with a better name for what it does).

Also, it's at 50+ installs so it's either really new or not used much.
