### ISSUE TITLE
Forgotten password and user name. Cannot use the app. Any way of fixing this?

### ISSUE THREAD

**Issue by RoodParel** [kiswa/TaskBoard#483]
### Prerequisites ###

* [x] Are you running Taskboard with the same requirements as describe in [README.md](https://github.com/kiswa/TaskBoard/blob/master/README.md)?
* [x] Did you [perform a cursory search](https://github.com/kiswa/TaskBoard/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?
* [ ] Are you sure your problem come from the Taskboard project and not your environment ? Google is your friend :)

### Description ###

[Short description of problem here]

### Steps to Reproduce ###

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Actual behavior:**

[Describe observed behavior here]

``` lua
-- If you recived an error, place it here.
```

``` lua
-- Separate them if you have more than one.
```

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**Installed AddOns:**

[List of installed addons which may conflict with the Aurora skin]

**Comment by RoodParel** [comment]
Please provide links to retrieve usernames and password

**Comment by kiswa** [comment]
You could certainly lookup usernames in the DB, but there is no way to recover your password as they are hashed.

I may need to add a "forgot password" utility, but that is a far future thing.

**Comment by RoodParel** [comment]
Thanks for responding Matthew. 
The App has just got the required simplicity I am after, but it does not play well with my mac.
I will follow your work monitoring on progress, but for now I will have to use Trello.

Wishing you well,
Margaretha
