### ISSUE TITLE
installation on windows 10

### ISSUE THREAD

**Issue by Ahmad-Zaklouta** [kiswa/TaskBoard#486]
I followed the instruction in wiki for IIS but at the end I could not import the rule **RewriteEngine On**  because the apply was grayed.

I tried to follow the instruction in https://github.com/Opzet/TaskBoard and did everything exactly but when I login nothing happen. the login page staid and didn't change.

**Comment by kiswa** [comment]
As I don't have access to Windows 10, this will require outside assistance.

**Comment by Ahmad-Zaklouta** [comment]
I manage to make it work with IIS now after installing PHP manager from IIS. However, I could not apply the rule **RewriteEngine On** at all. I don't know if it matter or not or even what this rule is but it is working.
Thanks
