### ISSUE TITLE
scroll bar strange behavior

### ISSUE THREAD

**Issue by Ahmad-Zaklouta** [kiswa/TaskBoard#487]
It seems that the page is refreshed each 5 seconds. 
Now I have several tasks in one column that are more than what can be fitted in a screen so a scroll bar is shown on the right side of the column. but when I scroll down to check some tasks, the scroll bar goes back to the top by itself each 5 second.

I tried to click on the scroll bar on hold so I can read the task but it still goes up  after 5 seconds by itself.

I am using IIS with windows 10.

**Comment by kiswa** [comment]
Long-standing issue that is not being fixed in v0.3.1 branches.

The `re-write` branch is nearly complete to release 1.0 and does not have this issue.
