### ISSUE TITLE
Unable to make changes in settings

### ISSUE THREAD

**Issue by bawejaapoorv** [kiswa/TaskBoard#488]
Hello ,

We are unable to change settings .

### Prerequisites ###

* [ ] Are you running Taskboard with the same requirements as describe in [README.md](https://github.com/kiswa/TaskBoard/blob/master/README.md)?
* [ ] Did you [perform a cursory search](https://github.com/kiswa/TaskBoard/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?
* [ ] Are you sure your problem come from the Taskboard project and not your environment ? Google is your friend :)

### Description ###

[Short description of problem here]

### Steps to Reproduce ###

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Actual behavior:**

[Describe observed behavior here]

``` lua
-- If you recived an error, place it here.
```

``` lua
-- Separate them if you have more than one.
```

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**Installed AddOns:**

[List of installed addons which may conflict with the Aurora skin]

**Comment by kiswa** [comment]
This does not provide any information about your issue.
