### ISSUE TITLE
External Users (LDAP, OpenAuth, etc.)

### ISSUE THREAD

**Issue by anotherspot** [kiswa/TaskBoard#49]
Would be fantastic if we could use an external user directory i.e. LDAP for authentication.

**Comment by Kernle32DLL** [comment]
Well that depends. I did not look into how authentication works in TaskBoard, but how I see it, you still need to create some kind of "reference user" in the system (so you can set triggers, assign tasks, etc.). So you need to add an "source" reference into each user either way (is it a board generated user, LDAP, Google, Github, etc. etc.). Authenthication on login would then fork down the appropriate way for authentication. If this is coded generic enough, you could add all sorts of logins.

I personally prefer LDAP, cause we use that at work ;-)

**Comment by poVoq** [comment]
Owncloud and Django would be great.

**Comment by dionysiusmarquis** [comment]
+1 on LDAP

**Comment by ninsbl** [comment]
More authentication methods / external users would be really cool. Amazing piece of software BTW.
