### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [kiswa/TaskBoard#490]
**Describe the bug**
Every request to the /api/ folder leads to a Slim Application Error

**To Reproduce**
I cloned the github repo and installed the necessary depencies with composer.
I tried to convert the htaccess files to nginx as good as possible and it seems to work.
After login, it won't got past the loading page.
Every request that hits an api file leads to the error above.

**Additional context**
Full error log:

`Slim Application Error`
`The application could not run because of the following error:`

`Details`
`Type: ErrorException`
`Code: 2`
`Message: Illegal string offset 'Dnt'`
`File: /TaskBoard/api/helpers.php`
`Line: 11`
`Trace`
`#0 /TaskBoard/api/helpers.php(11): Slim\Slim::handleErrors(2, 'Illegal string ...', '...', 11, Array)`
`#1 /TaskBoard/api/helpers.php(53): getallheaders()`
`#2 /TaskBoard/api/helpers.php(328): getUser()`
`#3 /TaskBoard/api/helpers.php(306): checkDbToken()`
`#4 /TaskBoard/api/boardRoutes.php(5): validateToken()`
`#5 [internal function]: {closure}()`
`#6 /TaskBoard/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)`
`#7 /TaskBoard/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()`
`#8 /TaskBoard/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()`
`#9 /TaskBoard/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()`
`#10 /TaskBoard/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()`
`#11 /TaskBoard/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()`
`#12 /TaskBoard/api/api.php(52): Slim\Slim->run()`
`#13 {main}`

**Comment by kiswa** [comment]
I have never seen that error before. What branch did you use (`master`, `dev`, `re-write`)?

**Comment by kiswa** [comment]
Closing due to lack of response.
