### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by dicijr** [kiswa/TaskBoard#495]
**Describe the bug**
Does not work.

**To Reproduce**
Normal install

**Expected behavior**
Give me login screen

**Screenshots**
/api reads:

{"status":"failure","data":[{"status":"One of \"success\" or \"failure\".","data":"An array of data (JSON objects and\/or arrays). The first object is a new JWT for the next request.","alerts":"An array of alerts, with \"type\" of \"success\", \"error\", \"warn\", or \"info\" and a \"text\" message."}],"alerts":[{"type":"error","text":"No API functionality at this endpoint."}]}

**Please complete the following information:**
Brave Browser
Ubuntu Server 18.04
Apache2 
Php 7.2

**Comment by kiswa** [comment]
That is what you should get when navigating to the API directly. It describes the `ApiResponse` object that is returned with API calls (and is also one itself).

**Comment by clanhunter** [comment]
what to do next.
How to install.

**Comment by kiswa** [comment]
You go to the installed location, _e.g._ `yoursite.com/taskboard` instead of `yoursite.cim/taskboard/api`.

**Comment by clanhunter** [comment]
Sir can you get connected with me and help me in setting up the things
