### ISSUE TITLE
Configuration with caddy server

### ISSUE THREAD

**Issue by guizmoau** [kiswa/TaskBoard#496]
**Describe the bug**
I have errors when I try to first login with admin/admin

in chrome console
Failed to load resource: the server responded with a status of 404 () /api/authenticate:1

and then when trying to login
zone.js:3324 POST https://task.domain.com/api/login 404
core.js:4117 ERROR TypeError: Cannot read property 'alerts' of null

this is my caddyserver configuration file :

task.mydomain.com {
        root * /var/www/task
        php_fastcgi / unix//var/run/php-fpm/php-fpm.sock
        file_server
}

**To Reproduce**
1. install caddyserver and configure
2. download and extract TaskBoard
3. run caddy and access via web browser address

**Expected behavior**
I want to be able to first connect, configure user and start using

**Screenshots**

**Please complete the following information:**
- OS: debian
- Browser chrome
- Version v2b1

**Additional context**

**Comment by Nico207** [comment]
Hi!
Same problem here (Ubuntu/Apache)

On the home page, I have a 404 error on "authenticate" (URL : http: //localhost/api/authenticate)
And when I clic on the "Sign In" button I also have a 404 error, but on "login" (URL : http: //localhost/api/login)

![image](https://user-images.githubusercontent.com/1179972/83891703-e1277000-a74d-11ea-82df-e84e835ec836.png)

**Comment by Nico207** [comment]
After adding the following lines to my configuration

```
<Directory /var/www/taskboard>
        AllowOverride All
</Directory>
```

I have instead an 500 error.

**Comment by kiswa** [comment]
Are you sure everything in the [Prerequisites](https://github.com/kiswa/TaskBoard#prerequisites) is setup correctly?

What is the content of the response in the 500 error?

**Comment by guizmoau** [comment]
Yes I have everything in the pre-requirements

Yes I am still having a 404 in the console

**Comment by Nico207** [comment]
😳 whoops...
Maybe I forgot something... like **activate sqlite**.

It works better after enable it.
Sorry! 😅

**Comment by guizmoau** [comment]
Ok I am glad for you but this topic was about caddy webserver configuration not apache

and I am still stuck :/

**Comment by Nico207** [comment]
Sorry, I thought it was a bug that could have the same origin (pretty much the same error messages in the same place and after a new installation), when it was simply a bad configuration on my side.

**Comment by guizmoau** [comment]
So I have just installed TaskBoard 
When I try to connect at first screen with admin / admin I have no error or visible change in the page

In the console of the web browser it gets 404 on /api/authenticate and /api/login

If i go in the folder of the installation, I have inside api only the folders controllers helpers and vendor, together with an index.php file.
The right on the folder has been given to all for writing in that /api folder.

Any clue, for anyone to help ?!

**Comment by davidlag0** [comment]
We worked around these issues by enabling Apache2 modules rewrite and expires. I don't know if expires is really required but this was taken from an old Dockerfile we found out on Docker Hub. Right now, we're stuck with 400 errors that show "Invalid API token" in the dev tools. I'm not sure what else to enable. Where should we look? Any way we could enable more logs? Apache isn't showing anything in error.log so that makes it tricky to troubleshoot!

**Comment by kiswa** [comment]
You should get that error on the initial login page @davidlag0. It checks to see if you have a valid token so it skips the login if you do. Do you get that error after logging in?

**Comment by kiswa** [comment]
Also, if the server-side errors it will create a `logs/api.log` file under the `api` directory. See if you have that file, and see what it has.

**Comment by kiswa** [comment]
@guizmoau I know nothing about Caddy Server, but if you get 404 errors it means the `.htaccess` is not functioning, so it's a setup issue with the server. 

You'll have to figure out how to translate what is in the `.htaccess` file to the configuration Caddy uses. This is my best guess for where to start: https://caddyserver.com/docs/caddyfile/directives/rewrite

**Comment by guizmoau** [comment]
ok thanks for your answer...too bad caddyserver is not working with it
