### ISSUE TITLE
not able to login

### ISSUE THREAD

**Issue by Vipul007info** [kiswa/TaskBoard#497]
After successfully installed on server, and having input username= admin and password=admin, login not done... no any response

**Comment by Nico207** [comment]
Probably the same problem as #496

**Comment by kiswa** [comment]
What shows in dev tools (usually <kbd>F12</kbd> in your browser) when you try to log in?

**Comment by kiswa** [comment]
Closing due to lack of response. If you still need help, comment and we can re-open.
