### ISSUE TITLE
Unable to log in with v1.0.1

### ISSUE THREAD

**Issue by davidlag0** [kiswa/TaskBoard#501]
**Describe the bug**
Impossible to use taskboard as we cannot go in "Settings" to make any change.

**To Reproduce**
1. Do a fresh install on Apache 2 with PHP 7.4.x (in our case we installed in a container with Ubuntu 20.04). Ensure AllowOverride is set to All for the folder where Taskboard is installed. Ensures "api" folder is writeable.
2. Use the default admin/admin credentials to log in.
3. At the default home page, click on "Settings".
4. We should now be back at the login page.
5. If we try to log in again, we see a flashing home page but the login screen is back again.

**Expected behavior**
It is possible to see the "Settings" screen to make changes as we desire.

**Screenshots**
![image](https://user-images.githubusercontent.com/40720561/84079864-3c08d380-a9a9-11ea-9d98-5e7fdef9c9b0.png)

In the screenshoot we can see the Authorization header has the token twice separated by a comma which I believe could help find the root issue.

**Please complete the following information:**
- OS: Ubuntu 20.04 running in a Docker container.
- Browser: Chrome
- Version: Chrome 83.0.4103.97.

**Additional context**
I don't believe Docker makes a real difference here. We are using TaskBoard behind an NGINX reverse proxy.

**Comment by kiswa** [comment]
What is the result of the `Preview` or `Response` tabs?

Do you have php7-sqlite and sqlite installed?

**Comment by davidlag0** [comment]
Yes, I have these installed:
- php7.4-sqlite3/focal-updates,focal-security,now 7.4.3-4ubuntu2.2 amd64 [installed]
- sqlite3/focal,now 3.31.1-4 amd64 [installed]

`Response` tab shows `{"status":"failure","data":[],"alerts":[{"type":"error","text":"Invalid API token."}]}`

**Comment by davidlag0** [comment]
Related to my response in another thread [(Issue #496)](https://github.com/kiswa/TaskBoard/issues/496), I see I get the error on the initial login page and I understood it was fine according to what I saw in the Chome Dev Tools (Authorization Header missing or something). It totally made sense to me. The problem is after I click on Settings and get that login screen again and cannot login anymore. That is problematic.

We installed the code at `/var/www/html`. I cannot see any log file in that directory. In the `api` directory, there is also no log file. I then looked in `/var/log/apache2` and can see the usual `access.log` and `error.log` that do not contain anything interesting to help figure out the issue.

**Comment by davidlag0** [comment]
Issue fixed with the addition of these lines in our NGINX config:
`proxy_set_header Authorization $http_authorization;
proxy_pass_header Authorization;
`

**Comment by kiswa** [comment]
Glad you found a fix. I should really familiarize myself with NGINX. Can you share (a sanitized version if needed) your config for me to use as a starting point?

**Comment by gusarg81** [comment]
Hi, I am facing this issue, but cannot pass the Login page. php7.1-sqlite and sqlite3 are installed (Ubuntu 18.04 server).

Browser:

```
ERROR TypeError: "e.alerts is undefined"
    login login.component.ts:51
    RxJS 31
    Angular 8
```

Apache logs when even load the site (just In case if relevant):
```
.htaccess: Invalid command 'php_value', perhaps misspelled or defined by a module not included in the server configuration`
```

Any ideas? Thanks.

**Comment by kiswa** [comment]
I'm going to guess that's because [PHP 7.1 is EOL](https://www.php.net/supported-versions.php)

**Comment by gusarg81** [comment]
Switched to php7.4 and the same thing happens.

**Comment by kiswa** [comment]
Wow, just realized the log error was with the `.htaccess`, sorry.

Is PHP running in CGI mode, or as a module in Apache? Because it needs to be as an Apache module.

**Comment by gusarg81** [comment]
I always use PHP as FPM with apache. There is no way I can run php using mod_php in my server.

**Comment by kiswa** [comment]
I will look into it, certainly.

**Comment by kiswa** [comment]
After some research, you should be able to use PHP-FPM if you remove (or comment out) the `php_value` items in the `api/.htaccess` file.

Then, those values can instead be set in a `.user.ini` file: https://www.php.net/manual/en/configuration.file.per-user.php

**Comment by gusarg81** [comment]
Hi!,

Now I can login.

BTW, php settings in FPM does not set there but in, for example, /etc/php/7.4/fpm/pool.d/mysite.conf (in my case, this is in Ubuntu server and I am sure Debian is the same as well).

**Comment by superian** [comment]
"I'll make sure to update the README to include mention of this."

I forgot to make a note of this, and got caught by it again on upgrading to 1.0.2 - if it is in the README, I can't spot it.

Would having wrapping these in an 'if mod_php enabled' test be a workaround for later versions?

**Comment by kiswa** [comment]
@superian Dang it, I should've made a separate issue to update the README. I'll add it now, and look into workarounds to allow either setup.

**Comment by davidlag0** [comment]
Hi @kiswa ,

I apologize it took so long for me to answer. The last config we had in NGINX for TaskBoard is this location block:

  # TaskBoard v1.0.1
  location /taskboard/ {
    set $upstream_server taskboard;
    rewrite /taskboard/(.*) /$1 break;

    proxy_pass http://$upstream_server;
    proxy_redirect http:// $scheme://;

    proxy_http_version  1.1;
    proxy_cache_bypass  $http_upgrade;

    proxy_set_header Upgrade           $http_upgrade;
    proxy_set_header Connection        "upgrade";
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host  $host;
    proxy_set_header X-Forwarded-Port  $server_port;
  }

I believe we had issues related to buffering and had to use "proxy_buffering off;" as well in this location block. Because we have this option set globally and we might have gone and removed this parameter in each location block as we now had it globally, it could explain why I don't see it in the last config we used. We don't use TaskBoard anymore but hopefully this could be useful for yourself and others.

Have a good day!
