### ISSUE TITLE
How install??

### ISSUE THREAD

**Issue by TomasIPV** [kiswa/TaskBoard#504]
it's not that easy

I have installed it CENTOS 7 , 8 , UBUNTU 14, 18... PHP 7..

what is needed to install?

APACHE 2 + MOD re write
PHP 7+
Sqlite3

Donwload code.

And? Angular?

In Directory /var/www/html/taskboard/

npm install

Any wiki?

Thanks

**Comment by kiswa** [comment]
https://github.com/kiswa/TaskBoard#install

Download the TaskBoard*.zip for the release, not the code.
