### ISSUE TITLE
Set category action isn't triggered on task moves to column

### ISSUE THREAD

**Issue by ra1101** [kiswa/TaskBoard#507]
Issue Description

When an action trigger is configured to set the task category upon moving the task to a column, the task category is not set.

1. Create a board with 4 columns
2. Create one or more categories
3. Create an action for the board:
  - task moves to column: <column name>
  - set category: <category>
4. Add a task
5. Move it to the column which should trigger the action

Exptected behavior:
The task that was moved to the column which should trigger the action, should have the specified category applied.

**Screenshots**

- OS: Mac OS Catalina 10.15.2
- Browser: Chrome 
- Version Version 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
This occurred on the demo instance, v1.0.1

Note: upon setting 'view tasks side by side', all categories appeared.

**Comment by ra1101** [comment]
Refreshing the browser window causes the category to show up on the task.

**Comment by 2Belette** [comment]
Yes tested and like @ra1101 mentioned it is like there is no realtime effect but browser needs to be refreshed. Is it intended ? I guess there is still missing a piece

**Comment by kiswa** [comment]
Good to know that it happens with a refresh. Means the UI isn't updating when it should (which is a much simpler fix).

**Comment by jjgg7** [comment]
Hello, now the Triggers doesn't work at all.
