### ISSUE TITLE
Special characters in emails not displayed correctly

### ISSUE THREAD

**Issue by Nico207** [kiswa/TaskBoard#509]
In emails, with French language set up, all characters with accents are not displayed correctly.
 
> t**â**che modifi**é**e → t**Ã¢**che modifi**Ã©**e 
> **É**ch**é**ance → **Ã©**ch**Ã©**ance

The problem is probably the same for all "special" characters like
`À Â Ä È É Ê Ë Î Ï Ô Œ Ù Û Ü Ÿ à â ä è é ê ë î ï ô œ ù û ü ÿ Ç ç « » €`

**Comment by kiswa** [comment]
Odd, I'll look into that.

**Comment by ben-so** [comment]
German umlauts (äöüÄÖÜß) are affected too.

**Comment by kiswa** [comment]
Good to know.

**Comment by ben-so** [comment]
Found out, that Emails were sent with wrong charset in PHPMailer and created a PR #543

**Comment by kiswa** [comment]
Thank you @ben-so!
