### ISSUE TITLE
Tracking dependencies between tasks?

### ISSUE THREAD

**Issue by koyae** [kiswa/TaskBoard#510]
I'm shopping around for some way of organizing personal projects in a saner way than I previously have, but I'm interested in something that can help me manage dependencies between tasks.

Is this either a current feature or something you would accept a pull-request on? Thanks.

**Comment by kiswa** [comment]
Sorry, no. While TaskBoard does do some interesting things (% completion, auto actions, etc.) The main goal is to be as simple as possible.

To me, dependencies between tasks should be handled by categories and columns (and soon, with the ability to link directly to a task).
