### ISSUE TITLE
Feature Request : Collapse/Expand all tasks default option in settings

### ISSUE THREAD

**Issue by 2Belette** [kiswa/TaskBoard#512]
**Is your feature request related to a problem? Please describe.**
When opening a board all the tasks are Expanded by default. It is fine as all the tasks descriptions can be seen at a glance. On the reverse side and when a large amount of tasks are it is very busy.

**Describe the solution you'd like**
Would be nice to have an option in Settings (like the one for side-by-side, animations, show assignee) for Expand/Collapse all tasks. 
![2020-06-19-20:31:52](https://user-images.githubusercontent.com/2325706/85169347-f206d400-b26b-11ea-8b20-31aecd2b994a.png)

**Describe alternatives you've considered**
Now the alternative is to manually click on Collapse on each individual column. This option should remains as it is very useful anyway.

**Additional context**
This would keep large number of tasks on the same board clean & neat

**Comment by kiswa** [comment]
Seems reasonable to me!

On a different note: If that's what the toggles look like for you, please open a bug about them and let me know what browser, OS, etc. so I can address the way they look.

**Comment by 2Belette** [comment]
oki ! doing it now (will open another one for timeout)
