### ISSUE TITLE
Toggle button looks weird

### ISSUE THREAD

**Issue by 2Belette** [kiswa/TaskBoard#513]
**Describe the bug**
It seems to you that the toggle button are not what we should expect

**To Reproduce**
1. Go to Settings

**Expected behavior**
I guess the cursor should be centered verticaly

**Screenshots**
![2020-06-19-20:31:52](https://user-images.githubusercontent.com/2325706/85170401-9c332b80-b26d-11ea-98a8-c9d04958e531.png)

**Please complete the following information:**
- OS: Linux Hyperbola 0.3 
- Browser Iceweasel (based on Firefox)
- Version 52.9.20200112 (64-bit)

**Additional context**
The browser is based on the LTS version

**Comment by kiswa** [comment]
Nice title. And yes, they should look like this: ![](https://i.imgur.com/TWcyvWv.png)

**Comment by 2Belette** [comment]
Indeed I like yours much better :) If you need some FF Console logs let me know

**Comment by 2Belette** [comment]
![2020-09-10-17:27:43](https://user-images.githubusercontent.com/2325706/92754385-11a12a80-f38b-11ea-9ea8-2a079c698aad.png)
Screenshot from 1.0.2, same issue plus the dropdown menu is also weird...let me know if you need me to test anything ?

**Comment by kiswa** [comment]
I do not, so good call. And WTF?! Is the browser still Iceweasel 52.9.20200112 (64-bit)?

**Comment by 2Belette** [comment]
Yep almost : 52.9.20200525 (64-bit), apparently a couple of minor updates

![2020-09-10-17:56:49](https://user-images.githubusercontent.com/2325706/92758454-05b76780-f38f-11ea-9048-f023ad78bd56.png)
