### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by divinitystar** [kiswa/TaskBoard#515]
Install looks good, but first login doesn't work for me.  I see that I'm getting a 500 internal server error for api/login and api/authenticate.  I think I have all the prerequisites, but based on this, does it look like I"m missing something?

ERROR TypeError: "e.alerts is undefined"
    login login.component.ts:51
    RxJS 31
    Angular 8
        c
        invokeTask
        onInvokeTask
        invokeTask
        runTask
        invokeTask
        h
        p
core.js:4117:18

**Comment by kiswa** [comment]
How is PHP running? `mod_php` or PHP-FPM?

Also, can you give me the result of the API calls from the Network (or similar) tab in your browsers Dev Tools?

**Comment by divinitystar** [comment]
Thank you for the prompt reply!   I'm running php 7.2 with PHP-FPM.  Attached is a screenshot of chrome network console.  

![net-error](https://user-images.githubusercontent.com/4382211/85234776-d7546c80-b3dd-11ea-8546-96138a77a594.png)

**Comment by kiswa** [comment]
I meant the Network tab like this: ![](https://i.imgur.com/Q7oTI4K.png)

Doesn't matter though, it's because it's PHP-FPM. See [this bug comment for a resolution](https://github.com/kiswa/TaskBoard/issues/501#issuecomment-647173454)

**Comment by divinitystar** [comment]
I'm getting closer after making the changes outlined in that resolution.  No more 500 errors, but now I'm getting 400 errors.  The database was created, but I can't get past the login screen to make changes to the settings.
![net-error2](https://user-images.githubusercontent.com/4382211/85240138-07633600-b405-11ea-9980-25dddf46a61f.png)

**Comment by divinitystar** [comment]
After a little research, I found that the Authorization header was getting stripped out and that was causing the 405 error.  I added the following rewrite condition to the htaccess in the API folder and that allowed me to get to the settings screen.  

RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

**Comment by kiswa** [comment]
I wonder if that means the line `SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0` is no longer the solution it used to be.

**Comment by divinitystar** [comment]
Oh ok, I didn't see that comment in the root htaccess.  I am now using  `SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0` instead and it is working.  Thanks again.
