### ISSUE TITLE
Translations: Spanish

### ISSUE THREAD

**Issue by gusarg81** [kiswa/TaskBoard#516]
Hi,

   Is this the right place for this? I found (still) one translated string when you create a Task, the list of assignees. Translation of this words seems was literally to "Cesionarios" which is wrong. I suggest there something more like a translation to "Assigned to" -> "Asignado a:" or "Asignados:" (I would go more with the first one).

Also others strings I saw in settings page (user settings)

- Cambia Nombre de Usuario -> "Cambiar Nombre de Usuario"
- Cambia Contraseña -> "Cambiar Contraseña"
- Cambia Email -> "Cambiar Email"

"Cambia" is another literally translation of "Change" instead of the verb. "Cambiar" is the verb.

I will keep digging in other translated strings later as well.

Let me know if I can help with translations (specially Spanish; I am from Argentina) or maybe discuss with the one who translated to this language. 

Thanks!.

**Comment by kiswa** [comment]
I did the initial translations, and while I consulted my wife (from Spain) a few times, I used Google Translate more than I should admit.

I would love it if you opened a PR against the `dev` branch with any fixes you find in the `es.json` and `es_api.json` files!

**Comment by kiswa** [comment]
Have you found any additional issues with the Spanish translations @gusarg81?

**Comment by gusarg81** [comment]
> 
> 
> Have you found any additional issues with the Spanish translations @gusarg81?

@kiswa Hi, sorry. Like I said in another issue, I not longer user TaskBoard... So will be difficult to spend time in helping with Spanish translations.

**Comment by kiswa** [comment]
I didn't even realize that was you, my bad. I'll at least be able to get the fixes from this issue in. Gracias por ayudarme @gusarg81.

**Comment by gusarg81** [comment]
No problem, if you release a Docker image someday (most of all, for easy installation and testing), maybe I can help with translations to Spanish (since I remember I saw some other bad translated strings).
