### ISSUE TITLE
Unable to log in.

### ISSUE THREAD

**Issue by jrcook416** [kiswa/TaskBoard#517]
Running the newest version.
Unable to log in after installation.
SQLite and PHP7 installed on shared hosting.
AllowOverride set to use .htaccess files.

Getting a 301 redirect when I call https://www.iemssupply.net/taskboard/api.
Installed at https://www.iemssupply.net/taskboard/ if you want to take a look. 

Thanks in advance,
JC

**Comment by 2Belette** [comment]
Have you made your api directory writable (chmod 777 ./api) ?

**Comment by jrcook416** [comment]
Yes. Permissions are set to 0777 for the directory itself, do the permissions need to be set recursively for everything below that?

**Comment by jrcook416** [comment]
I am guessing this has to do with the fact that my shared hosting provider won't let me make modifications to the AllowOverride directive in my httpd.conf file.  Thanks anyways.

**Comment by jrcook416** [comment]
I think I'm going to take a stab at this anyways. Wish me luck :-)

**Comment by jrcook416** [comment]
After some digging, some comment deleting, and a little bit of thought, I went ahead and installed this on a laptop that I control.  It would certainly be nice to figure out how to get it up and running on a shared hosting service, but I'll let it go for now.  Cheers!

**Comment by kiswa** [comment]
Does your shared hosting allow `.htaccess` files to use rewrite? I ask because every endpoint I try to hit just gives a 404 Not Found (instead of say a 500 Server Error).

**Comment by jrcook416** [comment]
To my knowledge, it does.  I have several other software packages on this domain/server that allow .htaccess files to use rewrite.  It's (ugh) GoDaddy shared.

**Comment by kiswa** [comment]
Do you have access to any error logs for the server? Maybe that would point us in the right direction.

**Comment by jrcook416** [comment]
Let me dig and see which logs I can get my hands on.  Might be a day or two since this is a sideline thing.  Can I get back to you?

**Comment by kiswa** [comment]
Of course.

**Comment by jsponz** [comment]
Any update on this? I do have the same issue.  Thanks!

**Comment by jrcook416** [comment]
Which error logs did we need to look at?  Raw Access, other?
Thanks,
JC

**Comment by kiswa** [comment]
If there is anything in `api/logs/` that's a good start. Otherwise, logs for the Apache (or whatever server) that coincide with the failure.

**Comment by jrcook416** [comment]
xxx.xxx.xxx.xxx - - [17/Jul/2020:11:50:18 -0700] "POST /taskboard/api/authenticate HTTP/2.0" 404 63 "https://www.iemssupply.net/taskboard/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
xxx.xxx.xxx.xxx - - [17/Jul/2020:11:50:20 -0700] "POST /taskboard/api/login HTTP/2.0" 404 63 "https://www.iemssupply.net/taskboard/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"

**Comment by jrcook416** [comment]
I've decided to go another direction with this.  Unfortunately, I have some other projects to get in above this one.  Thanks for the help anyways, maybe I'll have some time to pick this back up later. 
JC
