### ISSUE TITLE
php_values

### ISSUE THREAD

**Issue by superian** [kiswa/TaskBoard#525]
**Describe the bug**

/api/.htaccess contains

```
php_value upload_max_filesize 80M
php_value post_max_size 100M
php_value file_uploads On
php_value memory_limit 256M

```
Are these only valid if you have mod_php* installed in Apache, rather than using fcgi to call PHP?

From the error log:

`[Sun Jul 05 09:59:42.024055 2020] [core:alert] [pid 14181:tid 139685179336448] [client 81.110.226.145:47236] /home/test/public_html/taskboard/api/.htaccess: Invalid command 'php_value', perhaps misspelled or defined by a module not included in the server configuration, referer: http://taskboard.example.com/
`

**Comment by kiswa** [comment]
Yes, that is the problem. See [this comment](https://github.com/kiswa/TaskBoard/issues/501#issuecomment-647173454) for a workaround.
