### ISSUE TITLE
Allow assigned tasks to become unassigned again

### ISSUE THREAD

**Issue by superian** [kiswa/TaskBoard#531]
**Is your feature request related to a problem? Please describe.**

Once a task has been assigned to someone, it doesn't seem to be possible to set them back to being unassigned.

**Describe the solution you'd like**

Being able to unselect all users in the 'assign to' list.

**Describe alternatives you've considered**

Assigning them to a dummy user and then deleting that user might work, but it might case other problems.

Creating a 'no-one' user - current solution.

**Comment by kiswa** [comment]
The standard browser behavior for a multi-select is to press <kbd>Ctrl</kbd> while clicking to remove selections. By doing this, you can return a task to the "Unassigned" state.
