### ISSUE TITLE
Wrong due date in Emails

### ISSUE THREAD

**Issue by ben-so** [kiswa/TaskBoard#536]
I'm using the dev-branch with commit till 13th July.

When I change or create a task I get an Email like this:

benjamin edited task in board #01.270.
Task: Mail mit monatlicher Statistik
Description: 
Due Date: January 24, 1970, 9:06:40 AM
Asignees: benjamin
Categories: normal 
Points: 10
Column: doing
Position: 3

But the task has a due date on 24th July 2020.
I assume, the there are different reference points used in Taskboard and for email.

As I see Taskboard only uses days and in Email the UNIX timestamp is used including the time.

**Comment by kiswa** [comment]
Guess I missed the formatting for the email dates. Thanks for submitting!
