### ISSUE TITLE
Allow right click on Task description

### ISSUE THREAD

**Issue by gusarg81** [kiswa/TaskBoard#538]
In my case, I need the right button function in task description (which is disabled) so I can check spelling (from web browser menu).

**Comment by kiswa** [comment]
I'm not sure I see the point here.

Doesn't the browser give you spell-check when editing the task? Why would you also need it when viewing the task?

**Comment by gusarg81** [comment]
Is when editing the task description, there is no Right click menu, like that event is disabled. 

Anyway I just switched to Wekan since I need more functionality for a Kanban app to manage my projects development. So I've removed TaskBoard from my server. Thanks for all!
