### ISSUE TITLE
Allow Authentication/Logout Timer to be confiugured via Web GUI

### ISSUE THREAD

**Issue by spsymes** [kiswa/TaskBoard#540]
Hi I would like to be able to adjust the logout timer so that you don't need to login in after 30mins

I would like a field in user settings page that allows you to put in time in minutes or hours to allow users to customize their own timeout setting or at least a global system setting for the timeout.

I've edited the Auth.php to alter the timeout as a work around.

   return JWT::encode(array(                                              
  -  'exp' => time() + (60 * 30) * $mult, // 30 minutes * $mult       
  + 'exp' => time() + (60 * 60 * 24) * $mult, // 24Hours * $mult

**Comment by kiswa** [comment]
That's what the "Remember Me" checkbox is for on the log in screen. If you check it, it changes from the default 30 minutes to something like a day and a half (don't remember exactly).
