### ISSUE TITLE
Can't Log In

### ISSUE THREAD

**Issue by webtimgist** [kiswa/TaskBoard#545]
After installing in a Virtual Host with SSL enabled, I can't log in with username: admin password: admin.

I have a Virtual Host where a Nginx Server is a proxy for and Apache2 server, so I have to have vhost files for both.

How after enabling the SSL port:443 Vhost and running the Comodo SSL checker, everything was reported as OK.

**Comment by kiswa** [comment]
Going to need more details on this. What errors do you see in your browser dev tools (<kbd>F12</kbd>, usually).

**Comment by webtimgist** [comment]
Here is the error message:
ERROR TypeError: e.alerts is undefined
    login login.component.ts:51
    RxJS 31
    Angular 8
core.js:4117:18
    Angular 4
    RxJS 6
    Angular 11

**Comment by kiswa** [comment]
Sounds like the API isn't setup correctly. What shows up in the 'Network' tab of dev tools for the call to `api/login`?

**Comment by webtimgist** [comment]
```
Fatal error: Uncaught PDOException: Could not connect to database (?). in /var/www/my-websites/data/www/subdomain.domain.us/api/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php:440 Stack trace: #0
/var/www/my-websites/data/www/subdomain.domain.us/api/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php(161): RedBeanPHP\Driver\RPDO->connect() #1
/var/www/my-websites/data/www/subdomain.domain.us/api/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php(464): RedBeanPHP\Driver\RPDO->runQuery('SELECT `user`.*...', Array) #2 /var/www/my-websites/data/www/subdomain.domain.us/api/vendor/gabordemooij/redbean/RedBeanPHP/Adapter/DBAdapter.php(118): RedBeanPHP\Driver\RPDO->GetAll('SELECT `user`.*...', Array) #3 /var/www/my-websites/data/www/subdomain.domain.us/api/vendor/gabordemooij/redbean/RedBeanPHP/QueryWriter/AQueryWriter.php(1155): RedBeanPHP\Adapter\DBAdapter->get('SELECT `user`.*...', Array) #4
/var/www/my-websites/data/www/subdomain.domain.us/api/vendor/gabordemooij/redbean/RedBeanPHP/Repository/Fluid.php(294): RedBeanPHP\QueryWriter\AQue in /var/www/my-websites/data/www/subdomain.domain.us/api/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php on line 440
```

**Comment by kiswa** [comment]
Do you have `sqlite3` and `php-sqlite` installed and setup?

**Comment by webtimgist** [comment]
It is perhaps because I didn't have sqlite3 and php7-sqlite installed and enabled,

**Comment by webtimgist** [comment]
That was likely the problem. I am asking the host now, and if not I will install and enable them

**Comment by webtimgist** [comment]
Unfortunately that did not solve the problem.

**Comment by webtimgist** [comment]
The host notes that there is no database, but it is my impression that the database is a file based database which is why there is no instruction for providing a username password for the database.

Everything required is installed and enabled both I and the host made sure. The host also note that the Nginx proxy is not involved in serving these pages so that can't be the issue either.

**Comment by kiswa** [comment]
I know nothing about Nginx proxies, so I can't say either way. As for there being no database, that is completely normal. It's also the reason the `api/` directory needs full write access (`0777`) because it creates the DB on first sign in.

And no, you don't need SQLite Browser unless you want it for something.

**Comment by webtimgist** [comment]
OK, both the hosting company and I tried to get the login to work and I still get the same response:

```
Fatal error: Uncaught PDOException: Could not connect to database (?). in /var/www/my-websites/data/www/subdomain.domain.us/api/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php:440 Stack trace: #484 
/var/www/my-websites/data/www/subdomain.domain.us/api/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php(161): RedBeanPHP\Driver\RPDO->connect() #1 
/var/www/my-websites/data/www/subdomain.domain.us/api/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php(464): RedBeanPHP\Driver\RPDO->runQuery('SELECT `user`.*...', Array) #2 
/var/www/my-websites/data/www/subdomain.domain.us/api/vendor/gabordemooij/redbean/RedBeanPHP/Adapter/DBAdapter.php(118): RedBeanPHP\Driver\RPDO->GetAll('SELECT `user`.*...', Array) #3 
/var/www/my-websites/data/www/subdomain.domain.us/api/vendor/gabordemooij/redbean/RedBeanPHP/QueryWriter/AQueryWriter.php(1155): RedBeanPHP\Adapter\DBAdapter->get('SELECT `user`.*...', Array) #4
/var/www/my-websites/data/www/subdomain.domain.us/api/vendor/gabordemooij/redbean/RedBeanPHP/Repository/Fluid.php(294): RedBeanPHP\QueryWriter\AQue in /var/www/my-websites/data/www/subdomain.domain.us/api/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php on line 440
```
If I can't log in the first time, then the database will not be created. So not sure what else needs to be installed.

**Comment by kiswa** [comment]
The only reason that error would occur is because it was unable to create the DB. The only reason it would be unable to create the DB is because the `api` directory is missing write privileges. Did you (and/or the hosting company) verify that anyone can write to `api`?

**Comment by kiswa** [comment]
Just had another thought. Are you using PHP-FPM? If so, take a look at [this issue](https://github.com/kiswa/TaskBoard/issues/527) or [this one](https://github.com/kiswa/TaskBoard/issues/501#issuecomment-647173454).

**Comment by kiswa** [comment]
Closing due to lack of response. If you still need assistance, comment and I'll re-open.
