### ISSUE TITLE
Can't Connect to Database

### ISSUE THREAD

**Issue by gistambo** [kiswa/TaskBoard#546]
I just installed Taskboard 1.01 with PHP 7.3 and sqlite 3.7.17 on a CentOS 7 machine.

Note sure if this is a bug, but I can't move beyond the initial login page:

![Capture](https://user-images.githubusercontent.com/49824185/89472721-eeed7780-d735-11ea-877c-1c93443354b9.PNG)

I see the following in the error log:
PHP Fatal error:  Uncaught PDOException: Could not connect to database (?). in /var/www/html/taskboard/api/vendor/gabordemooij/redbean/RedBeanPHP/Driver/RPDO.php:440...

This always happens on my first login attempt using the default admin/admin authentication. The PHP function that's throwing this exception and which includes line 440 referenced above is this:

![Capture](https://user-images.githubusercontent.com/49824185/89472488-6f5fa880-d735-11ea-9953-241ddf293ce7.PNG)

Any help you can provide on this issue is appreciated.

Edit: I forgot to mention that the .htaccess has permission 644 and its parent directories are 755. And I don't believe this to be an SELinux issue, as I tried it also with SELinux in permissive mode as well.

**Comment by kiswa** [comment]
Is `php-sqlite` installed and setup? Is the SQLite module enabled for your server?

**Comment by gistambo** [comment]
A php_info() page shows this:

![Capture](https://user-images.githubusercontent.com/49824185/89570991-cc159e80-d7db-11ea-9a16-a1a4864e1978.PNG)

Not sure if there anything else I need to do to enable sqlite.

**Comment by kiswa** [comment]
That looks right for PHP. The `api/` directory needs to be writable to all though (`766`), so that's probably the problem.

**Comment by gistambo** [comment]
![Capture2](https://user-images.githubusercontent.com/49824185/89690592-bd9eb400-d8bb-11ea-96ee-c50223de208f.jpg)

**Comment by kiswa** [comment]
Had another thought - are you using PHP-FPM? If so, [check this issue](https://github.com/kiswa/TaskBoard/issues/527) or [this one](https://github.com/kiswa/TaskBoard/issues/501#issuecomment-647173454).

**Comment by gistambo** [comment]
I don't believe I am using php-fpm. Here is a list of loaded mod, not sure if helpful:
![capture](https://user-images.githubusercontent.com/49824185/90044077-f8b93280-dc81-11ea-91c6-a20b843ea433.PNG)

**Comment by kiswa** [comment]
What does it show as the "Server API" entry?

**Comment by gistambo** [comment]
Apache 2.0 Handler

**Comment by kiswa** [comment]
Is it possible SELinux is doing something unexpected? The only thing I can think of is to maybe try creating a `taskboard.sqlite` DB and see if that lets the API connect.

**Comment by gistambo** [comment]
I added the empty database in `/var/www/html/taskboard/api/taskboard.sqlite/taskboard.sqlite`. Not sure if that's the right location. 
I also set SELinux to permissive, and still I couldn't initiate the app. Same error as before in the error log (`/var/log/httpd/error_log`).
![Capture](https://user-images.githubusercontent.com/49824185/90449491-6e673900-e09c-11ea-9924-465cc7389072.PNG)

**Comment by kiswa** [comment]
It should be at `/var/www/html/taskboard/api/taskboard.sqlite`

**Comment by gistambo** [comment]
Success. Adding that file at the right location and disabling SELinux worked. This is weird, as I couldn't find any SELinux related errors. I was probably looking in the wrong log(s).

Have you ever considered writing an SELinux policy for this app?

Thank you so much.

**Comment by kiswa** [comment]
I have not, but it's certainly something I can look into. Glad you got this resolved!
