### ISSUE TITLE
move tickets from one board to a other board

### ISSUE THREAD

**Issue by StephanKrauss** [kiswa/TaskBoard#547]
Hello,

i have for my work many boards.
I'm looking for a simple way to move tickets from one bord a single column to a other bord in a single column.

Have you an Idea ?

Your sincerly

Stephan

**Comment by kiswa** [comment]
Well, there is a context menu item to move a task to another board. If you have quite a few and need to bulk move, I'd recommend getting to know SQLite and just running queries directly against the DB.
