### ISSUE TITLE
i have a dream

### ISSUE THREAD

**Issue by StephanKrauss** [kiswa/TaskBoard#550]
Hello,

i have some ideas. In my next bigger project i will use the taskboard for a project.

+ My main idea is taskboard use a external mysql database !
+ Use taskboard in a docker container
+ Is there a way to get more fields in the ticket ?
    + select fields, specified by the board administrator
    + input fields
+ Can I assign a ticket to another ticket? I want to assign parent tickets to child tickets.
+ If an expiration date has passed, the color of a ticket changes

Your sincerly

Stephan

**Comment by kiswa** [comment]
Some of those things are already there!

You can absolutely use MySQL if you want, just change line 14 in `src/api/index.php` ([see here](https://redbeanphp.com/index.php?p=/connection) for details).

You can use TaskBoard in a Docker container! I just don't have an official setup out yet (it's planned though).

I'd need to see what you mean about those additional fields.

While you can't assign a task to another task, there is going to be the ability to link directly to a task which will allow you to at least link one task to another (this is actually done, just not released yet).

The color of a ticket doesn't change when overdue (though that would be a nice addition to the automatic actions), but the date does get a highlight when it's overdue.

**Comment by StephanKrauss** [comment]
Hello,

thanks for the quick response.
In my next project, i hope this will start in 2020, i will use the taskboard.
I need additional fields. 

+ In one field I would like to connect a task to a wiki. I want to enter a url. If this URL is clicked, a wiki with an information page opens.

+ Another field should contain the URL to Github. Here, too, Github should be accessible via a button. I would like to have these additional input fields in the parent / main task.

+ I can assign child / sub-tasks to the parent / main task.

+ I can see the entry point in the subtask. I would like to enter this entry point in an input field. Example: / myApp / findPersons. This entry point is recognizable in every child / subtask.

With this division into parent and child tasks, I would like to better organize the task.

Best regards

Stephan

**Comment by kiswa** [comment]
I'll take those into consideration. That said, you'll be able to handle a lot of this with linking to a task, and following a specific format for things you want in every task.

Also, you can setup linking to GitHub issues already (Settings > Add Board or Edit Board). Technically, you could use this to create links to just about anything.
