### ISSUE TITLE
Install on ubuntu 20.04 failed due to missing build folder

### ISSUE THREAD

**Issue by ybudiya** [kiswa/TaskBoard#552]
@kiswa  - first of all thank you for developing this and kudos for making a useful straight to the point web app.

**Describe the bug**

I followed instruction on 
https://vitux.com/how-to-install-taskboard-kanban-on-debian-10/
https://www.howtoforge.com/how-to-install-and-configure-taskboard-on-ubuntu-1804/
https://computingforgeeks.com/how-to-install-and-configure-taskboard-on-ubuntu-18-04-lts/
https://www.rosehosting.com/blog/how-to-install-taskboard-on-ubuntu-18-04/

I am stuck at the point where composer command

`/build/composer.phar self-update`
-bash: ./build/composer.phar: No such file or directory

Then I look at install instruction on https://github.com/kiswa/TaskBoard  -  It is vastly different. Please advise what you recommend me to do next. Thank you.

====================================================
Installing TaskBoard is as easy as 1, 2, 3!

    Download the latest release since v1.0.0
    Extract it to your webserver
    Verify the api directory is writable

====================================================

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Please complete the following information:**
- OS: [e.g. Windows 10]
- Browser [e.g. Chrome, Firefox]

**Additional context**

**Comment by kiswa** [comment]
Any instructions created elsewhere are no longer accurate since the release of `v1.0.0`. Please use [the instructions in the README](https://github.com/kiswa/TaskBoard#installation) to install.
