### ISSUE TITLE
TaskBoard_v1.0.2 stucks at "TaskBoard is Loading..."

### ISSUE THREAD

**Issue by 2Belette** [kiswa/TaskBoard#557]
**Describe the bug**
Installing the latest version, unzipping it, make API writable.
"TaskBoard is Loading..." is shown on my browser. (like on some previous versions where I already had the same issue).

I realized that unzipping the code, it is like the "src" is the folder we have to put on the webserver and not the entire directory (or point the virtualhost to the src instead of the zip root directory), is it correct ?

Thanks !

**Comment by kiswa** [comment]
You shouldn't be using the "Source Code" downloads. Instead download the `TaskBoard_v1.0.2.zip` file and extract that to wherever you want TaskBoard.

**Comment by 2Belette** [comment]
:facepalm: I am a dumb !

working perfectly... sorry for the noise

**Comment by camesa** [comment]
I'm having the same issue using TaskBoard_v1.0.2.zip file
I'm unzipping it, making api folder writable but gets stuck in "TaskBoard is Loading..."

If I open up Web Console of Firefox it shows me this:
Loading failed for the <script> with source “file:///C:/TaskBoard_v1.0.2/index.html/runtime.js”. index.html:53:1
Loading failed for the <script> with source “file:///C:/TaskBoard_v1.0.2/index.html/polyfills.js”. index.html:53:1
Loading failed for the <script> with source “file:///C:/TaskBoard_v1.0.2/index.html/main.js”. index.html:53:1

It shows the same error on macos with Safari, except with the verbiage "Not allowed to load local resource: file:///xxxxxxxxx/TaskBoard_v1.0.2/index.html/runtime.js" etc

I even tried the 1.0.1 version zip but having the same issue. What am I missing?

Thanks!
