### ISSUE TITLE
Need help in installation 

### ISSUE THREAD

**Issue by clanhunter** [kiswa/TaskBoard#577]
![Screenshot (7)](https://user-images.githubusercontent.com/21201727/102679038-88439480-41d2-11eb-9af3-d0fdd6d95fb6.png)
**Describe the bug**
Kindly see the screenshot 

And I'm using cyberpanel, which is running centos 8 and openlightspeed server with marina DB.
Kindly guide me how to install taskboard in my server.

**Comment by kiswa** [comment]
If you're using MariaDB instead of SQLite, you'll need to edit the `api/index.php` file. You should also ensure the API directory is writable, mod_rewrite is allowed, and basically all the stuff in the [Prerequisites](https://github.com/kiswa/TaskBoard#prerequisites)
