### ISSUE TITLE
How does one log into TaskBoard locally?

### ISSUE THREAD

**Issue by JedzieGoat** [kiswa/TaskBoard#579]
"Open your browser to the location you put TaskBoard and log into the site"

How do I do this?  When I click on index.html in the directory in which I
unzipped the files, "TaskBoard is Loading..." appears and it just sits there.
The demo on https://taskboard.matthewross.me/demo-live/ works
just fine (Windows 7, Firefox 85) but how do I "log in" to (from?) the files
which I unzipped from the install?  What obvious thing am I missing?  Not
familiar with Java or web hosting.  Any help would be appreciated, it looks
like a really nifty application.

**Comment by kiswa** [comment]
TaskBoard must be hosted by a web server (IIS, Apache, nginx, _etc._).
