### ISSUE TITLE
Is this program still being developed?

### ISSUE THREAD

**Issue by neadfiles** [kiswa/TaskBoard#583]
I'm not seeing any bug fixes for 2021.  A large group of users, including myself, are unable to log in with admin/admin after installation and I am not seeing any fix listed.

**Comment by kiswa** [comment]
Feel free to make fixes and submit PRs. I'm a little busy with family health issues, and haven't had the time or energy to work on TaskBoard for a bit now.

**Comment by neadfiles** [comment]
I totally understand, Matthew.  I would suggest a simple note on your
website and at Github letting folks know you are taking a hiatus from
support and development (?)
Stay safe!
Sam
