### ISSUE TITLE
Fix HTML & fonts

### ISSUE THREAD

**Issue by computcon** [kiswa/TaskBoard#604]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when HTML formatting is invalid, like in the index.html file.

**Describe the solution you'd like**
My solution is making the index.html file look like the attached one. It's zipped because github doesn't support uploading HTML files directly.

**Describe alternatives you've considered**
You can download the font files from Google Fonts and put then in a separate folder to load them from there instead of Google.
[index.zip](https://github.com/kiswa/TaskBoard/files/7601465/index.zip)

**Comment by kiswa** [comment]
Couple of things here: one, I don't see how this is an improvement; and two, make a PR if you have code changes.
