### ISSUE TITLE
CORS policy blocks a file from accessing other files

### ISSUE THREAD

**Issue by marcozucchi** [kiswa/TaskBoard#608]
**Describe the bug**
CORS policy blocks a file from accessing other files

**To Reproduce**
1. Go to index.html on browser (I was able to reproduce on both Firefox and Chromium-based web browser)
2. Click on Inspect Element --> Console
3. See error

**Expected behavior**
The files should be accessed and let the rendered application load

**Screenshots**
The below screenshot shows the CORS policy block: 

![image](https://user-images.githubusercontent.com/46170114/155904697-84f5775b-ff3f-43f5-9b20-702ea47a1bb4.png)

Error Message: 
Access to internal resource at 'file:///home/{user}/{Download folder}/TaskBoard/favicons/site.webmanifest' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, brave, chrome-untrusted, https

**Please complete the following information:**
- OS: Linux x86_64
- Browser: Brave Browser

**Additional context**
Maybe there's a way the application can be refactored so that it creates a server on localhost, so that it can be accesed from an http:localhost:PORT URL.

**Comment by marner2** [comment]
The app only works when served from a php server. What you are trying to do is access it directly from the file system. Please see the [installation prerequisites on the main README](https://github.com/kiswa/TaskBoard#prerequisites).
