### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by AlbertFR** [kiswa/TaskBoard#76]
a way to have the app into our language
(for me in French, for example)

**Comment by Matthias84** [comment]
I offer a translation to german. I would prefer to avoid transiflex but use launchpad, translatewiki, ... instead :-)

**Comment by tamielbr** [comment]
I can help with portuguese. I often use transifex, but others are reasonable too.

**Comment by pablonunez-dev** [comment]
I can translate to Spanish :)

**Comment by fkosmala** [comment]
I can translate in French too :)

**Comment by andreasb242** [comment]
As I can see, translation is not yet done. So I forked the TaskBoard to my Account: https://github.com/andreasb242/TaskBoard

I'm currently thinking to translate the partials with https://angular-translate.github.io/docs/#/guide/07_multi-language to German.

I didn't work with Angular JS yet, but it shouldn't be that much work.

**Comment by andreasb242** [comment]
@kiswa You may have a look at my code?
I didn't yet create a language selection yet, as I'm not familiar with AngularJS.
But are the used libs OK for you?

**Comment by kiswa** [comment]
@andreasb242 Thank you for taking the initiative and starting translation! The code looks great.

Unfortunately, now may not be the best time to do this... I'm completely re-writing TaskBoard, and any translations will have to re-done once it's released. That said, I'm still happy to accept a PR for your code once it's fully integrated.

For anyone else checking this issue:
# **NOTICE**
Please consider offering translations against the re-write branch. If there is enough interest, I can go ahead and get the initial work done to support i18n in Angular 2 and start accepting translations against the existing code.

**Comment by andreasb242** [comment]
OK, no Problem for me. I need a simple solution for Ticketing / Work Organization, for a company in the family.
They don't do Scrum, but this tool is exactly what they need ;-) Because of this I did the translation.

For now: I don't translate the Settings, and wait for your next release. (I don't create a Pull Request)
It's relative easy to do the translation... 
I'll simple do it again if your rework is finished?

**Comment by kiswa** [comment]
If you're still willing to translate once the re-write is done, I'd be happy to have your help!

**Comment by olaulau** [comment]
could help to translate into french.
in fact, we already have translated it to french, i'm gonna publish a fork for people that can't wait.
