### ISSUE TITLE
Column Sorting by date due, date last modified, and/or priority

### ISSUE THREAD

**Issue by captainwasabi** [kiswa/TaskBoard#77]
It would be nice to be able to sort the columns by some basic fields

**Comment by kiswa** [comment]
It has occurred to me that when a column is sorted by anything other than the default position (which is either the creation order, or where items have been dragged by the user), then drag/drop must be disabled.

Really, the drag/drop functionality only works with the default sorting setup. Changing the sort would have to make columns 'read-only' until it is reset. I'm wondering how useful the sort feature would be in this case...

**Comment by klodha** [comment]
I think adding a filter of date range may help ? So that one can view the task board specific for the day (based on due dates) ?

**Comment by kiswa** [comment]
@klodha I think that's a good idea.

**Comment by tamielbr** [comment]
Perhaps this is another idea: that a trigger could make items move to a column based on how close they are to a due date.

**Comment by momo-aux** [comment]
Is this still a Problem?
I would love to have the entries sorted by due date to have it like a priority list.
The one with the closest due date should be on top. 
It would also be great if a due date can be combined with a column.
Like: Item has to be "Done" until "Friday"
So Due Date for friday and if not moved to "Done" until then BGcolor turns red or something like that.
