### ISSUE TITLE
email notification

### ISSUE THREAD

**Issue by AlbertFR** [kiswa/TaskBoard#78]
a really good enhancement would be an automatic email notification on change for all others board members

**Comment by Kernle32DLL** [comment]
:+1: +1 This could be set up like the triggers, so board admins can specify which mails are send on which actions. Also, like captainwasabi said - this should be possible to be turned off (as a user setting). Maybe something like "receive mails from board".

**Comment by torwag** [comment]
Maybe it is worse to check how this is done in owncloud. They allow sending emails as well. e.g. for password recovery. Furthermore, an action related automatic email notification would be great. E.g. if I assign or remove users to task that should inform them that there is work waiting for them.

**Comment by Shattenjagger** [comment]
Hi there. :) I'd done it for one of my clients. Add me to contributors, so I'll push it to separate branch and you'll be able to make the merge!

**Comment by kiswa** [comment]
Anyone can submit a PR against the dev branch. If you have a working solution for this already, I'd be glad to have your PR!

**Comment by kiswa** [comment]
Closing thanks to @Shattenjagger 

A new issue will need to be created to fine-tune the email options, but it's at least a thing now!
